### ISSUE TITLE
New bulk unpublish script: re-publishing bug

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1013]
Related to new script described in ticket https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/898

I tested the new script using dev2 and PMID 36804072 but ran into the old republishing bug described in ticket 191(https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/191)

I used the new script to first unpublish and then publish PMID 36804072
Checking one of the studies, there is a date in both the publish date and unpublish date columns on the tracking page: http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/studies/104097231/housekeeping and the button to unpublish has disappeared, see screenshot:
![Screenshot 2023-05-09 at 17.00.15.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/3b3cedac-8435-4c35-96e4-0808829dc31f) 

Here is an example of what it should look like (unpublished and republished manually):
![Screenshot 2023-05-09 at 17.00.20.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/f62b7edf-83e2-4b36-b608-bcb3c02dc517)

**Comment by ljwh2** [comment]
Established this is not an issue
