### ISSUE TITLE
In studies tables, Search box should be enabled for sample description 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1019]
In the studies tables on all pages, the Search box should be enabled for sample description. We agreed that sort would not be enabled for now, but there is still a use case for Search only.

**Comment by ljwh2** [comment]
If this is same issue with sort then we can deprioritise

**Comment by ala-ebi** [comment]
@sajo-ebi we need API support for this search

**Comment by sprintell** [comment]
Column not indexed in Solr, hence the back end API. requires this to be added as a new feature
