### ISSUE TITLE
Remap to Ensembl 110

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1037]
Once the mapping pipeline is fully documented and bugs fixed, remap the Catalog to Ensembl 110, which is due to release by end of June.

**Comment by sajo-ebi** [comment]
Mapping successfully ran for all associations

**Comment by ljwh2** [comment]
@sajo-ebi to create ticket for log scanner to analyse issues

**Comment by ljwh2** [comment]
Documentation still needs to done
