### ISSUE TITLE
Alternative license for submission

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1038]
User van der Laan has requested sumstats submission under CC-BY-NC. User to create Body of Work, then Lizzy will make the submission bypassing the license agreement and setting embargo till published (to give us time to make the changes). @earlEBI please note here when submission has been completed. 

Previous ticket is here: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/790

**Comment by ljwh2** [comment]
Note, check if license is included in metadata file

**Comment by sprintell** [comment]
STill waitinng for the user

**Comment by earlEBI** [comment]
@sprintell Hi, the user has now submitted successfully under submission id '64db9f30788f0000010e6a14'. It is embargoed until date of publication. Could you please make sure the correct license information will be showing once embargo is removed?

**Comment by earlEBI** [comment]
@sprintell Hi, the embargo has now been removed from this publication so it will currently appear as prepublication landing pages in the next DR. 
The PMID for this publication is 37770635, although it has not been added to the submission yet.

**Comment by earlEBI** [comment]
Publication is now published to Catalog, will be in next DR.

**Comment by earlEBI** [comment]
done.
