### ISSUE TITLE
As a user if I search for a specific GCST and no results are returned I would like a message returned to indicate how I might find results

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#104]
As a user if I search for a specific GCST and now results are returned I would like to see a message that indicates that I may want to check the ftp, which will also include GCSTs for unpublished GWAS
"If you are unable to locate a specific GCST please check our ftp [link] which also includes data for unpublished studies"

**Comment by JalMacArthur** [comment]
Laura - please could you review the text of this message and check you're happy with this.

**Comment by ljwh2** [comment]
I am happy with this.

**Comment by ljwh2** [comment]
Not required due to implementation of landing page
