### ISSUE TITLE
Submission missing in deposition and depocuration app PMID:35870639 (632c967737db2600018dd446)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1044]
This is a published submission in Catalog. I need to unpublish it to update EFO's but it is missing in the deposition and depo-curation tool. 

It is available in the curation app: http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/publication/35870639.

There are 2 other tickets (CLOSED) related to this submission: 902 and 867

**Comment by sajo-ebi** [comment]
@Santhi1901 the submission has been unarchived , can you upload the edited template , Also check the GCST once you upload to ensure we don't get the duplicate GCST issue

**Comment by Santhi1901** [comment]
@sajo-ebi Till yesterday I was able to access sumstats through FTP, but now it is showing an error **403 Forbidden. You don't have permission to access this resource**. eg: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90237001-GCST90238000/GCST90237703/
When I checked the sumstat on /nfs/production/parkinso/spot/gwas/prod/data/summary_statistics/ the sumstats files are there and it looks fine.
I checked the submission history of this submission in deposition app and it looks like it became invalid on 24th Feb 2023. I am not sure how. 
[Submission.history.xlsx](https://github.com/EBISPOT/goci/files/11830991/Submission.history.xlsx)

**Comment by sprintell** [comment]
Hi @Santhi1901 could you please help confirm tis is done ?

**Comment by Santhi1901** [comment]
yes, the submission is re-published.
