### ISSUE TITLE
Change PMID linked to body of work GCP000627

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1048]
The wrong PMID was assigned to this body of work, and needs to be changed.

GCP: **GCP000627**
Currently assigned PMID (incorrect, to be removed): **35862124**
Correct PMID to be added: **37285119**

**Comment by sajo-ebi** [comment]
@eks-ebi is there any submission associated with this GCP?

**Comment by eks-ebi** [comment]
@sajo-ebi yes, this one: 64637b8a95f42a0001ed4eb9
https://www.ebi.ac.uk/gwas/deposition/submission/64637b8a95f42a0001ed4eb9

**Comment by eks-ebi** [comment]
thanks! I can see the correct PMID in deposition, and the curation app is also correctly showing that there is an available submission for the correct PMID. Can you let me know when the sync has run?

**Comment by eks-ebi** [comment]
@sajo-ebi The Import button is still disabled for this submission - could you please check what the issue is?

**Comment by eks-ebi** [comment]
This has now been resolved - @sajo-ebi discovered that the PMID that was added in deposition had not been synced to curation. This was manually added and statuses changed. I was then able to import the submission, and have now published the studies in the curation interface.

Ticket can be closed.
