### ISSUE TITLE
GCST90014045 sumstats need replacing 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1054]
The sumstats available on the ftp  for GCST90014045 are for chr1 only, and do not match the top associations in the paper.  The submitters say they do not have the full summary statistics available but have provided 38K top associations. 

The sumstats should be replaced with that top associations file, with a note in the readme file stating that full genomewide summary statistics are not available for this study. 

Data is here: https://drive.google.com/file/d/1SYmHgUbWU35RXd_Vw2JoQ6tUpsqRSmKL/view?usp=drive_link

**Comment by earlEBI** [comment]
Done. 
Also hid the harmonised folder so it's no longer visible. Could remove if preferred.

**Comment by ljwh2** [comment]
Just tagging @jdhayhurst so he is aware
