### ISSUE TITLE
Create Reported traits in the curation app/database for a large submission before import

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#106]
We have a submission containing a large number of new reported traits that are not currently in the database. When the submission is imported, these traits will be missing from the created study entries and will be difficult to add one by one in the curation app. See submission page: https://www.ebi.ac.uk/gwas/deposition/submission/5ef9a208ee10690001662119

We need to add these traits in bulk before importing the submission. List of traits has been emailed to Trish.

**Comment by twhetzel** [comment]
These are added now.
