### ISSUE TITLE
Sumstats not in database

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1065]
These studies exist in a sumstats submission, but are not in the sumstats db: GCST90268027-GCST90268029. James thinks this could be due to failed PUT request. 

Could be useful for @sajo-ebi to work on with @jdhayhurst ?

**Comment by ljwh2** [comment]
@sajo-ebi please provide submission ID for these GCSTS

**Comment by sajo-ebi** [comment]
Hi @eks-ebi the submission id is. same for all GCST's '644ae1731bb62600014f2c81'

**Comment by ljwh2** [comment]
OK, I searched for the submission ID in emails and looks like the user got caught by the globus errors and gave up.  I think this ticket can be closed.
