### ISSUE TITLE
Trait count is incorrect on variant dedicated page

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#107]
- Go to https://www.ebi.ac.uk/gwas/variants/rs433852
- Toggle over each trait name in the "Traits" table
Each trait has a separate EFO URL for a total of 3, but the trait count displays 2

Alternative test:
- Get the associations for a variant: 
https://www.ebi.ac.uk/gwas/rest/api/singleNucleotidePolymorphisms/rs433852/associations

- For each association, follow the "efoTraits" link:
https://www.ebi.ac.uk/gwas/rest/api/associations/43791/efoTraits
https://www.ebi.ac.uk/gwas/rest/api/associations/16567596/efoTraits

- For each efoTrait, find it's parent category mapping:
https://www.ebi.ac.uk/gwas/rest/api/parentMapping/EFO_0005760
https://www.ebi.ac.uk/gwas/rest/api/parentMapping/EFO_0000249
https://www.ebi.ac.uk/gwas/rest/api/parentMapping/Orphanet_54247

**Comment by ljwh2** [comment]
I think this is the expected behaviour - it is counting reported traits (ie lines in the table) not EFOs
