### ISSUE TITLE
Trait page not loading reliably in search UI 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1073]
This page is not loading reliably in the UI: https://www.ebi.ac.uk/gwas/efotraits/EFO_0004725

It will load one or other of the tabs but not all of them (e.g.e studies but not associations). After refreshing, sometimes a different tab is successful. 
![Screenshot 2023-07-19 at 11.40.32.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/1e476ac1-3cb7-4d0c-bc0a-0db96077fd1a)![Screenshot 2023-07-19 at 11.40.09.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/2eaba335-21a0-4ea5-8649-52f4c881442e)![Screenshot 2023-07-19 at 11.38.54.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/fb667b37-cbd7-4817-b20b-478667b3d844)

@sprintell says: Its the Solr API failing periodically.  This is one of the endpoints that page is calling : https://www.ebi.ac.uk/gwas/api/v2/efotraits/EFO_0004725/studies?includeChildTraits=true&includeBgTraits=false&size=5&page=0&_=1689763984159

also: https://www.ebi.ac.uk/gwas/efotraits/EFO_0803533

**Comment by ljwh2** [comment]
Now seems like it is always failing

**Comment by sprintell** [comment]
@ala-ebi should please update this ticket on what was fixed, it seems its working now

**Comment by ljwh2** [comment]
Now not working again

**Comment by ala-ebi** [comment]
https://www.ebi.ac.uk/gwas/efotraits/EFO_0803533
this term also isnt loading correctly

**Comment by ljwh2** [comment]
A user reporting this page was giving an error, but seems to work now: https://www.ebi.ac.uk/gwas/efotraits/EFO_0005741

**Comment by sajo-ebi** [comment]
EFO_0004725 is now loading  made Solr config changes in order to fix the issue, for 'EFO_0803533' & ' MONDO_0005351' we are getting error from OLS while trying to retreive child traits @ljwh2 should we follow up with OLS team w.r.t same

**Comment by ljwh2** [comment]
Resolved by changing to OLS4

**Comment by sprintell** [comment]
@sajo-ebi will check and ensure its properly deployed.

**Comment by sajo-ebi** [comment]
fix deployed in Prod
