### ISSUE TITLE
Curators need to extract submission ID from GCST 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1075]
In order to more efficiently deal with helpdesk queries and triage the celery errors, curators need to be able to identify 
the submission ID associated with a given GCST. For triaging the celery errors, the curator may have the callback ID, but for user queries, they do not. At the moment, a developer is required to make this link.

**Comment by ljwh2** [comment]
In first instance, @sajo-ebi to train curators to query MONGOdb

**Comment by sajo-ebi** [comment]
finished KT with Curators
