### ISSUE TITLE
Triage celery errors

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1076]
Since James implemented the celery error alert, several email alerts have been triggered. Once gwas-sumstats-service#252 has been implemented, this should fix most of these going forwards, but previous errors will not be corrected. The existing alerts should be triaged and prioritised for attention.

**Comment by earlEBI** [comment]
There are 3 errors which I can see so far: 
1.                 Exception was raised:
('POST', 'https://auth.globus.org/v2/oauth2/token', 'Basic', 401, 'UNAUTHORIZED', 'Basic auth failed')
- known issue.
2. ValueError: Could not find one and only one matching file for ...
3. pydantic.error_wrappers.ValidationError: 1 validation error for MetaModel
     minor_allele_freq_lower_limit
     value is not a valid float (type=type_error.float)

**Comment by earlEBI** [comment]
For the second type of error, submissions are:
64b553d0e6cd8200017eb9d7
649020e5dd0dc60001aaddf9
64a83135788f0000010c4b87
64c92101e6cd8200017f702e
63f8b04261d3e70001799bf9
64dff56c788f0000010e906c

**Comment by earlEBI** [comment]
For the third error (re: minor allele freq), the submissions are:
'64d8f33053c4ef0001f01886' - valid. MAF freq in submission template = '0.1%'. 2 out of 3 directories have not been created on staging. (GCST90277452, GCST90277451). The directory which has been created has only the sumstats file and no yaml or readme or md5 (GCST90277451).
'64d6ba9553c4ef0001f007ee' - valid. MAF freq in submission template = '1%'. File is on staging but there is no yaml file.

**Comment by earlEBI** [comment]
For the fourth issue, I can see only one submission and it has been successfully submitted under GCP000675. Files are on staging with yaml files.
