### ISSUE TITLE
update reported traits for a user prepub submission GCP000684

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1079]
User contacted us to update the reported trait field of their submission as they had filled it as 'protein abundance levels' for all studies. The protein was only given in the study tag column. 

I downloaded the template and re-uploaded it with correct reported traits (see screenshot of file diff), but Sajo could not see the change in the database overnight. 

![Screenshot 2023-07-27 at 09.33.20.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/799ef6e6-146a-4061-a7a4-024f088df78d)

Please investigate whether the updated reported trait field will be visible after the data release. 

submission ID: '64bed0bf53c4ef0001ef0e51'

**Comment by sajo-ebi** [comment]
Updated the traits manually in Curation DB as currently the Deposition sync workflow doesn't support updating of traits via Depo Curation , need to create a dev ticket to make this behaviour happen

**Comment by ljwh2** [comment]
@sajo-ebi please create dev ticket as described

**Comment by sprintell** [comment]
Hi @sajo-ebi please create te dev ticket

**Comment by sajo-ebi** [comment]
Created a Dev ticket [https://github.com/EBISPOT/goci/issues/1108](https://github.com/EBISPOT/goci/issues/1108)
