### ISSUE TITLE
EFO terms producing errors in Update and obsolete EFO job report

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1085]
I have looked into the EFO terms with errors reported the last time this job was run (17th July). I think they can be divided into a few categories. 

1. These terms have studies annotated to them, and are findable in the search UI , but the trait page does not load (info box spins forever; data tables have errors). This is high priority to fix due to impact on UI.  
EFO_0600029
HP_0410139
MONDO_0001039
MONDO_0015938
MONDO_0021081
OBA_2050073
OBA_2050082

2. Similar to (1) this one has studies annotated to it, which are visible in UI (e.g.for PMID 22116812), and the trait page does not load (info box spins forever; data tables have errors). In this case the term is not findable in the search, searching for vascular dementia gives an EFO term (but with no studies or assocations). I guess the MONDO term should be replaced by the EFO one.   
MONDO_0004648

3. There terms are not in any study in the Catalog as far as i can see, and are not findable in the UI except for the last one. There does not seem to be any use for these to exist in the DB, possibly they were in use at one time and then replaced by curators by a more appropriate term. This is lower priority to fix, no impact on users but would improve the usability of the error report if these did not appear.  
EFO_0008147
EFO_0009462
EFO_0021579
EFO_0021606
EFO_0021673
HP_0001096
HP_0003077
HP_0005293
HP_0005560
HP_0100532
MONDO_0000745
MONDO_0004631
MONDO_0005070
MONDO_0005372
MONDO_0019543
MONDO_0020128
Orphanet_558
EFO_0803533 . 

4. This one was obsoleted in EFO with replacement, unclear why it wasn't caught by the job
MONDO_0022880

@ala-ebi to please create sub-tickets for these issues as required.

**Comment by ala-ebi** [comment]
1) EFO_0600029, MONDO_0015938, not in OLS
HP_0410139, MONDO_0001039, MONDO_0021081, OBA_2050073, OBA_2050082 in OLS but not imported to EFO, they are under other ontologies
2) MONDO_0004648 is not in EFO, you're correct should be replaced
3) Will be cleaned up after confirmation
4) I think it's because in the OLS REST API, there is "term_replaced_by": "MONDO:0022308", the colon in the short form makes it unfindable in OLS when we lookup the URL, must add code to handle these.

**Comment by ljwh2** [comment]
1. Created EFO ticket: https://github.com/EBISPOT/efo/issues/2085
2. ok
3. Yes, please clean these up
4. Does this need fixing on their side?

**Comment by ljwh2** [comment]
@ala-ebi will complete 3 and 4 before DR

**Comment by ala-ebi** [comment]
3)  EFO_0803533 will be treated separately in goci#1073

**Comment by ala-ebi** [comment]
4) not only term_replaced_by has a colon, it's pointing to itself https://www.ebi.ac.uk/ols4/api/ontologies/mondo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0022880

**Comment by ljwh2** [comment]
Double check after DR

**Comment by ljwh2** [comment]
Confirmed 2 is fixed. 4 is a strange one, looks like studies in the Catalog that were annotated with MONDO_0022880 (corticobasal degeneration) are now annotated with an unrelated trait CHEBI_20710, but the replacement term should be MONDO_0022308 (corticobasal degeneration disorder) [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9MQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d76a08e72c2a8c7c313180d6a61c17568ca7fa68/Screenshot%202023-10-05%20at%2016.50.49.png)

**Comment by ljwh2** [comment]
@ala-ebi investigate further and create issue with EFO/OLS if necessary

**Comment by ljwh2** [comment]
@ala-ebi Update manually for now

**Comment by ljwh2** [comment]
@ala-ebi Update manually for now

**Comment by ala-ebi** [comment]
MONDO_0022308 is not in EFO ontology

**Comment by ala-ebi** [comment]
fixed an issue caused by using "shortform" instead of "short_form" httpParam, likely was the reason for the issue above ^

**Comment by ljwh2** [comment]
@ala-ebi do we need to request addition of MONDO_0022308 to EFO?

**Comment by sprintell** [comment]
@ala-ebi will do a manual database update before ...

**Comment by sprintell** [comment]
@ala-ebi will do a manual database update before ...

**Comment by ala-ebi** [comment]
Bug in OLS caused the EFO changes not to be reflected. https://github.com/EBISPOT/ols4/issues/583

**Comment by ala-ebi** [comment]
added to ols and updated in our dbs
