### ISSUE TITLE
Delete submission 636457e4c6aae2000191bb95 (PMID: 36176292)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1088]
Need to delete [this](https://www.ebi.ac.uk/gwas/deposition/submission/636457e4c6aae2000191bb95) submission as the PMID needs to be linked to another submission submitted by a user (6304d7b115ccca0001f1101b).

It is not yet published in Catalog; it is level 1 curation done. (http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/publication/36176292)

**Comment by sajo-ebi** [comment]
@Santhi1901 the submission has been deleted
