### ISSUE TITLE
Missing sumstats

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1097]
@earlEBI  found the following directories with issues (GCSTs from 3 submissions)
GCST90086067 GCST90086068 GCST90086069 GCST90086070 GCST90086071 GCST90086072 GCST90086073 GCST90086074 GCST90086075 GCST90086076 GCST90086077 GCST90086078 GCST90086079 GCST90086080 GCST90086081 GCST90086082 GCST90086083 GCST90086084 GCST90086085 GCST90086086 GCST90086087 GCST90086088 GCST90086089 GCST90086090 GCST90086091 GCST90086092 GCST90086093 GCST90086094 GCST90086095 GCST90086096 GCST90086097 GCST90086098 GCST90086099 GCST90086100 GCST90086101 GCST90086102 GCST90086103 GCST90086104 GCST90086105 GCST90086106 GCST90086107 GCST90086108 GCST90086109 GCST90086110 GCST90086111 GCST90086112 GCST90086113 GCST90086114 GCST90086115 GCST90086116 GCST90086117 GCST90086118 GCST90086119 GCST90086120 GCST90086121 GCST90086122 GCST90086123 GCST90086124 GCST90086125 GCST90086126 GCST90086127 GCST90086128 GCST90086129 GCST90086130 GCST90086131 GCST90086132 GCST90086133 GCST90086134 GCST90086135 GCST90086136 GCST90086137 GCST90086138 GCST90086139 GCST90086140 GCST90086141 GCST90086142 GCST90086143 GCST90086144 GCST90086145 GCST90086146 GCST90086147 - just md5sums
GCST90102485 - hidden files only
GCST90177062 , GCST90177721 - no sumstats files

This needs investigating

**Comment by ljwh2** [comment]
For the last one, this was a large submission of 3000+ files, only 2 are missing.

**Comment by ljwh2** [comment]
1. Check if files are on staging
2. Check in curation notes, emails etc
3. Files were submitted for these. Check if they are on staging. Also check in emails etc.

**Comment by earlEBI** [comment]
For the first submission, PMID 33893285
- Folders are on staging (and public), but they contain md5sum files only, which are empty. 
- There is an unresolved gwas-subs thread with the last e-mail from the user in Dec 2021 asking where the sumstats are. 
    - (There is a record of this PMID in the master list of submitters we've emailed after sumstats release, but I don't know if this was before or after.)
- From the same gwas-subs thread, there was some problem with original validation of the files which James replied to, saying it had gone through successfully. 
- I've searched for the PMID in submission app and depocuration app, and there is no sign. There is also no triangle indicating a submission in the curation app. Suggests somehow the submission has been deleted after import? 
- from e-mail search, I think the submission ID was 6185126281051b00017070d1 but can find no other record of it. 
- I can't see any curation notes in the curation app. 
- I can see the original raw sumstats file names in the curation app study details page, eg. Results_ALLERGIC_RHINITIS_GERA_chr_1_22_dom.tsv , and have searched for it in our Globus upload folders but can find nothing. 

Maybe a developer would be able to shed more light.

**Comment by earlEBI** [comment]
For the second submission (GCST90102485, '62711bd328d70900018d85fd', GCP000336):
- No sign of the submission Submission app or depocuration app. 
- The GCST page appears after searching in the GWAS Catalog UI as prepub landing page. 
- Public FTP folder is completely empty. 
- Staging files are hidden. 
- Found a ticket to delete this submission: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/923
    - Ticket needs reopening as it's still appearing in the UI.
- I think I hid the files because I was cautious bout deleting files. I will delete them now.

**Comment by earlEBI** [comment]
For the third submission (GCST90177062 , GCST90177721 ), I'm not sure why these files weren't on staging (or public) but I was able to find them in the original Globus upload directory, so I've moved them over to staging and created yaml files for them. So these two are done.

**Comment by earlEBI** [comment]
For the first submission, James let me know some other places the files might be and I found them in depo_ss_validated using callback_id. 
Have moved the files to staging and made md5sum files (as these were empty). Should sync to pub overnight.
