### ISSUE TITLE
Investigate REST API loading issues

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1098]
A user has reported that some API pages do not load:

https://www.ebi.ac.uk/gwas/rest/api/studies?page=2
https://www.ebi.ac.uk/gwas/rest/api/studies?page=1&size=100

However, some similar queries _do_ return a result:

https://www.ebi.ac.uk/gwas/rest/api/studies?page=2&size=1
https://www.ebi.ac.uk/gwas/rest/api/studies?page=1&size=10

Sajo has started to investigate and commented:

> this looks like data releated issue will need to check log files
> I tried for page=2 & size =15 it works till that
> fails when I give 16 so issue with 16th record probably

**Comment by sprintell** [comment]
Done @eks-ebi pls confirm

**Comment by eks-ebi** [comment]
Confirmed, this is now fixed.

**Comment by eks-ebi** [comment]
Confirmed, this is now fixed.

**Comment by eks-ebi** [comment]
Confirmed, this is now fixed.

**Comment by eks-ebi** [comment]
Confirmed, this is now fixed.

**Comment by eks-ebi** [comment]
Confirmed, this is now fixed.

**Comment by eks-ebi** [comment]
Confirmed, this is now fixed.

**Comment by eks-ebi** [comment]
Confirmed, this is now fixed.
