### ISSUE TITLE
Harmonise task - subticket 3 - PMID 33414548

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1100]
6 empty studies: 
GCST90010743
GCST90010756
GCST90010808
GCST90010729
GCST90010780
GCST90010753
(also GCST90010744)

It looks like the problem is the p-values are in quotation marks. 

I've deleted the harmonised folders on public.
Removed quotation marks from the original raw files on staging. Hopefully will sync to pub overnight. There's no need to recreate formatted files as headers are already in standard pre-SSF format. 
All studies have yaml files so should re-enter harmonisation queue.

**Comment by earlEBI** [comment]
done

**Comment by ljwh2** [comment]
@jiyue1214 to prioritise for hm

**Comment by ljwh2** [comment]
not harmonised successfully, @jiyue1214 investigating
