### ISSUE TITLE
non-GWAS-SSF yamls

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1106]
I've found 12,059 sumstats files that should have non-GWAS-SSF format in their yaml file. 
(11,669 of these are from the same large submission still undergoing curation.)
List for reference: [non-GWAS-SSF GCSTs.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHBmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--db01326b2c0b29f8e1e76ee08607f0cdf2434a19/non-GWAS-SSF%20GCSTs.txt)

(I happened to check the last one - GCST90277270 - and I don't think this is non-standard but may possibly be corrupt.) - fixed.

**Comment by earlEBI** [comment]
I have edited the yamls for all these files so that they say non-GWAS-SSF.

**Comment by earlEBI** [comment]
Note, I have not changed this for the Backman gene-based studies because they contain chromosome and base_pair_location so are still ok to go through harmonisation?

**Comment by ljwh2** [comment]
@earlEBI We won't harmonise any gene-based, please change the Backman ones as well.

**Comment by earlEBI** [comment]
I've changed the Backman gene-based studies yamls to non-GWAS-SSF as well. 
Also deleted their harmonised folders (had already been created) because the harmonised files were empty. 
Also realised that edited yamls do not sync to pub on their own so edited all non-gwas-ssf yamls on pub as well. 

Done.
But I hope the harmonisation queue is updated at this point so all of these are removed.
