### ISSUE TITLE
New version of studies download

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1112]
As a user I want to have access to cohort and summary statistics location data via the studies downloads, available from this page: https://www.ebi.ac.uk/gwas/docs/file-downloads
Note, cohort data is entered by curators and submitters via the submission template, and is imported to the curation app, e.g. on this page: https://www.ebi.ac.uk/gwas/curation/studies/106775325: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkp4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7f40b9cedb574907333bcb244a2750777473fa8c/Screenshot%202023-09-06%20at%2014.54.49.png)

There should be a two new versions All studies v1.0.2.1 and All studies v1.0.3.1  

*All studies v1.0.2.1*
Same as All studies v1.0.2 with three additional columns:
“COHORT”, containing cohort identifiers. For consistency with other fields, the separator should be a comma, but could be pipe (this is how it is entered in the submission template) if this is difficult to do. 
“FULL SUMMARY STATISTICS”, containing information on whether the study has sumstats. This can be obtained from the fullpvalueset flag
“SUMMARY STATS LOCATION” containing the ftp path to the sumstats

*All studies v1.0.3.1* 
Same as All studies v1.0.3 with two additional columns “COHORT” and “FULL SUMMARY STATISTICS”
This file already has the “SUMMARY STATS LOCATION”, but it is not currently populated. The field should be populated. 
(Note the “submission date” field is also not currently populated, if easy to do, this could be populated as well) 

The new fields need adding to solr if not already and included in the DR

**Comment by ala-ebi** [comment]
empty cohort: leave blank
empty ftplink: NA

**Comment by ala-ebi** [comment]
All studies v1.0.3.1:
instead of fixing "SUMMARY STATS LOCATION" and adding two fields, I removed the existing "SUMMARY STATS LOCATION" from the middle and added it to the end of the file so it's consistent with v1.0.2.1 and we can reuse the same code block.

**Comment by ala-ebi** [comment]
@ljwh2 or @earlEBI please update the documentation accordingly https://www.ebi.ac.uk/gwas/docs/fileheaders

**Comment by ljwh2** [comment]
Final list of files is here: https://docs.google.com/spreadsheets/d/1lMkVVueCb_-_Csdg57lLBJG5hdXeDLNESfvUjDqv7NA/edit#gid=0

**Comment by ala-ebi** [comment]
unpublished studies' cohorts are not stored in STUDY_EXTENSION and should be handled separately
