### ISSUE TITLE
Make full list of cohort IDs and names available to users

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1114]
As a user, i want access to the full list of cohort identifiers and their full names. 

Laura to spec where this should go and find out how PGS generate theirs: https://www.pgscatalog.org/downloads/

**Comment by ljwh2** [comment]
If we first consolidate with PGS we could simply cross link to their file: https://ftp.ebi.ac.uk/pub/databases/spot/pgs/metadata/pgs_all_metadata_cohorts.csv

**Comment by sprintell** [comment]
@ljwh2 pls check

**Comment by ljwh2** [comment]
closing as covered by goci#1189
