### ISSUE TITLE
Bulk replace incorrect sumstats files for 582 studies (PMID 34662886)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1115]
The author of this publication (PMID 34662886, originally submitted under GCP000236) has brought to our attention an error in the standard_error column, which affects 582 studies.

The author has sent us amended copies of the files and these are currently stored on the private FTP. I have identified the following information, which is stored in the attached Excel spreadsheet:

**study_accession**: GCST of the study
**study_tag**: Study tag for the study in the original submission
**study_directory**: Existing directory for this study on the public FTP
**current_filename**: Filename of the current summary statistics file (within the study_directory) which contains the error and needs to be replaced
**replacement_directory**: Location of the new corrected file, which needs to be moved to the study_directory to replace the old file. Note that the replacement files are split between two subfolders, depending on the type of study (single variant vs gene burden), but I don't think this should affect the replacement process. 
**replacement_filename**: Filename of the new replacement summary statistics file (within the replacement_directory). When the new file is moved to the study_directory, it should be renamed to match the current_filename.
**replacement_md5sum**: md5sum of the replacement file

I need help to replace all of these files in bulk. I think the steps should be:
1. Move each **replacement_filename** from **replacement_directory** on private FTP to **study directory**, to overwrite the **current_filename**.
2. Update the YAML file in the **study_directory**: the only thing that should need changing in the YAML file is the md5sum. Everything else should stay the same.
3. Update the md5sum.txt file to display the new md5sum.
4. Restart harmonisation of the file (I'm not sure of the details about this).

[34662886-amendments-plan.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk54IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d8ab3645ef6eb4809e595b7665b283f15ba95b3/34662886-amendments-plan.xlsx)

**Comment by earlEBI** [comment]
1. I've replaced each file on staging, so it should sync to pub overnight. 
2. I need to make some updates to yamls anyway so I will do this separately. 
3. The md5sums are updated. 
4. I've removed the harmonised folders on public for these GCSTs. We will check with Yue next week if anything else needs to be done.

**Comment by earlEBI** [comment]
Will give the GCSTs to Yue to be re-harmonised.

**Comment by eks-ebi** [comment]
@earlEBI Just checked that one study that hadn't updated yesterday, and the new file is there! So all good now I think
