### ISSUE TITLE
Sumstats not available on FTP after removing embargo

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1117]
GCST90274713-GCST90274717 for submission `64b82b5ae6cd8200017eda46` and 
GCST90278615-GCST90278674 for submission `64e39b7ae6cd820001333d7b` are not available on FTP.

Have removed the embargo on 30th Aug and 31st Aug for the above submissions, respectively.

**Comment by ala-ebi** [comment]
Running the sync *unpublished* process locally fixed it, it is not clear why this is the case and more investigation is required.
Possible that it needs more resources and worth checking if runs normally as a bsub?

**Comment by ljwh2** [comment]
@ala-ebi to create technical ticket to investigate next time there is a problem
