### ISSUE TITLE
YAML files - missing sample info

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1118]
This is a ticket related to manually creating yaml files for old summary statistics submissions. There are three separate issues relating to calling the ingest api. 
**1.** sample info is completely empty
**2.** sample info is unclear. eg. where there is discovery and replication stages, two sample numbers will be given without explanation (and without ancestry). 
--- I think we might not want to show replication sample info in yaml files? 
**3.** yaml file generation fails with _embedded error.

**Here is the gwas-sumstats-tools config**: https://github.com/EBISPOT/gwas-sumstats-tools/blob/61eb5714d2455ec2ff2553679c544ed386944f2f/gwas_sumstats_tools/config.py#L44

**To create a yaml file I use the following example script:**
f = file_path
gwas-ssf format $f -m --meta-edit --file_type=pre-GWAS-SSF --genome_assembly=GRCh38 -g 

## issue one - empty samples ##
As I understand it, from a brief chat with James, the -g flag points to the ingest API.

For newer files, the sample info is created correctly, eg:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHVBIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18e683dcf61766984855d6deb64a8569c5ca806e/Screenshot%202023-09-08%20at%2015.01.06.png)

But for older files, the samples info is empty, eg:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDJBIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0bba0201c8101ed3303ddeaac2dcdf3e5bc0a820/Screenshot%202023-09-08%20at%2011.02.04.png)

In the latter case, the output of the gwas-ssf command was:
gwas-ssf format $f -m --meta-edit --file_type=pre-GWAS-SSF --genome_assembly=GRCh37 -g
---------- METADATA ----------
(ERROR): https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST006079 returned 404 status code
(ERROR): https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST006079/samples returned 404 status code
adjusted_covariates: null
analysis_software: null
author_notes: null
coordinate_system: null
data_file_md5sum: 480569ffe4adfadfc07b63db0c0f914e
data_file_name: GCST006079.tsv.gz
date_last_modified: 2023-09-08
file_type: pre-GWAS-SSF
genome_assembly: GRCh37
genotyping_technology: null
gwas_catalog_api: https://www.ebi.ac.uk/gwas/rest/api/studies/GCST006079
gwas_id: GCST006079
harmonisation_reference: null
imputation_panel: null
imputation_software: null
is_harmonised: false
is_sorted: false
minor_allele_freq_lower_limit: null
ontology_mapping: null
samples: []
sex: null
trait_description: null
Writing metadata -->
/nfs/ftp/public/databases/gwas/summary_statistics/GCST006001-GCST007000/GCST006079/GCST006079.tsv.gz-meta.yaml

Note the 404 errors re: api endpoints. 

## issue two - unclear samples ##
For the following example, this was the yaml sample section generated: 
gwas_catalog_api: https://www.ebi.ac.uk/gwas/rest/api/studies/GCST90077560
gwas_id: GCST90077560
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTZBIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e8d7d73aaa2b0f1777b90b5002c83911fb1226/Screenshot%202023-09-08%20at%2015.12.08.png)
issues: 
- no ancestry info is given
- discovery and replication sample numbers are given, without any description.

**Comment by earlEBI** [comment]
@ljwh2 I'm torn whether to rerun the yaml file generating for any yamls which currently have no samples section (eg. they were made without -g flag), so that all yamls either have sample info or an empty sample section. Or whether to wait until these issues have been fixed and then re-run.

**Comment by earlEBI** [comment]
There is a ## third issue ## where there is an error generating yaml file when using -g flag. Here is the output which means no yaml is generated:
---------- METADATA ----------

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /hps/nobackup/parkinso/spot/gwas/data/sumstats/formatting/earl/ssformat/lib/python3.9/site-packa │
│ ges/gwas_sumstats_tools/cli.py:188 in ss_format                                                  │
│                                                                                                  │
│   185 │   │   if custom_header_map else {}                                                       │
│   186 │   meta_dict = metadata_dict_from_args(args=extra_args.args) \                            │
│   187 │   │   if metadata_edit_mode else {}                                                      │
│ ❱ 188 │   format(filename=filename,                                                              │
│   189 │   │      data_outfile=data_outfile,                                                      │
│   190 │   │      minimal_to_standard=minimal_to_standard,                                        │
│   191 │   │      generate_metadata=generate_metadata,                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │      custom_header_map = False                                                               │ │
│ │           data_outfile = None                                                                │ │
│ │             extra_args = <click.core.Context object at 0x153c6ae1f580>                       │ │
│ │               filename = PosixPath('/nfs/ftp/public/databases/gwas/summary_statistics/GCST0… │ │
│ │      generate_metadata = True                                                                │ │
│ │             header_map = {}                                                                  │ │
│ │              meta_dict = {'file_type': 'pre-GWAS-SSF', 'genome_assembly': 'GRCh37'}          │ │
│ │     metadata_edit_mode = True                                                                │ │
│ │ metadata_from_gwas_cat = True                                                                │ │
│ │        metadata_infile = None                                                                │ │
│ │       metadata_outfile = None                                                                │ │
│ │    minimal_to_standard = False                                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /hps/nobackup/parkinso/spot/gwas/data/sumstats/formatting/earl/ssformat/lib/python3.9/site-packa │
│ ges/gwas_sumstats_tools/format.py:144 in format                                                  │
│                                                                                                  │
│   141 │   # Get metadata                                                                         │
│   142 │   if generate_metadata:                                                                  │
│   143 │   │   print("[bold]\n---------- METADATA ----------\n[/bold]")                           │
│ ❱ 144 │   │   metadata = formatter.set_metadata(                                                 │
│   145 │   │   │   from_gwas_cat=metadata_from_gwas_cat, custom_metadata=metadata_dict            │
│   146 │   │   )                                                                                  │
│   147 │   │   print(metadata)                                                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │           data_outfile = None                                                                │ │
│ │               filename = PosixPath('/nfs/ftp/public/databases/gwas/summary_statistics/GCST0… │ │
│ │              formatter = <gwas_sumstats_tools.format.Formatter object at 0x153c6ae1fa30>     │ │
│ │      generate_metadata = True                                                                │ │
│ │             header_map = {}                                                                  │ │
│ │          metadata_dict = {'file_type': 'pre-GWAS-SSF', 'genome_assembly': 'GRCh37'}          │ │
│ │ metadata_from_gwas_cat = True                                                                │ │
│ │        metadata_infile = None                                                                │ │
│ │       metadata_outfile = None                                                                │ │
│ │    minimal_to_standard = False                                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /hps/nobackup/parkinso/spot/gwas/data/sumstats/formatting/earl/ssformat/lib/python3.9/site-packa │
│ ges/gwas_sumstats_tools/format.py:95 in set_metadata                                             │
│                                                                                                  │
│    92 │   │   )                                                                                  │
│    93 │   │   if from_gwas_cat:                                                                  │
│    94 │   │   │   accession_id = parse_accession_id(filename=self.data_infile)                   │
│ ❱  95 │   │   │   meta_dict.update(metadata_dict_from_gwas_cat(accession_id=accession_id))       │
│    96 │   │   if custom_metadata:                                                                │
│    97 │   │   │   meta_dict.update(custom_metadata)                                              │
│    98 │   │   self.meta.update_metadata(meta_dict)                                               │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ──────────────────────────────────────╮            │
│ │    accession_id = 'GCST001404'                                                    │            │
│ │ custom_metadata = {'file_type': 'pre-GWAS-SSF', 'genome_assembly': 'GRCh37'}      │            │
│ │   from_gwas_cat = True                                                            │            │
│ │       meta_dict = {                                                               │            │
│ │                   │   'genotyping_technology': None,                              │            │
│ │                   │   'gwas_id': 'GCST001404',                                    │            │
│ │                   │   'trait_description': None,                                  │            │
│ │                   │   'minor_allele_freq_lower_limit': None,                      │            │
│ │                   │   'data_file_name': 'GCST001404_buildGRCh37.tsv',             │            │
│ │                   │   'file_type': 'GWAS-SFF v1.0',                               │            │
│ │                   │   'data_file_md5sum': 'd735db9caa99bc6704819f2dc281e9de',     │            │
│ │                   │   'is_harmonised': False,                                     │            │
│ │                   │   'is_sorted': False,                                         │            │
│ │                   │   'date_last_modified': datetime.date(2023, 9, 8),            │            │
│ │                   │   ... +12                                                     │            │
│ │                   }                                                               │            │
│ │            self = <gwas_sumstats_tools.format.Formatter object at 0x153c6ae1fa30> │            │
│ ╰───────────────────────────────────────────────────────────────────────────────────╯            │
│                                                                                                  │
│ /hps/nobackup/parkinso/spot/gwas/data/sumstats/formatting/earl/ssformat/lib/python3.9/site-packa │
│ ges/gwas_sumstats_tools/interfaces/metadata.py:102 in metadata_dict_from_gwas_cat                │
│                                                                                                  │
│    99 │   │   │   │   │   │   │   │   │   │    fields_to_split=STUDY_FIELD_TO_SPLIT)             │
│   100 │   sample_url = study_url + "/samples"                                                    │
│   101 │   sample_response = download_with_requests(url=sample_url, params={"size": 100})         │
│ ❱ 102 │   samples_list = _parse_gwas_api_samples_response(sample_response,                       │
│   103 │   │   │   │   │   │   │   │   │   │   │   │   │   replace_dict=GWAS_CAT_SAMPLE_MAPPING   │
│   104 │   │   │   │   │   │   │   │   │   │   │   │   │   fields_to_split=SAMPLE_FIELD_TO_SPLI   │
│   105 │   meta_dict['samples'] = samples_list                                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    accession_id = 'GCST001404'                                                               │ │
│ │       meta_dict = {                                                                          │ │
│ │                   │   'study_tag': 'ieu-a-1057',                                             │ │
│ │                   │   'studyId': '6196625d81051b000178b83d',                                 │ │
│ │                   │   'study_accession': 'GCST001404',                                       │ │
│ │                   │   'sample_description': '41 Japanese ancestry cases, 866 Japanese        │ │
│ │                   ancestry controls',                                                        │ │
│ │                   │   'trait': 'Gallbladder cancer',                                         │ │
│ │                   │   'summary_statistics_file': 'formatted_ieu-a-1057.tsv',                 │ │
│ │                   │   'checksum': 'd735db9caa99bc6704819f2dc281e9de',                        │ │
│ │                   │   'genome_assembly': 'GRCh37',                                           │ │
│ │                   │   'agreedToCc0': True,                                                   │ │
│ │                   │   'submissionId': '619660e406ff2000019198bc'                             │ │
│ │                   }                                                                          │ │
│ │ sample_response = b'{\n  "_links" : {\n    "self" : {\n      "href" :                        │ │
│ │                   "http://www.ebi.ac.uk/gwas/ingest'+163                                     │ │
│ │      sample_url = 'https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST001404/samples'      │ │
│ │  study_response = b'{\n  "study_tag" : "ieu-a-1057",\n  "studyId" :                          │ │
│ │                   "6196625d81051b000178b83d",\n  "stu'+375                                   │ │
│ │       study_url = 'https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST001404'              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /hps/nobackup/parkinso/spot/gwas/data/sumstats/formatting/earl/ssformat/lib/python3.9/site-packa │
│ ges/gwas_sumstats_tools/interfaces/metadata.py:156 in _parse_gwas_api_samples_response           │
│                                                                                                  │
│   153 │   formatted_list = []                                                                    │
│   154 │   if response:                                                                           │
│   155 │   │   result_dict = json.loads(response.decode())                                        │
│ ❱ 156 │   │   sample_list = result_dict["_embedded"].get('samples')                              │
│   157 │   │   if sample_list:                                                                    │
│   158 │   │   │   for element in sample_list:                                                    │
│   159 │   │   │   │   if replace_dict:                                                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ fields_to_split = ('ancestry_method', 'sample_ancestry')                                     │ │
│ │  formatted_list = []                                                                         │ │
│ │    replace_dict = {                                                                          │ │
│ │                   │   'size': 'sample_size',                                                 │ │
│ │                   │   'ancestry': 'sample_ancestry',                                         │ │
│ │                   │   'ancestryMethod': 'ancestry_method',                                   │ │
│ │                   │   'caseControlStudy': 'case_control_study',                              │ │
│ │                   │   'caseCount': 'case_count',                                             │ │
│ │                   │   'controlCount': 'control_count'                                        │ │
│ │                   }                                                                          │ │
│ │        response = b'{\n  "_links" : {\n    "self" : {\n      "href" :                        │ │
│ │                   "http://www.ebi.ac.uk/gwas/ingest'+163                                     │ │
│ │     result_dict = {                                                                          │ │
│ │                   │   '_links': {                                                            │ │
│ │                   │   │   'self': {                                                          │ │
│ │                   │   │   │   'href':                                                        │ │
│ │                   'http://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST001404/samples?page=… │ │
│ │                   │   │   }                                                                  │ │
│ │                   │   },                                                                     │ │
│ │                   │   'page': {                                                              │ │
│ │                   │   │   'size': 100,                                                       │ │
│ │                   │   │   'totalElements': 0,                                                │ │
│ │                   │   │   'totalPages': 0,                                                   │ │
│ │                   │   │   'number': 0                                                        │ │
│ │                   │   }                                                                      │ │
│ │                   }                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: '_embedded'

**Comment by ljwh2** [comment]
I agree it makes sense to wait until we can fix the errors. Let's discuss with Yue in the first instance but we may need to wait for Karatug.

**Comment by earlEBI** [comment]
I also just found a yaml for a more recent GCST which seems to have failed silently - GCST90271757 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXlmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6fb5fae0e15a49a0fd010a8fd30e1994bbef1de0/Screenshot%202023-09-14%20at%2017.02.04.png)
So, the readme info entered into the submission template has not been copied across. 

All of the other GCSTs for the submission: GCST90271752 to GCST90271756 have been generated correctly, eg:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblNmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0ad0054adcce4b8f83290a9158149db449f98182/Screenshot%202023-09-14%20at%2017.05.10.png)

**Comment by jiyue1214** [comment]
Here are two different issues:
GCST006079 

- issue: the samples info is empty
- cause: no API entry for this study (https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST006079 ). Help from Sajo, ‘GCST006079’ was created in Curation app before Submission app was created hence no data is pulled for this
- solution: A broader discussion with curators and Sajo is needed to resolve this issue.

GCST90077560
- issue: no ancestry info
- cause: The metadata information for this study does not include the keyword, "sample_ancestry". (https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST90077560/samples) and the formatter failed to extract ancestry info.
- Solution:
1. Discuss with curators how to fill sample_ancestry for studies.
2. Use ancestry_category instead of sample_ancestry to write metadata.

**Comment by sprintell** [comment]
@sprintell please check with @jiyue1214 what the progress of this is.

**Comment by jiyue1214** [comment]
I am making some revisions to the code for:
1. When the ingest API is available: 
    * Show both ancestry and ancestry_category
    * Show multi-ancestries in different lines
2. When the ingest API is not available:
    * Extract yaml file required fields from the Rest API, and omit fields that are not available to extract from the rest API.

**Comment by jiyue1214** [comment]
In addition to the previous revisions to the code, I made additional revisions to make the yaml output prettier:
1. Date_last_modified -> Date_metadata_last_modified
2. Reorder to show Ancestry_category firstly (mandatory field) and then ancestry
3. For multiple ancestry groups, but only one number, show sample information correctly ( GCST001482, GCST90278188)
4. Showing categories comments in the yaml file

Next step: Merge the branch to the master (pull request) -> Karatug need to review the code and accept the request to generate a new release on gwas-sumstat-tool.
