### ISSUE TITLE
Replace incorrect sumstats files for 2 studies (PMID 37291194)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1121]
The author of this publication (PMID 37291194) has brought to our attention an error in the summary statistics files, which affects 2 studies.

The author has sent us amended copies of the files and these are currently stored on the private FTP. I have identified the following information, which is stored in the attached Excel spreadsheet:

**study_accession**: GCST of the study
**study_tag**: Study tag for the study in the original submission
**study_directory**: Existing directory for this study on the public FTP
**current_filename**: Filename of the current summary statistics file (within the study_directory) which contains the error and needs to be replaced
**replacement_directory**: Location of the new corrected file, which needs to be moved to the study_directory to replace the old file. Note that the replacement files are split between two subfolders, depending on the type of study (single variant vs gene burden), but I don't think this should affect the replacement process. 
**replacement_filename**: Filename of the new replacement summary statistics file (within the replacement_directory). When the new file is moved to the study_directory, it should be renamed to match the current_filename.
**replacement_md5sum**: md5sum of the replacement file

I need help to replace these files in bulk. I think the steps should be:
1. Move each **replacement_filename** from **replacement_directory** on private FTP to **study directory**, to overwrite the **current_filename**.
2. Update the YAML file in the **study_directory**: the only thing that should need changing in the YAML file is the md5sum. Everything else should stay the same.
3. Update the md5sum.txt file to display the new md5sum.
4. Restart harmonisation of the file (I'm not sure of the details about this).

[37291194-amendments-plan.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2VOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5318083909b6f1929043b8d377de0383f008d644/37291194-amendments-plan.xlsx)

**Comment by eks-ebi** [comment]
confirmed, files have been synced

**Comment by earlEBI** [comment]
Will pass GCSTs to Yue to be re-harmonised.
