### ISSUE TITLE
Create new submission for 36914875 and update sumstats files

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1125]
The author of this publication would like to make a correction to the existing sumstats files, and add additional studies with new sumstats files. The new files have all been uploaded via Globus, and we now need to make a new submission that should replace the existing data.

Process has been discussed and agreed as follows (review as needed throughout process):

- [x] Obtain new files from author via Globus - @eks-ebi 
- [x] Create new meta-data template with author's help - @eks-ebi 
- [x] Reset the PMID in deposition to allow a new sumstats+metadata submission - @sajo-ebi
- [x] Unpublish existing studies in curation interface -  @eks-ebi 
- [x] Create spreadsheet of original GCSTs and study tags -  @eks-ebi 
- [x] Create new submission - @eks-ebi 
- [x] Upload new summary statistics via Globus, add new metadata template and complete new submission - @eks-ebi 
- [x] Map new GCSTs to the old ones and add to spreadsheet - @eks-ebi 
- [x] Manually change the new GCSTs back to the original ones - @sajo-ebi 
- [x] Import new submission into curation interface - @eks-ebi 
- [x] Make sure that the existing studies have been replaced and retain original GCSTs, and that there are new entries for the new studies with new GCSTs - @eks-ebi 
- [x] Make sure new folders have been created for new studies in staging - @eks-ebi 
- [x] Where applicable, move new sumstats files to the old GCST folders  and replace the old ones
- [x] Delete the newly made redundant folders on staging

**Comment by sajo-ebi** [comment]
@eks-ebi Pmid '36914875' is open for submission

**Comment by eks-ebi** [comment]
New submission is here: https://www.ebi.ac.uk/gwas/deposition/submission/6501d04d788f0000012e6c59

**Comment by eks-ebi** [comment]
New submission has been created, but sumstats fail validation. This is expected, because they are in the old format. However, I will need to run the old validator (ss-validate) on them to make sure there are not any additional errors in the files. A quick first check suggests there is an issue with the header row. To be investigated tomorrow.

**Comment by eks-ebi** [comment]
@sajo-ebi I've now finally completed the submission and pushed the files through validation. Could you please now change the GCSTs for the four original studies back to what they were before? (As discussed, the remaining studies are all new so the GCSTs do not need to be changed)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakg2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a35aaea96b80fbaff24feff200e332bb190e3a61/image.png)

**Comment by sajo-ebi** [comment]
@eks-ebi can you copy the old & new GCST in the ticket , easier to create a DB query that way

**Comment by sajo-ebi** [comment]
@eks-ebi done , please validate

**Comment by eks-ebi** [comment]
@sajo-ebi yes, looks good!

**Comment by earlEBI** [comment]
@eks-ebi 
I've:
- removed the yamls and md5sums from the public ftp.
- moved new files to staging
- updated md5sum in md5sum.txt and yaml on staging
the three files should hopefully sync to public ftp overnight.

**Comment by eks-ebi** [comment]
@earlEBI thank you so much, all sumstats, md5sum.txt and yaml files have synced overnight!
