### ISSUE TITLE
Investigate unreleased sumstats for GCST90281274

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1126]
This study (submitted in GCP000725) has not been released to the public FTP even though the embargo period has passed. Could you please investigate this, and release the sumstats if required?

**Comment by sajo-ebi** [comment]
@eks-ebi the sumstats should have released now, kindly validate

**Comment by eks-ebi** [comment]
@sajo-ebi confirmed - sumstats are now released
