### ISSUE TITLE
Bug in exporting Studies table

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1127]
A user has reported a bug, where it is not possible to export data from the Studies table on a trait page.

For example, on this page: https://www.ebi.ac.uk/gwas/efotraits/EFO_0005741. On the Associations and Summary statistics tables, the export button works and returns a .tsv. However, on the Studies table, the export button returns an unexpected message: https://www.ebi.ac.uk/gwas/api/v2/efotraits/EFO_0005741/studies/download?includeBgTraits=false&includeChildTraits=true

I have tested it and clicking Export opens a new tab with only this message: `Index: 4, Size: 4`

**Comment by ljwh2** [comment]
This was due to commas in sample description that weren't handled. Fixed but needs releasing in prod.

**Comment by sprintell** [comment]
Not working yet, @sajo-ebi will double-check

**Comment by sprintell** [comment]
Not working yet, @sajo-ebi will double-check

**Comment by sajo-ebi** [comment]
fix deployed in Prod
