### ISSUE TITLE
Delete user submission - 650825d7788f0000012f8e31 - and update prefilled metadata - PMID 34493870

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1130]
The metadata in this prefilled template needs updating. 

Please delete this submission '650825d7788f0000012f8e31' so I can update the metadata in Curation App.

I will then comment on this ticket with the new metadata which I believe a developer needs to add to depocuration. 

I should then be able to create a new submission and download a corrected template.

**Comment by earlEBI** [comment]
The user is waiting for me to do this.

**Comment by sajo-ebi** [comment]
@earlEBI the submission has been deleted

**Comment by earlEBI** [comment]
I don't know which way @sajo-ebi wants to do it, but if I pass the GCSTs that were created in the Curation app... they are GCST013196 and GCST013197... which might be strange as sumstats brackets start from [GCST000001-GCST001000/](http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST000001-GCST001000/)
