### ISSUE TITLE
GCST change for PMID: 33230300 (submission id:60c366fa53729000012f79f7)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1131]
The following GCST should be changed:
GCST90292471 change back to GCST012378
GCST90292472 change back to GCST012377
GCST90292473 change back to GCST012376

This is an old paper (2021) where these 3 studies without sumstats were submitted by the curation app, and the rest of the studies with sumstats were submitted through the deposition app. The submission was unpublished to add more studies (without sumstats), and the GCST for these 3 studies was changed and needs to be changed back to the original ones.

**Comment by Santhi1901** [comment]
@sajo-ebi It is not imported to the curation app.

**Comment by ljwh2** [comment]
can this ticket be closed @Santhi1901 ?

**Comment by Santhi1901** [comment]
yes, this can be closed. It is completed.
