### ISSUE TITLE
Summary statistics not released to public FTP as expected

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1132]
I checked for 'date submission last updated' going back 7 days and found **3 submissions which have not been released as expected:** 
1. **'65064a3753c4ef00014a72d6'** - GCST90292488 - appears on staging. last updated on 18th. not on public. (parent directory also not on public). Embargo date is ‘2023-09-16’.
   - appears in the 'unexpected on staging' list of summary statistics release report e-mail. 
2. **'650780a153c4ef00014a7b2b'** - GCST90267361-GCST90267364 inclusive - appears on staging. last updated on 18th. not on public. no embargo date as not a BoW.
   - appears in 'unexpected on staging' list.
3. **'64f84d3f788f0000010f81cb'** - GCST90281365 - appears on staging. last updated on 14th. no embargo date as not a BoW.
   - appears in 'unexpected on staging' list. 

**The most recent submission I can find which was released correctly:**
1. '64f84d3f788f0000010f81cb' - eg. GCST90281274 - lasted updated on 12th. released to public on 15th. Embargo date was '2023-09-12'.
   - had appeared in the 'unexpected on staging' list on 13th. A ticket was made to release manually.

**Comment by sprintell** [comment]
@earlEBI could you please help check this in details ...

**Comment by earlEBI** [comment]
@sprintell The first two have been released as expected. The third one needs to be prioritised for curation by curators in order to be released.

**Comment by ljwh2** [comment]
@Santhi1901 confirmed all unembargoed GCSTs to date have been released. Closing ticket, but we will keep an eye going forward.
