### ISSUE TITLE
Deployment of Obsolete EFO process

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/goci#1134]
to finish goci#564

**Comment by sajo-ebi** [comment]
Done , need one particular clarification before pushing to Prod

**Comment by sprintell** [comment]
@sajo-ebi will do this before the next Data release

**Comment by sprintell** [comment]
This should be closed at the end of sprint, a new ticket be created to fix the credentials in git problem

**Comment by sajo-ebi** [comment]
This is done & deployed in Prod using Bamboo

**Comment by sajo-ebi** [comment]
@sprintell have created [https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/gwas-data-services/30](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/gwas-data-services/30) to track git history cleanup issue
