### ISSUE TITLE
Celery error - studies not moved to staging - GCP000726

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1137]
study ID '6504680ce6cd8200013a05f6'
5,543 studies
Only SOME of the GCSTs from this submission have appeared on staging correctly: from GCST90286909 to GCST90287029.
   - although GCST90287029 has been created on staging, no Yaml file has been created.
   - I don't think any of the GCSTs from this point onwards were created. GCST90287030 to GCST90292451.
   - We received a celery error containing these GCSTs, ending:
      **"Exception was raised: Can only use .str accessor with string values!"**
          - I wonder if this is because some of the study tags entered by the user are numbers, not strings. See GCST spreadsheet: [gcst_list - 2023-09-21T142336.281.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVBEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0de07de562f4a04997af519f190ee2f6ae428b50/gcst_list%20-%202023-09-21T142336.281.xlsx)
             - note: a level 2 curator will need to re-upload the template after making edits at some point. 
             
**To do**: missing GCSTs need to be created on staging along with yaml files for GCST90287029 onwards.
- I don't know if a validation step needs to be put in place to stop users from submitting numbers as study tags, or whatever the issue is.

**Comment by ljwh2** [comment]
Moving to backlog pending info from author. @earlEBI please flag me in the ticket when this is recieved.

**Comment by earlEBI** [comment]
@ljwh2 
The user got back to us with updated traits which I added to the submission template and re-uploaded via Depocuration. 
The sumstats files still need to be moved from the original Globus folder to staging before they are auto-deleted, and yaml files generated.

**Comment by ljwh2** [comment]
Need to clarify if action is needed by Sajo or Lizzy

**Comment by sprintell** [comment]
Need to clarify if action is for @earlEBI

**Comment by earlEBI** [comment]
@sprintell @ljwh2 I can only move the files to staging, but then I would have to regenerate the yamls manually and that may not pull the same information (from the submission template) as would be generated from scratch. So if there is a way to re-kick off the process that moves the files to staging _along with yamls_ then that would be preferable.

**Comment by ljwh2** [comment]
@earlEBI: since Yue is recreating the yamls for all studies shortly, will that solve the problem?

**Comment by earlEBI** [comment]
@ljwh2 I assume so, depending on how Yue finds files to [re]generate yamls for. Should I move the files to staging, in that case?

**Comment by ljwh2** [comment]
@earlEBI yes, please move the files to staging and @jiyue1214 will handle the yaml file generation.

**Comment by earlEBI** [comment]
These studies should now all be in their staging directories without yamls, to be released to public once embargo is lifted.
