### ISSUE TITLE
Deleting multiple GCP associated with PMID 35512355

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1143]
The author submitted 3 different submissions, GCP000314, GCP000302, and GCP000316, for the PMID. Upon request, they clubbed the data and submitted it directly to 35512355 (https://www.ebi.ac.uk/gwas/deposition/submission/6285d8a9a2d24400017d85c5). 

Need to delete the 3 GCPs; not sure if GCSTs also need to be deleted.

**Comment by sajo-ebi** [comment]
@Santhi1901 the GCST are different for these body of works from the submission, kindly confirm of it is still fine to delete body of work.

**Comment by Santhi1901** [comment]
@ljwh2 do we need to delete the GCSTs for these submissions? all the submissions are under embargo (GCP000314, GCP000302, and GCP000316). and the correct [submission](https://www.ebi.ac.uk/gwas/deposition/submission/6285d8a9a2d24400017d85c5) is already available on the [Catalog](https://www.ebi.ac.uk/gwas/publications/35512355)

**Comment by ljwh2** [comment]
Yes, the 3 GCPs mentioned and associated GCSTs can be deleted

**Comment by sprintell** [comment]
This will be done before the Data Release by @sajo-ebi

**Comment by sajo-ebi** [comment]
the Body of works & the associated studies &s submission have been deleted from Deposition side

**Comment by ljwh2** [comment]
@Santhi1901  please confirm this looks ok from your side

**Comment by Santhi1901** [comment]
it looks ok
