### ISSUE TITLE
Deleting multiple GCP associated with PMID 36329257

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1144]
User submitted 2 different submissions for this PMID: GCP000440 (2 studies) and GCP000443 (1 study).

They also submitted sumstats directly to pmid: 36329257 (3 studies with sumstat) (https://www.ebi.ac.uk/gwas/deposition/submission/637349737325c2000189ffca). GCST mentioned in the paper matches this submission.

Need to delete 2 GCPs; not sure if the GCSTs also needs to be deleted.

**Comment by sajo-ebi** [comment]
@Santhi1901 The GCP's have been deleted from DB
