### ISSUE TITLE
Make and Inventory of all changes required for SLurm Migration and Analyse 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#1158]

**Comment by karatugo** [comment]
Here's the list of LSF usage in our repos. https://docs.google.com/spreadsheets/d/16MWz8ZaKubWdYHu0WP6gJ_Py53FUR0iD6TdnsnHKZ-k/edit?usp=sharing

**Comment by sajo-ebi** [comment]
List of LSF usage in Bamboo, Shell scripts in VM & Java repository
[Slurm_Inventory](https://docs.google.com/spreadsheets/d/1sS7rhjVe3hlbR3FI91xfmJBHdDuepCTg1KgvjbSVtpQ/edit#gid=0)
