### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#116]
Adding a citation and updating submission documentation to strengthen message about validation

**Comment by twhetzel** [comment]
@ljwh2 do you have any more changes? Were you able to confirm your updates on Snoopy 9580?

**Comment by ljwh2** [comment]
updated submission-content.adoc

**Comment by ljwh2** [comment]
@twhetzel all changes now made, but i can't see them on Snoopy 9580

**Comment by twhetzel** [comment]
@ljwh2 the changes are there now, the site was automatically updated about 54 minutes ago. There is about a ~5 minute delay after committing changes to the `documentation` branch before seeing them on the server.

Let me know if you can see them now and if they look good and all is done to add this to the release.

**Comment by ljwh2** [comment]
All good to go @twhetzel
