### ISSUE TITLE
GCP000466 associated with wrong PMID

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1164]
I added PMID 27481432 to this GCP, using this page in the Submission App: https://www.ebi.ac.uk/gwas/deposition/bodyofwork/GCP000466
I then realised the correct PMID was PMID:37768647
I edited the PMID in the Submission App. The correct PMID is now showing on the GCP page (link above) but when I search for that PMID, no submission is found. It's still linked to the first PMID, see screenshot: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1QQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--918dedbce5ed1be8b998b021ae7f27de22e88e1b/Screenshot%202023-10-06%20at%2008.43.55.png)

I deleted '27481432' from the Curation App to see if it would help, but it hasn't. 
Please delete pmid 27481432 from this GCP and re-assign 37768647. 

This is a newly published submission so should be curated in the next week.

**Comment by ljwh2** [comment]
@sajo-ebi could you please investigate in this sprint, thanks

**Comment by sajo-ebi** [comment]
@earlEBI the submission has been updated to reflect the new Pmid

**Comment by earlEBI** [comment]
looks good thanks
