### ISSUE TITLE
OLS4 - slim solr

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1167]
Analyse what action needs taking in slim solr to ensure smooth switchover to OLS 4

**Comment by sprintell** [comment]
@sajo-ebi will coordinate with @karatugo to give some insight on how to commence with this.

**Comment by sprintell** [comment]
@karatugo wil check if the index files change as expected before DR.

**Comment by karatugo** [comment]
Test OK, can be closed.
