### ISSUE TITLE
update sample numbers for GCP000702

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1169]
submission id '64e39b7ae6cd820001333d7b'
A few weeks ago the user contacted us to update 4 of the prepub sumstats studies and their associated sample numbers. 
I replaced the sumstats files and updated the sample number in the submission template through Depocuration app. 
I've checked the latest data release dev environ but the sample number changes have not carried across to the landing pages. 
The 4 studies can be seen in red on the sample tab of this file:
[gcst_list - 2023-10-12T101349.085.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzRyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1718c815eaf29bb22e5d5e1bd834e5ea4c8f9853/gcst_list%20-%202023-10-12T101349.085.xlsx)

Please update the sample number for these 4 studies for the user. 
TWB.AFP	GCST90278615	discovery	65360
TWB.FEV1	GCST90278626	discovery	62901
TWB.FEV1R	GCST90278627	discovery	62901
TWB.FVC	GCST90278629	discovery	62901

**Comment by sajo-ebi** [comment]
@earlEBI the sample numbers have been updated

**Comment by earlEBI** [comment]
looks good thanks
