### ISSUE TITLE
Submission stuck in depo-curation, blocking trait assign tasks

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1170]
This submission is somehow stuck while loading in depocuration: https://www.ebi.ac.uk/gwas/depo-curation/submissions/63f8add57325c20001210db7

1. There is a spinning wheel in the submission history
2. The bulk assign traits feature is not responsive
3. Approve all SNPs also fails

I've just realised now that there are also duplicates of each study. There should be 4443 studies, but in the studies tab, the table contains 8886 rows with two copies of each study.

**Comment by ljwh2** [comment]
Resolved itself after few hours. Celery workers did not pick up jobs. Unclear why. Sajo will investigate why this happened.
