### ISSUE TITLE
User receives error when submitting - GCP000744

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1171]
submission iD: '6529a5aee6cd8200013bdf6c'

The user contacted us as when they upload their template, they receive this error:

MSA_GWAS_AdditiveSummStats_FINAL_TIDY_VALIDATED.tsv.gz: There is a problem on our side, please contact gwas-subs@ebi.ac.uk for further advice.
MSA_GWAS_RecessiveSummStats_FINAL_TIDY_VALIDATED.tsv.gz: There is a problem on our side, please contact gwas-subs@ebi.ac.uk for further advice.

I've checked that their files pass validation offline, and they are present in the Globus folder. 
Their metadata passes validation. 
But the status is 'template invalid'. I tried copying the unformatted rows to a new template but still the same error appears.

Please investigate, thank you.

**Comment by sajo-ebi** [comment]
Discussed with James , this was caused by some celery worker issue , have retriggered the validation manually , the submission should go through in some time

**Comment by earlEBI** [comment]
Thank you. It is still showing as TEMPLATE INVALID to me.

**Comment by sajo-ebi** [comment]
@earlEBI the submission is now sorted , it should be picked by ftp sync to copy files to staging & Prod

**Comment by earlEBI** [comment]
Thanks!
