### ISSUE TITLE
Sumstats download stats - user request - 30054458

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1175]
GWAS-info request, 
Please provide the number of times the summary statistics file for GCST006867 has been downloaded. 
Thank you

**Comment by ala-ebi** [comment]
-https://meter.ebi.ac.uk/app/kibana/
-dashboards
-ftpLogs
-untick default filters
-add filter: "file_name" is {FTP path for GCST} (e.g. /pub/...../GCST120-GCST130/GCST125/*)
-click the search button in top search bar
-results are towards the bottom of the page
