### ISSUE TITLE
Submission GCP000565 not moved to staging as expected

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1176]
I removed the embargo for study id '640fa26482c5590001386883' on 24.10.23
On 25.10.23 I noticed the files had not been moved to public, so I checked on staging but only 8 of the 91 studies are there….
1. why would the 8 that are there (eg. GCST90257015) not have synced to public overnight?
2. is there a way for developers to see what error was thrown that stopped the rest of the studies being created on staging?
3. I can move the files to staging manually … but I’m concerned if I have to create the yamls manually they might not have all the metadata correctly pulled from the template… so is there a way to retrigger moving the files to staging and creating the yamls automatically?

**Comment by sajo-ebi** [comment]
@earlEBI there was an issue with Depo Sync process due to couple of GCP we deleted as part of ticket , we had to manually remove the submissions linked to those deleted GCPIds , the Depo Sync run tonight should create the studies in DB & then FTP sync process should move files from staging to Prod

**Comment by earlEBI** [comment]
@sajo-ebi But shouldn't the directories already be created on staging soon after submission? It was submitted in March. only 8 of the 91 studies are on staging.

**Comment by sajo-ebi** [comment]
@earlEBI they are created in staging after Depo Sync runs & syncs studies , I am not sure about the 8 that are already there , but I checked there are no records for this submissionId yet, it should be picked by depo sync run tonight

**Comment by earlEBI** [comment]
@sajo-ebi The 8 GCSTs which were on staging have been released to public but the other 83 are still missing from staging.

**Comment by ljwh2** [comment]
Note from iteration meeting: The nextflow validation wasn't completed due to some issue with file copy permissions & error not propogated to the backend Submission service , decided to rest the submission & retrigger the sumstats workflow , GCST will need to be changed manually for this

**Comment by ljwh2** [comment]
@sajo-ebi @karatugo  please keep Lizzy updated on the status of this ticket so she can communicate with the user

**Comment by earlEBI** [comment]
The GCSTs now appear on public as expected. but now the landing pages for the GCSTs are appearing as: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1BzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05cfc38323e8f980bec4542de9e9d747922bed11/Screenshot%202023-11-20%20at%2009.49.43.png)

**Comment by earlEBI** [comment]
Landing pages currently appear as expected.
