### ISSUE TITLE
user request - Study API whitelabel error

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1177]
**gwas-info query re: study API:** 

I am writing to inform you about an issue we are currently facing while using the Study API at the following URL: https://www.ebi.ac.uk/gwas/rest/api/studies/GCST90086814.
Unfortunately, we have encountered a whitelabel error page with a status code of 500,
 
Please let me know the estimated timeline for when the API will be responsive and the issue resolved.

**Comment by ala-ebi** [comment]
no problem detected, resolved itself after a few minutes, probably an intermittent memory issue
