### ISSUE TITLE
Setup Monitoring Tools in Hinxton Cluster 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#1178]
As a developer
I need **Prometheaus, Grafana, Alert Manager and Jaeger** to be installed in the Hinxton Kubernetes Cluster.
So we can monitor the cluster as well as all the deployments and services in the cluster.

**Comment by ala-ebi** [comment]
Alerts for:
High mem usage
High CPU usage
Service down

**Comment by sprintell** [comment]
<dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>1.12.0</version>
        </dependency>

**Comment by sprintell** [comment]
<dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>1.12.0</version>
        </dependency>

**Comment by ala-ebi** [comment]
Prometheaus, Grafana on HX done,
Alerts to be added

**Comment by ljwh2** [comment]
Slack alerts set up - also add email to gwas-dev
