### ISSUE TITLE
Migrate Spring Framework

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#1183]
- [ ] GWAS Search UI:               https://github.com/EBISPOT/gwas-ui
- [ ] GWAS Template Validator       https://github.com/EBISPOT/gwasdepo-template-validator
- [ ] GWAS Ingest Service           https://github.com/EBISPOT/gwasdepo-ingest-service
- [ ] GWAS Deposition Service       https://github.com/EBISPOT/gwasdepo-deposition-service
- [ ] GWAS Audit Service            https://github.com/EBISPOT/gwasdepo-audit-service
- [ ] GWAS Curation Service         https://github.com/EBISPOT/gwas-curation-service
- [ ] GWAS Curation Infrastructure  https://github.com/EBISPOT/goci

**Comment by ljwh2** [comment]
searchUI to be deployed after DR
