### ISSUE TITLE
Studies on staging not released to public FTP - GCP000165

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1187]
study id '6086a786d805de0001cf9125'
Embargo was removed on Thursday 26th October. 
Study GCST90016665 is on staging and [edit: not] in curation DB unpublished studies table, but has not been released to public.

**Comment by sajo-ebi** [comment]
@earlEBI this is an Old submission whose Status is not in proper state, For Body of work submission the status should be 'DEPOSITION_COMPLETE' but the status is 'SUBMITTED', the study is not in Unpublished_study table , will manually change the status to 'DEPOSITION_COMPLETE' & it should be picked up by Depo Sync today , worth checking the status of old submissions for Body of work submission while changing the embargo date

**Comment by sprintell** [comment]
Hi @earlEBI could you please help confirm if this is good to be closed ? Thanks

**Comment by earlEBI** [comment]
@sprintell looks good, thanks
