### ISSUE TITLE
Remove the pmid from submission GCP000278 (submission ID: 61dd9eb1911f5a00015648a8)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1193]
The PMID (35167808) added to this submission needs to be removed. This is to allow the user to add more studies with sumstats for the submission. 

Presently they have added a single summary statistics file for 47 traits.

**Comment by ljwh2** [comment]
@Santhi1901 please confirm this can be closed

**Comment by Santhi1901** [comment]
The status of PMID is showing closed in the depo app. It needs to be open for submission as the user needs to submit sumstats to the pmid.

**Comment by Santhi1901** [comment]
@sajo-ebi can you delete the PMID from the deposition app and curation app. Also delete the GCP000278 and submission.

**Comment by sajo-ebi** [comment]
@Santhi1901 this is done

**Comment by ljwh2** [comment]
@Santhi1901 can this be closed?

**Comment by Santhi1901** [comment]
yes this can be closed
