### ISSUE TITLE
Calculate metrics for API usage

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1199]
User requires metrics for GWAS Catalog REST API access via  gwasrapidd R package. gwasrapidd accesses the API using the user agent "gwasrapidd: GWAS R API Data Download". User agents are logged in the Load Balancer logs. 

We should calculate relative traffic from gwasrapidd vs other users (i.e. % of total), also considering how much of the traffic is internally generated (e.g. by GWAS Catalog UI).

**Comment by ala-ebi** [comment]
From November last year until today, the total number of valid requests (HTTP response code 200) received by our API was 25053829 out of which 8781152 were from user-agent 'gwasrapidd: GWAS R API Data Download' making up 35% of the total number of requests with a success response.


For future reference, these were the commands used to retrieve both numbers respectively:
```
find . -regextype posix-extended -regex '.*access_.(2022-11|2023).*$' | xargs grep -o '/gwas/rest/api/.*200.*gwasrapidd:\sGWAS\sR\sAPI\sData\sDow.*\n'  | wc -l
242483
find . -regextype posix-extended -regex '.*access_.(2022-11|2023).*$' | xargs grep -o '/gwas/rest/api/.*200.*\n'  | wc -l

```
repeated on all 4 VMs and aggregated.

**Comment by ala-ebi** [comment]
From November last year until today, the total number of valid requests (HTTP response code 200) received by our API was 25053829 out of which 8781152 were from user-agent 'gwasrapidd: GWAS R API Data Download' making up 35% of the total number of requests with a success response.


For future reference, these were the commands used to retrieve both numbers respectively:
```
find . -regextype posix-extended -regex '.*access_.(2022-11|2023).*$' | xargs grep -o '/gwas/rest/api/.*200.*gwasrapidd:\sGWAS\sR\sAPI\sData\sDownload.*'  | wc -l
find . -regextype posix-extended -regex '.*access_.(2022-11|2023).*$' | xargs grep -o '/gwas/rest/api/.*200.*'  | wc -l

```
repeated on all 4 VMs and aggregated.
