### ISSUE TITLE
Publication page - feedback from testing

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1201]
- [x] Export button does not work - deprioritised as needs back end work
- [x] Add filter for status
- [x] Add filter for submitter
- [x] Submitter sort does not work but can be removed if filter for submitter is added
- [x] Sorting sometimes doesn't work after expanding the number of rows to 50
- [x] Sort by First author should be on surname not first intial
- [x] Sort by Title does not work but also is not required, so can be removed.
- [x] Curators would prefer to have an explicit "save" action after changing curator and status

Main feedback doc is here: https://docs.google.com/document/d/1hlihpeERA0beyRoMJT5OvzIHWaJNRGjamxCdOvTSUy4/edit

**Comment by sprintell** [comment]
Crate a ticket for optimizing codebase of backend search filter @ala-ebi
