### ISSUE TITLE
Recreating yaml files

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1207]
Due to goci#1118, several metadata yaml files have missing info. In addition, Yue has made several improvements on layout. The yaml files should be recreated for all existing unharmonised summary statistics, and any harmonised summary statistics harmonised with the new pipeline.

**Comment by jiyue1214** [comment]
1. meta-yaml file generated during data submission was not generated by the gwas-sumstat-tools, instead, gwas-sumstat-service convert_meta.py converted meta.xlsx into meta.yaml file.
2. The YAML file generation script cannot automatically detect the file type, we need to read the original meta.yaml file to generate the new one (which is supported by the function -e --file_type=$old_yaml_file_type)

**Comment by ljwh2** [comment]
@earlEBI could you please spot check some yaml files to check they look ok? Particularly ones that had missing info before.

**Comment by jiyue1214** [comment]
From @earlEBI: Lizzy noticed that the prepublication submissions' YAML files lacked trait descriptions. This occurred because the ingest API didn't have the trait descriptions initially. However, the trait descriptions in the old YAML files, which were created by the gwas-sumstat-service, were available because they came directly from the user's template.

What to do next: Lizzy will provide a list containing prepublication GCSTs, and then Yue needs to check their trait description from old yaml files and regenerate yaml files for them.

**Comment by earlEBI** [comment]
I've checked quite a few accession IDs and for the most part they look good but there's a few issues I see:
1. As mentioned above, prepublication submissions don't have trait information. Here is the list of 16,000 accession IDs affected. (note: I found 2 prepub submissions that DO have trait info (eg. GCST90204063-GCST90201021)... so I'm not sure why that would be. Therefore the list is not created from prepublication submissions but was done through searching for all yamls that do not contain the line 'trait_description')
[no-trait-in-yaml.txt](https://github.com/EBISPOT/goci/files/13873367/no-trait-in-yaml.txt)

2. Duplicated sample information for some studies eg. GCST90010229 (submission id '5f697cd6a54daa00013cf263')
      - known issue for a different submission, ticket: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1218
      - The duplicates are in the ingest API eg: https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST90010190/samples
3. Missing YAMLs for eg. GCST90287029, related to duplicate issue above 
4. Some files are still in the old format - possibly just one bracket affected - GCST90302001-GCST90303000

**Comment by jiyue1214** [comment]
Thank you for your help in reviewing the YAML files and the detailed report. I wanted to share my plan and progress here:

1. I have kept all original YAML files and can regenerate meta-YAML files for all prepublication studies as needed.
2. @sajo-ebi is helping me investigate why their samples are duplicates. Once the ingest API is functioning properly, I will generate YAML files for them.
3. Same as step 2.
4. GCST90302001-GCST90303000 comes into the staging folder after I regenerate yaml files and I missed them. I will generate yaml files for them.

**Comment by earlEBI** [comment]
I think there is another issue I had not yet encountered:
- For submission id '6525d89b53c4ef00014bcc25', GCST90297535 - GCST90297272 , the sample information is empty: []

**Comment by ljwh2** [comment]
Replication stage issue - yaml files have been regenerated by @jiyue1214

**Comment by jiyue1214** [comment]
Yue updates:
- [x] Prepublication submissions don't have trait information: Yue has fixed the code causing it (trait was named as trait_description), and has regenerated meta-YAML files for all prepublication studies.
- [ ] Replicated samples: Yue needs to regenerate meta-yaml files and remove duplicate samples (Meanwhile, @sajo-ebi  will clean the database. ).
- [ ] Meta-yaml file for new submissions: new gwas-sumstat-service is released. Yue needs to check and generate a new meta-yaml file for files which are still in old format

**Comment by jiyue1214** [comment]
replicated samples:
@jiyue1214 needs to keep an eye on regenerating meta-yaml files for those submissions.
| submission ID | GCP_id | affected studies | PMID |
| --- | --- | --- | --- |
| 6504680ce6cd8200013a05f6 | GCP000726 | GCST90286909-GCST90292451 | |
| 5f697cd6a54daa00013cf263 | GCP000054 | GCST90007534-GCST90010354 | |

**Comment by jiyue1214** [comment]
Yue updates:
- [x] Prepublication submissions don't have trait information: Yue has fixed the code causing it (trait was named as trait_description), and has regenerated meta-YAML files for all prepublication studies.
- [x] Missing Sample: GCST90297535 - GCST90297272, has regenerated meta-YAML files for these files
- [x] Replicated samples: Yue needs to regenerate meta-yaml files and remove duplicate samples (Meanwhile, @sajo-ebi  will clean the database. ).
- [x] Meta-yaml file for new submissions: new gwas-sumstat-service is released. Yue needs to check and generate a new meta-yaml file for files which are still in the old format

**Comment by jiyue1214** [comment]
@earlEBI, Lizzy. Only if you have time, could I ask for your help to check them? Thank you so much for your help!

**Comment by earlEBI** [comment]
I've checked all the problem yamls I found before and they look good, except for one more which has duplicate samples I'm sorry I didn't mention before. @jiyue1214 Please could you regenerate yamls for these two GCSTs, without duplicate samples? 
GCST90002218
GCST90002217

I will add the submission to the ticket for Sajo to fix in database as well.

**Comment by ljwh2** [comment]
@earlEBI with generate the yamls mentioned in the previous comment

Closing ticket as other parts are all now implemented.
