### ISSUE TITLE
Disable author PMID addition feature

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1210]
Currently, authors and curator both have the possibility to add PMIDs to submissions via the deposition app. Since we have no way to know when an author has added a PMID, this can cause confusion. In the short term, this feature could be disabled for authors.

**Comment by ljwh2** [comment]
The "Add PMID" link appears on the Body of Work page e.g. https://www.ebi.ac.uk/gwas/deposition/bodyofwork/GCP001022 (note I can't guarantee this hasn't had a PMID added since I wrote the ticket). We could replace the functionality so that clicking the link opens an email to gwas-subs (like the feedback link on the righthand side). Ideal the email should be titled "Request to add PMID to submission"

**Comment by sprintell** [comment]
STll in sandbox @ljwh2  could you please help confirm this works now

**Comment by ljwh2** [comment]
This looks good in sandbox and the email link works. Suggest changing the text to: To associate this submission with a journal publication, contact gwas-subs@ebi.ac.uk and quote the PubMed ID
