### ISSUE TITLE
Update SNP validation tool to use same version of Ensembl as mapping pipeline

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1213]
The SNP validation tool is hard coded to a specific Esembl database. This needs manually updating to use the same version as the main SNP mapping pipeline, now and each time a full remapping is done

**Comment by sprintell** [comment]
Should be released after full database remap

**Comment by ljwh2** [comment]
@Santhi1901 this is now in sandbox, please couodl you test it? @ala-ebi to provide details
