### ISSUE TITLE
Check yaml files get generated for all studies in GCP000726

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1218]
Please confirm metadata yaml files have been corrected generated for studies in GCP000726 as described in goci#1137

**Comment by jiyue1214** [comment]
I generated YAML files for the top 10 studies and I found their sample info is duplicated (example:https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST90292447/samples) on the ingest API. Could someone help me with it?

**Comment by earlEBI** [comment]
This is another submission id affected by this issue: 5f697cd6a54daa00013cf263. I can see from gwas-info there were “unforeseen technical issues” (in Jan 2021) but i don’t know what they were.

**Comment by jiyue1214** [comment]
- For GCP000726, please review the progress on #1207
- '5f697cd6a54daa00013cf263', @earlEBI  Could I know more details on it? If it is not a YAML file issue, should we create a new ticket for it? Thanks!

**Comment by earlEBI** [comment]
@jiyue1214 Hi Yue, sorry this was more a note for Sajo to see when he was investigating, that there was a similar issue to look into. It's now mentioned in [this ticket ](https://github.com/EBISPOT/goci/issues/1234)that Sajo hopes to resolve by reuploading the template. It's the very old submission from 2020. The yamls are affected in the same way as the GCP000726 so will need regenerating at some point.

**Comment by jiyue1214** [comment]
I have recreated files for GCP000726 and '5f697cd6a54daa00013cf263'. Once Lizzy @earlEBI  reviews them, this ticket can be closed. Thanks!

**Comment by earlEBI** [comment]
Yamls for both these submissions now look good!
