### ISSUE TITLE
Update Summary Statistics from a Submission

### ISSUE THREAD

**Issue by mcerezof** [EBISPOT/goci#122]
A submitter contacted us (gwas-info from Dennis Van der Meer) 17th July 2020

Hello,
Is it possible to update the 25 GWAS summary statistics for publication 30279459 (hippocampal subfields)? All the meta information is correct but someone pointed out that the beta column is missing for some of these sumstats, and for others the labelling appears off. I have this all fixed in the summary statistics available here: https://mega.nz/file/r1wx2a5a#IoHQc9N7M0i7RrkGZOvbPpatvhvHEc7xrA9S8kIeo3Y  .

**Comment by ljwh2** [comment]
@mcerezof we agreed in the meeting today you would do this manually, please confirm

**Comment by ljwh2** [comment]
@mcerezof please confirm whether this is complete

**Comment by mcerezof** [comment]
I made it last week
