### ISSUE TITLE
Change the GCSTs for 3 studies in the submission 64ede9b253c4ef0001f0e2ab (PMID: 38036550)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1220]
The  GCSTs for 3 studies in this submission should be changed to match the GCSTs mentioned in the article. 
[GCST change.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2x4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f2c71a2afbc27cc4f68cfa416b819ccacb08be5/GCST%20change.xlsx)

The user submitted studies under 2 different GCPs. Added the 3 studies in one GCP (GCP000751) to the other (GCP000711). This submission needs to be published before the next DR on 5th Jan 2024.

**Comment by sajo-ebi** [comment]
@Santhi1901 what should we do with the studies in 2nd column , there are already studies with those GCST , do we need tp delete them?

**Comment by Santhi1901** [comment]
In Pmid 38036550, for these 3 studies GCSTs (in column B) need to be changed to GCST in column C. GCSTs in column C have sumstats associated with them, which are the ones needed.

**Comment by sajo-ebi** [comment]
@Santhi1901 the GCST has been changed & as discussed the submission & studies related to 'GCP000751' has been deleted

**Comment by ljwh2** [comment]
@Santhi1901 can this ticket be closed?

**Comment by Santhi1901** [comment]
yes this is completed
