### ISSUE TITLE
Reharmonising a file with error

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1226]
GCST002047 was not harmonised successfully because our harmonisation pipeline cannot recognise the column “Effect_Allele”. The harmonisation pipeline reads the “effect_allele” column in the input file to harmonise the variant. However, all data in this column is NA. This is the reason why all variants give hm 14. If we change the header of this file, it should be able to be harmonised. (same as other_allele)

Please fix the file and re-qeue for harmonisation

**Comment by karatugo** [comment]
When unzipped two files appeared. I fixed the header for both but the metadata yaml files are missing. Since the study is old, the data is not available from the ingest api.

**Comment by karatugo** [comment]
- [ ] Create metadata yaml files that contain GCST ID and genome assembly for the harmonisation. 
- [ ] Submit the harmonisation

**Comment by karatugo** [comment]
Submitted to codon with the submission script `/hps/software/users/parkinso/spot/gwas/prod/scripts/cron/start_harmonisation_pre_standard_goci1226.sh`

```
Job <92779129> is submitted to default queue <standard>.
```

**Comment by karatugo** [comment]
- [ ] Compare two studies in FTP ("EduYears" and "College")
- [ ] If they are the same, replace the zipped file with the correct one
- [ ] Also, upload only one harmonised file with the correct title

**Comment by karatugo** [comment]
- [ ] Use `variant_id` in the header (as per `pre_gwas_ssf` standard)
- [ ] Rename the file with GCST ID

**Comment by karatugo** [comment]
Using the script at `/hps/software/users/parkinso/spot/gwas/prod/scripts/cron/start_harmonisation_pre_standard_goci1226.sh`

```
Job <93028342> is submitted to default queue <standard>.
```

**Comment by karatugo** [comment]
Harmonised files, metadatta files, running logs and .tbi files are copied to respective harmonised directories. 

- http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST002001-GCST003000/GCST002047/harmonised/
- http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST008001-GCST009000/GCST008396/harmonised/

**Comment by sprintell** [comment]
This is confirmed done, @earlEBI will double check

**Comment by earlEBI** [comment]
Reopening as the yaml files do not look quite right. (is_harmonised = false). 
Also, the .tbi files should be renamed .tbi.gz.

**Comment by karatugo** [comment]
Fixed the following fields:

```
genome_assembly: GRCh38
is_harmonised: true
is_sorted: true
```

@earlEBI Could you check again please? Thanks.

**Comment by earlEBI** [comment]
The yamls are only five lines long. Should they not contain more detail? 

![Screenshot 2024-05-22 at 10 21 14](https://github.com/EBISPOT/goci/assets/61545198/30779ee3-8b6e-4727-8efe-b3ba31b8d534)

**Comment by karatugo** [comment]
I thought that's because it's a very old submission. And also they are not available in the ingest api. @sajo-ebi 

https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST008396
https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST002047

**Comment by sprintell** [comment]
Old studies are meant to be retrieved fromthe public rest API:  https://www.ebi.ac.uk/gwas/rest/api/studies/GCST008396

**Comment by karatugo** [comment]
TODO: Update sumstats tools so that we fetch the REST API if Ingest API does not return any data.

**Comment by sprintell** [comment]
Harmonization done, but yaml file has some missing data.

**Comment by karatugo** [comment]
@earlEBI What should be the file type for these?

https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST008396
https://www.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST002047

**Comment by karatugo** [comment]
Regenerated YAML files for GCST002047 and GCST008396. Expect them in the public ftp in 2 days.

**Comment by karatugo** [comment]
YAML files are in staging FTP but not in public FTP. Investigating this.

**Comment by ljwh2** [comment]
Agreed to keep original files as per old guidelines
