### ISSUE TITLE
Harmonisation pipeline - incorrect bracketing code

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1228]
Noticed that a harmonised directory had been created within the wrong bracket: 
https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90266001-GCST90267000/GCST90266000/

@jiyue1214 has checked and confirmed the issue stems from the code and will fix.

**Comment by jiyue1214** [comment]
I have modified the code and will check and move the harmonised file to the correct folder.

**Comment by ljwh2** [comment]
@jiyue1214 to check if any other instances of this error

**Comment by jiyue1214** [comment]
1. I have moved harmonised data from https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90266001-GCST90267000/GCST90266000/ to the correct folder
2. I have checked all the other folders and GCST90266000 is the only study affected. 
This ticket can be closed.
