### ISSUE TITLE
Deploy new yaml file generation feature

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1230]
Deploy without SLURM migration changes in first instance

**Comment by karatugo** [comment]
My Plan for this task

1. **Rollback Changes in `dev` and `master`**:
   - Checkout to `dev` branch: `git checkout dev`.
   - Create a backup branch: `git branch backup_dev`.
   - `git reset --hard 1ada7b9636b3c4c9b6ff73e9a17f389c9d4000ac` to rollback to this commit https://github.com/EBISPOT/gwas-sumstats-service/commit/1ada7b9636b3c4c9b6ff73e9a17f389c9d4000ac
   - Repeat these steps for the `master` branch.


2. **Merge Feature Branch to `dev`**:
   - `git checkout dev`.
   - Merge feature branch: `git merge new_yaml_from_master`.


3. **Test in sandbox**:
   - Conduct our tests.


4. **Merge `dev` to `master`**:
   - Checkout to `master`: `git checkout master`.
   - Merge `dev`: `git merge dev`.


5. **Briefly test in prod**:
   - Make sure that everything is up and running


6. **Merge Rolled Back Changes to `dev`**:
   - Manually re-apply the changes in `backup_dev`.

**Comment by karatugo** [comment]
My Plan for this task

- [x] **Rollback Changes in `dev` and `master`**:

   - Checkout to `dev` branch: `git checkout dev`.
   - Create a backup branch: `git branch backup_dev`.
   - `git reset --hard 80437fd6dff05c855063af597d27d568e229219c` to rollback to this commit https://github.com/EBISPOT/gwas-sumstats-service/commit/80437fd6dff05c855063af597d27d568e229219c
   - Repeat these steps for the `master` branch.


- [x] **Cherry pick changes to `dev`**:
   - `git checkout dev`.
   - Cherry pick: `git cherry-pick 7847851 bb3ddb7`.


- [ ] **Test in sandbox**:
   - Conduct our tests.

- [ ] **Merge `dev` to `master`**:
   - Checkout to `master`: `git checkout master`.
   - Merge `dev`: `git merge dev`.

- [ ] **Briefly test in prod**:
   - Make sure that everything is up and running


- [ ] **Merge Rolled Back Changes to `dev`**:
   - Manually re-apply the changes in `backup_dev`.

**Comment by karatugo** [comment]
Test OK in sandbox.

**Comment by karatugo** [comment]
Merged dev to master. https://github.com/EBISPOT/gwas-sumstats-service/pull/284

**Comment by karatugo** [comment]
Created tag `v1.3.9` https://github.com/EBISPOT/gwas-sumstats-service/releases/tag/v1.3.9

**Comment by karatugo** [comment]
Published the release `v1.3.9`. https://github.com/EBISPOT/gwas-sumstats-service/releases/tag/v1.3.9

**Comment by karatugo** [comment]
Released to prod now. https://gitlab.ebi.ac.uk/gwas/gwas-sumstats-service/-/pipelines/485458

**Comment by jiyue1214** [comment]
I confirm that yaml files for the new submission are in the new format. I will suggest closing this ticket.
