### ISSUE TITLE
Updated sumstats need re-harmonising - GCP000734

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1231]
The user got in touch to update 2 sumstats files (originally submitted filtered by significance. Now replaced with full results.)
GCSTs have already been harmonised. These need deleting and to be redone. 
IDs:
GCST90293086
GCST90293085

**Comment by karatugo** [comment]
Submitted to codon-slurm.

             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          62991435  standard goci1231 gwas_lsf  R       0:04      1 hl-codon-11-01

**Comment by karatugo** [comment]
The job in SLURM failed, submitted using LSF.

```
Job <92617909> is submitted to default queue <standard>.
```

**Comment by karatugo** [comment]
The harmonisation is now complete and files are avaliable in the public ftp. https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90293001-GCST90294000/
