### ISSUE TITLE
Investigate missing Globus directory

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1232]
A user has contacted us because they are unable to access the Globus directory linked to their submission, and therefore cannot upload summary statistics files.

This is the submission page:
https://www.ebi.ac.uk/gwas/deposition/submission/6599bc2ce6cd820001ee3b9d

Clicking through to the Globus link gives an error:
<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1BsQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec8050ab7560440d29c6e1fb413981557751a8b4/Screenshot%202024-01-22%20at%2008.50.27.png" alt="Screenshot 2024-01-22 at 08.50.27.png" />

Please check if the directory exists, and if anything can be done to enable the user to upload files for this submission.

**Comment by karatugo** [comment]
Created new dir and updated the database.

**Comment by eks-ebi** [comment]
confirmed this is done
