### ISSUE TITLE
PMID 22952805 not syncing to Deposition App

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1237]
I added this PMID to the Curation App on 31.01.23. 
The PMID is not yet available when searching https://www.ebi.ac.uk/gwas/deposition/curation_queue

Please add this PMID to the Deposition App so I can curate.

**Comment by sprintell** [comment]
This will be doen before the Data release

**Comment by sajo-ebi** [comment]
@earlEBI I can see the Pmid is available in the queue now , the issue appears to have resolved itself, kindly confirm

**Comment by earlEBI** [comment]
Confirmed, thank you. Ticket can be closed.
