### ISSUE TITLE
Incomplete submission is on public ftp

### ISSUE THREAD

**Issue by mcerezof** [EBISPOT/goci#124]
The submissions GCP000022 and GCP000023 are the same, both appear as incomplete submissions in deposition app (17/07/2020), however the SumStats has been released on ftp and also in the UI as GCST90001389

**Comment by ljwh2** [comment]
Confirmed this submission does not appear in "active submissions" table, only in "incomplete submissions". It is available in the pre-published table in the UI, unclear which GCP this is under.

**Comment by ljwh2** [comment]
Further clarification: 
Maria noticed there are two submissions that are listed as "incomplete submissions" in the deposition UI, GCP000022 and GCP000023. The data associated with these submissions appears on the UI in the pre-published table as GCST90001389 (ie there has been a successful submission of this data). However, there is nothing in the deposition UI to indicate that either GCP000022 or GCP000023 has been as successful submission, nor is there any other GCP containing this data. We don't have any more information, this needs investigating by a developer.

**Comment by tudorgroza** [comment]
GCP000022 and GCP000023 don't have submissions associated with them. GCP000024 seems to be the 'proper' body of work among these 3 (they're all the same), which also has a successfully submitted submission associated with it (`5f0326c523919f000123d327`). This submission is the one belonging to `GCST90001389`.

In conclusion, GCP000022 and GCP000023 are unsuccessful attempts of GCP000024 and can be deleted.

Should I proceed with this?

/cc @mcerezof @ljwh2

**Comment by ljwh2** [comment]
Agree GCP000022 and GCP000023 can be deleted but....do you know why GCP000024 has "NA" in first author, but in the UI table first author is listed as "Emma Jones"? @tudorgroza

**Comment by tudorgroza** [comment]
Can you please send me a screenshot? I don't understand. In the DB all 3 have the first author appropriately filled in with 'Emma Jones'.

![Screen Shot 2020-08-27 at 9 54 31 pm](https://user-images.githubusercontent.com/1421201/91451365-eceb8400-e8af-11ea-97a6-466126c71a9a.png)

**Comment by ljwh2** [comment]
In deposition UI:
![Screenshot 2020-08-27 at 15 36 34](https://user-images.githubusercontent.com/30795297/91456449-31a8f800-e87b-11ea-93bf-edbab5569a47.png)

In search UI:
![Screenshot 2020-08-27 at 15 38 23](https://user-images.githubusercontent.com/30795297/91456631-69b03b00-e87b-11ea-8e46-888375415660.png)

**Comment by ljwh2** [comment]
There are a lot with "NA" in first author in the deposition UI. I checked a couple and they seem to be the same.....first author visible if you click through to the submission, but not displayed in the table.

**Comment by twhetzel** [comment]
In the Depo UI on the "Active" submissions tab, currently if the submission is from a BoW then the author may be NA since First Author is not a required field for BoW. The "Active" submissions tab shows a mix of submissions from the Body of Work and Publication(?) provenance type.

**Comment by ljwh2** [comment]
@twhetzel but if there is a First author, it should be displayed - no?

**Comment by tudorgroza** [comment]
In this case ... it should be there. Let me check if I didn't do something wrong  ...
@twhetzel - what call are you making for that page?

**Comment by twhetzel** [comment]
From memory, I think the call is to `/submissions`.

**Comment by tudorgroza** [comment]
The issue is here on the front (src/Submissions/index.js):
```
title: 'First author', field: 'publication.firstAuthor', sorting: true,
render: rowData => {
	if (!rowData.publication) { return 'NA' }
	else { return rowData.publication.firstAuthor }
}
```

This is not a publication submission - the firstAuthor comes from the `bodyOfWork` object.

**Comment by ala-ebi** [comment]
The issue is for Active Submissions with no PMID, the first author should be retrieved from bodyOfWork object.
For some Incomplete submissions, the API does not return the First Author, I guess those belong to when there was no validation for the author fields and should not exist anymore.
I have created a fix for the above scenario, if you confirm @ljwh2 I will merge it to dev.

**Comment by ljwh2** [comment]
@ala-ebi all looks good on sandbox
