### ISSUE TITLE
Documentation on curation utility scripts needs updating after SLURM migraton 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1241]
Curators have several scripts that are used routinely, documented here: https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Using+the+Codon+Cluster

This page needs updating with any changes to usage following the migration to SLURM. 

***

- [x] Update https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Using+the+Codon+Cluster
- [x] Update https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Curators+daily+task+utility+scripts
- [x] Update https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=GOCI&title=Globus
- [x] Update https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Summary+Stats+Formatter+and+Validator

**Comment by ljwh2** [comment]
Please check with @earlEBI if clarification is needed

**Comment by karatugo** [comment]
Updated the Confluence page. 

- Updated the commands
- Updated login method
- Updated scrontab
- Updated the code how to run scripts

Please let me know if it looks good @earlEBI

**Comment by karatugo** [comment]
I added `toglobus` function to bashrc as well but I didn't get the use of it. If you encounter any errors, let me know again please.

**Comment by karatugo** [comment]
Updated all pages in the description, please review @Santhi1901 @earlEBI @eks-ebi

**Comment by karatugo** [comment]
created a service now ticket for curators salloc access. https://embl.service-now.com/esc?id=ticket&table=incident&sys_id=b28db9d91b838610973a646fe54bcbd8

**Comment by earlEBI** [comment]
Looks ok to me.

**Comment by karatugo** [comment]
The updated commands worked fine for Santhi.
