### ISSUE TITLE
Update metadata in database for submission '653f646de6cd82000152e763'

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1243]
By user request, I needed to update metadata for 2 studies with sumstats: GCST90296499 and GCST90296498

**In the submission template, through the DepoCuration App, I edited the following columns:**
analysis_software: PLINK.
readme

**I also edited the reported traits to:**
Educational attainment (years of education)(excluding related participants) 

**In the yaml file on staging, I edited:** 
reported_trait
author_notes [same as readme in template]
analysis_software [same as template]

**Please amend this information in the database as well**

Submission template: 
[Chen_TT_-_user_submission-_L2_-_ST3 - update (4th study).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUpaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb111cd8b1a2e3902d2723f803f1141db021b6b2/Chen_TT_-_user_submission-_L2_-_ST3%20-%20update%20%284th%20study%29.xlsx)

**Comment by ljwh2** [comment]
@eks-ebi to add to next user support epic

**Comment by sprintell** [comment]
@earlEBI will re-upload the metadata template to re-initiate

**Comment by sprintell** [comment]
@earlEBI will re-upload the metadata template again to re-initiate

**Comment by ljwh2** [comment]
@earlEBI we confirmed analysis_software exists in mongo but not Oracle.

**Comment by earlEBI** [comment]
Done. Looks good. Ticket can be closed.
