### ISSUE TITLE
Investigate and Fix Problem of Determining Latest Ensembl Release

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#1244]
There is a continuous email at the moment saying Problem Determining Latest Ensembl Release. Checking the ensembl release check API.

**Comment by ala-ebi** [comment]
seems to be caused by dev servers using https://apr2020.rest.ensembl.org/info/data/?content-type=application/json which no longer works
changed to https://rest.ensembl.org/info/data/?content-type=application/json
