### ISSUE TITLE
VALID status on 'view submissions' page in curation interface should be SUBMITTED

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#125]
While testing on Sandbox/Snoopy, I saw that studies submitted through the submission interface no longer need you to press 'submit' after uploading a template that validates. 

Then, on the 'view submissions' tab in the curation interface, the status of a publication remains as VALID, where it should be SUBMITTED. Or at least consistent as, at the moment, there is a mixture of statuses for recent submissions eligible for import.

**Comment by twhetzel** [comment]
@tudorgroza looks like this is fixed now. Did you push an update for this?

**Comment by tudorgroza** [comment]
Nope.
