### ISSUE TITLE
All publications in depo-curation must be assigned a curator and curation status

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1250]
Since publications can now be assigned a status in Depo-curation, all existing publications should be assigned a status and curator that matches the status and curator in the curation app. 

This should be done in the same way as for publications without a submission:

Curator & status (note, not all the studies of a publication may be the same. If we are setting statuses at publication level the following rules could be applied: 
Ignore any study with Requires review. 
Publish study overrules other statuses (but ensuring that any unpublished studies are not accidentally published due to their status). 
Other publications with mixed statuses may need manual review (I expect these will be few).

**Comment by ljwh2** [comment]
@ljwh2 to check

**Comment by earlEBI** [comment]
@sajo-ebi Could I please get an export of the publications in Depocuration Sandbox for me to check?

**Comment by sajo-ebi** [comment]
@earlEBI here is the export of Publications in Sandbox https://docs.google.com/spreadsheets/d/1sKZRym7CGbark4ELAlA5hB3ctc9e0jbn06qy5fHFaZc/edit#gid=0

**Comment by earlEBI** [comment]
@sajo-ebi I've requested access.

**Comment by earlEBI** [comment]
All publications that were added to the Curation queue before the 28th March are in Depocuration Sandbox. I cannot check that the statuses match, however, unless there is a sandbox-depocuration export with curation status, @sajo-ebi ?

**Comment by ljwh2** [comment]
@sajo-ebi will provide the list of publications with curation status "submission complete"

**Comment by sajo-ebi** [comment]
@earlEBI please find attached sheet Pmid with submission Complete status [https://docs.google.com/spreadsheets/d/1rul6CVlSOk72DSTe6MZBdNcCPTxDG__oW8QhJ_y3IAA/edit#gid=0](https://docs.google.com/spreadsheets/d/1rul6CVlSOk72DSTe6MZBdNcCPTxDG__oW8QhJ_y3IAA/edit#gid=0)

**Comment by ljwh2** [comment]
We later discovered that the rule "Publish study overrules other statuses" wasn't successfully applied resulting in 15 publications with incorrect status in DepoCuration (Curation abandoned or Permanently unpublished, instead of Publish Study). These have now been updated manually, just noting here for future reference.
