### ISSUE TITLE
Create Process Flow Documentation for Matching, Linking and  Adding Publication to the New Curation Database

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#1251]
This Documentation should live under this parent [here](https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Data+Flow+Process+Documentations) in confluence: 

This is linked to this UI [ticket](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/gwas-curation-ui/113) and this backend API [ticket](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/gwas-curation-ui/113)

**Comment by ala-ebi** [comment]
https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Importing+publications+from+EuropePMC%2C+matching+and+linking+to+existing+submissions
