### ISSUE TITLE
GCST changed for the user submission (65d1b430db8d9f0001726e94) for pmid: 38150807 when uploading in the depo curation app

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1255]
One of the GCSTs: GCST90319472 got changed to GCST90308719 while uploading the template in the depo curation app. 
GCST90308719 was part of an invalid submission (659cff8e53c4ef0001838433) for the same pmid. 

Discussed and concluded to keep GCST90308719 and move sumstats from GCST90319472 to GCST90308719 as GCSTs are not mentioned in the paper.

**Comment by ljwh2** [comment]
@sajo-ebi to create dev story to prevent future occurrences

**Comment by sajo-ebi** [comment]
Created Dev ticket [210](https://github.com/EBISPOT/gwas-curation-service/issues/210)
