### ISSUE TITLE
Yaml file not generated - GCST90315948

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1256]
The yaml file was not automatically generated for GCST90315948, submission id '65c0bc4fe6cd8200012ae294'. 

Please investigate and generate.

**Comment by karatugo** [comment]
I've regenerated the metadata yaml and md5sum files and uploaded them to the public FTP. Please review them at: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90315001-GCST90316000/GCST90315948/

**Comment by earlEBI** [comment]
Looks good to me, ticket can be closed, thank you
