### ISSUE TITLE
Regenerate YAMLs for GCST90268462 to GCST90268500

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1257]
Corrected sumstats have been provided by the author for GCST90268462 to GCST90268500.
I have deleted the old sumstats and moved the corrected sumstats into the staging folders.

YAMLs now need to be re-generated for these GCSTs.

**Comment by karatugo** [comment]
Testing the following for the new metadata yaml update feature: 

- [ ] https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90268001-GCST90269000/GCST90268462/
- [ ] https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90268001-GCST90269000/GCST90268463/
- [ ] https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90268001-GCST90269000/GCST90268464/
- [ ] [ ] https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90268001-GCST90269000/GCST90268465/

**Comment by karatugo** [comment]
All tests passed. Regenerated all other metadata YAML files; expect them on the public FTP tomorrow.

**Comment by karatugo** [comment]
New metadata YAML files and `md5sum.txt` files are now available on the public FTP. Please verify: https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90268001-GCST90269000/
