### ISSUE TITLE
Reharmonise updated sumstats for GCST90268462 to GCST90268500

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1258]
GCST90268462 - GCST90268500 have been updated manually (replaced on staging).

New harmonised files need to be generated for these studies.

**Comment by karatugo** [comment]
They are not harmonised yet either. Can be closed.

**Comment by eks-ebi** [comment]
@karatugo Just to make sure I understand: I recently manually replaced the summary statistics for these studies with corrected versions supplied by the author. The old summary statistics files had already been harmonised, so I deleted the old harmonised versions. I would now like new harmonised files to be created for the new summary statistics that I have added.Are you saying that we can just wait, and this task will be picked up automatically by the harmonisation pipeline?

**Comment by karatugo** [comment]
@eks-ebi Sorry for the misunderstanding. I didn't realize the old harmonised files were deleted. I thought they hadn't been created yet. In that case, they would automatically enter the harmonisation pipeline. But, since they were already generated and then deleted, we need to reharmonise them. I'll take care of it.

**Comment by eks-ebi** [comment]
thanks @karatugo!

**Comment by karatugo** [comment]
Submitted to codon-slurm. 

             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          62990405  standard goci1258 gwas_lsf  R       3:30      1 hl-codon-10-03

**Comment by karatugo** [comment]
LSF job is likely to fail, do first https://github.com/EBISPOT/goci/issues/1257

**Comment by karatugo** [comment]
https://github.com/EBISPOT/goci/issues/1257 done. 

Submitted a SLURM job now. 


             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
            383374  standard goci1258  spotbot  R       0:13      1 hl-codon-10-01

**Comment by karatugo** [comment]
still running...

**Comment by karatugo** [comment]
I have contacted Yue for assistance in debugging the issue, as similar failures are occurring frequently.

```
[1a/b4a5a3] process > NFCORE_GWASCATALOGHARM:GWAS... [100%] 39 of 39, failed: 39
```

**Comment by karatugo** [comment]
- [ ] Copy harmonised files from `/nfs/ftp/private/gwas_cat/harm_test/success/GCST90268001-GCST90269000/` to the public ftp.

**Comment by karatugo** [comment]
@eks-ebi Please confirm that the files are indeed on the public FTP.

**Comment by eks-ebi** [comment]
@karatugo Yes this is done! sorry for the delay
