### ISSUE TITLE
Write script to create EBI Search indexing data

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#126]
In order to have the GWAS Catalog data searchable from the EBI Search and therefore the Covid portal, the GWAS data needs to be provided in the indexing format for the EBI Search. A script or new endpoint in the Search UI code is needed to create this data format for each GWAS Catalog Data Release.

@ljwh2 will the data for the EBI Search be limited to only the GWAS Catalog Covid data? And will this be limited to only data tagged with `MONDO:0100096`? In EFO, only this Covid related term exists, however in MONDO there are child terms [1].

[1] https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100096

**Comment by ljwh2** [comment]
It doesn’t make sense to me to only index covid data, it should be everything. 
We (curators) can make sure we tag everything with the high level term.

**Comment by twhetzel** [comment]
@ljwh2 there are cases where not all currently published studies have reported trait annotations. In the EBI Search Index the reported trait will be used in the name of the search snippet. 

For this script and the Data Release process this script is executed during, should:
- the Data Release fail if this script identifies studies missing reported trait information
OR
- the Data Release continue and this script email curators with the studies missing reported trait annotations and the script only create EBI Search Index data for studies with reported traits

**Comment by ljwh2** [comment]
It shouldn't be possible to publish a study without a reported trait. I tried to verify this in Snoopy 9680, but I haven't been able to (I got a javascript error on clicking save from the study tab), I will check with the curators. This should be dealt with at the point of publication in the curation interface, not at the point of data release.

**Comment by ljwh2** [comment]
Curators verified that it is possible to publish a study without reported trait, so these studies likely arose due to curator error. The studies will be fixed manually, and I will make a new ticket to block this in the curation interface. No further work is needed at the level of the data release.

**Comment by twhetzel** [comment]
@ljwh2 it's possible this EBI Search indexing script will be run before both the current studies are fixed and/or before there is a released version of a fix to prevent this from happening in the Curation app, so I'm not clear what the expected behaviour is for this script if studies with missing reported traits are found? 

For example, should this script just skip those studies with missing Reported traits and log the cases when this happens or should this fail the Data Release at this step?

**Comment by ljwh2** [comment]
Yes, skip those studies with missing Reported traits and log the cases when this happens

**Comment by twhetzel** [comment]
A similar issue with initial sample information also occurs, skip these records also and include in alert email.

**Comment by twhetzel** [comment]
Also, include pre/unpublished studies.

**Comment by twhetzel** [comment]
First pass at script completed. Currently only study data from published studies is included. Need to sort out ancestry representation for unpublished studies. See ticket

**Comment by twhetzel** [comment]
NOTE: The report of studies missing curation fields is formatted as:
Report of publications or studies with missing curation information
```
[Info] Date of run: 07-08-2020
[Info] Source database: DEV3

[Info] Errors found with:

No data issues found.

This report was created by the "create_ebi_search_index_data.py" script run by the "Data Release(prod)" Bamboo build plan.
```

**Comment by twhetzel** [comment]
Since the first pass of the script is done, closing this and will continue in other related tickets.
