### ISSUE TITLE
Replace all EFO trait annotations of MONDO_0009354 with OBA_2040073

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1262]
A number of studies and associations have been incorrectly annotated with **MONDO_0009354** (methylcobalamin deficiency type cblE). This seems to have happened when the original ontology term used to annotate these studies and associations was made obsolete, and it was accidentally changed to an incorrect replacement term. The correct new EFO term is **http://purl.obolibrary.org/obo/OBA_2040073** (**trait in response to paclitaxel**)

Action: **MONDO_0009354** term needs to be replace with **OBA_2040073** (trait in response to paclitaxel), wherever it appears in the Catalog.

**Comment by jiyue1214** [comment]
Studies with the MONDO_0009354 term (based on gwas-catalog-v1.0.3.1-studies-r2024-03-01.tsv):
| No of studies | PMID     | publication date |
| ------------- | -------- | ---------------- |
| 1             | 22843789 | 2012-07-27       |
| 1             | 23006423 | 2012-09-24       |
| 1             | 23204130 | 2012-11-30       |
| 2             | 23648065 | 2013-05-04       |
| 1             | 23776197 | 2013-06-17       |
| 1             | 24025145 | 2013-09-11       |
| 2             | 26015512 | 2015-05-26       |
| 1             | 26138065 | 2015-07-02       |
| 1             | 26840454 | 2016-01-31       |
| 3             | 27047539 | 2016-03-22       |
| 3             | 28763429 | 2017-07-31       |
| 2             | 28935272 | 2017-09-18       |
| 1             | 29367611 | 2018-01-24       |
| 4             | 34162658 | 2021-06-23       |
| 1             | 34437536 | 2021-08-26       |

**Comment by eks-ebi** [comment]
I will check the new EFO after the next DR. I'll move this ticket to the new user support epic, even though it's done, just so that I don't forget to have a look.
