### ISSUE TITLE
Replace obsolete EFO term: GO_0007568

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1266]
http://purl.obolibrary.org/obo/GO_0007568 "aging" is obsolete and needs to be replaced in the GWAS Catalog.

The new term is http://www.ebi.ac.uk/efo/EFO_0022597 "aging" - Zoe has said that this new term will be available after the March 18th EFO release.

**Comment by ala-ebi** [comment]
no "termReplacedBy" field for GO_0007568 in OLS, Obsolete-EFO process couldnt handle it, done manually

**Comment by eks-ebi** [comment]
confirmed, new term is correct in depocuration
