### ISSUE TITLE
Investigate & fix duplication of SNPs

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1275]
Occasionally SNPs are duplicated during the curation process. It looks like this happens on import to Oracle. 

If the studies are not yet published, the data release breaks 

If the studies are published, this causes issues in prod as the SNP is listed twice in UI and download, here in GCST90085780

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDRWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7442fe227ab97d5e6e0ac7909634501316120dd/Screenshot%202024-03-27%20at%2013.44.07.png" alt="Screenshot 2024-03-27 at 13.44.07.png" />
 
<img width="466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b27dfb1c28a82d51bc65965c482a54feb1b2f81c/Screenshot%202024-03-27%20at%2013.36.33.png" alt="Screenshot 2024-03-27 at 13.36.33.png" />

-
Some recent examples are rs71543110, rs199679345, see also goci#719

I did some quick analysis of the associations download, looks like there are 83 SNPs which are duplicated in prod. A quick check suggests all of these look like merged SNPs in our UI, with the variant ID appearing as rs1 (rs2) in the search snippet, but I can't verify this in Ensembl.  

<img width="880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8948c5761a281205af4b24a4d215f1fe7d7b7406/Screenshot%202024-03-27%20at%2014.03.16.png" alt="Screenshot 2024-03-27 at 14.03.16.png" />

All but 3 of them have the "merged" flag set to 0. 

All are included in studies published in the Catalog after March 2022, although there are also examples of merged SNPs added recently that are correctly represented in UI e.g. https://www.ebi.ac.uk/gwas/search?query=rs138055607. Note this is around the time we switched to using depo-curation for routine curation workflow. 

The full list of associations with duplicate SNPs (411 associations, 83 SNPs) is attached: [assocs with SNP duplication.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b370b7a6559bc75e1b97ba22774fa2da77cb1a4/assocs%20with%20SNP%20duplication.xlsx)

This needs investigating and fixing such that
-curators can extract SNPs as described in papers, which may include old or new rsIDs
-unpublished SNPs do not break the DR
-published SNPs appear only once in the UI & download

**Comment by Santhi1901** [comment]
rs71543110, found in pmid:37500982 (GCST90321118) with status level 2 curation done, was causing issues during DR. For the current ongoing DR, I deleted all associations for this particular GCST. Also attached is the list of SNPs from this publication that were not found in Ensembl.
[SNP_not found in ensembl.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0574907d4476b0a568b65d0832c13ac46aed8fc2/SNP_not%20found%20in%20ensembl.xlsx)

**Comment by Santhi1901** [comment]
This PMID containing rs71543110 was published and didn't cause any issues during the DR. It was duplicated in UI.

**Comment by ljwh2** [comment]
Another example that caused the DR to fail:
Association 131528254, Accession Id ‘GCST90428059’ Study Id ‘131528155’

**Comment by ala-ebi** [comment]
There's a join table called SNP_MERGED_SNP which contains duplicate values, this was the case for both published and unpublished studies that I have checked that have the duplicate SNPs or issues in DR respectively.
I think deleting the duplicates would solve both issues, we can test this in next DR.

**Comment by ljwh2** [comment]
Check after DR, if successful, make changes to mapping pipeline

**Comment by ala-ebi** [comment]
this DR should fix all the existing duplicates and DR purge issues for unpublished studies, @sajo-ebi to add code ti prevent duplicating from happening in the mapping pipeline

**Comment by ljwh2** [comment]
Closing this issue and created https://github.com/EBISPOT/goci/issues/1451 for remaining issue
