### ISSUE TITLE
Sync new PMIDs from mongo to Oracle 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1276]
- Given there are new PMIDs added in depo-curation using the new software feature
  -  the PMIDs should be synched to the curation database
  - Then the import process can proceed using the new PMIDs
  - And curators can start to use the new software features in their daily workflow
 
This is required until the import & publish process goes offline.

**Comment by sajo-ebi** [comment]
@Santhi1901 the Pmid sync can be tested , as part of this you need to import new Pmid from EuropePMC & then create a new submission for the Pmid & then import the same in Snoppy Curation  app

**Comment by Santhi1901** [comment]
tested, and it looks all good

**Comment by ljwh2** [comment]
@sajo-ebi how often will this sync run? Or how soon after adding new PMIDs will they be available for import.

**Comment by sajo-ebi** [comment]
@ljwh2 it will be realtime the issue today was it was not setup to run continuously in Dev environment but in production it will be running continuously
