### ISSUE TITLE
Regenerating yaml and md5sum txt files

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1278]
The md5sum txt and yaml files need to be regenerated for the following GCSTs. The sumstats for these GCSTs have been updated as the user requested, and the metadata has not been changed. 
GCST90308719
GCST90319473
GCST90319474
GCST90319475
GCST90319476
GCST90319477
GCST90319478
GCST90319479
GCST90319480
GCST90319481
GCST90319482
GCST90319483
GCST90319484
GCST90319485
GCST90319486

**Comment by karatugo** [comment]
Regenerated metadata YAML files and md5sums.txt files; expect them on the public FTP tomorrow.

**Comment by sprintell** [comment]
@Santhi1901  could you please help review and approve.

**Comment by Santhi1901** [comment]
yes this is done
