### ISSUE TITLE
Yaml file not updated correctly - PMID 37619450

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1279]
User submission '64f84d3f788f0000010f81cb'. 
Submitted in 2023. 
I picked this up on 03/04/24, added trait and EFO in depocuration app, edited template (added author_notes), published on 04/04/24. 
Checked release to public FTP on 05/04/24. File and yaml are there but yaml has not been updated correctly, namely: 
- trait and EFO have not been updated. 
- author_notes have not been updated. 

Karatug is investigating. Also a file_type issue in newly generated yaml. 
Please investigate.

**Comment by karatugo** [comment]
- Repaired the template editing function in the SumStats service.
- Corrected file types due to multiple metadata entries in MongoDB during updates. Now using the most recent.
- Also, regenerated YAML files, which will be available on the public FTP tomorrow.

**Comment by earlEBI** [comment]
Yaml looks good thank you
