### ISSUE TITLE
Change study GCST

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1282]
A user submitted sumstats under GCST90295957 (submission id `6525350ce6cd8200013b5056` - body of work)

Curator submitted without sumstats under GCST90328130 (submission id `65fd5102b73c7400017cc520` - PMID 38190104 - now in Catalog). 

Could a developer please change GCST90328130 to GCST90295957. 

Then let me know so I can:
- unpublish the study
- tick full p-value set for the study in Curation App
- republish. 

Sumstats will then be correctly linked.

**Comment by sajo-ebi** [comment]
@Santhi1901 changed GCST & also deleted the '6525350ce6cd8200013b5056' submission as we can't have two submission with same GCST, please validate

**Comment by ljwh2** [comment]
@Santhi1901 please confirm

**Comment by sprintell** [comment]
@Santhi1901 could you please confirm this ...

**Comment by Santhi1901** [comment]
Lizzy created this ticket. I am not able to check it in the deposition curation app, as it shows an error.

**Comment by ljwh2** [comment]
@earlEBI please confirm when you are back (sorry Santhi!)

**Comment by earlEBI** [comment]
I confirm this ticket is now complete.
