### ISSUE TITLE
Delete GCP000339 (submission id: 627a1e1728d70900018e0c2f) and change GCST

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1283]
We need to delete this submission as the user has clubbed sumstats for different traits under one study.
The sumstat is now split and submitted under PMID: 36681271 (`6614fa7cb73c740001cd3cd1`). The paper mentions GCSTs from GCP000339.
After deleting the submission, the 2 GCSTs from `6614fa7cb73c740001cd3cd1` need to be changed 
GCST90399399 needs to be changed to GCST90102551
GCST90399400 needs to be changed to GCST90102552

**Comment by sajo-ebi** [comment]
@Santhi1901 done please validate

**Comment by Santhi1901** [comment]
The GCSTs have been changed correctly
