### ISSUE TITLE
 Documentation for gwas-sumstat-tools

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/goci#1287]
We need to create an online documentation/ tutorial about how to use gwas-sumstat-tools, so that both internal and external users can read and use gwas-sumstat-tools using CLI or UI. When our formatted UI/webassembly mainly aim external users, this documentation is essential to guide how to edit the configure file to reformat their data. The documentation template is here: https://jiyue1214.github.io/gwas-sumstats-tools-Documentation/#/

  - [x] Create an template for gwas-sumstat-tools documentation (https://jiyue1214.github.io/gwas-sumstats-tools-Documentation/#/).
  - [x] Editing the content for format CLI users
  - [x] Editing the content for format UI users
  - [x] Editing the content for read, validate and generate meta_data

When a user visits the documentation website, the user should find clear instructions on how to use the tools, including formatting and editing the configure file

**Comment by eks-ebi** [comment]
@eks-ebi to think about where to display documentation on GWAS Catalog website

**Comment by jiyue1214** [comment]
Here is the [initial draft](https://ebispot.github.io/gwas-sumstats-tools-Documentation/#/), and I would appreciate any suggestions you may have to improve it.

**Comment by eks-ebi** [comment]
@jiyue1214 The documentation looks really nice and very helpful! I've started writing up some feedback [in this document](https://docs.google.com/document/d/1n7Chm_dAGSKUQsEKkD4HZOut0TlhfpxaQzQtqSqirmo/edit#heading=h.ryyf7gt0wxsm) - I haven't gone through everything yet, but I'll try to keep updating it over the next few days

**Comment by jiyue1214** [comment]
I have improved the documentation according to Elliot's suggestion.

**Comment by jiyue1214** [comment]
I have migrated the documentation repo to EBISPOT: https://ebispot.github.io/gwas-sumstats-tools-Documentation/#/

**Comment by eks-ebi** [comment]
@eks-ebi add link to this documentation in the main GWAS Catalog submission documentation

**Comment by jiyue1214** [comment]
This ticket can be closed.
