### ISSUE TITLE
Create Reported traits in the curation app/database for a large submission before import (n2)

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#129]
We have a submission containing a large number of new reported traits that are not currently in the database. When the submission is imported, these traits will be missing from the created study entries and will be difficult to add one by one in the curation app. See submission page:

https://www.ebi.ac.uk/gwas/deposition/submission/5ee00d1ed1d92a000192189e

We need to add these traits in bulk before publishing the entries in the Catalog. Annalisa has sent a list of traits to Trish.

**Comment by twhetzel** [comment]
@buniello these are added now to the Production Curation app database.
