### ISSUE TITLE
User request for sumstats harmonisation

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1300]
Please prioritise the sumstats associated with this publication for harmonisation https://www.ebi.ac.uk/gwas/publications/36474045

**Comment by karatugo** [comment]
Job <97669165> is submitted to default queue <standard>.

**Comment by karatugo** [comment]
As the prev LSF job submission failed, I submit again. 

```
Job <98014643> is submitted to default queue <standard>.
```

**Comment by karatugo** [comment]
LSF job failed again. Submitted in SLURM. 

```
Submitted batch job 4623821
```

**Comment by karatugo** [comment]
SLURM job failed too according to the logs. Asked for @jiyue1214 help.

**Comment by karatugo** [comment]
Need to restart again as Yue updated the code.

**Comment by karatugo** [comment]
Restarted `/hps/software/users/parkinso/spot/gwas/prod/scripts/cron/start_harmonisation_pre_standard_slurm_goci1300.sh`

             JOBID PARTITION NAME                                                    USER     ST TIME       NODES  NODELIST
           8384004 standard  pre_gwas_ssf_harmo                                      gwas_lsf R  0:23       1      hl-codon-05-01

**Comment by karatugo** [comment]
Failed again, need help from @jiyue1214 again.

**Comment by jiyue1214** [comment]
The harmonised result is available on the FTP right now and could @karatugo double-check if the data is correct?

**Comment by karatugo** [comment]
Looks good to me, thanks @jiyue1214

**Comment by karatugo** [comment]
http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90132001-GCST90133000/GCST90132314/harmonised/

http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90132001-GCST90133000/GCST90132315/harmonised/

**Comment by ljwh2** [comment]
@ljwh2 to confirm

**Comment by ljwh2** [comment]
confirmed
