### ISSUE TITLE
Move sumstats files and yamls to the public ftp

### ISSUE THREAD

**Issue by karatugo** [EBISPOT/goci#1304]
✅ One particular submission with more than 6,000 studies only has md5sums in GCST directories on staging and released to public. No sumstats files or yamls have been created. Submitted on 31.03.24. https://www.ebi.ac.uk/gwas/deposition/submission/6608c665db8d9f000198b901
-- ✅ Copy files to staging
-- ✅ Check if the files moved to the staging ftp
-- ✅ Check if the files moved to the public ftp
-- ✅ Generate metadata yaml files

**Comment by karatugo** [comment]
Started copying files from the private ftp to staging.

```
ID: 	3670454
Name: 	copy_goci1304
```

**Comment by karatugo** [comment]
Copying files from the private ftp to staging complete.

**Comment by karatugo** [comment]
Study files are synced successfully to the public ftp.

**Comment by karatugo** [comment]
Generate metadata yaml files started here. https://github.com/EBISPOT/goci/issues/1292#issuecomment-2093095857

**Comment by karatugo** [comment]
Randomly checked a couple of them and the yaml files are in the public ftp.

**Comment by sprintell** [comment]
@eks-ebi pls help confirm ...

**Comment by eks-ebi** [comment]
I checked a few and the sumstats and yaml files are there in the public FTP. There is just one weird thing: the **filetype** field appears to be blank. See examples yaml file here: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90384001-GCST90385000/GCST90384080/

**Comment by karatugo** [comment]
I think this is because they are validated manually. I need to update them in the database. 

@eks-ebi Do you know what their correct file types are?

**Comment by eks-ebi** [comment]
@karatugo as far as I can tell, they should all be `GWAS-SSF v1.0`

**Comment by karatugo** [comment]
Added the missing file type to https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1281 and will work on them soon

**Comment by karatugo** [comment]
If there's nothing else, is it okay close this ticket? @eks-ebi

**Comment by eks-ebi** [comment]
sorry @karatugo yes I think it's okay to close this ticket
