### ISSUE TITLE
Fix folders on staging for GCSTs without sumstats

### ISSUE THREAD

**Issue by karatugo** [EBISPOT/goci#1306]
✅ There seem to be folders being created on staging for GCSTs which do not have sumstats. Previously, folders were only created on staging for those GCSTs with full p-value set ticked (i.e. have sumstats) - eg. GCST90321079, GCST90310292, GCST90397904

**Comment by karatugo** [comment]
Couldn't reproduce the issue on sandbox. Perhaps it was fixed by https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1292

**Comment by karatugo** [comment]
Test with GCST90428125-GCST90428269 and GCST90428282-GCST90428285

**Comment by karatugo** [comment]
Should be fixed now.

**Comment by sprintell** [comment]
Please clean te empty folders created by the bug. @karatugo

**Comment by karatugo** [comment]
Can't find empty dirs other than `GCST90102485`. Perhaps my script at `/hps/nobackup/parkinso/spot/gwas/scratch/goci1306` is wrong?

**Comment by karatugo** [comment]
@earlEBI Could you please verify that the folders without sumstats are deleted?

**Comment by ljwh2** [comment]
@earlEBI please confirm when you are back, thanks

**Comment by earlEBI** [comment]
The three directories I gave as examples still exist on staging, empty. These studies do not have sumstats.

**Comment by karatugo** [comment]
Okay, my script was wrong: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1306#issuecomment-2091113483

For some weird reason, I was checking the public ftp.

**Comment by karatugo** [comment]
Now submitted a new SLURM job that checks the staging FTP.

**Comment by earlEBI** [comment]
I confirm the original empty directories I listed are now removed from staging.
