### ISSUE TITLE
yaml file-types need changing from non-GWAS-SSF to GWAS-SSF

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1308]
Submission id '662ca8a7a6e7cc0001fe7acc' was pushed through validation due to 0 p-values. 

Yaml file-type need to be changed from non-GWAS-SSF to GWAS-SSF v1 for all GCSTs. 

GCST90428438 - GCST90428399

**Comment by karatugo** [comment]
That's already the case for the mentioned studies.

**Comment by karatugo** [comment]
For example, this study is in the public ftp and has the correct file type. https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90428001-GCST90429000/GCST90428399/

**Comment by karatugo** [comment]
Expect missing yaml files tomorrow in the public ftp.

**Comment by earlEBI** [comment]
I'm a bit confused as to why the file-type is correct after pushing through. Maybe is due to yamls not being generated at point of validation. Will confirm tomorrow if the 2nd yaml appears and is correct.

**Comment by earlEBI** [comment]
Yamls look ok.
