### ISSUE TITLE
Silent errors in sumstats pipeline

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1309]
During the process of sumstats release to FTP, silent errors can occur, eg:

- Sumstats not successfully moved to staging ftp. (eg. '6608c665db8d9f000198b901', ticket #[1304](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1304))
- Yaml file not created on staging ftp (eg. above example)

Please investigate if an e-mail could be sent notifying of these kinds of issues, per GCST, not just per submission. 

Data to include in notification email:
- Submission id
- GCST id
- Type of failure
- Reason for failure

Or else / additional an auto-retry mechanism.

**Comment by karatugo** [comment]
If metadata YAML generation fails, we'll receive an email to gwas-dev mail address. 

As you can see in the sample email below, it includes the following data.
- GCST id
- Type of failure
- Reason for failure

Note that submission ids are difficult fetch at this layer, therefore it's skipped.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/sumstats_service/sumstats_service/app.py", line 390, in convert_metadata_to_yaml
    return au.convert_metadata_to_yaml(gcst_id, is_harmonised_included)
  File "/sumstats_service/sumstats_service/resources/api_utils.py", line 442, in convert_metadata_to_yaml
    raise FileNotFoundError(
FileNotFoundError: 
            Data file not available for GCST90268003
            at '/pub/databases/gwas/summary_statistics/GCST90268001-GCST90269000/GCST90268003'
            
 Task was called with args: 
                 ['GCST90268003'] kwargs: {}.

                 Exception was raised:

            Data file not available for GCST90268003
            at '/pub/databases/gwas/summary_statistics/GCST90268001-GCST90269000/GCST90268003'
            

                 Traceback:
<traceback object at 0x7fb7c7d17b80>
```

**Comment by ljwh2** [comment]
@karatugo to change so the check is for files on staging, not production

**Comment by karatugo** [comment]
@karatugo to create a new table in mongo, save failed ones there, and send single email every day for the prev day's failures.

**Comment by karatugo** [comment]
- [ ] Report only the ones with sumstats in the email

**Comment by karatugo** [comment]
Deployed to sandbox.

**Comment by karatugo** [comment]
Test with studies `GCST90275903` and `GCST90275904` successful.

**Comment by karatugo** [comment]
Deployed to prod. Expect nightly emails around 23:00 for sandbox and 23:05 for prod for that day.
