### ISSUE TITLE
African American samples imported to curation interface with the word 'ancestry'

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#131]
The word "ancestry" should not appear after admixed sample groups imported from the submission interface to the 'sample description' field in the curation interface on the 'sample information' tab. eg:

Imported as: African American ancestry individuals 
Should be: African American individuals 

Also applies to: 
- Hispanic/Latino/Latin American

Eg. submission ID 5ede2b89d1d92a0001920cf9. Already manually corrected in the curation interface (PMID 32650023).

**Comment by twhetzel** [comment]
Ready for Curator QA

**Comment by earlEBI** [comment]
Is this the right address to test importing submissions? I get 'internal server error'. 
http://snoopy.ebi.ac.uk:9580/gwas/curation/submissions/new

**Comment by twhetzel** [comment]
@earlEBI yes, it should be. Let me know if you run into any other issues

**Comment by earlEBI** [comment]
On testing import of PMIDs 32080354 and 32077919 , now no information at all appears on 'sample information' and 'SNP associations' tabs.

**Comment by tudorgroza** [comment]
Hmmm - not sure the two are connected. My PR and fix should have affected only the text displayed in the description - and nothing else.

**Comment by twhetzel** [comment]
Yes, based on the code updates we added into `2.x-dev` for #97 and this ticket I would not expect the sample information to not be imported. 
@tudorgroza do you want to take it from here or shall I investigate further, e.g. try on localhost and look/log errors, check logs on Snoopy for any errors, etc?

**Comment by tudorgroza** [comment]
Yeah - could you please get some logs data, to see what's going on? Thank you.

**Comment by twhetzel** [comment]
Sent logs, this issue appears to be related to #97
