### ISSUE TITLE
Investigate unexpected sumstats+metadata submission by external user

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1311]
An external user seems to have been able to create a sumstats + metadata submission for a publication (https://www.ebi.ac.uk/gwas/depo-curation/submissions/661e2936d222f50001984929), even though there was already curated data for the publication in the curation database, and a metadata-only submission already existed (https://www.ebi.ac.uk/gwas/depo-curation/submissions/62823f4e28d70900018e63e1). This should not occur, because the presence of an existing metadata submission should cause a study to appear as CLOSED FOR SUBMISSION and therefore prevent any new metadata submissions.

This is a possible loop-hole in the process, which needs further investigation.

Relevant background:
1. The original metadata-only submission was created by Lizzy in 2022.
2. The author later made a sumstats-only submission and attempted to add additional studies to the pre-filled template, which is impossible, therefore their submission was INVALID.
3. The author emailed to ask us to add the additional studies to the Catalog.
4. I (@eks-ebi) unpublished the original curated studies using the curl command, in order to edit the metadata-only submission and add the new requested studies.
5. We deleted the invalid sumstats-only submission in order to allow the changes to the metadata-only submission to be imported into the curation app: see [goci #1286 ](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1286)
6. I could not import the updated metadata-only submission at first, and asked @sajo-ebi to manually change the publication status, in order to enable the import. I'm not sure from the notes in [goci #1286 ](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1286) whether any action was done at this point, or whether the import was re-enabled simply by waiting overnight.
7. The next day, I was able to import the updated metadata-only submission.
8. It seems that at some point _after_ the status was changed (if it was) and _before_ I actually imported the updated metadata-only submission, the author created the new sumstats + metadata submission.

**Comment by ljwh2** [comment]
@sajo-ebi will add details of investigation

**Comment by eks-ebi** [comment]
@sajo-ebi We discussed this morning that since there is no clear explanation for this situation, we can go ahead and clean up the two submissions. I have now saved a copy of the sumstats, so I am ready for you to delete the author’s submission: `661e2936d222f50001984929`.

**Comment by sajo-ebi** [comment]
@eks-ebi the submission '661e2936d222f50001984929' has been deleted

**Comment by eks-ebi** [comment]
Thanks @sajo-ebi !

**Comment by eks-ebi** [comment]
I'll leave the ticket open for you to add any details from the investigation

**Comment by sajo-ebi** [comment]
I investigated the DB & code couldn't find any scenario where the user can create two submissions, the logs are not there to determine what exactly happened
