### ISSUE TITLE
Publication management page: column sort

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1335]
In the sandbox [Publication management page](https://wwwdev.ebi.ac.uk/gwas/depo-curation/publications), sort by first author and publication date does not work. Sometimes it works on first click, but then no results are shown and the page becomes non responsive. @sajo please fix

**Comment by ala-ebi** [comment]
caused by PMIDs assigned to more than one BoW (sandbox data), pushed a fix to get only one
