### ISSUE TITLE
Investigate why submission is failing validation

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1340]
This submission is failing validation, but the cause of the failure is unclear.

https://www.ebi.ac.uk/gwas/deposition/submission/665086c4d222f500010e2aba

**Comment by karatugo** [comment]
Restarted the validation and it failed due to mandatory columns being missing. For example, check the header of the file `reformatted_residDist.results_240224.tsv`.

```
chromosome	base_pair_location	p_value	variant_id
```

**Comment by karatugo** [comment]
Also see https://github.com/EBISPOT/goci/issues/1342

**Comment by eks-ebi** [comment]
@karatugo Is it only that one file (`reformatted_residDist.results_240224.tsv`) that has an error? I actually expect an error in that file because it is a non-standard GWAS design. But the other files need to meet all of the validation requirements - can you tell if the others look ok?

**Comment by karatugo** [comment]
- [ ] Restart validation excluding this one particular file

**Comment by karatugo** [comment]
@eks-ebi I've rerun the validation, excluding this specific file. But we're still encountering md5sum errors with several files, including "Merged_micronuciformis.tsv", "Merged_Veillonellaceae.tsv", and "Merged_ASV0009.tsv" etc.

For instance, the md5sum for "Merged_micronuciformis.tsv" from our private FTP is `650aa6dedeff99a4b54182e1bc3dd2a0`, but in the template, it is `d6665937d97682f915b3331b4fd364b5`.

**Comment by eks-ebi** [comment]
ok great, thanks Karatug! I'll go back to the authors and ask them to check the md5sums.
