### ISSUE TITLE
Submission 665a1272f2bba900017a9f6f failed validation 

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1341]
This submission shows failed validation, but the error is not clear.

**Comment by karatugo** [comment]
Submission 665a1272f2bba900017a9f6f failed validation due to exceeded disk quota in the `/homes/gwas_lsf` directory. Manually cleaning up solved the issue. 

See https://github.com/EBISPOT/goci/issues/1342 for further investigation.
