### ISSUE TITLE
Investigate why submission is failing validation

### ISSUE THREAD

**Issue by karatugo** [EBISPOT/goci#1343]
This submission is failing validation, but the cause of the failure is unclear.

https://www.ebi.ac.uk/gwas/deposition/submission/665f293ed222f500010ec51f

**Comment by karatugo** [comment]
- [ ] Investigate the following error.

After validation request, I see the following logs.

```
[2024-06-05 14:17:45,669: WARNING/ForkPoolWorker-29] Running NextFlow command...
[2024-06-05 14:17:45,853: WARNING/ForkPoolWorker-29] Error in submitting job:
[2024-06-05 14:17:45,853: WARNING/ForkPoolWorker-29] ERROR: Cannot find 'curl' nor 'wget' utility --  please install one of them
```

This causes validation fail.

**Comment by karatugo** [comment]
@earlEBI  I restarted validation manually. 

File header error for the file `Weight_M_k1_k2_k3_sumstats.tsv.gz`

```
CHR	POS	Tested_Allele	Other_Allele	BETA	SE	AF_Tested	PVALUE	SNP
1	717587	G	A	-0.000909902	0.0114664	0.984489	0.94	rs144155419
1	731718	T	C	-0.00402037	0.0040427	0.879571	0.32	rs58276399
...
```

**Comment by earlEBI** [comment]
@karatugo Thanks Karatug - so the submission pages' error reports are broken?

**Comment by karatugo** [comment]
@earlEBI They are not correct as I rerun manually. Please ignore them.

**Comment by earlEBI** [comment]
The user resubmitted and it's gone through.
