### ISSUE TITLE
Delete submission GCP000598 6437f889d0b15a0001259abb

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1345]
Please delete this submission. 

The user will re-submit under a new submission id. 

Submission '6437f889d0b15a0001259abb' needs to be deleted so it is not confused when adding PMID. 

I will delete the data on sumstats staging FTP. 'GCST90267555 - GCST90267562' - done

**Comment by sajo-ebi** [comment]
@earlEBI the submission & associated studies have been deleted

**Comment by ljwh2** [comment]
@earlEBI please confirm all good from your end

**Comment by earlEBI** [comment]
@ljwh2  Can be closed.
