### ISSUE TITLE
Change sumstats file_type 665086c4d222f500010e2aba

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1346]
This submission '665086c4d222f500010e2aba' was pushed through validation due to one file being non-standard ('GCST90429842'). 

This should mean all the meta yamls (44 studies) are given file_type 'non-GWAS-SSF'. 

Only 'GCST90429842' should be non-GWAS-SSF. 

All other GCSTs (GCST90429799 - GCST90429841) should be the standard GWAS-SSF file_type.

**Comment by karatugo** [comment]
fixed the file type for `GCST90429842` - expect it in the pub ftp in 2 days
other file type were GWAS-SSF v1.0, so I kept them

**Comment by karatugo** [comment]
The YAML in the staging FTP has the correct file type.

**Comment by sprintell** [comment]
Hi @earlEBI please help confirm this. Thanks

**Comment by sprintell** [comment]
Hi @earlEBI please help confirm this. Thanks

**Comment by earlEBI** [comment]
Hi @karatugo 
GCST90429841 has no yaml. 
GCST90429842 has yaml but sample is empty?

**Comment by ljwh2** [comment]
@earlEBI please check if this looks ok now?

**Comment by earlEBI** [comment]
Looks okay now
