### ISSUE TITLE
All studies of a PMID are showing in the pre-pub table, even though they are published. 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1347]
All the studies associated with PMID 36635386 (4443 studies; GCST90199621 - GCST90204063; `63f8add57325c20001210db7`) can be found in the [pre-pub table](https://www.ebi.ac.uk/gwas/downloads/summary-statistics) even though they are published in the Catalog. They should be removed from the pre-pub table. Note the studies & submission themselves should not be removed from the database, only that they should not be displayed in the prepub table.  

There is another submission with a similar issue, see Lizzy's comment below

**Comment by ljwh2** [comment]
@ljwh2 to find out submission ID/GCP

**Comment by earlEBI** [comment]
@ljwh2 Submission ID for the above submission is '63f8add57325c20001210db7'. 
(note: the submission itself should not be deleted as it is linked to a PMID. It should just be removed from prepub table.)

**Comment by earlEBI** [comment]
The same issue exists for PMID 38182883, submission id '653f646de6cd82000152e763'. 
4 GCSTs are present in the prepub sumstats table despite being linked to a PMID. 
2 of the GCSTs weren't even submitted prepublication (they were added later by a curator.)
Please remove this submission from the prepublished sumstats table.

**Comment by sajo-ebi** [comment]
@earlEBI the Unpublished studies has been deleted

**Comment by ljwh2** [comment]
@earlEBI please could you verify this after the DR is complete

**Comment by sajo-ebi** [comment]
Hi @Lizzy regarding Backman submission I see there are two submissions the one ‘63f8add57325c20001210db7’ & another one ‘6352df9a37db26000190659a’ which has 1400 studies which share same GCST as ‘63f8add57325c20001210db7’ so we might need to delete the submission ‘6352df9a37db26000190659a’ as we can’t have 2 submission that share same studies

**Comment by earlEBI** [comment]
For the record, this is not Backman. It is Chen.

**Comment by earlEBI** [comment]
For the publication with 4 studies (PMID 38182883), I've unpublished, re-imported and will re-publish to try to fix the issue.

**Comment by earlEBI** [comment]
Both PMIDs no longer appear to be in the prepublished table. Issue seems to be resolved.
