### ISSUE TITLE
Bulk assign trait-EFO feature not working - Sandbox

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1354]
The bulk assign trait-EFO tool is throwing an error for all uploaded rows. 

Eg. https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/666833cd51d43d0001d7e113
2941 studies
Bulk assign file = [dhindsa-test-import-traits-EFOs.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8bf459be7684a75266decc35f6713cee4271a70/dhindsa-test-import-traits-EFOs.txt)
Error report = [study-trait-bulk-report(17).txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2RxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb2244451718b4de92d0846c8d6a159db328bbde/study-trait-bulk-report%2817%29.txt)

Error for every line = "Study not found. Please check accession and tag."

Santhi also tested with a smaller submission - https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/666ac8bc51d43d0001d98d9a - and found the same issue. 

Please investigate.

**Comment by sajo-ebi** [comment]
there was UI bug that caused the upload to fail ,the issue has been resolved & the traits uploaded successfully
