### ISSUE TITLE
Sumstats filetype for GCST90432154 is GWAS-SSF v1.0 but should be non-GWAS-SSF

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1358]
This summary statistics file is missing two mandatory columns: _beta_ and _standard_error_, so should not meet the GWAS-SSF format. I also pushed it through validation manually. I would therefore expect the file type to be **non-GWAS-SSF**, but it is unexpectedly showing as **GWAS-SSF v1.0** in the yaml file.

Actions:

- [x] Change file type to **non-GWAS-SSF** for this submission
- [x] Investigate to make sure that files with validation manually overriden are being annotated as non-GWAS-SSF as expected in future

**Comment by karatugo** [comment]
fixed the file type in mongo

**Comment by karatugo** [comment]
expect the new metadata yaml in 2 days

**Comment by karatugo** [comment]
Discuss tomorrow in the meeting. 

`/gwas/deposition/api/v1/bypass-ss-validation` - this endpoint sends payloads with `forceValid=True` and `skipValidation=False`. I wonder how they should affect file type detection. For example, should we set `non-gwas-ssf` when either is True? (currently only set `non-gwas-ssf` when `skipValidation=True`).

**Comment by karatugo** [comment]
deployed to sandbox

**Comment by karatugo** [comment]
test okay in sandbox

**Comment by karatugo** [comment]
deployed to prod

**Comment by karatugo** [comment]
Looks good to me: https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90432001-GCST90433000/GCST90432154/

**Comment by eks-ebi** [comment]
yes, me too! thanks @karatugo
