### ISSUE TITLE
Change file type to non-GWAS-SSF for 2 studies GCST90328147 and GCST90328148

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1360]
The current file type for these 2 studies is GWAS-SSF, as the user has populated the beta and SE columns with values '0', and the z-score column is provided after the p-value column. The file type should be changed to a non-GWAS-SSF.

**Comment by karatugo** [comment]
fixed their file types

**Comment by sprintell** [comment]
Hi @Santhi1901 

Could you pls help confirm if this good to be closed?

Thanks

**Comment by Santhi1901** [comment]
this can be closed, the file type appears correct on FTP
