### ISSUE TITLE
Second user for harmonisation pipeline

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1362]
Discussion with Open Targets on adding us as user in their group. Need to ensure we can publish harmonised files to our ftp.

**Comment by jiyue1214** [comment]
Resource limits: Limits on SLURM are applied per GTL. Reaching the resource limit for a group will block all the group members' jobs from starting till any of the running jobs are completed. For the harmonisation pipeline, we use 1 datamover node per day to move the data to FTP and all others are short node

datamover: 120CPU, 960G per GTL
Other CPU partitions: 3000 CPUs, 30TB per GTL

If we harmonize the data using the second user account under the other GTL name, we will have higher quota on computing resources and can harmonize more data.

**Comment by jiyue1214** [comment]
Prashant Uniyal from the open target group already created a virtual account `ot_gwas` under the GTL Ellen McDonagh's account that, Karatug David Ochoa can access it.

An account has been created, but we are encountering some issues with the settings, preventing successful access. We are currently awaiting TSC's assistance (ticket created): RITM0019933 (Service Desk) and RITM0019826 (HPC)

**Comment by jiyue1214** [comment]
Can access to the `ot_gwas` now. Waiting for the permission of `/hps/software` and `/hps/nobackup/` to be `drwxrwxr-x`

**Comment by jiyue1214** [comment]
Deployment plan
<img width="772" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6a8a0a0813ae00ee4e21e4f713f44425af13498/image.png" alt="image.png" />

**Comment by jiyue1214** [comment]
All the script are finishe. ot_gwas is running 20 studies / file_type/day for the test period for 1 week. If no problem, will run 400 studies / file_type/day after the test period. Can be moved to the review.

**Comment by jiyue1214** [comment]
Two accounts setting are running well during 1 week test period. I have upgrade the daily running number for ot_gwas from 20 to 400 studies.

**Comment by jiyue1214** [comment]
The pipeline works well and harmonised data were synchronised to the FTP successfully. This ticket can be closed.
