### ISSUE TITLE
Change PMID status to allow Depocuration submission

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1367]
Related to ticket https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/xgwas-curator-tasks/26

PMID 30104761 is closed for submission as it was originally curated through the Curation App. 

Please change the status to 'open for submission' so that I can submit extra studies. 
This needs to be done well before a DR starts.

**Comment by sajo-ebi** [comment]
@earlEBI done

**Comment by earlEBI** [comment]
@sajo-ebi The status is closed again. This needs to be opened as early as possible before 23rd July to allow me to curate before the next DR, thank you.

**Comment by ljwh2** [comment]
@earlEBI please flag when this ticket can be closed, thanks

**Comment by earlEBI** [comment]
This ticket can be closed.
