### ISSUE TITLE
Release new readme files but NOT summary statistics for all studies in PMID 37601966

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1368]
Summary statistics cannot be released for this publication due to restrictions on sharing certain data from China.

So far, I have set the full p-value sumstats flag to **no** to prevent the summary statistics from being released publicly. This means that their are FTP links displayed in the UI (see https://www.ebi.ac.uk/gwas/publications/37601966) but the links are broken as there are no public FTP folders. The folders do exist on staging, but are hidden.

However, we want to display a readme to users that explains why the files are not available (readme.txt file attached):

[readme.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTIwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d729446e57f287175402f4ae2d12778fb6351697/readme.txt)

Goals:
* create public FTP folders for each study, containing the readme.txt
* make sure the summary statistics are not released to the public FTP
* ideally, do this without permanently deleting the summary statistics files, so that we may release them at a later date if restrictions ease

**Comment by karatugo** [comment]
Implemented and tested. Please check @eks-ebi

**Comment by eks-ebi** [comment]
Thanks @karatugo that looks perfect!
