### ISSUE TITLE
Reset the submission 6687f8eff2bba90001a93384 (Details for GCP ID: GCP000952)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1369]
The submission needs to be reset for the user to reupload the template.

The user added the same study tag for multiple studies, and the submission stats show 0 studies, samples and no GCST. The metadata is shown as VALID

**Comment by sajo-ebi** [comment]
@Santhi1901 the submission has been reset

**Comment by ljwh2** [comment]
@Santhi1901 please confrim
