### ISSUE TITLE
Curation reporting

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1372]
Curators need access to the following metrics, to be generated weekly at 7pm on sunday evening: 

Detailed specifications are here: https://docs.google.com/document/d/1JA8VqKy685dZdyngpN0S-Kqw86uMMOFRwJAYctfL1wU/edit

**Comment by sajo-ebi** [comment]
this is reviewed by curators & good to be released to prod will be done asap.

**Comment by ljwh2** [comment]
First author showing as null, needs fixing

**Comment by sajo-ebi** [comment]
Resolved the issues reported by Lizzy but Publication weekly stats didn't get generated due to some error will investigate & fix it before next run

**Comment by sajo-ebi** [comment]
The purge job fix didn't work in last DR , to fix before DR start

**Comment by ljwh2** [comment]
@Santhi1901 to provide list of sandbox PMIDs that are showing in prod report, Sajo will delete them

**Comment by Santhi1901** [comment]
I've placed the list of PMIDs that needs to be removed from prod: https://docs.google.com/spreadsheets/d/1t2rQTkERAbMvVfaRp2Dk4LrvO5cvNO48BkfqVwLk66s/edit?gid=1644809304#gid=1644809304 

Some of them are not in the sandbox, and there is one publication with pmid as null; it is a duplicate copy of https://www.ebi.ac.uk/gwas/depo-curation/publications/64397b43c7f2a40001c2bac3

**Comment by sprintell** [comment]
Hi @sajo-ebi create a bug ticket to fix the few extra issues reported

**Comment by earlEBI** [comment]
> First author showing as null, needs fixing
> 
> @earlEBI please check user requested and Open targets are showing correctly, there are not many to test

There is only one 'user requested' in the report, I assume this is correct from old L2 prioritisation spreadsheet which had 0 user-requested. 

For the OT flag, I'm still not convinced this is being saved permanently. There are 3 OT flagged in the report. I will continue to monitor for a few weeks.
