### ISSUE TITLE
Add GxE column to studies download

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1374]
All v2 and v3 studies downloads should have an additional column indicating GxE yes or no. 

Background info: GxE status is entered in the studies tab of the submission template.

**Comment by ljwh2** [comment]
The column header definitions will need updating @ljwh2

**Comment by eks-ebi** [comment]
@ala-ebi  I can only see 5 studies (from 1 publication) with GxE = yes. That doesn't seem right. Is the data up to date?

**Comment by eks-ebi** [comment]
ugh sorry, I'm commenting before reading all the information - I see this was intentional, so this looks good for the current test!

**Comment by ala-ebi** [comment]
should be fixed in next DR
