### ISSUE TITLE
Sumstats folders without yamls - 6662c6faf2bba900017af11d

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1377]
3 out of 4 studies for this submission have no yamls on staging: 
GCST90429796-GCST90429798

(GCST90429795 has a yaml). 

Please generate the missing files.

**Comment by karatugo** [comment]
The files are in staging ftp and public ftp. They are generated 1-2 days after the ticket is created. Please check if they look okay @earlEBI 

- https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90429001-GCST90430000/GCST90429795/
- https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90429001-GCST90430000/GCST90429796/
- https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90429001-GCST90430000/GCST90429797/
- https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90429001-GCST90430000/GCST90429798/

**Comment by earlEBI** [comment]
Checked first and last look good - thanks! Ticket can be closed.
