### ISSUE TITLE
GxE study status indicator on each study page

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1378]
GxE study status should be indicated on each study page e.g. https://www.ebi.ac.uk/gwas/studies/GCST004800. This could be presented alongside “Full summary statistics” and “Terms/License”. Could be yes/no or would be nice to have an icon like the sumstats.  An icon could also be displayed in the search snippet, similar to sumstats and targeted arrays (but this is lower priority).

**Comment by eks-ebi** [comment]
looks good, although I've only seen the "X" for non-GxE studies. Could you give an example with the "yes" icon?

**Comment by sajo-ebi** [comment]
waiting for DR to confirm
