### ISSUE TITLE
Zhou - PMID:30104761 - keep original GCSTs

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1382]
Related to ticket https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/xgwas-curator-tasks/26

This PMID is being re-curated to match sumstats. 
4 GCSTs already existing in UI. 
New submission has been created: https://www.ebi.ac.uk/gwas/depo-curation/submissions/669e2604f8167b0001a7388e

Please edit 4 of the new GCSTs to keep the original GCSTs as given in this .txt file:
[Zhou - change GCSTs.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFVGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--717f686f2d0daea486807e989c35e28c6f6d327f/Zhou%20-%20change%20GCSTs.txt)

**Comment by sprintell** [comment]
Hi @earlEBI  could you please confirm if this ticket can be closed ? Thanks

**Comment by earlEBI** [comment]
This ticket can be closed.
