### ISSUE TITLE
Change yaml file types to pre-GWAS-SSF - PMID 30104761

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1387]
For submission '669e2604f8167b0001a7388e', please change all summary statistics file types to 'pre-GWAS-SSF'. 
There should be 1403 files (not yet on staging at time of creating ticket. Karatug looking into why.)

GCSTs listed here: [gcst_list - PMID 30104761.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNllMQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bb165dc86aabf6e7074f39f1d69c282f0024c1d/gcst_list%20-%20PMID%2030104761.xlsx)

**Comment by karatugo** [comment]
Fixed file types. Renamed GCST008370-GCST008373 manually. Published GCST IDs to rabbitmq.

**Comment by karatugo** [comment]
Expect yaml files in 2 days.

**Comment by karatugo** [comment]
@karatugo Investigate where maf and software data come from.

**Comment by karatugo** [comment]
The issue is caused by sbatch/slurm. So I regenerated the yaml files. Thanks @earlEBI for catching that error.

**Comment by karatugo** [comment]
Checked the files again, looks good to me.

**Comment by earlEBI** [comment]
@karatugo The issue seems to persist for eg. GCST008372 and GCST90435509

**Comment by karatugo** [comment]
Hmm, thanks @earlEBI, evidently the issue is not fixed for some GCSTs. Re-generating YAML files again. This time I'll check more :)

**Comment by sprintell** [comment]
Hi @earlEBI please help us check if this can be closed. Thanks

**Comment by earlEBI** [comment]
I've checked a few look okay, thank you
