### ISSUE TITLE
Introduce a new field in the template schema to enforce field length and validation.

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/goci#139]

**Comment by tudorgroza** [comment]
@eks-ebi - this is now available for testing in Sandbox. You will need the download the latest template definition and try to force an invalid entry by filling in a mandatory field with a value larger than 255 characters. Thank you.

**Comment by eks-ebi** [comment]
Tested 2020-08-04 in Sandbox. Created a new submission for a publication, downloaded the submission form and entered >255 characters into the Study Description field.

> http://193.62.54.159/gwas/deposition/submission/5f291e7856dfd500015e350f

Got this error:

> Invalid file uploaded. Please download a new template from the submission page and try again.

Is this the expected error for when a template has a field with too many characters? (if so, I don't think it's specific enough to be informative for the user) Or did I need to do something different to get the latest template definition??

**Comment by tudorgroza** [comment]
That's not the error you should have received. Let me have a look.

**Comment by tudorgroza** [comment]
@eks-ebi - can you please delete the file and re-upload. Error should be fixed now. Thank you.

**Comment by eks-ebi** [comment]
Retested and the error message is now correct:

> Studies: Column 'Study description' in row(s) [5] contains a value with a size larger than accepted. Accepted value size should is: '255'

**Comment by tudorgroza** [comment]
Oops ... need to fix the text ... `Accepted value size should __be__`.
Thank you.

**Comment by tudorgroza** [comment]
I'll fix that. Are you happy with this outcome? Can I move the EPIC to done?

**Comment by eks-ebi** [comment]
Oops yeah I didn't notice that mistake! If that's fixed then yeah, I'm happy with the outcome
