### ISSUE TITLE
Change field names in search UI pages

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1391]
On study pages:

- [x] In study information box: Replace “Discovery ancestry (country of recruitment)” with “Discovery ancestry label (country of recruitment)”

“Replication ancestry (country of recruitment)” with “Replication ancestry label (country of recruitment)”

- [x] To this text above, add "?" with hover text "What is an ancestry label?" and link to https://www.ebi.ac.uk/gwas/docs/ancestry (noting url will change, see goci#1389) 

- [ ] If possible, add the same hover to Studies table to the header of the sample column as shown (red is just for illustration):

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2dOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ecedab245c672896546d6e1880047d46f7139cc1/Screenshot%202024-07-25%20at%2017.01.04.png" alt="Screenshot 2024-07-25 at 17.01.04.png" />

**Comment by sajo-ebi** [comment]
@ala-ebi to prioritize in this sprint
