### ISSUE TITLE
Unlink PMID 39002897 and submission GCP000922 / 66752b42d222f50001ba59b9

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1393]
These have been accidentally linked through Depocuration. 

Please unlink ASAP.

**Comment by ala-ebi** [comment]
*Publication: remove curator, curationStatus and submitter
*BodyOfWork: remove pmid from pmids list
*Submission: remove publicationId
*Study: remove publicationId

**Comment by earlEBI** [comment]
Submission and PMID look to be unlinked in DepoCuration and Deposition, done, thank you!
