### ISSUE TITLE
Variant mapping query

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1397]
A user wanted an explanation of how the variants are mapped.

They are particularly interested in this variant, rs6011066, which is mapped to gene ZGPAT in UI. But the link to Ensembl shows the variant is in a gene-dense region that includes all of these genes (ZGPAT, LIME1, SLC2A4RG).

**Comment by sajo-ebi** [comment]
@Santhi1901 based on my investigation the mapped Gene is computed as the below -:

We check the overlapping gene , if any matching vaues are found mapped gene is assigned 
if no overlapping gene exists then 2 closest genes are found , 1 upstream & 1 downstream.

In this case ZGPAT came out to be the overlapping gene for 'rs6011066'

**Comment by sajo-ebi** [comment]
@Santhi1901 kindly confirm if this can be closed

**Comment by Santhi1901** [comment]
this can be closed
