### ISSUE TITLE
Unlink PMID from the submission 662b5b62f2bba90001c36699

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1399]
The PMID added to this submission is the pre-print PMID. It needs to be removed.

The correct PMID for this submission is 39013416.

**Comment by ljwh2** [comment]
Awaiting fix for goci#1398

**Comment by ljwh2** [comment]
@Santhi1901 please confirm if you were able to add the new PMID to the submission?

**Comment by Santhi1901** [comment]
yes, the new PMID was added to the submission

**Comment by eks-ebi** [comment]
@ljwh2 I'll close this too now that Santhi has confirmed
