### ISSUE TITLE
The value for "Date Created" on the view single submission page is wrong

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#140]
See attachment

![Screenshot 2020-07-29 at 13.18.16.png](https://images.zenhubusercontent.com/59fafd6b8a75884b9085c552/3886f390-879c-4876-b0cf-d4507a3b10f3)

**Comment by ljwh2** [comment]
@earlEBI please check if this is still required

**Comment by earlEBI** [comment]
This doesn't seem to be an issue anymore.
