### ISSUE TITLE
Reopen the PMID:29531354

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1400]
The status is closed for the PMID. It is curated through the old curation app, and no submission is present.

We need to reopen the PMID to edit the sample details and submit it through the deposition app. 

This needs to be done before the next data release

**Comment by sajo-ebi** [comment]
@Santhi1901 done

**Comment by ljwh2** [comment]
@Santhi1901 can this be closed?

**Comment by Santhi1901** [comment]
yes, this can be closed

**Comment by eks-ebi** [comment]
@ljwh2 I've closed this
