### ISSUE TITLE
Yamls not being generated

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1401]
I found many GCSTs across several different GCST parent brackets which do not have yamls, eg: 

09/08/24 - http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90445001-GCST90446000/GCST90445932/
18/07/24 - http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90435001-GCST90436000/GCST90435443/
10/08/24 - http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90446001-GCST90447000/GCST90446130/
12/06/24 - http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90432001-GCST90433000/GCST90432041/
08/08/24 - http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90444001-GCST90445000/GCST90444337/
07/08/24 - http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90443001-GCST90444000/GCST90443943/

This is not an exhaustive list. 
Please investigate, thank you.

**Comment by karatugo** [comment]
I tested body of work in sandbox, metadata yaml create successful.

**Comment by karatugo** [comment]
Also tested publishing `GCST90446130` to RabbitMQ. Metadata yaml create successful.

**Comment by karatugo** [comment]
Also this yaml file was created during that period. http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90435001-GCST90436000/GCST90435387/

**Comment by karatugo** [comment]
@karatugo 

Create a new meta table where we keep success/fail states of metadata yaml generation. Run a daily report.

**Comment by karatugo** [comment]
I'll prioritise this issue after my holidays.

**Comment by karatugo** [comment]
https://github.com/EBISPOT/gwas-sumstats-service/pull/358

**Comment by karatugo** [comment]
- [ ] Test scenarios as in TODO in the code
- [ ] Fix nightly cron
- [ ] Fix file type issues first
- [ ] Write a script that scans all missing yaml files and adds them to the DB

**Comment by karatugo** [comment]
- [x] Submit failed YAML emails
- [x] Deploy to prod
- [x] Add to cron jobs
- [x] Attempt to generate 'failed' YAMLs

**Comment by karatugo** [comment]
- [ ] Check YAMLs generated today arrived to staging ftp

**Comment by karatugo** [comment]
- [ ] Update Confluence docs

**Comment by karatugo** [comment]
Please find the updated docs here. https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/SummaryStats+metadata+YAML+Update+Mechanism

**Comment by karatugo** [comment]
fixed email script for prod

**Comment by karatugo** [comment]
created a new script to update status of failed attempts from the previous day

**Comment by jiyue1214** [comment]
Thank you, Karatug. I also observed a significant reduction in the 'not_harm' file, from 17,655 to 7,900. This suggests that many studies that were previously missing meta-yaml files have now had their yaml files regenerated by this script

Not_harm file
|20240703 |20240827| 20240918 |20240924|
|--- |---| --- |---|
|9654|17631|17655|7900|

**Comment by karatugo** [comment]
@karatugo 

- [ ] Add the script that attempts to generate YAML files of the failed attempts of prev day. Run it once again only. Send emails only for those cases (failed twice) that needs human attention. Perhaps also add the number of successful generations of the prev day?

**Comment by karatugo** [comment]
Deployed to prod.
