### ISSUE TITLE
Improve submission of Country of Recruitment info for users

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#141]
The GWAS Catalog needs to present consistent terminology for countries of recruitment to support user queries and use of the ancestry ontology. However (1) the requirement for users to check exact spellings in the standard list puts a burden on users and (2) special characters in the list may be problematic. 

We need a solution that allows users to enter 
1. common variants of popular countries (eg USA instead of U.S.) and converts them to standard terminology in the public database. 
2. Names of countries without special characters eg Sao Tome and Principe instead of São Tomé and Príncipe

**Comment by ljwh2** [comment]
assigned to me to come up with list of common variants

**Comment by tudorgroza** [comment]
@ljwh2 - can you please give me access to the document? Thank you

**Comment by ljwh2** [comment]
@tudorgroza what testing environment should be used for this? Sandbox?

**Comment by tudorgroza** [comment]
Yes please.

**Comment by aoifemcm** [comment]
Tested with CoRs UK, US and Iran. Validator does not accept these as CoR.  Error message 'Samples: Column 'CoR in row(s) 5 contains incorrect value.  Accepted values are: etc'.
Tested each of the three CoRs separately. ie not pipe separated in one row or on separate rows but using three separate upload templates e.g. Template attached.
[CoR template test_AMcM1.xlsx](https://github.com/EBISPOT/goci/files/5137399/CoR.template.test_AMcM1.xlsx)

**Comment by tudorgroza** [comment]
@aoifemcm - can you please download and use the latest template? This example contains an old version (1.5). Thank you.

**Comment by eks-ebi** [comment]
New test submission:
http://193.62.54.159/gwas/deposition/submission/5f58cbad10d4370001594213

1. Tested with all variations listed in Laura's doc for `U.S.`, `U.K.`, `Republic of Korea`, `China, Hong Kong SAR` and `Iran (Islamic Republic of)` - all of these passed validation, as expected.
2. Tested with/without special characters for `Côte d’Ivoire`, `Réunion`, `São Tomé and Príncipe` - either version passed validation, as expected.
3. Tested with completely made-up countries - these failed validation, as expected.

**Comment by eks-ebi** [comment]
I have spotted a few other country names in the list, where I think users might be likely to enter alternative spellings. I'm adding these to the Google doc now, but not necessarily saying these need to be added now (I think all are countries that we might not have seen in papers so far, but could come up in future).

**Comment by tudorgroza** [comment]
@eks-ebi - thank you for this!
Can you please just copy-paste the list here and I'll add them to the template. It's an easy process.

**Comment by eks-ebi** [comment]
Standard name in the database = Likely variations
Brunei Darussalam = Brunei
China, Macao SAR = Macao|Macau
Czech Republic = Czechia
Côte d’Ivoire = Ivory Coast
Democratic People’s Republic of Korea = North Korea
Faeroe Islands = Faroe Islands
Lao People’s Democratic Republic = Laos
Libyan Arab Jamahiriya = Libya
Micronesia (Federated States of) = Micronesia|Federated States of Micronesia
Occupied Palestinian Territory = Palestine
Republic of Ireland = Ireland
Republic of Moldova = Moldova
Russian Federation = Russia
Swaziland = Eswatini
The former Yugoslav Republic of Macedonia = North Macedonia
U.S. Virgin Islands = US Virgin Islands|United States Virgin Islands
United Republic of Tanzania = Tanzania
Viet Nam = Vietnam
[Not currently included] = South Sudan

**Comment by eks-ebi** [comment]
There are also some examples where the name we use is no longer the official name (and maybe others I've missed), so we may want to consider changing the default name at some point. I don't suggest you do anything about these now @tudorgroza. But I've added some notes to the Google doc for @ljwh2's info
