### ISSUE TITLE
Remove the submission and sumstats 65fb1cc0db8d9f000196a32e

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1411]
The submission and sumstats need to be removed as the user has requested it to be retracted

**Comment by karatugo** [comment]
Deleted its studies using the scripts at `/hps/nobackup/parkinso/spot/gwas/scratch/goci-1411`.

Please find the deleted gcst id list attached. [delete-65fb1cc0db8d9f000196a32e.csv](https://github.com/user-attachments/files/17116045/delete-65fb1cc0db8d9f000196a32e.csv)

**Comment by ljwh2** [comment]
@Santhi1901 please confirm

**Comment by Santhi1901** [comment]
the submission is still present in depo app: https://www.ebi.ac.uk/gwas/deposition/submission/65fb1cc0db8d9f000196a32e

**Comment by sprintell** [comment]
@sajo-ebi  will need to delete the submission

**Comment by sajo-ebi** [comment]
@Santhi1901 the submission has been deleted

**Comment by ljwh2** [comment]
@Santhi1901 please confirm the ticket can be closed

**Comment by Santhi1901** [comment]
this can be closed
