### ISSUE TITLE
Import button is orange

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/goci#1412]
submissions 650deeb553c4ef00014ab71c: Elliot unpublished, then clicked Allow Import, saw it in the list but the Import button was inactive (orange). This was caused by the Pulication still having status PUBLISHED in Mongo after being unpublished.

submission 66704811a6e7cc0001352d44: has to do with the user adding pmid to BoW… PMID is not added to the submission only added to BoW and studies. Manually added pmid to submission, Laura to create ticket to fix the issue

**Comment by ljwh2** [comment]
@ljwh2

**Comment by sajo-ebi** [comment]
@ljwh2 kindly confirm if this can be closed

**Comment by ljwh2** [comment]
Follow up ticket about adding PMIDs to submissions: goci#1435
