### ISSUE TITLE
Investigate/restart submission stuck in validation

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1413]
This submission https://www.ebi.ac.uk/gwas/deposition/submission/66b09e262500c600017e952e seems to have been stuck in validation for several days.

Please investigate if there is a bug, and restart the validation to allow the submission to be completed.

**Comment by ala-ebi** [comment]
https://www.ebi.ac.uk/gwas/depo-curation/submissions/668c542ca6e7cc00012f63cf celery workers were down, fixed as soon as I started them
https://www.ebi.ac.uk/gwas/deposition/submission/66b09e262500c600017e952e doesnt have callback ids, deposition logs from the day of upload say failed to contact ss-service, probably will need to fire the POST request that was supposed to call ss-service from deposition app

**Comment by sajo-ebi** [comment]
@Ala to mark the submission as invalid then @eks-ebi  will download the submission template in Depo curation , post we should reset the submission from backend & reupload the submission template
