### ISSUE TITLE
EFO_0003761 has obsoletion error

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1414]
There is an error coming in the obsolete EFO report for EFO_0003761, which was deprecated with replacement in EFO

Please find out what the error is and whether any action is required.

**Comment by sajo-ebi** [comment]
@Ala to look in to it in new sprint

**Comment by ala-ebi** [comment]
Errors for this term because it already exists in our DB, likely added manually by a curator.

**Comment by ljwh2** [comment]
@ala-ebi to create a ticket to handle this scenario in the obsoletion process

**Comment by ljwh2** [comment]
Moving the obsolete EFO's studies and associations to point to the replacement one still needs to be done

**Comment by ala-ebi** [comment]
this is now done, for future reference:
here’s what to do to replace an obsolete EFO with the new one that already exists, in Oracle and Mongo:
1.  updates to oracle
```
UPDATE STUDY_EFO_TRAIT SET EFO_TRAIT_ID = oracleIdNew WHERE EFO_TRAIT_ID = oracleIdOld;
UPDATE STUDY_BACKGROUND_EFO_TRAIT SET EFO_TRAIT_ID = oracleIdNew WHERE EFO_TRAIT_ID = oracleIdOld;
UPDATE ASSOCIATION_EFO_TRAIT SET EFO_TRAIT_ID = oracleIdNew WHERE EFO_TRAIT_ID = oracleIdOld;
UPDATE ASSOCIATION_BKG_EFO_TRAIT SET EFO_TRAIT_ID = oracleIdNew WHERE EFO_TRAIT_ID = oracleIdOld;
```
2.  updates to mongo
```
db.studies.updateMany(
  { "efoTraits": "mongoIdOld" },
  { $set: { "efoTraits.$[elem]": "mongoIdNew" } },
  { arrayFilters: [ { "elem": "mongoIdOld" } ] }
)
```
3.  delete the old efotrait from depo-curation (or mongo)
