### ISSUE TITLE
Some searches not loading in GWAS Catalog UI

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1419]
Some searches are spinning forever in the search UI, including ACE2 (gene) and schizophrenia (trait), also the generic search that displays the 20 most recent publications. 

> The issue with UI search is caused by some publications that should not be published but still passed pruning step, discussed with devs and we think it could be related to the Publications newly imported from EPMC, synced to Oracle, but don’t have that empty study and Housekeeping entry which is likely how the pruning process identifies what to keep and what to omit.

**Comment by sajo-ebi** [comment]
this will be fixed as part of data purge fix to remove the newly imported Pmids from EuropePMC before Data release

**Comment by sajo-ebi** [comment]
Fixed the data purge job to add all publications that have been recently imported

**Comment by ljwh2** [comment]
@Santhi1901 could you please give Sajo an example of a PMID that was added recently and not curated yet?

**Comment by Santhi1901** [comment]
These were added on 6th Sep and not yet curated
39202552
39192094
39215135
39192486
39187189
