### ISSUE TITLE
Unable to edit Reported Trait name in depocuration

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1422]
I need to correct the name of this Reported Trait in depocuration (https://www.ebi.ac.uk/gwas/depo-curation/reported-traits). But when I tried to edit the name, I get the following message:
`An unexpected error occurred.`

The change I am trying to make is:
**Alpha- levels** --> **Alpha-(1,6)-fucosyltransferase levels**

**Comment by eks-ebi** [comment]
Discovered that trait name can;t be changed because it already exists. So need to delete "Alpha- levels" and reannotate study.

@sajo-ebi can you check in database to see if any other studies are annotated with "Alpha- levels" as Reported trait?

**Comment by ljwh2** [comment]
@eks-ebi check if any published studies are annotated with Alpha- levels, if so, reannotate these studies in Depo-Curation

**Comment by eks-ebi** [comment]
@ljwh2 Lizzy has reannotated the study with the correct Reported trait as part of a larger update to the submission, and it will be re-published today. I have also now deleted the incorrect `Alpha- levels` reported trait from the traits list in depo-curation.

So this ticket can be closed.

**Comment by eks-ebi** [comment]
confirmed in staging
