### ISSUE TITLE
Document issues arising from recent cluster maintenance

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1434]
Please document all known issues that occurred following the recent cluster maintenance and the impact on our workflow (e.g. sumstats did not get released, associations did not get mapped), and how they were addressed so we can be prepared to check after future round of maintenance.

These include:
- celery workers failed affecting sumstats released
- harmonisation pipeline failed due to permissions on home directory
- cronjobs did not run, affecting multiple parts e.g. validation pipeline, mapping pipeline. 

Set to high priority so this can be done while it's fresh in the mind. @karatugo please assign relevant parts to others where needed.

**Comment by karatugo** [comment]
Please find the Confluence document here: https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Issues+arising+from+recent+cluster+maintenance
