### ISSUE TITLE
Studies missing the `date_metadata_last_modified` on meta-yaml file

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/goci#1440]
There are totally 2237 GWAS_SSF
GCST ids are listed here [GCST_missing_in_date.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDRFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c15742cb2d818f21f6c4258bb18a879ff5bc061a/GCST_missing_in_date.txt)

For those studies missing the date_metadata_last_modified. Need to regenerate the meta-yaml file for them and then rerun the harmonisation pipeline.

**Comment by karatugo** [comment]
@karatugo 

- [ ] Mark GCST IDs as pending
- [ ] Check tomorrow if they are generated successfully

**Comment by karatugo** [comment]
Marked the GCST IDs as pending using the script `/hps/software/users/parkinso/spot/gwas/prod/scripts/cron/sumstats_service/mark_as_pending.py`.

**Comment by karatugo** [comment]
I will check tomorrow if they are generated successfully.

**Comment by jiyue1214** [comment]
Thank you so much, @karatugo. I checked all studies and I verified that they all already have new meta-yaml files with the field 'date_metadata_last_modified' in the staging folder. 

I have put them back in the queue for harmonisation. 

Thank you so much for your help.

**Comment by karatugo** [comment]
Public FTP looks good.

**Comment by jiyue1214** [comment]
These studies are still not being harmonised successfully. They were harmonised one time during July time but failed on the step of moving the running.log file into the harmonised folder.

I checked the GCST90313127, which cannot initiate the harmonisation pipeline queue because the file type is  ' GWAS-SSF v1.0', because of quota and space, it failed the queueing script and is recognised as "not_harm" type, which cannot queue the hm pipeline.

**Comment by jiyue1214** [comment]
Instead of giving the allowed values, we can think about not allowing empty strings here, like `''`,`' '`, or any space at the beginning. - need to update meta yaml schema.

**Comment by jiyue1214** [comment]
GCST                        genome_assembly   coordinate       file_create_time
GCST90310250	 GRCh37	 1-based	 ''	2024-10-05 -> Missing file_type
GCST90319471     ''      1-based         GWAS-SSF v1.0  2024-10-16 -> missing genome assembly
GCST90319472     ''      1-based         GWAS-SSF v1.0  2024-10-16 -> missing genome assembly

**Comment by karatugo** [comment]
Successfully updated GCST90310250 to GWAS-SSF v1.0.

**Comment by karatugo** [comment]
YAML file for GCST90310250 will be created in 2 days.

**Comment by karatugo** [comment]
> GCST90319471: `genome_assembly`:`GRCh37`
> GCST90319472: `genome_assembly`:`GRCh37`

This is consistent with mongo. Just regenerating YAML files.

**Comment by karatugo** [comment]
YAML files will be created in 2 days.

**Comment by jiyue1214** [comment]
Studies are being harmonised, and three days are needed to finish all GWAS-SSF studies reharmonisation.

**Comment by jiyue1214** [comment]
I confirmed that the YAML files of ` GCST90310250` and `GCST90319471` are done on staging and FTP.
@karatugo could you please help with `genome_assembly` of the study `GCST90319472`? it is still missing now.

**Comment by karatugo** [comment]
@jiyue1214 I investigated this issue. Genome assembly data comes from either the ingest or rest api. However GCST90319472 is not present in either of them. Hence yaml generation fails.

**Comment by karatugo** [comment]
@jiyue1214 Can't we simply add GCST90319472 to ingest api?

**Comment by jiyue1214** [comment]
These studies already be harmonised. This ticket can be closed.
