### ISSUE TITLE
Studies need to be re-assigned the file_type as 'not_harm"

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/goci#1441]
There are some studies cannot be harmonised, but they are labelled as pre-fwas-ssf or gwas-ssf. Need to re-assign the file type into 'not_harm".

- 3 studies PMID_37592023 - gene_based
- 594 studies PMID_33983923, need to drop, there is no allele info
- 102 studies PMID_35240056, missing other allele information
- 10 studies PMID_37469131, missing other allele information
- 9 studies PMID_36085083, missing other allele information
- GCST90002235, GCST90002241 only have het_p_value, no_p_value
- GCST003922 beta is not a value

**Comment by jiyue1214** [comment]
In the [file](https://docs.google.com/spreadsheets/d/1_fHcurSt3Tg1-cYWWnJggFDnByYTBhzZ0ca7EyRNKV8/edit?gid=512151099#gid=512151099&fvid=31583167), the spreadsheet `Studies in worng file_type`,  I list 803 studies that they were labelled as `pre-GWAS-SSF`, but harmonisation pipeline found they should be classified as `non-GWAS-SSF` since they are missing allele information. 
 You can check these studies via Data -> change view -> non-GWAS-ssf

I also attached a pure version with those studies only:

**Comment by jiyue1214** [comment]
GWAS-SSF v1: Version 1 of the GWAS-SSF standard format.
Pre-GWAS-SSF: The previous, minimal format requiring only chromosome, base_pair_location/rsID and p-value.
Non-GWAS-SSF: Not conforming to any standard format. Can include gene-based, CNV and multivariate analyses where eg. effect information is not available.

**Comment by jiyue1214** [comment]
@karatugo  Only these three study need to changed from "GWAS-SSFv1.0" into "non-GWAS-SSF" because they are gene base analysis.

GCST90267996	2023-07-03	GWAS-SSFv1.0	non-GWAS-SSF
GCST90267997	2023-07-03	GWAS-SSFv1.0	non-GWAS-SSF
GCST90267998	2023-07-03	GWAS-SSFv1.0	non-GWAS-SSF

**Comment by karatugo** [comment]
Updated above GCST IDs as `non-GWAS-SSF` and marked them as pending yaml generation.

**Comment by karatugo** [comment]
Just to be clear - files are generated but the file types are not correct.

**Comment by karatugo** [comment]
I checked all and they seem correct to me.

**Comment by jiyue1214** [comment]
Example of  the log file:
################################################################

HARMONISATION RUNNING REPORT

################################################################

1. Pipeline details

    A. Pipeline Version: 0.1.0

    B. Running date: Oct 29 2024

    C. Input file: GCST90027397_buildGRCh37.tsv.gz

################################################################

6. Failed harmonisation

100% ( 21594955 of 21594955 ) sites failed to harmonise.

The harmonisation process was unsuccessful due to missing essential data (effect allele and/or other allele information). The pipeline harmonises each variant against the Ensembl VCF reference using its chromosome, base pair location, and alleles (effect and other alleles). Missing allele information means this data cannot be harmonised by the pipeline. 

################################################################

7. Overview

Result	FAILED_HARMONIZATION

**Comment by jiyue1214** [comment]
There are 26 studies, and we can still infer their other allele information:
condition 1: variant_id:rs3934834	effect_allele:T (risk: some rsid may already dropped to be used) data from publication various from 2021 to 2023
condition 2: SNP:1:715265:C:T	effect_allele:T (publication in 2023-07)

Should we try to format them?

**Comment by ljwh2** [comment]
Yes we should try to format them

**Comment by jiyue1214** [comment]
Already generated log files for 766 sumstat cannot be harmonised ([example](http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90000001-GCST90001000/GCST90000530/harmonised/GCST90000530.running.log))

For 26 that can be formatted, add them to the ticket [Studies need to be reformated to harmonise](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1442)

**Comment by jiyue1214** [comment]
This ticket can be closed.
