### ISSUE TITLE
Change the study accession for the submission 66f6aca0e6802e0001ec74d1 (PMID: 20453842)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1445]
The GCST needs to be changed from GCST90449065 to **GCST000679**

The PMID was curated through the old curation app. Created a new submission -> need to change the GCST to the one that is published.

**Comment by sajo-ebi** [comment]
@Santhi1901 done

**Comment by ljwh2** [comment]
@Santhi1901 please confirm if ticket can be closed

**Comment by Santhi1901** [comment]
this can be closed
