### ISSUE TITLE
Studies appearing incorrectly in prepub table 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1465]
Studies from PMID 36635386 are appearing in the[ unpublished sumstats table](https://www.ebi.ac.uk/gwas/downloads/summary-statistics) with NA in author and title, but they are published. Please remove them from the unpublished table. 

List of GCSTs is attached[list_gwas_unpublished_summary_statistics_17_Oct_2024.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--064d8a9ffb40195bc7950c1aabd6be8eccddf90b/list_gwas_unpublished_summary_statistics_17_Oct_2024.txt)

**Comment by sajo-ebi** [comment]
@ljwh2 the studies in the attached sheet have been deleted from curation DB will reflect after DR
