### ISSUE TITLE
File type incorrect for GCST90451650,GCST90451651,GCST90451652,GCST90451653

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1469]
The file type for these GCST (GCST90451650,GCST90451651,GCST90451652,GCST90451653) are presently gwas-ssf, but all these are gene-burden files which don't follow the format and it should be non-gwas ssf format. 

These belongs to this GCP001053 which also has single variant studies which has correct file type.

**Comment by karatugo** [comment]
Successfully updated GCST90451650 to non-GWAS-SSF.
Successfully updated GCST90451651 to non-GWAS-SSF.
Successfully updated GCST90451652 to non-GWAS-SSF.
Successfully updated GCST90451653 to non-GWAS-SSF.

**Comment by ljwh2** [comment]
@Santhi1901 please confirm

**Comment by Santhi1901** [comment]
this can be closed; the file types for gene-burden studies are now correctly updated to non-gwas ssf
