### ISSUE TITLE
Fix file type for 66b49220e6802e0001eb4602

### ISSUE THREAD

**Issue by karatugo** [EBISPOT/goci#1470]

**Comment by karatugo** [comment]
GCST90446475 should be gwas-ssf and GCST90446476 should be non-gwas ssf

**Comment by karatugo** [comment]
GCST90446475 and GCST90446476 don't exist in the meta collection.

**Comment by karatugo** [comment]
Added them to meta collection.

**Comment by karatugo** [comment]
YAML files will be generated in 2 days.

**Comment by ljwh2** [comment]
@Santhi1901 please confirm these look ok

**Comment by Santhi1901** [comment]
The file type is correct for the 2 studies
