### ISSUE TITLE
Delete existing submission for PMID 32424353 and reopen for new metadata submission

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1472]
I need to make a new metadata+sumstats submission for this publication to add several new studies and add summary statistics.

- [x] First, an existing sumstats only submission needs to be deleted: https://www.ebi.ac.uk/gwas/deposition/submission/670d3273e6802e000116d656
- [x] Second, the publication status needs to be changed to re-open the PMID for metadata+sumstats submission

**Comment by sajo-ebi** [comment]
@eks-ebi done

**Comment by eks-ebi** [comment]
@sajo-ebi thanks! I've completed the new submission now, however I'm stuck at the import stage. I've unpublished the existing studies, and clicked "Allow import" in Depo-curation but the import button is not active in Curation: https://www.ebi.ac.uk/gwas/curation/submissions/671b9d74e6802e0001ada74a
Can you help?

**Comment by sajo-ebi** [comment]
@eks-ebi the submission is enabled now

**Comment by eks-ebi** [comment]
great thanks @sajo-ebi ! I've imported the submission now, so this should be all done!
