### ISSUE TITLE
GCP reorganisation

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#148]
All studies should belong to a parent GCP (project). This includes all existing studies in the GWAS Catalog and any studies already associated with a publication. 
Question: Should GCPs have a relationship to publications? If so, they may be required to have one-to-many relationships.

GCP can be used for grouping studies, GCSTs. This will enable us to:
a) create structure on the ftp
b) create stable links for studies regardless of their publication status
c) it can be used to identify multiple studies belonging to the same project.

**Comment by jdhayhurst** [comment]
- One to many relationship for GCP to publications is non-trivial as it is currently assumed one-to-one everywhere in the code base. 
- We could continue with a one-to-one relationship for gcp --> pmid to create structure on the ftp, or we could use pmids in addition to gcps like this (which makes browsing more meaningful as pmid carries more meaning than GCP):
summary_statistics
+-- published
|    +-- pmid1
|    |   +-- gcst1
|    |   +-- gcst2
|    +-- pmid2
|    |   +-- gcst3
+-- unpublished
|    +-- gcp1
|    |   +-- gcst4
|    |   +-- gcst5
|    +-- gcp2
|    |   +-- gcst6
+-- gcst...(left to preserve paths)
+-- author_pmid_gcst...(left to preserve paths)

**Comment by tudorgroza** [comment]
@jdhayhurst - let me know when you want to discuss the overall solution. (aka including also what I have to do, so that we can create appropriate tickets.)

**Comment by ljwh2** [comment]
@jdhayhurst I don't think we need this functionality anymore, please check if you agree

**Comment by jdhayhurst** [comment]
agreed, closing.
