### ISSUE TITLE
Allow new sumstat upload for reactivated submission

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1480]
The creator of this submission (https://www.ebi.ac.uk/gwas/deposition/submission/67001be72500c60001d84d4b) did not work on it for 30 days and it was therefore deleted. The creator then contacted us to request it to be reactivated. That has been done, however, the globus directory it was linked to (see https://app.globus.org/file-manager?origin_id=868002db-3d05-4e88-989f-1a265e3c2eb1) has been permanently deleted, so there is currently no way for the author to upload their summary statistics again.

**Comment by eks-ebi** [comment]
@sajo-ebi As discussed in the meeting this morning, can you just delete this submission and reopen the PMID instead? Then I will ask the user to just create a new submission

**Comment by sajo-ebi** [comment]
@eks-ebi done

**Comment by eks-ebi** [comment]
great, thanks!
