### ISSUE TITLE
Manually re-assign original GCSTs in PMID 32424353

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1485]
3 studies were created in the old curation interface. I then created a submission to add new studies, and this caused the import process to overwrite the original 3 GCSTs with new ones. In order to maintain persistent identifiers, these should be reverted back to the original GCSTs:

Please change the following GCSTs:
GCST90454341 --> change back to GCST010098
GCST90454342 --> change back to GCST010099
GCST90454343 --> change back to GCST010100

If possible, this should be done before the next data release.

**Comment by eks-ebi** [comment]
@sajo-ebi oops, I didn't realise that. This submission has already been imported and the new GCSTs were already released in the last DR. Does that mean it is too late to change them back to the original GCSTs?

**Comment by sajo-ebi** [comment]
@eks-ebi  this will be fixed in latest DR , the new GCST will reflect in latest DR

**Comment by eks-ebi** [comment]
confirmed, the GCSTs are correct in depo-curation - I'll check again to confirm in production after the DR
