### ISSUE TITLE
Open PMID 30718454 for metadata submission

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1494]
30718454 has been curated through the old Curation App with 7 studies. 

I need to add 6 more studies. 

Please change the status of this PMID to allow metadata submission.

**Comment by sajo-ebi** [comment]
@earlEBI done

**Comment by earlEBI** [comment]
@sajo-ebi Speedy! Thank you! Can be closed.

**Comment by earlEBI** [comment]
@sajo-ebi Sorry, I created the metadata submission and thought it would be okay to leave it overnigth before submitting, but it's reverted to sumstats only. Can you please re-open as metadata and sumstats submission?
https://www.ebi.ac.uk/gwas/deposition/submission/673dfc702500c60001040bec

**Comment by sprintell** [comment]
Lizzy has created another submission, hence @earlEBI could you please confirm if this ticket can be closed ? Thanks

**Comment by earlEBI** [comment]
Yes, I created a new submission with Sajo's help and it has been imported to the Curation App.
