### ISSUE TITLE
Trish Hand Over Meetings with Yomi

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#150]
Trish will need have meetings with Abayomi, regarding How the things below work, where they are and ... so there can be smooth operation of the Software and Hardware Infrastructure afterwards

1. Code walk-through of the Curation App and how the app works
2. Code walk-through of the goci (note: There is ticket somewhere on some modules that should be removed from goci) and Its Oracle Data DB Data Model and how it works
3. Code walk-through of the Search UI -  (Note: its goes through about 7 deployment steps) and how the app works
4. Code walk-through of the Search Back End (code to create the part of the data used by the Search UI, the search and search snippets) - 
5. GWAS Catalog Rest API 
6. GWAS Data release 
7. Data release document - 
8. Curation metrics - one of the files is created via a cron job on Garfield (Trish)
9. Deposition UI Code walk through and and how the app works
10. Kubernetes Cluster, Name spaces, Configurations and Deployments
11. Gitlab Mirrors and CIs
12. Documentation on things in Github - Trish will help to look at and get to know what each repository in github is used for.
13. Visual chart that shows the interaction between each of the tools in 1 and 2 above - Not really, Trish has been working to document the architecture and James has some diagrams.
14. How the system integrate with OLS and description of how the ontology powered search works - There is only a loose connection to OLS and the Curation app and Search UI.
15. An architectural document of how the search indexing works - GWAS Catalog - New Solr specification 
16. Quick review of Bamboo build plans 
17. Quick review of the  What+Runs+Where
18. General GWAS tasks

**Comment by twhetzel** [comment]
Aug 5 - Reviewed:
- GWAS Data release
- Data release document
- Quick review of Bamboo build plans (Data Release plan)
- Quick review of the What+Runs+Where
- General GWAS tasks
- New Solr specification 
- Diagram of testing environments
- Curation app and Search UI configuration information
- Database connection details
- Adding a user to the database

**Comment by twhetzel** [comment]
Aug 6 - Reviewed:
- Data release deployment debugging
- GWAS Python scripts
- Curation app set-up

**Comment by twhetzel** [comment]
Aug 7 - Reviewed:
- Solr slim
- AAP user management
