### ISSUE TITLE
Submission associated with GCST008311 needs removing 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#154]
The user submitted a file containing only 18 associations. Curators have removed "full pvalue set" tick and link to ftp has been successfully removed from UI in latest data release. We want to invite the author to submit full sumstats, but the status of the PMID in deposition app remains CLOSED, therefore the submission needs deleting and the status resetting.
Note, the file will also need removing from the ftp, @jdhayhurst should be alerted to this "unexpected" folder by the sumstats release report. 

Submission ID: 5efd55b036723b0001c785b4
PMID: 31000673
GCST: GCST008311

**Comment by tudorgroza** [comment]
@ljwh2 @eks-ebi - just to clarify: do you want me to actually *remove* this submission, or just to *re-open* it for the author to re-upload a file and resubmit?

/cc @twhetzel

**Comment by eks-ebi** [comment]
I'm not sure, but from reading what Laura has written, I think the request is to:
1. _remove_ the summary statistics files that we currently have for this submission from the FTP 
2. _remove_ any summary statistics files that the user has uploaded to their Globus submission folder (https://app.globus.org/file-manager?origin_id=e1bf4e58-bc14-11ea-bef6-0e716405a293) - might the same thing as step 1??
3. _re-open_ the submission (https://www.ebi.ac.uk/gwas/deposition/submission/5efd55b036723b0001c785b4) so that the user can transfer new files via Globus _and_ upload a new submission form in the deposition app

**Comment by eks-ebi** [comment]
Does it make much difference whether the submission is deleted and they start again (i.e. status returns to OPEN FOR SUBMISSION), or if the same submission continues to exist but has all the files wiped (i.e. status returns to STARTED, I guess)?

**Comment by tudorgroza** [comment]
For a user perspective it kind of does make a difference: it's a 'everything you've done is wrong - hence we delete it and you start afresh' vs. 'you've done some mistakes, please correct them and resubmit'. The part I'm not really sure about is the impact the latter option has on re-importing the submission in the Curation App.

**Comment by jdhayhurst** [comment]
Folder/files removed from public FTP

**Comment by tudorgroza** [comment]
@eks-ebi - what was communicated to the author?

**Comment by eks-ebi** [comment]
@tudorgroza I'm afraid I don't know. I haven't been involved in the communication myself, and I'm struggling to find any related emails etc. Maybe it's best to wait until Laura is back on Monday, as she created the ticket, and will probably know more of the details.

**Comment by tudorgroza** [comment]
Oki doki. Thank you!

**Comment by ljwh2** [comment]
@tudorgroza I have't communicated anything to the author yet. What i want to do is contact them and say:
Unfortunately your submission is not eligible since it is not full summary stats, and we have removed the file accordingly. If you would like to submit full summary stats, please now do so by....what? depends on the decision above. 

You said: 
For a user perspective it kind of does make a difference: it's a 'everything you've done is wrong - hence we delete it and you start afresh' vs. 'you've done some mistakes, please correct them and resubmit'. The part I'm not really sure about is the impact the latter option has on re-importing the submission in the Curation App.

In theory it's the second, because they only need to submit a new file, the metadata etc should be the same. But they might decide not to submit, or not for now but decide to at a future date. I could contact them to ask, but sometimes this takes a while so it would be cleaner to just remove the submission and they are not relying on actions from us before they start. Especially if we have concerns about the impact on the curation app, I don't think there's a strong argument not to just start over.

**Comment by tudorgroza** [comment]
@ljwh2 - sounds good to me. So it's a go to delete - correct?

**Comment by ljwh2** [comment]
Yes, delete please

**Comment by tudorgroza** [comment]
Done. Apologies for the delay.
