### ISSUE TITLE
Deposition sync failed

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#161]
The Deposition sync failed because information to be added for a database column was too large. See Bamboo logs for the "Depo sync" process for more details.

Error message from Bamboo log: 
`Caused by: java.sql.BatchUpdateException: ORA-12899: value too large for column "GWAS"."UNPUBLISHED_STUDY"."ARRAY_INFORMATION"`

**Comment by sprintell** [comment]
@twhetzel , @tudorgroza  whats the status of this , is it fixed ? It sounds like what Tudor was mentioning in the morning

**Comment by tudorgroza** [comment]
Well ... the `array_information` field in this one (submission: `5f160ab1753ca500016c269a`) has 600 characters:
* `Subset of Illumina coreExome|HumanOmniExpressExome-8|HumanOmniExprss-12|HumanExome-12|Affymetrix UK Biobank Axiom Array|Illumina HumanOmni1-Quad_v1 Beadchip|Illumina 370CNV BeadChip|Illumina Global screening array|PCR-free Whole Genome Sequencing|Affymetrix Human Mapping 500K Array Set and the 50K Human Gene Focused Panel|Custom Axiom arrays described in PMID 21903159, 21565264|A combination of Illumina 1M and Illumina 1M Duo arrays|Affymetrix 6.0|MEGA|Illumina 550K|Illumina 610K and 660K|Illumina HumanOmni2.5-Quad|Cytochip 370k, Affymetrix Gene Titan, Axiom Genome-Wide Human CEU I Array Plate` ... and it looks legit.

The new validation will stop this, however ... it seems like our 255 characters limit is well below what we should support.

Proposed solution:
* Increase length of `ARRAY_INFORMATION` field in `UNPUBLISHED_STUDY` table to 1,000 characters
* Increase length of `STUDY_DESIGN_COMMENT` field in `STUDY` table to 1,000 characters
* Change current validation parameters for the `array_information` field in the 1.6 template schema to 1,000 characters.

/cc @jdhayhurst @sprintell @twhetzel

**Comment by tudorgroza** [comment]
Oh ... also - we need to check if anything was created during the sync and clean-up.
Finally - I've created this self-explanatory ticket: https://github.com/EBISPOT/goci/issues/162

**Comment by ljwh2** [comment]
@tudorgroza I don't think we should increase the character limit. The information is genuine, but we don't curate/publish this level of detail about the arrays. The documentation is clear they should only enter Affymetrix, Illumina or Perlegen. one thing that occurs to me is to change the column header to "array manufacturer" rather than "array information", which would be more specific

**Comment by tudorgroza** [comment]
@ljwh2 - this is *not* the array manufacturer column. That was correctly filled in and has proper value-based validation on it. This is an additional 'comment / description' field about the array.

**Comment by ljwh2** [comment]
Oh I see. I'm looking at the template now. TBH I'm not sure what we expect from this field.

**Comment by twhetzel** [comment]
FWIW, the longest value currently in the `UBPUBLISHED_STUDY.ARRAY_INFORMATION` is 90 characters.

**Comment by ljwh2** [comment]
Discussed on Slack, this data is not exposed to users anywhere. Decided to manually trim this one but we should discuss what we expect in this field for the future @eks-ebi @JalMacArthur @buniello

**Comment by tudorgroza** [comment]
@ljwh2 - `array_information` in all studies belonging to submission `5f160ab1753ca500016c269a` has been trimmed to `Subset of Illumina coreExome|HumanOmniExpressExome-8|HumanOmniExprss-12|HumanExome-12|Affymetrix UK Biobank Axiom Array|Illumina HumanOmni1-Quad_v1 Beadchip|Illumina 370CNV BeadChip|Illumina Global screening array|others`

**Comment by twhetzel** [comment]
We ran the Depo sync yesterday and it worked. Thanks for fixing this!
