### ISSUE TITLE
Refocusing UI to allow exclusion of background traits

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#165]

**Comment by ljwh2** [comment]
in road map due April

**Comment by ljwh2** [comment]
https://docs.google.com/document/d/1agaBcPxuCws0pKnuZh_PJylk5TO84FG9YGgpxIXzZpY/edit?usp=sharing

**Comment by eks-ebi** [comment]
Testing 2021-06-14:

* Separate trait and background trait columns are very clear and fit well with the other columns in both the Association and Study tables, e.g. on a publication page (http://snoopy.ebi.ac.uk:9580/gwas/publications/30267110)
* Separate fields at the top of each Study page are also very clear and well formatted (e.g. http://snoopy.ebi.ac.uk:9580/gwas/studies/GCST007192)
* The "include background traits data" checkbox on the Trait page (e.g. http://snoopy.ebi.ac.uk:9580/gwas/efotraits/EFO_0004246) is a useful feature. It seems to perform the correct filtering when clicked: e.g. there are 91 associations annotated with EFO_0004246, 26 where it is a background trait, so when "include background traits data" is unticked, 91 - 26 = 65 associations displayed. Same for studies: 19 total - 8 with background trait = 11 after checkbox is unticked. @ljwh2 I think this is a nice way to allow users to see both sets of data, but I think maybe background traits should be "off" by default and users can opt in to adding them (at the moment they are "on" by default) - what do you think?
* Tried searching for the same trait in the main search results (http://snoopy.ebi.ac.uk:9580/gwas/search?query=mucocutaneous%20lymph%20node%20syndrome) - weirdly this gives different numbers (46 associations and 15 studies), which doesn't match either the "with background traits" or "with our background traits" numbers above... but maybe this is also complicated by the child traits?
* LocusZoom diagram on Trait page: the diagram includes all associations by default and filters out the background trait annotations when you untick the box. As above, I think this is a nice feature but should be the other way around (i.e. background traits off by default, you can add them if you want)
* I found one study (http://snoopy.ebi.ac.uk:9580/gwas/studies/GCST90013538) where the background trait was correctly split out for the study but not for each association. I'm not sure how we could systematically check for other examples like this.

**Comment by eks-ebi** [comment]
Oddly, for the example study above with the incorrectly annotated associations (http://snoopy.ebi.ac.uk:9580/gwas/studies/GCST90013538), when I click on the individual variant links, the resulting Variant pages do not contain any studies or associations (e.g. http://snoopy.ebi.ac.uk:9580/gwas/variants/rs6017006)...
So maybe there is something else going on with this study

**Comment by ala-ebi** [comment]
@eks-ebi good catch! data in DB and in Solr Search server is correct, it's UI thing, I'm investigating.

**Comment by ljwh2** [comment]
@eks-ebi The study that has split studies but not associations was a submission, I wonder if that had some effect? Do you have any other examples of submissions with a background trait?

**Comment by ljwh2** [comment]
Overall functionality looks great!

I agree scientifically it would be better to exclude background traits by default if possible (unchecked box) BUT this requires us to define behaviour of traits which are only background (note - an example of this is Trypanosoma cruzi seropositivity). We can discuss, but on balance it may be better to leave as is. 

I noticed an issue for traits that have both child terms and background traits. Unchecking background traits seems to exclude child traits as well. Unchecking and rechecking child traits adds them back in. 
Example: hypertension EFO:0000537
755 associations, 91 studies.
Uncheck background traits:
394 associations, 33 studies.
Uncheck child traits as well:
394 associations, 33 studies.
Recheck child traits:
515 associations, 58 studies.

Another example is schizophrenia EFO:0000692, behaviour is the same.

**Comment by ala-ebi** [comment]
Cheers, well spotted! I have deployed a fix.

**Comment by ljwh2** [comment]
@eks-ebi Re-tested checking and unchecking child & background boxes, works as expected now. 

We discussed and decided it would be better to have the background traits box unticked by default.

**Comment by ala-ebi** [comment]
'Apply efo traits to associaitons' to associations now takes into account background traits as well, they can be seen later on in the association page 
![image.png](https://images.zenhubusercontent.com/60190c8d2d567e0492e6fdd9/3e46f847-098f-49c4-ad58-aa83642af95e)

**Comment by eks-ebi** [comment]
Tested UI again today: I've looked through all the different pages (Trait, Study etc.) and everything looks correct. Ticking/unticking the bg trait box working fine.

Not sure if anything else specific needs testing?

**Comment by eks-ebi** [comment]
Testing the Curation interface:

The 'Apply efo traits to associations' button works well: I added a bg trait to a study that already had a main trait --> the button left the main trait as it was and added bg trait to all associations.

**Comment by eks-ebi** [comment]
@ala-ebi let me know if there's anything else that needs testing

**Comment by eks-ebi** [comment]
We discussed adding a tooltip for the background trait field in the UI.

Proposed text:
"A trait that is not directly analysed in the GWAS, but is shared by all study participants as a common characteristic."
@ljwh2 Does this look ok?

**Comment by ljwh2** [comment]
Yes I'm happy with that @eks-ebi

**Comment by ala-ebi** [comment]
filled background traits in 'All studies v1.0.3' downloads

**Comment by eks-ebi** [comment]
@ala-ebi 
I've checked 'All studies v1.0.3' download and all of the background traits seem to be displayed correctly.

**Comment by eks-ebi** [comment]
I've also checked the tooltip mentioned above and it looks good on the Study page. But I think it would be good to also display the same tooltip in other places where the term "background trait" appears:

1. In the column header in the Associations and Studies tables:
![Screenshot 2021-07-21 at 09.22.25.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/b9ede895-61f2-48fc-8d64-76194beb26f2)
![Screenshot 2021-07-21 at 09.24.21.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/b00d9b71-4396-4858-81b1-611203322abd)

2. On the Trait page next to the background traits checkbox
![Screenshot 2021-07-21 at 09.25.44.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/3855af2b-1eb0-4478-a087-204836975bf2)

@ljwh2 Would you agree?

**Comment by ala-ebi** [comment]
done

**Comment by eks-ebi** [comment]
FAQs now updated to explain background traits, committed to documentation branch:
https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/faq-content.adoc
