### ISSUE TITLE
EFO Traits need to be loaded in batch

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#169]
The process to add EFO terms into the Curation app database needs to be updated to allow batch loading of terms. 

Currently the form on the page "Update EFO Traits" [.../gwas/curation/efotraits] is used to add traits, but only supports addition of a single trait at a time. With more complex studies, more new EFO terms will be needed and a more efficient way to add these into the database is needed.

There are a few implementation options for this feature:
- update the Curation app to allow for a file upload of EFO traits 
- use a script to load a file of EFO traits

Various factors need to be considered for which or both option to implement, e.g. how soon is this needed, how does each mechanism fit into the EFO curation workflow, how long will each option take to implement, etc.

**Comment by twhetzel** [comment]
When adding EFO traits these should be loaded into the table `EFO_TRAIT`. This is a leaf table so it is straightforward to add.

**Comment by ljwh2** [comment]
fixed in depocuration
