### ISSUE TITLE
Submission for GCST007687 needs removing 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#173]
Another submission with only 10 SNPs in the file. Files need removing from ftp and submission needs removing, same as GOCI#154 . I have already removed the "full p value set" tick in the curation app. This needs doing before the next data release (2020-08-24). SubmissionID is 5f04270d8a8b2700011b9193, PMID: 30899065

**Comment by tudorgroza** [comment]
@ljwh2 - what is the submission ID?

**Comment by ljwh2** [comment]
Just added it above, you're too fast for me @tudorgroza!

**Comment by tudorgroza** [comment]
This is done on my side.

**Comment by jdhayhurst** [comment]
cleared from FTP
