### ISSUE TITLE
Delete "prepublished" data for submissions that now have PMIDs

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#180]

**Comment by twhetzel** [comment]
Data that exists in both the "prepublished" and "published" tables needs to be removed from the "prepublished" tables. Based on our past work to clean this up, the data for submissions of this type needs to be deleted from:
- `UNPUBLISHED_ANCESTRY`
- `UNPUBLISHED_STUDY`
- `UNPUBLISHED_STUDY_TO_WORK`

@jdhayhurst can you add which submissions these are?

**Comment by jdhayhurst** [comment]
GCST90000522
GCST90000523
GCST90000524
GCST90000525
GCST90000526
