### ISSUE TITLE
Internal server error when saving 'study details' page

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#186]
When pressing the 'save' button on the 'study details' page on any publication in the curation interface, this error page is displayed: 
![Screenshot 2020-08-26 at 13.26.11.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/60fe2177-653d-4d94-a1fd-97a3ebcd8edf)

After pressing 'back', all changes have been saved successfully.

**Comment by tudorgroza** [comment]
Grrrr :) ... this one just doesn't want to go away :))
