### ISSUE TITLE
Submission associated with GCP000040 needs resetting

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#188]
5f4513ae2d70930001d640f5 

**Reset**
Submitter has uploaded ~16 sumstats files to Globus, but only filled in one study row in the template. 
Submission needs resetting, so I can email the user and tell them to fill in one row per sumstats file. 

**Template bug**
The user has also left the 'Sample' tab of the template completely blank. This should not be possible.

**Comment by tudorgroza** [comment]
@earlEBI - Should I just make the file invalid and let the re-upload the file? (since the summary stats files are fine)

**Comment by tudorgroza** [comment]
@earlEBI - they should be able to upload a new file.

**Comment by tudorgroza** [comment]
@earlEBI - anything else I need to action on this ticket, or can I close it? Thank you.

**Comment by earlEBI** [comment]
No, that's great, can be closed, thanks.
