### ISSUE TITLE
Broken FTP link - KimW_31000673_GCST008311

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#189]
Sumstats files were removed from FTP due to small number of SNPs, then updated via Deposition app and imported. 
I understand that the study won't appear in the available sumstats table until the next data release, but I think the direct link to the FTP should work: 
ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/KimW_31000673_GCST008311/

**Comment by ljwh2** [comment]
checked and this link does now work
