### ISSUE TITLE
Add EFO trait form - additional form validation needed

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#194]
In looking over the data in the `EFO_TRAIT` table there is a row with the value for the `SHORT_FORM` column of "1001114". The correct value should be "EFO_1001114" therefore the form validation should have prevented this incorrect entry.

Also, the value for this entry needs to be updated in the database.

**Comment by twhetzel** [comment]
Another incorrect value has since been added for the row for the trait "pantothenic acid", the `SHORT_FORM` value in the table is CHEBI:7916, but should be CHEBI_7916.

**Comment by ljwh2** [comment]
Closed since now incorporated into specifications for new features in DepoCuration
