### ISSUE TITLE
Handling submissions that have stalled for a significant amount of time

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#196]
Submissions that have stalled for some time (tbd) should be given a different status or archived in some way in order to clean up the active submissions table. An automated email should be sent to the submitter to prompt completion of the submission.

**Comment by tudorgroza** [comment]
@ljwh2 - Here's the proposed process:
* Monitor submissions that have either been started or are in an invalid state for more than 15 days (please let me know if you want a different time period)
* At 15 days - send email to user reminding them to come back and do something about the submission
* After 7 days - if submission is in the same state - send a second and final reminder
* After 7 more days - remove submission from system (soft delete). This will also remove it from the table.

Please confirm that this is satisfactory.

**Comment by ljwh2** [comment]
I'm not sure about removing the submission from the table - sometimes we have had submitters come back after a long period of time. Can we change the status and allow them to reactivate it? Or is it better if they just start over with a new template?

**Comment by tudorgroza** [comment]
They would be soft deleted - in other words, archived. We could re-instate them if need be.

**Comment by ljwh2** [comment]
OK. Would there be a mechanism to stop this happening - for example, user receives email reminder, user emails us to say "I'm waiting for my collaborator who is on holiday, don't delete my submission just yet"

**Comment by tudorgroza** [comment]
Yeah - we could manipulate this via the lastUpdated date.

**Comment by ljwh2** [comment]
Timeline as follows:
at 10 days - send email to user reminding them to come back and do something about the submission
After 7 more days - if submission is in the same state - send a second and final reminder warning that submission will be deleted after 30 days, otherwise contact us
After 13 more days - remove submission from system (soft delete). This will also remove it from the table.

**Comment by tudorgroza** [comment]
Great. Thank you.
Can you please send me the content of the emails?

**Comment by ljwh2** [comment]
Couple of questions - who will the email come from - no-reply@ebi.ac.uk? Ideally it would quote a relevant ID - should be the same as the submission emails - PMID or GCP?

**Comment by ljwh2** [comment]
Also, to confirm, this process will only delete the submission, not the files from Globus?

**Comment by tudorgroza** [comment]
Currently - in the 'proxy' emails I have in the implementation I've included the submission ID (as a link - so that they can click on it and get into the platform directly) and the title of the publication / body of work. But yeah - we can include whatever you want to include.

W.r.t. the deletion process - it's an archival. We don't actually delete anything (not even the submission).

**Comment by ljwh2** [comment]
Email text in this link: https://docs.google.com/document/d/1NnT-9dVaZP8t6oM-xR9VuhsqD2LmusXFtewAuNjZS2s/edit

**Comment by tudorgroza** [comment]
@ljwh2 - can I please get access to the document? Thank you!

**Comment by ljwh2** [comment]
done, sorry

**Comment by tudorgroza** [comment]
Oh :) ... you've changed the semantics of the last email :)
I thought the last one is ... 'this is to inform you that we've deleted your submission. If you want it back, get in touch with us, etc ...' type of thing ...

**Comment by ljwh2** [comment]
I missed some subtlety there. Now changed accordingly.

**Comment by tudorgroza** [comment]
Thank you!

**Comment by tudorgroza** [comment]
Thank you for the emails. I've replaced my proxies with your content.
