### ISSUE TITLE
Daily Summary Stats release report email is not giving correct information

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#20]
The summary stats release report email was developed when we moved to a daily release of sumstats (Jira GOCI-2801), to give curators an overview of which folders have been released. 

Background:
Curators indicate that a study has sumstats by ticking the “full p value set” box in the curation interface. There is no QC linked to this process, the folders on the ftp are manually created by the curator. The release report is in 4 parts that let curators know that
- they have correctly ticked the box and created the file, the two have been successfully linked and data has been released
- folders named with internal study_id have been successfully renamed with the GCST
-  the box has been ticked but no matching folder has been found 
- a folder has been created but the box has not been ticked

Bug:
Since 29th jan 2020, there has been an accumulation of studies listed in the first (“This round summary statistics of n studies were released”) and second (“The following folders were renamed in the staging area”) sections. Example: HoglundJ_31727947_GCST009522 has been listed as released in every email since 29th Jan. Expected behaviour is that a study, once released, should not appear in the report again unless it is unpublished and republished. Also, the release report is going out every night when it should only go out when sumstats are actually released. 

Also, in the last few days (26th & 27th), some unexpected files have appeared in the final section called “(A Document Being Saved By AUHelperService)”. It isn’t critical to get rid of this but it’s just additional clutter that reduces the utility of the report.

**Comment by jstewart-ebi** [comment]
Summary Stats script moved to Bamboo, working as expected. Closing.
