### ISSUE TITLE
Rule for when the word "ancestry" should appear in imported sample description

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#206]
### 'Sample Description' field in the curation app
The word "ancestry" should appear after some ancestries when imported to the curation app from deposition. 
By default, the word should appear after all ancestry categories. 

**Exceptions, where the word should *not* follow:** 
African American
Hispanic
Latin American
Hispanic/Latin American
Amish
Mexican American
Latino
Sardinian
Black
(founder/genetic isolate)
Ashkenazi Jewish
French Canadian
Puerto Rican
Hispanic/Latino
Peruvian
Mediterranean

**Comment by tudorgroza** [comment]
Add these rules in the validation document:
* https://docs.google.com/document/d/138ECKr0IxVnF0ik6901zOyJw1G4iH8jJS8vm8FmtS64/edit?ts=5f61d00b

**Comment by earlEBI** [comment]
@ljwh2 Could you please check this ticket is clear / correct? Thank you.

**Comment by ljwh2** [comment]
looks good, thanks. I added Hispanic/Latin American
