### ISSUE TITLE
Investigate creating a landing page for GWAS without PMIDs

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#209]
Investigate creating a landing page for GWAS without PMIDs - identify the blockers to this and estimate how much work this would be.

The landing page should have the URL https://www.ebi.ac.uk/gwas/studies/GCST# and have similar layout and information to the "published" GCSTs. The GCSTs without PMIDs will not have "top associations" so the page will not need this table.

A suggestion would be to just include the "information panel" which appears at the top of each current GCST page. EFO trait will not be assigned, suggest display "-" or "not assigned yet". In place of publication information include provenance information provided for submission/body of work.

**Comment by ljwh2** [comment]
Ideally these pages would be findable in the search (search on GCST only - not by trait or author), but this is not necessary in the first iteration.

On addition of PMID to the BoW, this landing page will be replaced by the normal study page.

**Comment by ljwh2** [comment]
Sketch out mockup of what landing page should look like

**Comment by ljwh2** [comment]
@sprintell mockup added above

**Comment by ljwh2** [comment]
Submissions that are under embargo should also have a landing page, but this is not necessarily MVP. The PGS Catalog already has something like this:![Screenshot 2020-12-07 at 17.50.45.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/33bece7c-32cb-41ad-afec-317b5f295264)

**Comment by sprintell** [comment]
Hi @ljwh2 ,
Can you please check the landing page for GWAS without PMIDs here:  http://snoopy.ebi.ac.uk:9680/gwas/studies/GCST90012882
I just saw that the date needs to be properly formatted, I’m fixing that now
Also what is Platform (SNPs passing QC) ? 
And what otehr things do you think should change

**Comment by ljwh2** [comment]
Platform (SNPs passing QC) should be populated from the columns "Array manufacturer" and "Variant count" in the template, in the format Array manufacturer [Variant count].
I noticed this field is also not being populated in the download file, see goci#350

"Discovery sample description" needs changing. There is a field in the curation app "Initial sample description" which is constructed from several fields in the template as part of the import process. This should be the same on the landing page. I will add details of the rules below.

The text at the top "Click here for more information" should link to an FAQ but I realised we don't have one, I will make another ticket to add this.

**Comment by ljwh2** [comment]
"Click here for more information" should link to https://www.ebi.ac.uk/gwas/docs/faq#faq-A1

**Comment by ljwh2** [comment]
@sprintell I've thought about the sample description a bit more and discussed with the other curators. We should not include the "Discovery Sample description" at all, but only the bottom line "Discovery ancestry (country of recruitment)". This should be as follows, and change the title to "Sample description":

Sample description: 1500 European (U.K.)
                                  300 East Asian (China)

From the metadata template in the screenshot below
![image.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/bef1167a-ef57-429c-85a5-d1b355d1ef1d)
 
Ideally we should provide case & control numbers where provided as well, but this is not necessary in the first iteration

Sample description: 1500 European (U.K.) (750 cases, 750 controls)
                                  300 East Asian (China) (100 cases, 200 controls)

**Comment by ljwh2** [comment]
I've now added a new FAQ, A21, see GOCI#355. The "Click here for more information" should link to this FAQ.

**Comment by ljwh2** [comment]
@sprintell I think all the information you need is in the ticket now - FAQ text and removing the "Discovery Sample description" 

please let me know if there's something else.

**Comment by jdhayhurst** [comment]
@ljwh2 tagging you here, so we can spec out exactly what the UI behaviour should be. We need to define how the search snippet should look, any behaviours, what information it should contain.

**Comment by ljwh2** [comment]
Mockup attached![study snippet.jpg](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/2a45c76a-8ac0-4c7a-976e-1e7a727db4dd)

Study description should be created from structured ancestry. This is the same way it is represented in the EBI search. 

GCST should hyperlink to study page.
Icon should be displayed for studies with sumstats (same as for publication snippet)

Currently searching for GCST returns the parent publication
Searching for GCST should return a study (first), plus parent publication if available. It should only return an exact match for GCST, it should never return a list of GCSTs (e.g. by searching for a truncated/wildcard GCST or other GCSTs in same publication) . 

Searching for PMID should ideally return PMID (first) plus all studies, but this is not necessary if it is a significant amount of work.   

Searching by trait, variant, gene or region should not return studies.

**Comment by ljwh2** [comment]
@eks-ebi please review specification for search above and give any feedback

**Comment by ljwh2** [comment]
As first release, we could release with just GCST & minimal text in the snippet. James suggested using the publication or BoW title in the text, another option to be consistent with future plans would be "PMID:123567" for published study and "Pre-published summary statistics dataset" for BoW study. 

GCST should hyperlink to study page.
Icon should be displayed for studies with sumstats (same as for publication snippet)

Searching for GCST should return a study (first), plus parent publication if available (search currently does this). It should only return an exact match for GCST.

**Comment by ljwh2** [comment]
Closed for MVP and replaced by goci#470 and goci#471
