### ISSUE TITLE
Genes disappear from LD plot at certain plot widths

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#21]
Daniel reported a bug with the LD plot. Genes that are visible in the 50kbp window disappear in the 25 and sometimes 200kbp window (genes displayed in track "Ensembl genes", below the plot; plot width changed using the drop-down on top right of the plot). I replicated the behaviour with a couple of other variants. As Daniel observes, it seems to occur when the gene is larger than the initial plot width:

https://www.ebi.ac.uk/gwas/variants/rs6466479
https://www.ebi.ac.uk/gwas/variants/rs45446698

but not

https://www.ebi.ac.uk/gwas/variants/rs7412

This is misleading for users and needs fixing so the genes are visible at all window sizes.
--------
Original GWAS-info email:
I wanted to show off with the LD plot and I have bumped into a bug. Check out this variant: https://www.ebi.ac.uk/gwas/variants/rs35407685
 
This variant is an intron variant (https://www.ensembl.org/Homo_sapiens/Variation/Mappings?db=core;r=7:140785945-140786947;v=rs35407685;vdb=variation;vf=20866875) overlapping with BRAF. When the LD plot is loaded the BRAF gene on the reverse strand is correctly displayed (50kb window by default). However it disappears when the window size is decreased to 25kb, and when you try to change back to 50kb it still not shown, only when the largest 500kbp window is selected.
 
I think when the plot is updated only those genes are shown, whose start and end coordinates are both included within the window. So I suspect the fix could not be too complicated.
Please take a look and verify if this indeed not the expected behavior.
---------------

**Comment by jstewart-ebi** [comment]
Issue moved to [EBISPOT/gwas-ui #160](https://github.com/EBISPOT/gwas-ui/issues/160) via [**ZenHub**](https://www.zenhub.com/)
