### ISSUE TITLE
Investigate how to ensure that the same p-value threshold applies across the deposition and curation apps

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#210]
**Background**

Currently, a different p-value threshold is used to validate eligible associations, depending on the application/workflow:

1. Our **published p-value threshold for eligible associations** (e.g. in documentation on the website) is **P < 1E-5**.
2. However, p-values are currently stored in the database as a separate mantissa and exponent. Both of these fields only permit an integer. To account for this, curators have always rounded the actual p-value to 1 significant figure. Because p-values ≥ 9.5E-6 round up to P = 1E-5, they cannot be entered in the curation interface. So the **practical p-value threshold used to date is P < 9.5E-6**. 
3. In the deposition interface, **p-value threshold in the template validation is P ≤ 1E-5**. Note that this is also not exactly the same as the published threshold.

How this affects specific example p-values:

Actual p-value | Database mantissa | Database exponent | Pass our published inclusion threshold? (P < 1E-5) | Pass template validation? (P ≤ 1E-5) | Pass curation interface validation? (Exponent ≤ -6)
-- | -- | -- | -- | -- | --
2.00E-05 | 2 | -5 | No | No | No
1.01E-05 | 1 | -5 | No | No | No
1.00E-05 | 1 | -5 | No | Yes | No
9.51E-06 | 1 | -5 | Yes | Yes | No
9.50E-06 | 1 | -5 | Yes | Yes | No
9.49E-06 | 9 | -6 | Yes | Yes | Yes

This means that when some associations are entered in the deposition app template, they will pass template validation - however, after import into the curation interface they will be flagged as invalid. In order to make curation more automated, we need to resolve these inconsistencies.

**Potential solutions**

_A. Choose **P < 1E-5** as definitive threshold but continue to round p-values to 1 sf in the database_

Requirements:
* change template validation from P ≤ 1E-5 to P < 1E-5, i.e. p-values of exactly 1E-5 should not pass validation
* change curation interface/database validation to allow associations with 9.5E-6 ≤ P < 1E-5. In practice this would mean allowing {Mantissa = 1, Exponent = -5}, but not {Mantissa ≥ 2, Exponent = -5}.

Pros:
* fits our published p-value threshold, "intuitive" number used as a cutoff
* I think fairly minimal changes to both template validation and curation interface validation
* include associations in the grey area of 9.5E-6 ≤ P < 1E-5, which we have "advertised" as eligible but are not currently including

Cons:
* by continuing to round p-values to 1sf, we lose information and specificity about those p-values
* inconsistency with older studies: associations in the grey area not included in older studies, now included under this model
* p-values rounded up to {Mantissa = 1, Exponent = -5} will appear in UI, download etc. and might appear to users to have been included incorrectly
* nothing to stop curators accidentally adding associations with P ≥ 1E-5 but that round _down_ to {Mantissa = 1, Exponent = -5}, relies on curator's own manual decisions

_B. Choose **P < 1E-5** as definitive threshold and move to storing actual p-values to multiple decimal places as presented by authors_

Requirements:
* change template validation from P ≤ 1E-5 to P < 1E-5, i.e. p-values of exactly 1E-5 should not pass validation
* restructure how p-values are stored in the database, to allow storage of multiple decimal places
* change curation interface/database validation to allow associations with 9.5E-6 ≤ P < 1E-5
* UI changes to the curation interface (and probably Search UI, download etc.) to _display_ p-values with multiple decimal places

Pros:
* fits our published p-value threshold, "intuitive" number used as a cutoff
* include associations in the grey area of 9.5E-6 ≤ P < 1E-5, which we have "advertised" as eligible but are not currently including
* by not rounding, we retain more information and greater specificity about p-values
* imposes a hard automated threshold, not dependent on curators rounding or manually excluding any values

Cons:
* more significant changes to the database and curation interface
* inconsistency with older studies: associations in the grey area not included in older studies, now included under this model
* inconsistency with older studies: associations from older studies would continue to be stored as integer Mantissa and Exponent, while associations from newer studies would be stored as a float (either a single number, or as float Mantissa and integer Exponent) - potential problems when displaying them side by side in Search UI etc., e.g. if we convert old associations to float, then we might add erroneous specificity (e.g. 8E-6 > 8.00E-6 for an older study vs. 8.34E-6 for a newer study)?

_C. Choose **P < 9.5E-6** as definitive threshold and continue to round p-values to 1 sf in the database_

Requirements:
* change template validation from P ≤ 1E-5 to P < 9.5E-6
* change our documentation to say that our actual threshold is P < 9.5E-6 rather than P < 1E-5 as previous stated

Pros:
* no changes to curation interface and minimal changes to template validation
* no inconsistency with older studies

Cons:
* by continuing to round p-values to 1sf, we lose information and specificity about those p-values
* will need to change our documentation, which may appear to users as if we are changing our criteria
* 9.5E-6 may be a less "intuitive" cut-off than 1E-5?

**Comment by eks-ebi** [comment]
**Current tasks for developers**

Investigate whether each potential solution would be feasible, and the amount of work involved - especially for the idea of changing how the p-values are stored in the database.

**Comment by ljwh2** [comment]
I think we could implement B without changes to the UI - continue to display single integer mantissa and exponent in UI but record multiple decimal places in db and make these available in download. 

A and C should require fairly simple changes, so B should be focus of investigation

**Comment by ljwh2** [comment]
@eks-ebi I'm just looping back to this in light of GOCI#269. Interim solution could be to implement option C and make more major changes when we retire the curation app

**Comment by tudorgroza** [comment]
Conclusion for the time being: going with Option A.
Once implemented, @tudorgroza will move content of Option B into a new ticket to investigate downstream effects of using multiple decimal places in Search UI, download etc.

**Comment by tudorgroza** [comment]
Left to do: `change curation interface/database validation to allow associations with 9.5E-6 ≤ P < 1E-5. In practice this would mean allowing {Mantissa = 1, Exponent = -5}, but not {Mantissa ≥ 2, Exponent = -5}.`

Note: Will have to consider the file upload mechanism mentioned by Lizzy - which apparently allows floating values to be used for mantissa.

**Comment by tudorgroza** [comment]
Option A above implemented. Curation changes deployed in SNOOPY; Depo changes deployed in Sandbox.

**Comment by eks-ebi** [comment]
Tested validation in deposition interface (see #269): p-values **≥ 1e-5 failed validation, < 1e-5 passed**. This is correct.

All p-values that pass the deposition validation should appear in curation interface after import without 

p-value | deposition | expectation in curation interface
-- | -- | --
9.9e-6 | passed | should round up to (mantissa 1, exponent -5) and pass
9.5e-6 | passed | should round up to (mantissa 1, exponent -5) and pass
9.4e-6 | passed | should round down to (mantissa 9, exponent -6) and pass
9e-1000 | passed | should be (mantissa 9, exponent -1000) and pass

Imported: http://snoopy:9680/gwas/curation/submissions/5fa4195bce8e310001e65996

Result: http://snoopy:9680/gwas/curation/studies/63075210/associations
- All associations imported successfully, rounded correctly and did not trigger any errors

**Comment by eks-ebi** [comment]
As a side test, I tried to create a new association manually in the curation interface (by clicking "Add standard SNP" on this page: http://snoopy:9680/gwas/curation/studies/63075210/associations?associationId=):
- it did not allow me to manually enter mantissa 1, exponent -5 (got an error: `The exponent must < -5`)
- this might be OK, as we are unlikely to want to enter a p-value of 1e-5 manually, however it's a bit confusing to have different rules applying in different contexts. Is it intentional that the validation works differently for manually created associations vs imported associations?

I then tried editing one of the imported associations (clicked "Edit" on the first assoc on this page: http://snoopy:9680/gwas/curation/studies/63075210/associations?associationId=)
- I changed the mantissa from 1 to 2, so that it is now mantissa 2, exponent -5 (i.e. p-value = 2e-5)
- it allowed me to save, but this is incorrect: _if_ exponent = -5 _then_ mantissa must only be 1, never >1
- I then changed the exponent from -5 to -4 and even that allowed me to save - so it looks like the validation has been turned off completely for imported associations. We're prob not likely to try to do this, but it could cause problems if someone makes a typo while editing an association.

**Comment by tudorgroza** [comment]
@eks-ebi - theoretically `1e-5` should have worked. Let me have a look.

**Comment by tudorgroza** [comment]
@eks-ebi - Interesting ... I've just tried editing this: http://snoopy:9680/gwas/curation/associations/63075214 and set a p-value of `1e-5` and it worked ... but adding one from scratch doesn't ... it seems to be a UI validation. Looking into it.

**Comment by tudorgroza** [comment]
@eks-ebi - fix deployed in DEV. Thank you.
