### ISSUE TITLE
Investigate adding curated associations to a publication that was previously imported as a user submission

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#212]
Study metadata (without top associations) can be submitted by external users using the deposition interface - the submission is then imported into the curation interface by a curator. As a curator, I need to be able to add top associations to these studies at a later date. I need to be able to do this for multiple studies within a publication at once.

**Comment by eks-ebi** [comment]
Could this be rolled into a more general use case for making bulk edits to a previously submitted BOW/publication after it has already been imported and possibly already published in the Catalog?

**Comment by ljwh2** [comment]
closing as long since implemented
