### ISSUE TITLE
Increase the character limit for the README text cell

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#214]
The current character limit for the README text cell in the submission template is not long enough for most authors to enter all the information we request. In the first instance, we decided to increase the character limit.

However, the process of entering README text in a spreadsheet cell is a bit clunky in general, so we decided that another ticket should be created to investigate more a more efficient and user-friendly way to receive readme files for summary statistics.

See also https://github.com/EBISPOT/goci/issues/68

**Comment by eks-ebi** [comment]
@jdhayhurst Do you have a good idea of what would be a more reasonable character limit? Should we double it to ~500 chars?

**Comment by jdhayhurst** [comment]
Tudor removed the restriction completely as that field is not imported to the curation db.

**Comment by eks-ebi** [comment]
Great! Thanks for clarifying
