### ISSUE TITLE
Bug in download assoc file .tsv reported first by  GitHub gwas-user-requests

### ISSUE THREAD

**Issue by mcerezof** [EBISPOT/goci#224]
A user made contacted us reporting a bug in the download file for associations

There appears to be an erroneous newline (\n) in the gwas_catalog_v1.0.2-associations_e100_r2020-09-09.tsv download file, line 143081, in the p_value_text field:
between: (parieto-frontal low theta coherence at P8-P4-F8-F4)
and coherence
https://www.ebi.ac.uk/gwas/variants/rs151174000

Same error appears in https://wwwdev.ebi.ac.uk/gwas/docs/file-downloads for gwas_catalog_v1.0.2-associations_e100_r2020-09-30.tsv

**Comment by ljwh2** [comment]
@earlEBI I think this was fixed, please check

**Comment by earlEBI** [comment]
The new line doesn't seem to be an issue anymore, although there are some strange characters in the p-value text:

![Screenshot 2021-01-27 at 10 41 07](https://user-images.githubusercontent.com/61545198/105980164-6f10ec00-608c-11eb-881f-8b71b4c123b5.png)

Not seen in the Ui

![Screenshot 2021-01-27 at 10 41 57](https://user-images.githubusercontent.com/61545198/105980187-759f6380-608c-11eb-88db-a77f2fd83c49.png)

**Comment by ljwh2** [comment]
looks like this might be fixable in the curation interface, could you try it please @earlEBI

**Comment by earlEBI** [comment]
Replaced some long dashes with hyphens. I think should be okay now.
