### ISSUE TITLE
Create project containing multiple GWAS

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/goci#23]
Users should be able to submit data for a “project” that can have multiple GWAS. This can be for a publication with a PubMed ID, a different publication or pre-print identifier, a publication prior to publication, or a paper with no associated publication accession.

**Comment by tudorgroza** [comment]
**Decision:** 3 types of domain objects:
 * Publication
 * Manuscript
 * Project

Submissions will have max 1 of each associated with them.
