### ISSUE TITLE
Assign data provenance for studies in project

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/goci#25]
Users should be able to submit provenance info for this “project”. Sources of provenance include PubMed ID, Biorxv ID, UK BioBank ID, or no external unique identifier. User should be able to see the connection between their data and the study or studies in the project.
 (https://docs.google.com/document/d/1SvRSbuVeud7M5_86uVDYRzshac2qkqdcsL0k5MqoS58/edit?usp=sharing)  (and Excel format https://docs.google.com/spreadsheets/d/19frfYpk2C_BU7zPiNMJaqetWrFOhnJ45hm7k16dvnw8/edit#gid=0)
Change to collect doi (e.g. for BioRxiv manuscript) rather than ID specific to a resource (e.g. asking for BioRxiv ID)
Add - URL to manuscript or information describing project

**Comment by tudorgroza** [comment]
@jstewart-ebi - unfortunately, these documents contain a mixture of workflow and domain object details. It's not clear what's a field and what's a question. Can we break them down here?

* Are these GWAS described in a manuscript? - Y/N - `Q: Is this a field?`
* Has this manuscript already been published? - Y/N - `Q: Is this a field?`
* Manuscript status -- `field`
* PMID -- `field`
* Journal -- `field`
* BioRxiv ID -- `field` -- `Q: are we explicitly asking for a BioRxiv ID ... or an identifier in general?`
* URL for manuscript -- `field`-- `Q: are we expecting the URL to be openly accessible?`
* Manuscript title -- `field`
* First Author -- `field`
* Last author -- `field`
* Corresponding author(s) -- `field`
* Alternative contact(s) -- `Q: What kind of field is this? String? List?`

**This is where things start to break:**

* None of the fields below belong to a manuscript. How are we going to treat them? Part of a manuscript or do we introduce a new `Project` object?
* Project Title -- `Q: This is things
* Project description
* Organisation/consortium

/cc @twhetzel

**Comment by twhetzel** [comment]
@tudorgroza I'll work on breaking these down into fields and then we can sort out what data object and endpoint(s?) they will be accessible from. In general, for the yes/no questions I view these as a workflow/navigation to lead the user to the proper set of fields to complete on a form. I do not expect these navigation questions will be stored in the database. If the state of the navigation questions needs to be stored for better usability, I can look into options to store the state in the UI. My inderstanding is once the form is submitted, the answers to these questions is no longer important.

**Comment by tudorgroza** [comment]
From the Google Doc:

**Manuscript** fields
 - manuscriptStatus
 - pmid
 - journalName
 - journalISSN
 - manuscriptDOI
 - manuscriptUrl
 - title
 - firstAuthor
 - lastAuthor
 - correspondingAuthors - List of CorrespondingAuthor
- alternativeContacts - List of String

**Project** fields:
 - title
 - description
 - organisation
 - url
