### ISSUE TITLE
Provide stable, unique ID for project upon submission

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/goci#26]
Users should be provided with an accession ID for the “project” and accession IDs (GCSTs) for each GWAS within this project. These should be provided as soon as the submission passes validation so that the authors can include these in the manuscript and also to Journal editors to confirm that they have submitted.

**Comment by tudorgroza** [comment]
@jstewart-ebi - we need a strategy here - and before the strategy - we need a template.
Options:
* GCSTs are assigned when pulling in the manuscript into the Curation App (or when some magic button is pressed there)
* We reserve a set of GCSTs (e.g., all starting with a certain digit - e.g., `8`) which the backend then freely assigns upon successful validation.
   * Alternatively, we can prefix these reserved GCSTs with a temp prefix - which could be removed upon pressing a magic button in the Curation App.


/cc @twhetzel

**Comment by tudorgroza** [comment]
Projects & Manuscripts will have a stable - nicely formatted ID
All samples will receive a temporary GCST - nicely formatted as well.
