### ISSUE TITLE
Allow submitters to apply a CC0 license to their submissions

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#262]
We need to require users to agree to apply a CC0 license to their submissions. This requires changes to the deposition UI and the search UI. 

Deposition UI UAT criteria
1. During the submission process, submitters are presented with a checkbox with the following text:
"I agree to my data being made freely available under the terms of CC0"
2. "CC0" text is hyperlinked to https://creativecommons.org/publicdomain/zero/1.0/
3. Submitter is unable to proceed with the submission without checking this box.
4. Curators are able to proceed with submissions without checking the box.

Mockup of deposition UI:
 
![Screenshot 2020-10-21 at 16 27 32](https://user-images.githubusercontent.com/30795297/96744606-21b21e00-13bd-11eb-8e26-127b5b26534d.png)

Search UI UAT criteria
1. User is able to access summary stats via landing page for dataset (landing page for unpublished studies or study page for published studies)
2. For those studies where CC0 has been agreed to, user is presented with the text "Summary statistics usage license: CC0", next to the sumstats ftp link in the study info box 
3. "CC0" text is hyperlinked to https://creativecommons.org/publicdomain/zero/1.0/  
4. For those studies where CC0 has not been agreed to (curator submitted/historical submissions), user is presented with the text "Terms of use", hyperlinked to https://www.ebi.ac.uk/about/terms-of-use/
4. User is able to access summary stats via table https://www.ebi.ac.uk/gwas/downloads/summary-statistics
5. Published and prepublished table contain an additional column entitled "Summary statistics usage license"
6. Column is filled with CC0 for those studies where CC0 has been agreed to. 

Mockup of study page:

![Screenshot 2020-10-21 at 17.10.01.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/06750e3e-4e10-4404-a0a8-ad4152d18847)

**Comment by ljwh2** [comment]
Note, curators must be able to submit sumstats without agreeing to license, added this to UAT criteria

**Comment by ljwh2** [comment]
There's something about generating machine readable code associated with CC0 here: https://creativecommons.org/choose/zero/ but I don't have the background to understand how we could apply it

**Comment by ala-ebi** [comment]
What I did so far is only in Deposition app:
For curators: CC0 checkbox exists, but they can proceed without checking it.
For non curators: CC0 checkbox exists and they can only submit if it's checked.
Questions: 
1 - If a curator does not check the box, does that mean that we won't display the license in the study's Search UI?
2 - Does curators need to see that box in the first place or I can always assume it is checked and not show it?
3 - Studies prior to this change will not have the license agreement text in Search UI?
Asking these questions to know if I should persist a flag for the agreement somewhere in the db or do things in a pure UI fashion.

**Comment by ljwh2** [comment]
@ala-ebi 
1. Yes, that's correct. Curators can only apply the license if the data is already available elsewhere under the same license. If it's freely available, eg on a personal website, with permission for reposting but without the formal license, we cannot apply the license ourselves - it's only permissible to apply this license to your own data. But if the data is already available under the license, we can replicate it.
2. No, it should be unchecked by default.   
3. Yes, that's correct. We can only apply the license if the author has specifically checked the box.  

Agree, we should have a flag for the agreement in the db somewhere. I think we may want to expose this to users in the future eg via the API.

**Comment by ljwh2** [comment]
note I will need to add some FAQ text before this is released

**Comment by ljwh2** [comment]
@ala-ebi as discussed, add some text "More info" on the checkbox which should link to item B5 on this page: https://www.ebi.ac.uk/gwas/docs/submission
@eks-ebi please inform when the new documentation is added

**Comment by eks-ebi** [comment]
The documentation is now fully updated. There are changes to the following files in GitHub:
* https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/submission-content.adoc
* 3 new/updated images in https://github.com/EBISPOT/gwas-ui/tree/documentation/goci-interfaces/goci-ui/src/main/docs/images: 
> * create_sub.png (different image with same filename)
> * enter_email2.png (replaces enter_email.png)
> * pre_sub_checklist.png (different image with same filename)
