### ISSUE TITLE
investigate small sumstats

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#263]
Several sumstats files are far too small. Investigate why.
160	29899525-GCST006099-EFO_0008002.h.tsv.gz
160	29899525-GCST006100-EFO_0008002.h.tsv.gz
161	29899525-GCST006097-EFO_0008002.h.tsv.gz
162	22581228-GCST005186-EFO_0004465.h.tsv.gz
162	23263486-GCST001790-EFO_0004274.h.tsv.gz
162	23263486-GCST001791-EFO_0004531.h.tsv.gz
162	29899525-GCST006098-EFO_0008002.h.tsv.gz
163	22581228-GCST005185-EFO_0004466.h.tsv.gz
170	26343387-GCST003116-EFO_0000378.h.tsv.gz
170	30323354-GCST006719-EFO_0009443.h.tsv.gz
193	22484627-GCST001475-EFO_0001073.h.tsv.gz

**Comment by jdhayhurst** [comment]
It looks like these are only the headers because the files are missing critical information for them pass qc.
For instance:
```
$zcat 29899525-GCST006079-EFO_0008002-build37.f.tsv.gz | head
variant_id	chromosome	base_pair_location	effect_allele	other_allele	effect_allele_frequency	beta	standard_error	ci_upper	ci_lower	odds_ratio	p_value
rs576404767	1	544584	C	T	0.998166	0.121041	0.0671768	NA	NA	NA	NA
rs12025928	1	546697	A	G	0.0866928	0.00740314	0.0101098	NA	NA	NA	NA
rs573042692	1	565111	T	C	0.998448	-0.0945035	0.082647	NA	NA	NA	NA
rs9283152	1	566792	T	C	0.997929	-0.0934729	0.0881429	NA	NA	NA	NA
rs565235853	1	567006	G	T	0.997019	0.0764542	0.0457031	NA	NA	NA	NA
rs2000096	1	567867	A	G	0.99705	-0.117665	0.0682673	NA	NA	NA	NA
rs12238997	1	693731	A	G	0.883456	0.00761658	0.00679107	NA	NA	NA	NA
rs72631875	1	705882	G	A	0.932401	-0.0115626	0.00991837	NA	NA	NA	NA
rs544671234	1	705942	A	T	0.996563	0.0183289	0.0448709	NA	NA	NA	NA
```
Here you can see the formatted file does not contain p-values. In the qc stage of the harmonisation, it drops any rows without pvalues as these are mandatory fields. I did not expect this, so it still wrote what it could to the output, which is just the header. 
Checking a few of the others, it appears to be the case for all of them - they're missing p-values.
@buniello How should these be handled?

**Comment by buniello** [comment]
I will re-format them and make sure all critical info are included. Does it sound like a good plan? @jdhayhurst

**Comment by jdhayhurst** [comment]
@buniello that's fine for me

**Comment by buniello** [comment]
All the files above have now been re-formatted with new formatting tool -and should contain all critical fields. 
They are here: /nfs/spot/data/prod/gwas/preanalysis_summarystats/AnnaB_forsummarystatsdatabase/READY_TO_LOAD/NewStudies/@j
@jdhayhurst

**Comment by jdhayhurst** [comment]
@buniello the new files have been harmonised and released on the ftp. I did notice that GCST006719 is missing the reference allele so this one was not harmonised. The "harmonised" file is still produced but none of the harmonised data are populated.

**Comment by ljwh2** [comment]
@buniello please could you check these files

**Comment by buniello** [comment]
@jdhayhurst @ljwh2  these files look ok. I confirm that GCST006719 is missing the reference allele (from raw file). Sorry I missed the first tag.
