### ISSUE TITLE
Fix pvalue validation to accept very low numbers.

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/goci#269]
Also - pvalues should never be 0.

**Comment by tudorgroza** [comment]
@ljwh2 @eks-ebi - this is now deployed in sandbox and ready for testing.
Here are the changes I've introduced:
* p-value must follow the scientific notation and it cannot be 0 (zero). If it's 0 or a standard double value notation is used, the validation will fail
* a maximal value for the exponent of -5 (which is the same as it was before) with no lower bound - e.g., it can be -1000 if it has to. I can, however, introduce this lower bound if you want.

Please let me know if this conforms with your expectations.

**Comment by ljwh2** [comment]
Agree with this and exponent should have no lower bound

**Comment by ljwh2** [comment]
Other relevant tickets: GOCI#271 - need to ensure rounding is working properly, GOCI#210, consider whether upper threshold could be 9.5E-6 rather than 1E-5

**Comment by eks-ebi** [comment]
Tested submission here: http://193.62.54.159/gwas/deposition/submission/5fa15b73f59a3b00016d5f23

P-values tested:

- 1e-6 passed
- 0.000001 (same as above but as float) failed `Associations: Column 'p-value' in row(s) [6, 8] contains incorrect value. Expected p-value exponent should be in the range: '-'`
- 9e-5
- 0 failed `Associations: Column 'p-value' in row(s) [6, 8] contains incorrect value. Expected p-value exponent should be in the range: '-'`
- 1e-1000 passed
- 9.95e-6 passed

**Comment by tudorgroza** [comment]
Besides the strange missing values in the error message - which I need to look into ... are any of the examples above inappropriately validated?

**Comment by eks-ebi** [comment]
Updated my comment above with a second test. @tudorgroza, above you said that the criteria are 

> a maximal value for the exponent of -5 (which is the same as it was before)

That's wrong, I think it should be a maximal value for the exponent of -6 (i.e. it should fail if it is -5)

**Comment by tudorgroza** [comment]
I see ... ok ... I need to think :) Thank you.

**Comment by tudorgroza** [comment]
Fix deployed in Sandbox.

**Comment by eks-ebi** [comment]
Tested with the following p-values:

row number in template | p-value | expectation
-- | -- | --
5 | 1.1e-5 | expected to fail
6 | 1e-5 | expected to fail
7 | 9.9e-6 | expected to pass and round up
8 | 9.5e-6 | expected to pass and round up
9 | 9.4e-6 | expected to pass and round down
10 | 9e-5 | expected to fail
11 | 9e-1000 | expected to pass and round up

Result:
see http://193.62.54.159/gwas/deposition/submission/5fa41716ce8e310001e61d79
Error message:
Associations: Column 'p-value' in row(s) [5-6, 10] contains incorrect value. Expected p-value exponent should be in the range: '1.0e-5 -'

Conclusion:
The validation performed as expected - p-values ≥ 1e-5 failed validation, while those < 1e-5 passed. This is correct.
Associations with very small p-values (e.g. 9e-1000) passed validation, as they should.
