### ISSUE TITLE
p-values import to the curation app with a mantissa of 10. 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#271]
When a p-value in the submission template has a mantissa of more than 9.5, eg. 9.6E-10, it is imported into the curation app as 10E-10. This should be imported as 1E-9. 

An error is reported in the submission import e-mail, eg: 

**Warnings:
Validating associations | [GCST90011293 | g] Full validation error: P-value mantissa [data]: Value not valid i.e. greater than 9 | false
Validating associations | [GCST90011295 | Memory] Full validation error: P-value mantissa [data]: Value not valid i.e. greater than 9 | false
Validating associations | [GCST90011298 | VNR] Full validation error: P-value mantissa [data]: Value not valid i.e. greater than 9 | false
Validating associations | [GCST90011298 | VNR] Full validation error: P-value mantissa [data]: Value not valid i.e. greater than 9 | false
Validating associations | [GCST90011298 | VNR] Full validation error: P-value mantissa [data]: Value not valid i.e. greater than 9 | false
Creating association | Save error: false | Value not valid i.e. greater than 9 | P-value mantissa
Creating association | Save error: false | Value not valid i.e. greater than 9 | P-value mantissa
Creating association | Save error: false | Value not valid i.e. greater than 9 | P-value mantissa
Creating association | Save error: false | Value not valid i.e. greater than 9 | P-value mantissa
Creating association | Save error: false | Value not valid i.e. greater than 9 | P-value mantissa**

@ljwh2 Just creating this ticket for when you have time to look at it. I don't know if the fix would be to stop rounding p-values, or to create a rule which means they are imported correctly, or just a QC measure. The SNPs are imported with a big red X next to them to show they have not been mapped, so it's easy enough to fix them manually for now.

**Comment by tudorgroza** [comment]
Confirming that the code does the rounding first and then passes on the rounded values to the validation checker. I can add some additional checks to cater for values of the form `9.5Xe-N` (where `X > 0` - i.e., `9.51`) to be converted to `1e-(N-1)` - before sending them to validation.

**Comment by eks-ebi** [comment]
That sounds like a good approach. Although to confirm, the description as written is not quite right:

> `9.5Xe-N` (where `X > 0` - i.e., `9.51`) to be converted to `1e-(N-1)`

This shouldn't just apply to `9.5Xe-N`, but to `9.Xe-N` (where `X ≥ 5`) - i.e. `9.5` itself (which should also round up, right?) and anything higher than that, i.e. `9.6`, `9.7` ... `9.99 (recurring)`

**Comment by tudorgroza** [comment]
Right - `9.Xe-N` with `X >= 5` - correct. Apologies - my mistake.

**Comment by tudorgroza** [comment]
Curation changes deployed in SNOOPY; Depo changes deployed in Sandbox.

**Comment by eks-ebi** [comment]
tested in #210:
- p-values of form `9.Xe-N` with `X>=5` now correctly round up to mantissa `1` exponent `-(N-1)` instead of mantissa `10` exponent `-N`
