### ISSUE TITLE
Make available "Sharing and standards workshop" materials on GWAS Catalog website

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#279]
Add page on the GWAS Catalog website to provide users with information on the “Sharing and standards” that took place in June 2020. The page will include summary information on the workshop, along with links to additional files (available on ftp), which will also provide supplementary material for the workshop proceedings publication.

Requires:
1. A page creating on the GWAS Catalog website
2. A folder creating on the GWAS Catalog ftp to contain files to be linked to from text within the page

Specification on the work required can be found here:
https://docs.google.com/document/d/1r0UxsBrlULoDnRgg6vbB2WwdHNAzc0YXk1Uvq5inJKc/edit?usp=sharing

**Comment by jdhayhurst** [comment]
@JalMacArthur please send me the files that you'd like to host and I'll publish them on the ftp

**Comment by JalMacArthur** [comment]
Thanks. I'll get the files together (I need to rename etc) and put them in a dropbox.

**Comment by JalMacArthur** [comment]
The remaining work required on this issue is:
- Add videos so they play when you click on them, rather than downloading - I think Yomi suggested adding to YouTube channel to facilitate this
- Add links from other pages to the https://www.ebi.ac.uk/gwas/docs/sharing-standards-workshop page once the publication is publicly available (see specification)

**Comment by sprintell** [comment]
http://snoopy.ebi.ac.uk:9680/gwas/docs/sharing-standards-workshop

**Comment by ljwh2** [comment]
I closed this but realised it is not in production yet, it can be released now @sprintell
