### ISSUE TITLE
Update project provenance identifiers

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/goci#28]
Curators or submitters should be able to add publication identifiers to studies in submitted “projects” that are subsequently published. This would associate a previously unidentified paper with a recognized unique identifier (PubMed ID, Biorxv ID, UK BB ID).

**Comment by tudorgroza** [comment]
@jstewart-ebi - please see comments on this first: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/25

This part: `associate a previously unidentified paper with a recognized unique identifier (PubMed ID, Biorxv ID, UK BB ID)` needs clarification on whether we introduce a general `identifiers` field (as a list of string that can take the `PREFIX: REFERENCE` form) - or do they have to be named? (I.e., to have an actual `ukBBID`?)

Question:
 * Where is this update taking place? Curation App or Deposition App?

/cc @twhetzel
