### ISSUE TITLE
Final stalled submissions email and associated functionality

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#285]
1. The links in the email point to sandbox, even though I created the submission in PROD (in the email subject line and link from the submission title in the email body). 
2. The submissions are still visible in the deposition app even though the email states it has been removed.

I am forwarding the emails to you @tudorgroza

**Comment by tudorgroza** [comment]
@ljwh2 - I've checked both submissions and they are created in Sandbox ... not PROD. What made you think that they're created in PROD?

Hence, the URL is correct - and if you check in Sandbox, you should not see them.

PS: Where exactly did you see these submissions visible in PROD?
