### ISSUE TITLE
Flags for Open Targets and User Requested should be set at publication level, not study

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#286]
In the curation app, the Study Details tab includes several check boxes for curator use, screen shot:![Screenshot 2020-11-12 at 16.08.30.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/d643acc4-bd89-4356-951d-09287d578802)

Conceptually speaking, "User Requested" and "Open Targets" are properties of the Publication and not of the Study - there is no instance where this flag would be set differently for different studies of a publication. They should be set on the publication view.  This feature is important for curator workflow when multi-study datasets are submitted via the deposition app.

UAT criteria
1. Curator accesses publication view for a given publication.
2. Curator is presented with the option to set flags for "User Requested" and "Open Targets" for the publication.
3. Once the flags are set, every study in the publication should be flagged accordingly.

**Comment by tudorgroza** [comment]
Note: The change in status at publication level can happen at any time (before, while and after the studies are created).

**Comment by ljwh2** [comment]
@tudorgroza 

The first (and maybe second) time I clicked the "change status" button for Open Targets for this publication http://snoopy.ebi.ac.uk:9680/gwas/curation/publication/33020668, I think the status did change to "true", but since then it does not change (nor for other publications, nor for the "User requested" one)

Clicking the button did not seem to have any impact on the existing flag on the study tab, but I can't verify this.: http://snoopy.ebi.ac.uk:9680/gwas/curation/studies/63073214

**Comment by tudorgroza** [comment]
Ok - I'll look into it. The status should have an impact on the existing flag in the study tab ...

**Comment by tudorgroza** [comment]
@ljwh2 - I've fixed this and tested on that publication. I need to fix the button though ... you should be able to press twice on it ... i.e., 'double-click'. Other than that - the functionality is there.

**Comment by buniello** [comment]
I have tested the functionality and clicked on buttons multiple times. It worked ok for me. @tudorgroza @ljwh2

**Comment by ljwh2** [comment]
Works fine for me now too @tudorgroza

**Comment by tudorgroza** [comment]
Thank you! Will consider this done and plan it for release on Thu.
