### ISSUE TITLE
Monitor PubMed for publication of pre-published paper

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/goci#29]
Curators should be notified if a PubMedID is added to queue that may already have been submitted pre-publication. Send alert message or automatically update with PMIDs via tracking of EuropePMC or BioRxiv status (RSS feed?)

**Comment by jstewart-ebi** [comment]
Interim solution was to indicate active submission and allow match for pre-published submission on creation of the publication in Curation.

**Comment by ljwh2** [comment]
@buniello Please comment when you have experience of whether this works reliably

**Comment by buniello** [comment]
The submission matching tool that Jon created for the interim solution above works reliably, though the matching scores (right-hand side of the screen) are not always of linear interpretation.
