### ISSUE TITLE
Support import of METADATA submissions on studies that are already in Level 1 curation

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/goci#290]
This emerged from a use case @earlEBI and I have discussed (and worked on) this week.
Scenario:
* Publication exists in curation and has N studies already in Level 1 curation.
* Studies have not been published yet
* Author wants to submit summary stats of M studies - with `M <= N` (in this particular case we had 7 studies in curation and author wanted to provide summary stats for 1)
* Publication is in `ELIGIBLE` status, which leads to the submission being a `METADATA` submission
* The import process does not do consolidation - it just adds the studies provided by the users as new and marks all existing studies as `Requires Review` with the note: `Review for deletion, replaced by deposition import`

To discuss:
* should we change the import process to support consolidation?
* or leave the functionality to be included as part of https://github.com/EBISPOT/goci/issues/102?

/cc @eks-ebi @ljwh2 @sprintell @earlEBI

**Comment by ljwh2** [comment]
From my reading, this is something to be handled by curators. The imported studies should be reviewed and consolidated manually with the curated entries. I don't see this as being any different than cases when M=N. Agree we should consider adding this functionality as part of #102.
