### ISSUE TITLE
Curators need to be able to submit/publish raw summary statistics as well as the formatted ones

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#291]
When curators submit sumstats, they'll have both raw and formatted versions. They should be able to publish both. Possibly the most robust solution is to enable curators to upload raw summary stats when they make a submission. Another field in the submission template for raw sumstats path (optional) that can be passed to the sumstats service, which can publish the raw file along with the formatted.

**Comment by jdhayhurst** [comment]
1. A new column in the meta data template on the study sheet, "raw sumstats file" only visible to curators and optional. [Template service, backend]
   a) metadata validation - it should be validated the same as the sumstats file value. 
2. This value needs to be passed to the sumstats service when the POST is made, let's call it "rawFilePath" (optional).  [Backend, sumstats service]
   a) sumstats service will attempt to download file (we probably don't need md5sums for this?) - if it can't download the file it will return an error stating this (still returning the 200)
3. This file needs to be published on the ftp. I can't see any reason why it needs to be imported to the curation app [gwas-utils]

Considerations:
Where multiple raw files have been concatenated - the curator will need to tar/zip these together.

**Comment by tudorgroza** [comment]
@jdhayhurst - should be enough for me to start the work.

**Comment by jdhayhurst** [comment]
Need to enable the "raw sumstats" field for all templates where the user is a curator

**Comment by Santhi1901** [comment]
@jdhayhurst checked and it is working the submission form has a column raw summary statistics file
