### ISSUE TITLE
Add links to "Sharing and standards workshop" page when manuscript is made public

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#306]
Specification on the work required can be found here:
https://docs.google.com/document/d/1r0UxsBrlULoDnRgg6vbB2WwdHNAzc0YXk1Uvq5inJKc/edit?usp=sharing

Texts and links need adding from related resources and summary statistics documentation page.

**Comment by ljwh2** [comment]
@eks-ebi Please could you create the links with text according to Jackie's specifications

**Comment by eks-ebi** [comment]
Updated the following pages in documentation branch:
- https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/related-resources-content.adoc
- https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/methods/summary-statistics-content.adoc

**Comment by eks-ebi** [comment]
Note: some specifications will need to be completed after the paper is out

**Comment by eks-ebi** [comment]
The Workshop page also needs to be updated - I have changed the ftp:// links to http:// to allow access by browsers that no longer support ftp.

https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/sharing-standards-workshop-content.adoc
