### ISSUE TITLE
Automate import of SUMSTATS submissions

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/goci#313]
SUMSTATS submissions currently require a curator to push the 'Import' button - although there's no other QC required on them.

Proposal: automatically import these submissions, without the curators pushing the button.

Question: is there any use case / scenario when one would *not* want this automation to take place?

/cc @jdhayhurst @ljwh2

**Comment by buniello** [comment]
Does this apply to both curators and authors' submissions? 
For author's submission, we need to be able to control import process according to data releases. For example, I am currently waiting for the data release to start before importing a big submission - as I knew we did not have time to curate 126 studies before Monday 14th.

**Comment by tudorgroza** [comment]
This is for all SUMSTATS-only submissions.

**Comment by buniello** [comment]
Thanks Tudor. I do not foresee any problem, in this specific use-case.

**Comment by ljwh2** [comment]
please go ahead @tudorgroza
