### ISSUE TITLE
Error message for import of publication that doesn't exist in curation DB

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#315]
In order to successfully import publications to the curation app, the publication must have a PMID adding in both deposition and curation. Publications that have a PMID added in deposition appear in the curation app submissions page (https://www.ebi.ac.uk/gwas/curation/submissions) with a PMID, regardless of whether the publication exists in the curation DB. Currently, attempting to import a publication that does not exist in the curation DB  appears to work successfully, yet the import never completes. 

Attempting to import a publication that does not exist in the curation DB should trigger an error message to the curator.

**Comment by tudorgroza** [comment]
@ljwh2 @buniello @earlEBI  - this is now deployed in SNOOPY and ready for testing.
I changed the outcome from an error message to not allowing the import at all. I've also added some extra tabs on the Submissions page - http://snoopy.ebi.ac.uk:9680/gwas/curation/submissions

@earlEBI - as per your comment - pre-publication submissions are now not under 'Ready to import' tab.

**Comment by ljwh2** [comment]
How should we test this? Do we need to know a publication that exists in deposition but not in curation? Maybe we can talk through it in the iteration meeting @tudorgroza

**Comment by buniello** [comment]
yes, please let me know!

**Comment by tudorgroza** [comment]
@ljwh2 - as mentioned below, I've changed the intent. If you look in the 'Other' tab under Submissions and pick one of type 'Pre-Publication', the 'Import' button should not be available.

**Comment by ljwh2** [comment]
Reviewed in iteration meeting and all looks good. Confirmed that publications that don't exist in curation db will not appear available for import, even if they have a PMID in deposition.
