### ISSUE TITLE
GWAS Catalog export to Europe PMC

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#316]
EuropePMC would like to be able to link back to GWAS Catalog data from their citation entries, this was done for older studies but we stopped producing the export at some point. See example here (under "Data" section): http://europepmc.org/article/MED/25917933

Info is included in 2 gwas-info emails 11 Dec from labslink@europepmc.org and pasted below

**Comment by ljwh2** [comment]
We have just re-sent the FTP details for the GWAS account.

We need two files to be uploaded for each set of links:

1. A profile file, this describes the set of links submitted.

2. The links file.

For information on how to produce the files:

You can find our schema at: labslink.xsd.

The technical documentation at: labslink_schema_documentation.pdf

Instructions on how to use Excel to generate external links data: labslink_excel_instructions.pdf

The demonstration Perl program to generate LabsLink files is attached (labslink_tab_convert.zip).

Please let us know if you have any questions at all.[https://app.zenhub.com/files/2995118/fa090389-5f09-451a-8057-1d9011fecfe4/download](https://app.zenhub.com/files/2995118/fa090389-5f09-451a-8057-1d9011fecfe4/download)

**Comment by ljwh2** [comment]
Dear Participant,
Thank you for your interest in the Europe PMC External Links Service.
We have assigned the following provider ID to you:
1375
Please include this ID in all files you send to us from now on, as per the instructions available here:
https://europepmc.org/LabsLink
The details of the FTP server are as follows:
SERVER:   labslink.ebi.ac.uk
USERNAME: elinks
PASSWORD: 8VhrURVH
Once logged in, change to the following directory:
zmoi12ok
That folder is hidden. So, if you use an FTP client with a graphic user interface, you will need to enter the above folder name in the remote path field. If you use a command-line FTP client, enter:
cd zmoi12ok
Files must be no bigger than 2 MB each. The total file size limit is 500 MB. All files must be named with one of the following
extensions:
.xml /.zip /.gz /.tar / .tar.gz / .targz
You can now begin uploading files unless either of the following exceptions apply:
If you already have PubMed LinkOut files we may be able to convert them for use by Europe PubMed Central (depending on which features of their schema you have used.) However, before uploading any such files, please reply to this email to inform us of the provider ID which the NCBI has assigned to you.
If you wish to maintain multiple sets of links (perhaps linking to different resources, or the result of different text mining methodologies) please reply to this email to tell us how many additional provider IDs you require.

**Comment by ljwh2** [comment]
Here is an example of how the data from old studies looks in EuropePMC: http://europepmc.org/article/MED/18463975

Click on "Data" and you will see a header NHGRI-EBI GWAS Catalog with the link to the publication page: http://www.ebi.ac.uk/gwas/search?query=18463975

**Comment by ljwh2** [comment]
Here is an example of how the spreadsheet should be filled (as I understand it)
ID is the PubMed ID
SOURCE is MED for all rows (indicating it's a PubMed ID)
URL is the url for each GWAS Catalog publication page corresponding to the PubMed ID
PROVIDER ID is our provider ID as described in the email text above
We will need to generate a file containing data for all publications in the Catalog.
[https://app.zenhub.com/files/2995118/4dc06d6b-e1b2-46a3-ad00-0e9caae07db5/download](https://app.zenhub.com/files/2995118/4dc06d6b-e1b2-46a3-ad00-0e9caae07db5/download)

**Comment by ljwh2** [comment]
I have emailed labslink@europepmc.org to find out if we can do this for prepublished studies as well

**Comment by sajo-ebi** [comment]
@ljwh2 Have transferred the Links & Provider file to the above mentioned location . The file names are as follows -:

GWASLinks-26022021.xml
GWASProvider-26022021.xml

**Comment by ljwh2** [comment]
@sajo-ebi will the file be generated after each data release?

**Comment by sajo-ebi** [comment]
@ljwh2 Yes at present it needs to manually done after each Data release.

We will create  a story to automate this in Data release pipeline at a later time.

**Comment by ljwh2** [comment]
@sajo-ebi see email thread from labslink@europepmc.org (Fran) - for the unpublished studies, they can not handle so many links per DOI. Therefore we can't proceed with linking from pre-prints, unless we create a dedicated page for each DOI (this is not currently on roadmap). So the only outstanding work here is to automate generation of the file for published studies as part of the data release pipeline.

**Comment by ljwh2** [comment]
Look at making a page for each DOI in future
