### ISSUE TITLE
Add text to successful submission email explaining data release process

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#321]
We get a lot of user queries about when data will become available after submission. This information should be added to the email sent to users upon successful submission. The simplest way to do this would be to link to the documentation page. I suggest:

For more information about how and when your data will become publicly accessible, please see our documentation pages: https://www.ebi.ac.uk/gwas/docs/submission#link-15

@eks-ebi @earlEBI if one of you has an example of the existing submission text, please could you paste it here and suggest where to add the new text.

**Comment by eks-ebi** [comment]
Like this?

> Dear ____,
> 
> The summary statistics for _19169253 - Deletion of the late cornified envelope LCE3B and LCE3C genes as a susceptibility factor for psoriasis._ by de Cid R et al., were successfully validated and submitted to the GWAS Catalog.
> 
> Following submission the accession ID(s) for your submission will be available to download by pressing on the 'Download Study Accessions' button on the studies page.
> 
> For more information about how and when your data will become publicly accessible, please see our documentation pages: https://www.ebi.ac.uk/gwas/docs/submission#link-14
>
> Thanks for sharing your data with us.
> 
> Best wishes,
> GWAS Catalog team

**Comment by ljwh2** [comment]
looks good, thanks

**Comment by sajo-ebi** [comment]
The Email text change has been implemented in Sandbox environment , Kindly verify @ljwh2 @eks-ebi .

Note : 1 change I have made is that instead of showing the entire URL as HyperLink text Documentation is shown as in the paragraph above for Studies page link

**Comment by Santhi1901** [comment]
@sajo-ebi checked and received the email (for PMID: 26473621 with submission ID: 60a7775e56a9f500011aef4a)

**Comment by sajo-ebi** [comment]
The changes have been deployed in Production.
