### ISSUE TITLE
Delete GCP000094 (and associated submission) from the deposition interface

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#327]
This is a duplicate body of work. The user has requested that this one be removed.

**Comment by ljwh2** [comment]
Confirm this is a completed submission that was made in duplicate, and does need deleting manually

**Comment by sajo-ebi** [comment]
@eks-ebi The body of work & submission associated have been manually deleted . Kindly verify the same

**Comment by eks-ebi** [comment]
@sajo-ebi Confirmed! It has been deleted
