### ISSUE TITLE
View Submissions page - sorting by date

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#329]
The View Submissions page in the Curation Interface does not sort correctly by 'date created'.
https://www.ebi.ac.uk/gwas/curation/imported_submissions

Sorting correctly would be particularly useful for the 'imported' sub-tab. 

![Screenshot 2021-01-14 at 11.20.57.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/1d45ad16-fb7a-4697-aca1-bbfd13a04c94)

**Comment by ala-ebi** [comment]
Investigating this issue I discovered that the date format is not consistent with the rest of the app, namely Studies page, so I changed the date format to "yyyy-mm-dd" for Submissions page which in turn solved the sorting issue.

**Comment by ljwh2** [comment]
@earlEBI please verify this is working now

**Comment by earlEBI** [comment]
Yes, looks good!
