### ISSUE TITLE
Exclude publications and their related studies with status "requires review" from Reporting metrics

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#33]
For publications and their related studies with status "requires review", exclude these from metrics in the Curation app "Reports" tab for "Overall weekly progress" and "Open targets weekly progress".

**Comment by twhetzel** [comment]
The reporting metrics are based on the list of values from `EVENT_TYPE`. 
@jstewart-ebi do you know if there is an event associated with the curation status "Requires review"?

**Comment by ljwh2** [comment]
@earlEBI when possible, please review whether "requires review" studies are including in reporting metrics and feedback to Trish

**Comment by earlEBI** [comment]
@ljwh2 @twhetzel Studies with status 'requires review' are included in the weekly_progress_totals*.csv spreadsheets, in the 'level 1 completed study IDs' column (and obviously in the 'created study IDs' column). Does that answer the question ?

**Comment by ljwh2** [comment]
discussed with @earlEBI and sounds like any effect of this will be highly dependent on what point the submission is imported and can be better dealt with on the curator side

**Comment by twhetzel** [comment]
@ljwh2 can this be closed then?

**Comment by ljwh2** [comment]
@twhetzel yes
