### ISSUE TITLE
Set up continuous code inspection tool to improve quality and reliability of old and new Java software

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#330]

**Comment by sajo-ebi** [comment]
We have integrated SonarCLoud & Travis CI to all Java projects , For Python projects we need more research & will be done later . The Sonar dashboard can be is available in the below mentioned link.


[](https://sonarcloud.io/organizations/gwas-ebi/projects)

**Comment by sajo-ebi** [comment]
Need to investigate alternative options to Travis CI as it has gone commercial , Need to decide between Gitlab & Github

**Comment by ljwh2** [comment]
Travis now working & replenishing free credits
