### ISSUE TITLE
Add Feature to allow curators add Reported Traits to studies in bulk 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#333]
curators upload csv of GCP and corresponding reported traits, and the reported traits are added to the concerned studies

**Comment by eks-ebi** [comment]
Question: What information do you need to enter in the template require for this bulk upload action?

Here is the example template I got from @sprintell:
```
GCST	Curated reported trait
GCST90011301	C_Actinobacteria abundance
GCST90011302	C_Alphaproteobacteria abundance
```
It seems that you have to have a GCST to identify each study. However, for studies added manually in the curation interface (i.e. not created by a submission) there is no GCST until the study has been published. e.g. 
http://snoopy.ebi.ac.uk:9680/gwas/curation/publication/33106475# (note the blank "Study accession" field) 

![Screenshot 2021-02-11 at 17.11.52.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/23cb8b91-1def-4b4d-b309-840f89fdc63c)

How can Reported traits be added for studies that do not yet have a GCST? Suggest using "Study ID" instead (this should exist for all studies in the curation interface). @ljwh2 could you check if you agree?

**Comment by ljwh2** [comment]
@sprintell @eks-ebi  If it's straightforward to allow addition of traits based on study ID this functionality should be added. However if it's not straightforward we should leave it for now and have the bulk addition of reported traits only available for studies curated through the deposition app.
