### ISSUE TITLE
Changes made to Documentation branch

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#337]
Edited the Methods section of Documentation page using this page: 
https://github.com/EBISPOT/goci/blob/documentation/goci-interfaces/goci-ui/src/main/docs/methods-content.adoc

Needs to be released.

**Comment by earlEBI** [comment]
Moved the changes across to here https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/methods/curation-content.adoc

**Comment by ljwh2** [comment]
@earlEBI could you please check if the changes are in production now?

**Comment by earlEBI** [comment]
Yes, changes have been made.
