### ISSUE TITLE
Submission template needs to allow NR in Variant Count column

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#338]
Curators need to be able to enter NR in the Variant Count column. 

![Screenshot 2021-01-22 at 15.10.13.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/016fdf57-5610-43e5-831a-b9f05b9b30a8)

At the moment, an error is received: 

![Screenshot 2021-01-22 at 15.10.02.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/8259a2e6-1fcf-45b5-be69-a162356f706a)

**Comment by ljwh2** [comment]
as first step investigate this and estimate amount of work/implications

**Comment by ljwh2** [comment]
seems like NR cannot be entered in the curation interface either, so the issue here is to allow curators to not enter SNPn, whilst forcing users to enter it, so could be something in the format -1 as proposed in the sprint meeting. Seems like NR is displayed in the user interface, if nothing is entered in the curation interface (needs verifying)

**Comment by jdhayhurst** [comment]
I can't enable this change from the template schema alone unless you want the field to be optional for all. With curator status, if I create a submission from an "open for submission" type, the template that gets used is "METADATA", which is the template that is used for non-curators. 
To understand this we need to understand the call between the backend and template-service - this might be something @sajo-ebi can help investigate

**Comment by earlEBI** [comment]
Tested -1 in variant count column for 601d5e01b13a9000016e3d15 / GCST90013480 and it validated, and nothing was imported in the variant count field.

**Comment by ljwh2** [comment]
Since we have a workaround, I think we can close this ticket - if you agree @jdhayhurst

**Comment by jdhayhurst** [comment]
We're going to run another test in sandbox to see how the data is materialised in the DB.

**Comment by ljwh2** [comment]
note - blocked by problems in sandbox

**Comment by jdhayhurst** [comment]
@earlEBI and @ljwh2 I've tested in sandbox and can confirm that a variant count of -1 is imported to curation db as Null.
