### ISSUE TITLE
SMTP Failure occurs  thousand of times in a month in goci while sending emails 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#349]
Detailed information and suggestions from systems below

| Date    | Count of failed SMTP Auth | Address                            |
|---------+---------------------------+------------------------------------|
| 202101* |                      1264 | f=<gwas-curation-system@ebi.ac.uk> |
| 202012* |                       458 | f=<gwas-curation-system@ebi.ac.uk> |
| 202011* |                       469 | f=<gwas-curation-system@ebi.ac.uk> |
| 202010* |                      1799 | f=<gwas-curation-system@ebi.ac.uk> |
|---------+---------------------------+------------------------------------|

| Date    | Count of failed SMTP Auth | Address               |
|---------+---------------------------+-----------------------|
| 202101* |                        70 | f=<spotbot@ebi.ac.uk> |
| 202012* |                       123 | f=<spotbot@ebi.ac.uk> |
| 202011* |                       168 | f=<spotbot@ebi.ac.uk> |
| 202010* |                       193 | f=<spotbot@ebi.ac.uk> |
|---------+---------------------------+-----------------------|

**Comment by sprintell** [comment]
Also gwas-curation-system@ebi.ac.uk is configured as the mailer and it isn’t formally registered ?

**Comment by sprintell** [comment]
Suggestion from systems on point of action

I think your Java Mail app does not have SMTP auth config, that's why we see 'SMTPD-AUTH=fail' logs for spotbot@ebi.ac.uk address.
Our email gateway(outgoing.ebi.ac.uk) accept any emails coming from EBI networks. But we configured outgoing.ebi.ac.uk smtp gateway for the active EBI member/virtual accounts.

My suggestions;
- If your apps/servers are in HX DC, you should use hx-smtp.ebi.ac.uk (with port 25) mail server for sending system related emails(log/notification, etc.),
- If your apps/servers are in HL DC, you should use hh-smtp.ebi.ac.uk (with port 25) mail server for sending system related emails(log/notification, etc.),
- If your app needs user credential, you need a virtual account with password and you should use outgoing.ebi.ac.uk (with port 587) - you can follow this guideline https://tsc.ebi.ac.uk/article/desktop/email/email-basics - for sending emails.

Regards,
Vahit

**Comment by ala-ebi** [comment]
changed to hx-smtp.ebi.ac.uk port 25 on DEV 1 DEV 2 and PROD
