### ISSUE TITLE
Platform (SNPs passing QC) column is not being populated in unpublished download

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#350]
In the unpublished download, eg gwas-catalog-v1.0.3-unpublished-studies-r2021-01-29, the column PLATFORM [SNPS PASSING QC]
is not being populated. It should be populated from the columns "Array manufacturer" and "Variant count" in the template, in the format Array manufacturer [Variant count]

**Comment by ljwh2** [comment]
Download files are here: https://www.ebi.ac.uk/gwas/docs/file-downloads

**Comment by ljwh2** [comment]
Also"Study" column is not populated, what should be here? @ljwh2

**Comment by jdhayhurst** [comment]
If these values are None/Null what should be displayed?

**Comment by jdhayhurst** [comment]
Null values should be displayed as NR
