### ISSUE TITLE
Create Download of all Available GWAS including no PubMed ID

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/goci#36]
To support the pre-published, unpublished workflow, we need to create a new download of all studies including studies from publications without a PubMed ID (from Deposition). Will need to determine what fields to include in download, format and link from download page.

**Comment by tudorgroza** [comment]
@jstewart-ebi - there are other tickets that need clarification before this can be implemented. Please see:
 * https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/23
 * https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/28
 * https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/25
