### ISSUE TITLE
Changes in EFO are not propagated to the GWAS Catalog UI

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#366]
Changes in EFO are not always reflected in the GWAS Catalog UI. For example,  EFO_0001645 has name "coronary heart disease" in the GWAS UI, but in OLS has been updated to "coronary artery disease", with an updated definition. It's unclear if this is an isolated case or a systematic issue. Trish previously raised an issue gwas-utils#15. In that example, the term name has been updated in the GWAS Catalog from influenza infection to influenza, but unclear if Trish updated this manually. 

This need investigating and (a) updating the info for EFO_0001645 (b) working out what changes need to be made to automatically keep up to date with EFO in future.

**Comment by ljwh2** [comment]
David O-S advised that there are changes coming in OxO that may help with this.

**Comment by ljwh2** [comment]
see also https://github.com/EBISPOT/gwas-utils/issues/15

**Comment by Santhi1901** [comment]
Another example I found recently was EFO ID: PATO_0000047, which has EFO name as 'sex' in GWAS UI and 'biological sex' in EFO
