### ISSUE TITLE
Publication with PMID 32404885 has wrong status in submission app

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#368]
The publication PMID 32404885 (COVID-19 Host Genetics Initiative) has 31 studies in the catalog: 15 with summary statistics and 16 without summary statistics. I need to submit sumstats for these 16 studies, but the publication has status "CLOSED" in the submission app. 
Its status should be "OPEN FOR SUMMARY STATISTICS", because of the 16 new entries without summary stats.

![Screenshot 2021-02-15 at 10.17.15.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/a59467aa-3a38-4acf-8d81-544d537f7f94)

**Comment by ljwh2** [comment]
@buniello is this still an issue? I think you mentioned all the sumstats are out now

**Comment by buniello** [comment]
issue resolved
