### ISSUE TITLE
Phase2-Implement Gateway Service as reverse proxy to forward requests to each microservice on the VM

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#373]

**Comment by sajo-ebi** [comment]
New Repo for gateway service has been created & gateway service deployed in Dev environment , forwarding to Gwas UI & Gwas Rest API, once apps are deployed in test, staging & Prod the gateway service will also be deployed

**Comment by sajo-ebi** [comment]
Deployed the Gateway app in Prod, validating the application

**Comment by sajo-ebi** [comment]
Have validated the Zuul proxy in Prod , it is working fine
