### ISSUE TITLE
List of PMIDs linked to author-submitted summary statistics that need harmonisation though automated pipeline when FTP restructuring work is completed 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#377]
As previously discussed with @jdhayhurst, I add here the list of PMIDs with author-submitted summary statistics that need attention in the future re harmonisation through the automated pipeline. List for our records. 

32612638
32835660
32558485
32042192
33462482
33536424
32888494
32915782
32917775
33045005
33106285
33208821
33204752
33288918
33303764
33414548
33414549
33510174
33547301
33589840
33589841
33575800

**Comment by jdhayhurst** [comment]
associated studies to check:
ACCESSION_ID
GCST90012102
GCST90012103
GCST90012104
GCST90012105
GCST90012106
GCST90012107
GCST90012108
GCST90012109
GCST90012110
GCST90012111
GCST90012112
GCST90012113
GCST90012114
GCST90000255
GCST90000256
GCST010116
GCST90002283
GCST90002284
GCST90002379
GCST90002380
GCST90002381
GCST90002382
GCST90002383
GCST90002384
GCST90002385
GCST90002386
GCST90002387
GCST90002388
GCST90002389
GCST90002390
GCST90002391
GCST90002392
GCST90002393
GCST90002394
GCST90002395
GCST90002396
GCST90002397
GCST90002398
GCST90002399
GCST90002400
GCST90002401
GCST90002402
GCST90002403
GCST90002404
GCST90002405
GCST90002406
GCST90002407
GCST90011881
GCST90011882
GCST90011883
GCST90007307
GCST90007308
GCST90007309
GCST90007310
GCST90007311
GCST90007312
GCST90007313
GCST90007314
GCST90007315
GCST90007316
GCST90007317
GCST90007318
GCST90007319
GCST90007320
GCST90007321
GCST90007322
GCST90007323
GCST90007324
GCST90007325
GCST90007326
GCST90007327
GCST90007328
GCST90007329
GCST90007330
GCST90002409
GCST90010715
GCST90006884
GCST90006885
GCST90006886
GCST90006887
GCST90006888
GCST90006889
GCST90006890
GCST90006891
GCST90006892
GCST90006893
GCST90006894
GCST90006895
GCST90006896
GCST90006897
GCST90006898
GCST90006899
GCST90006900
GCST90006901
GCST90006902
GCST90006903
GCST90006904
GCST90006905
GCST90006906
GCST90006907
GCST90006908
GCST90006909
GCST90006910
GCST90006911
GCST90006912
GCST90006913
GCST90006914
GCST90006915
GCST90006916
GCST90006917
GCST90006918
GCST90006919
GCST90006920
GCST90006921
GCST90006922
GCST90006923
GCST90006924
GCST90006925
GCST90006926
GCST90006927
GCST90006928
GCST90006929
GCST90006987
GCST90006988
GCST90006989
GCST90006990
GCST90006991
GCST90006992
GCST90006993
GCST90006994
GCST90006995
GCST90006996
GCST90006997
GCST90006998
GCST90006999
GCST90007000
GCST90007001
GCST90007002
GCST90007003
GCST90007004
GCST90007005
GCST90007006
GCST90007007
GCST90007008
GCST90007009
GCST90007010
GCST90007011
GCST90007012
GCST010819
GCST010818
GCST010817
GCST010816
GCST90007181
GCST90007182
GCST90007183
GCST90007184
GCST90007185
GCST90007186
GCST90007187
GCST90007188
GCST90007189
GCST90007190
GCST90007191
GCST90007192
GCST90007193
GCST90007194
GCST90007195
GCST90007196
GCST90007197
GCST90007198
GCST90007199
GCST90007200
GCST90007201
GCST90007202
GCST90007203
GCST90007204
GCST90007205
GCST90007206
GCST90007207
GCST90007208
GCST90007209
GCST90007210
GCST90007211
GCST90007212
GCST90007213
GCST90007214
GCST90007215
GCST90007216
GCST90007217
GCST90007218
GCST90007219
GCST90007220
GCST90007221
GCST90007222
GCST90007223
GCST90007224
GCST90007225
GCST90007226
GCST90007227
GCST90007228
GCST90007229
GCST90007230
GCST90007231
GCST90007232
GCST90007233
GCST90007234
GCST90007235
GCST90007236
GCST90007237
GCST90007238
GCST90007239
GCST90007240
GCST90007241
GCST90007242
GCST90007243
GCST90007244
GCST90007245
GCST90007246
GCST90007247
GCST90007248
GCST90007249
GCST90007250
GCST90007251
GCST90007252
GCST90007253
GCST90007254
GCST90007255
GCST90007256
GCST90007257
GCST90007258
GCST90007259
GCST90007260
GCST90007261
GCST90007262
GCST90007263
GCST90007264
GCST90007265
GCST90007266
GCST90007267
GCST90007268
GCST90007269
GCST90007270
GCST90007271
GCST90007272
GCST90007273
GCST90007274
GCST90007275
GCST90007276
GCST90007277
GCST90007278
GCST90007279
GCST90007280
GCST90007281
GCST90007282
GCST90007283
GCST90007284
GCST90007285
GCST90007286
GCST90007287
GCST90007288
GCST90007289
GCST90007290
GCST90007291
GCST90007292
GCST90007293
GCST90007294
GCST90007295
GCST90007296
GCST90007297
GCST90007298
GCST90007299
GCST90007300
GCST90007301
GCST90007302
GCST90007303
GCST90007304
GCST90007305
GCST90007306
GCST90010148
GCST90010149
GCST90010150
GCST90010151
GCST90010152
GCST90010153
GCST90010154
GCST90010155
GCST90010156
GCST90010157
GCST90010158
GCST90010159
GCST90010160
GCST90010161
GCST90010162
GCST90010163
GCST90010164
GCST90010165
GCST90010166
GCST90010167
GCST90010168
GCST90010169
GCST90010170
GCST90010171
GCST90010172
GCST90010173
GCST90010174
GCST90010175
GCST90010176
GCST90010177
GCST90010178
GCST90010179
GCST90010180
GCST90010181
GCST90010182
GCST90010183
GCST90010184
GCST90010185
GCST90010186
GCST90010187
GCST90010188
GCST90010189
GCST90010190
GCST90010191
GCST90010192
GCST90010193
GCST90010194
GCST90010195
GCST90010196
GCST90010197
GCST90010198
GCST90010199
GCST90010200
GCST90010201
GCST90010202
GCST90010203
GCST90010204
GCST90010205
GCST90010206
GCST90010207
GCST90010208
GCST90010209
GCST90010210
GCST90010211
GCST90010212
GCST90010213
GCST90010214
GCST90010215
GCST90010216
GCST90010217
GCST90010218
GCST90010219
GCST90010220
GCST90010221
GCST90010222
GCST90010223
GCST90010224
GCST90010225
GCST90010226
GCST90010227
GCST90010228
GCST90010229
GCST90010230
GCST90010231
GCST90010232
GCST90010233
GCST90010234
GCST90010235
GCST90010236
GCST90010237
GCST90010238
GCST90010239
GCST90010240
GCST90010241
GCST90010242
GCST90010243
GCST90010244
GCST90010245
GCST90010246
GCST90010247
GCST90010248
GCST90010249
GCST90010250
GCST90010251
GCST90010252
GCST90010253
GCST90010254
GCST90010255
GCST90010256
GCST90010257
GCST90010258
GCST90010259
GCST90010260
GCST90010261
GCST90010262
GCST90010263
GCST90010264
GCST90010265
GCST90010266
GCST90010267
GCST90010268
GCST90010269
GCST90010270
GCST90010271
GCST90010272
GCST90010273
GCST90010274
GCST90010275
GCST90010276
GCST90010277
GCST90010278
GCST90010279
GCST90010280
GCST90010281
GCST90010282
GCST90010283
GCST90010284
GCST90010285
GCST90010286
GCST90010287
GCST90010288
GCST90010289
GCST90010290
GCST90010291
GCST90010292
GCST90010293
GCST90010294
GCST90010295
GCST90010296
GCST90010297
GCST90010298
GCST90010299
GCST90010300
GCST90010301
GCST90010302
GCST90010303
GCST90010304
GCST90010305
GCST90010306
GCST90010307
GCST90010308
GCST90010309
GCST90010310
GCST90010311
GCST90010312
GCST90010313
GCST90010314
GCST90010315
GCST90010316
GCST90010317
GCST90010318
GCST90010319
GCST90010320
GCST90010321
GCST90010322
GCST90010323
GCST90010324
GCST90010325
GCST90010326
GCST90010327
GCST90010328
GCST90010329
GCST90010330
GCST90010331
GCST90010332
GCST90010333
GCST90010334
GCST90010335
GCST90010336
GCST90010337
GCST90010338
GCST90010339
GCST90010340
GCST90010341
GCST90010342
GCST90010343
GCST90010344
GCST90010345
GCST90010346
GCST90010347
GCST90010348
GCST90010349
GCST90010350
GCST90010351
GCST90010352
GCST90010353
GCST90010354
GCST90010355
GCST90010356
GCST90010357
GCST90010358
GCST90010102
GCST90010103
GCST90010104
GCST90010105
GCST90010106
GCST90010107
GCST90010108
GCST90010109
GCST90010110
GCST90010111
GCST90010112
GCST90010113
GCST90010114
GCST90010115
GCST90010116
GCST90010117
GCST90010118
GCST90010119
GCST90010120
GCST90010121
GCST90010122
GCST90010123
GCST90010124
GCST90010125
GCST90010126
GCST90010127
GCST90010128
GCST90010129
GCST90010130
GCST90010131
GCST90010132
GCST90010133
GCST90010134
GCST90010135
GCST90010136
GCST90010137
GCST90010138
GCST90010139
GCST90010140
GCST90010141
GCST90010142
GCST90010143
GCST90010144
GCST90010145
GCST90010146
GCST90010147
GCST90010722
GCST90010723
GCST90010724
GCST90010725
GCST90010726
GCST90010727
GCST90010728
GCST90010729
GCST90010730
GCST90010731
GCST90010732
GCST90010733
GCST90010734
GCST90010735
GCST90010736
GCST90010737
GCST90010738
GCST90010739
GCST90010740
GCST90010741
GCST90010742
GCST90010743
GCST90010744
GCST90010745
GCST90010746
GCST90010747
GCST90010748
GCST90010749
GCST90010750
GCST90010751
GCST90010752
GCST90010753
GCST90010754
GCST90010755
GCST90010756
GCST90010757
GCST90010758
GCST90010759
GCST90010760
GCST90010761
GCST90010762
GCST90010763
GCST90010764
GCST90010765
GCST90010766
GCST90010767
GCST90010768
GCST90010769
GCST90010770
GCST90010771
GCST90010772
GCST90010773
GCST90010774
GCST90010775
GCST90010776
GCST90010777
GCST90010778
GCST90010779
GCST90010780
GCST90010781
GCST90010782
GCST90010783
GCST90010784
GCST90010785
GCST90010786
GCST90010787
GCST90010788
GCST90010789
GCST90010790
GCST90010791
GCST90010792
GCST90010793
GCST90010794
GCST90010795
GCST90010796
GCST90010797
GCST90010798
GCST90010799
GCST90010800
GCST90010801
GCST90010802
GCST90010803
GCST90010804
GCST90010805
GCST90010806
GCST90010807
GCST90010808
GCST90010809
GCST90010810
GCST90010811
GCST90010812
GCST90010813
GCST90010814
GCST90010815
GCST90010816
GCST90010817
GCST90010818
GCST90010819
GCST90010820
GCST90010821
GCST90010822
GCST90010823
GCST90010824
GCST90010825
GCST90010826
GCST90010827
GCST90010828
GCST90010829
GCST90010830
GCST90010831
GCST90010832
GCST90010833
GCST90010834
GCST90010835
GCST90010836
GCST90010837
GCST90010838
GCST90010839
GCST90010840
GCST90010841
GCST90010842
GCST90010843
GCST90010844
GCST90010845
GCST90010846
GCST90010847
GCST90010848
GCST90010849
GCST90010850
GCST90010851
GCST90010852
GCST90010853
GCST90010854
GCST90010855
GCST90010856
GCST90010857
GCST90010858
GCST90010859
GCST90010860
GCST90010861
GCST90010862
GCST90011874
GCST90011875
GCST90011350
GCST90011351
GCST90011352
GCST90011353
GCST90011354
GCST90011355
GCST90011356
GCST90011357
GCST90011358
GCST90011359
GCST90011360
GCST90011361
GCST90011362
GCST90011363
GCST90011364
GCST90011365
GCST90011366
GCST90011367
GCST90011368
GCST90011369
GCST90011370
GCST90011371
GCST90011372
GCST90011373
GCST90011374
GCST90011375
GCST90011376
GCST90011377
GCST90011378
GCST90011379
GCST90011380
GCST90011381
GCST90011382
GCST90011383
GCST90011384
GCST90011385
GCST90011386
GCST90011387
GCST90011388
GCST90011389
GCST90011390
GCST90011391
GCST90011392
GCST90011393
GCST90011394
GCST90011395
GCST90011396
GCST90011397
GCST90011398
GCST90011399
GCST90011400
GCST90011401
GCST90011402
GCST90011403
GCST90011404
GCST90011405
GCST90011406
GCST90011407
GCST90011408
GCST90011409
GCST90011410
GCST90011411
GCST90011412
GCST90011413
GCST90011414
GCST90011415
GCST90011416
GCST90011417
GCST90011418
GCST90011419
GCST90011420
GCST90011421
GCST90011422
GCST90011423
GCST90011424
GCST90011425
GCST90011426
GCST90011427
GCST90011428
GCST90011429
GCST90011430
GCST90011431
GCST90011432
GCST90011433
GCST90011434
GCST90011435
GCST90011436
GCST90011437
GCST90011438
GCST90011439
GCST90011440
GCST90011441
GCST90011442
GCST90011443
GCST90011444
GCST90011445
GCST90011446
GCST90011481
GCST90011447
GCST90011448
GCST90011449
GCST90011450
GCST90011451
GCST90011452
GCST90011453
GCST90011454
GCST90011455
GCST90011456
GCST90011457
GCST90011458
GCST90011459
GCST90011460
GCST90011461
GCST90011462
GCST90011463
GCST90011464
GCST90011465
GCST90011466
GCST90011467
GCST90011468
GCST90011469
GCST90011470
GCST90011471
GCST90011472
GCST90011473
GCST90011474
GCST90011475
GCST90011476
GCST90011477
GCST90011478
GCST90011479
GCST90011480
GCST90011482
GCST90011483
GCST90011484
GCST90011485
GCST90011486
GCST90011487
GCST90011488
GCST90011489
GCST90011490
GCST90011491
GCST90011492
GCST90011493
GCST90011494
GCST90011495
GCST90011496
GCST90011497
GCST90011498
GCST90011499
GCST90011500
GCST90011501
GCST90011502
GCST90011503
GCST90011504
GCST90011505
GCST90011506
GCST90011507
GCST90011508
GCST90011509
GCST90011510
GCST90011511
GCST90011512
GCST90011513
GCST90011514
GCST90011515
GCST90011516
GCST90011517
GCST90011518
GCST90011519
GCST90011520
GCST90011521
GCST90011522
GCST90011523
GCST90011524
GCST90011525
GCST90011526
GCST90011527
GCST90011528
GCST90011529
GCST90011530
GCST90011531
GCST90011532
GCST90011533
GCST90011534
GCST90011535
GCST90011536
GCST90011537
GCST90011538
GCST90011539
GCST90011540
GCST90011541
GCST90011542
GCST90011543
GCST90011544
GCST90011545
GCST90011546
GCST90011547
GCST90011548
GCST90011549
GCST90011550
GCST90011551
GCST90011552
GCST90011553
GCST90011554
GCST90011555
GCST90011556
GCST90011557
GCST90011558
GCST90011559
GCST90011560
GCST90011561
GCST90011562
GCST90011563
GCST90011564
GCST90011565
GCST90011566
GCST90011567
GCST90011568
GCST90011569
GCST90011570
GCST90011571
GCST90011572
GCST90011573
GCST90011653
GCST90011574
GCST90011575
GCST90011576
GCST90011577
GCST90011578
GCST90011579
GCST90011580
GCST90011581
GCST90011582
GCST90011583
GCST90011584
GCST90011585
GCST90011586
GCST90011587
GCST90011588
GCST90011589
GCST90011590
GCST90011591
GCST90011592
GCST90011593
GCST90011594
GCST90011595
GCST90011596
GCST90011597
GCST90011598
GCST90011599
GCST90011600
GCST90011601
GCST90011602
GCST90011603
GCST90011604
GCST90011605
GCST90011606
GCST90011607
GCST90011608
GCST90011609
GCST90011610
GCST90011611
GCST90011612
GCST90011613
GCST90011614
GCST90011615
GCST90011616
GCST90011617
GCST90011618
GCST90011619
GCST90011620
GCST90011621
GCST90011622
GCST90011623
GCST90011624
GCST90011625
GCST90011626
GCST90011627
GCST90011628
GCST90011629
GCST90011630
GCST90011631
GCST90011632
GCST90011633
GCST90011634
GCST90011635
GCST90011636
GCST90011637
GCST90011638
GCST90011639
GCST90011640
GCST90011641
GCST90011642
GCST90011643
GCST90011644
GCST90011645
GCST90011646
GCST90011647
GCST90011648
GCST90011649
GCST90011650
GCST90011651
GCST90011652
GCST90011654
GCST90011655
GCST90011656
GCST90011657
GCST90011658
GCST90011659
GCST90011660
GCST90011661
GCST90011662
GCST90011663
GCST90011664
GCST90011665
GCST90011666
GCST90011667
GCST90011668
GCST90011669
GCST90011670
GCST90011671
GCST90011672
GCST90011673
GCST90011674
GCST90011675
GCST90011676
GCST90011677
GCST90011678
GCST90011679
GCST90011680
GCST90011681
GCST90011682
GCST90011683
GCST90011684
GCST90011685
GCST90011686
GCST90011687
GCST90011688
GCST90011689
GCST90011690
GCST90011691
GCST90011692
GCST90011693
GCST90011301
GCST90011302
GCST90011303
GCST90011304
GCST90011305
GCST90011306
GCST90011307
GCST90011308
GCST90011309
GCST90011310
GCST90011311
GCST90011312
GCST90011313
GCST90011314
GCST90011315
GCST90011316
GCST90011317
GCST90011318
GCST90011319
GCST90011320
GCST90011321
GCST90011322
GCST90011323
GCST90011324
GCST90011325
GCST90011326
GCST90011327
GCST90011328
GCST90011329
GCST90011330
GCST90011331
GCST90011332
GCST90011333
GCST90011334
GCST90011335
GCST90011336
GCST90011337
GCST90011338
GCST90011339
GCST90011340
GCST90011341
GCST90011342
GCST90011343
GCST90011344
GCST90011345
GCST90011346
GCST90011347
GCST90011348
GCST90011349
GCST90011694
GCST90011695
GCST90011696
GCST90011697
GCST90011698
GCST90011699
GCST90011700
GCST90011701
GCST90011702
GCST90011703
GCST90011704
GCST90011705
GCST90011706
GCST90011707
GCST90011708
GCST90011709
GCST90011710
GCST90011711
GCST90011712
GCST90011713
GCST90011714
GCST90011715
GCST90011716
GCST90011717
GCST90011718
GCST90011719
GCST90011720
GCST90011721
GCST90011722
GCST90011723
GCST90011724
GCST90011725
GCST90011726
GCST90011727
GCST90011728
GCST90011729
GCST90011730
GCST90007526
GCST90007527
GCST90007528
GCST90007529
GCST90007530
GCST90007531
GCST90011866
GCST011097
GCST011096
GCST90011898
GCST90011899
GCST90011900
GCST90011787
GCST90011773
GCST90011774
GCST90011775
GCST90011776
GCST90011777
GCST90011778
GCST90011779
GCST90011780
GCST90011781
GCST90011782
GCST90011783
GCST90011784
GCST90011785
GCST90011786
GCST90011788
GCST90011789
GCST90011790
GCST90011791
GCST90011792
GCST90011793
GCST90011794
GCST90011795
GCST90011796
GCST90011797
GCST90011798
GCST90011799
GCST90011800
GCST90012877
GCST90012878
GCST90001390

**Comment by jdhayhurst** [comment]
![image.png](https://images.zenhubusercontent.com/5e57db4a23eb16cef275ef41/829053a9-7738-4d93-8709-534cdde4dc7b)

**Comment by jdhayhurst** [comment]
Mostly complete and release with exception of:

```
28011712-GCST003922-EFO_0002508-Build37.tsv
32242144-GCST90000614-EFO_0004631-Build37.tsv
32242144-GCST90000617-EFO_0004631-Build37.tsv
32242144-GCST90000618-EFO_0004631-Build37.tsv
32298765-GCST90011885-EFO_0003095-Build37.tsv
33113361-GCST90013429-EFO_0000253-Build37.tsv
33283231-GCST90013540-EFO_0005116-Build37.tsv
33288918-GCST90007208-EFO_0007841-Build37.tsv
33288918-GCST90007236-EFO_0007841-Build37.tsv
33288918-GCST90007263-EFO_0007843-Build37.tsv
33288918-GCST90007281-EFO_0007845-Build37.tsv
33288918-GCST90007293-EFO_0010948-Build37.tsv
33303764-GCST90010320-EFO_0007937-Build38.tsv
33303764-GCST90010346-EFO_0007937-Build38.tsv```

**Comment by jdhayhurst** [comment]
fixed and requeued
