### ISSUE TITLE
Validation SumStats once deposition app is back up

### ISSUE THREAD

**Issue by mcerezof** [EBISPOT/goci#38]
This is a reminder to validate SumStats submitted by Matthew Sampson
For the study with PMID: 29903748
The submission ID is 5e613a18b8b8fd000143a5a2

**Comment by tudorgroza** [comment]
I have checked the submission and the backend only contains the empty SS template file. It seems like the user has not filled in the template and submitted it. As a result, the submission is still in `STARTED`.

**Comment by jdhayhurst** [comment]
Checked the ftp server and the files are there but not gzipped. The checksums provided are for gzip files and do no match the checksums of the files even if I gzip them.
