### ISSUE TITLE
Sumstats submission with very small p-values won't pass validation

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#380]
Sumstats fail validation due to very small p-values. Please push through. 

https://www.ebi.ac.uk/gwas/deposition/submission/6012aa320164810001f5c9ca

**Comment by jdhayhurst** [comment]
Hi @earlEBI this is released so it is possible. Any number between > 0 and and < 1 will now pass, including numbers in scientific notation that exceed system limits.
