### ISSUE TITLE
Greater Middle Eastern ancestry category is not imported into curation app from submission template

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#383]
Greater Middle Eastern ancestry category is not imported into curation app from submission template, but it should be added to list of ancestry categories upon import.
 
![Screenshot 2021-03-03 at 13.27.49.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/f5d214f1-eb2c-43c3-96e3-d2a53198e3a8)

**Comment by sprintell** [comment]
Lizzy tested thids, there was a problem in sandbox, @ala-ebi  is looking at it

**Comment by ljwh2** [comment]
Release held up pending Yomi changes - @ala-ebi  to create custom branch to release

**Comment by ljwh2** [comment]
Release held up pending Yomi changes - @ala-ebi  to create custom branch to release

**Comment by ala-ebi** [comment]
release done
