### ISSUE TITLE
Scripts to convert VCF to TSV format (GWAS and OTAR)

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#385]
the openGWAS/MRBase teams have shared >20 cancer GWAS summary statistics in VCF format. Scripts to convert VCFs to TSVs format are needed to process these datasets for integration into the GWAS Catalog and Open Targets Genetics databases.

Example VCF file preanalysis/buniello/ieu-b-94.vcf

**Comment by jdhayhurst** [comment]
Written and deployed to gwas server: `custom_formatters/gwasvcf2tsv.py`

usage:
`gwasvcf2tsv.py -f <gwas vcf file name>`

What the next step @buniello?

**Comment by buniello** [comment]
Thank you @jdhayhurst. Next week, i'll start processing the MRbase vcfs and will create submissions for the converted data.
Does the script work for -dir (all files in a dir)?

**Comment by jdhayhurst** [comment]
I haven't created an option for processing multiple files at once - let me add that feature in. If we do that, we'll need to make it so that it processes each file as a separate job on the cluster as well to make it efficient.

**Comment by jdhayhurst** [comment]
@buniello I've made the changes.
Usage notes:

login to cluster as usual then
```
format_task
vcf2tsv -f <vcf file>
```
To process multiple files use a wildcard e.g. to process both file1.vcf.gz and file2.vcf.gz you can do:
```
vcf2tsv -f file*.vcf.gz
```
This will create two jobs on the cluster that run in the background and you'll be emailed when they're complete.

**Comment by buniello** [comment]
Thank you @jdhayhurst. I Will start processing the files on Monday and will let you know how it goes.

**Comment by buniello** [comment]
@jdhayhurst I have tested the script (including functionality on multiple files ) and everything works as expected. 
Will now start using it systematically on the MR base files for integration in the Catalog.

**Comment by jdhayhurst** [comment]
Added a block to handle string and bytes when reading the vcf
