### ISSUE TITLE
COVID-19 data to process upon OTAR prioritisation

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#386]
OTAR prioritised these COVID-19 data for harmonisation: https://omicscience.org/apps/covidpgwas/. 
These results are presented in a single file of 1871196377 rows. The file contains results for 106 proteins, all defined by a code in one of the columns (header: somamer). All info on somamer protein codes are on the website. Formatting is not straightforward for Annalisa (cannot be processed with the current formatting tool).

**Comment by jdhayhurst** [comment]
@buniello I've split by the somamer column into 106 different files. e.g.
```
$ head Pietzner2020-10419_1.tsv
1	10177	rs367896724	chr1:10177_D_I	d	i	0.6204	0.0029	0.6135	0.6219	10419_1	0.0229	0.0154	0.1379	+-+	38.3	3.241	2	0.1978	10708
1	10352	rs555500075	chr1:10352_D_I	d	i	0.6227	0.0017	0.6191	0.6236	10419_1	-0.0011	0.0157	0.9438	+-+	28.3	2.789	2	0.248	10708
1	10511	rs534229142	chr1:10511_A_G	a	g	0.0015	0.0000	0.0015	0.0015	10419_1	0.2733	0.2420	0.2587	+??	0.0	0.000	0	1	8350
1	10616	rs376342519	chr1:10616_D_I	d	i	0.9933	0.0010	0.9910	0.9938	10419_1	-0.0391	0.0978	0.6891	+--	0.0	0.959	2	0.6191	10708
1	11008	rs575272151	chr1:11008_C_G	c	g	0.9147	0.0033	0.9130	0.9213	10419_1	-0.0020	0.0266	0.9405	+--	40.5	3.360	2	0.1864	10708
1	11012	rs544419019	chr1:11012_C_G	c	g	0.9165	0.0021	0.9154	0.9215	10419_1	-0.0065	0.0270	0.8101	+--	62.4	5.315	2	0.07012	10708
1	13110	rs540538026	chr1:13110_A_G	a	g	0.0563	0.0029	0.0490	0.0577	10419_1	-0.0008	0.0333	0.9811	-++	0.0	0.806	2	0.6683	10708
1	13116	rs62635286	chr1:13116_G_T	t	g	0.8213	0.0031	0.8199	0.8305	10419_1	-0.0146	0.0200	0.4666	--+	0.0	0.502	2	0.7779	10708
1	13118	rs200579949	chr1:13118_A_G	a	g	0.8157	0.0020	0.8134	0.8214	10419_1	-0.0011	0.0197	0.9556	--+	0.0	0.396	2	0.8203	10708
1	13273	rs531730856	chr1:13273_C_G	c	g	0.1317	0.0005	0.1305	0.1320	10419_1	-0.0074	0.0229	0.7481	+--	0.0	0.932	2	0.6275	10708
```
The header is here: 
```
chr     pos     rsid    MarkerName      Allele1 Allele2 Freq1   FreqSE  MinFreq MaxFreq Somamer Effect  StdErr  Pvalue Direction        HetISq  HetChiSq        HetDf   HetPVal TotalSampleSize
```

2 questions:
1) Please can you convert the above to the standard headers? I'll then add that to all the files.
2) What should we do with the indels? They've used "i" and "d" - I would suggest replacing these allele values with NA, but let me know your thoughts.

**Comment by buniello** [comment]
Thank you @jdhayhurst.

1. headers below, the ones I have not converted will be dropped in final standard files
chr: chromosome     
pos: bp    
rsid:  variant_id
MarkerName
Allele1: effect_allele
Allele2: other_allele 
Freq1 : eaf
FreqSE: 
MinFreq
MaxFreq
Somamer 
Effect: beta 
StdErr: se  
Pvalue: pvalue 
Direction 
HetISq  
HetChiSq
HetDf   
HetPVal 
TotalSampleSize: N

2. Yes, agree with NA for the "i" and "d" allele values for the indels

**Comment by jdhayhurst** [comment]
formatting...

**Comment by jdhayhurst** [comment]
pmid 33328453

**Comment by jdhayhurst** [comment]
effect and se missing from harmonised data - investigate why

**Comment by jdhayhurst** [comment]
Non-issue - effect and SE are present
