### ISSUE TITLE
Studies with status "scientific pilot" should be visible in deposition app

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#393]
Currently, studies with status "scientific pilot" are not currently findable in the deposition app. Submitters need to have access to these studies. This will allow submissions of whole genome sequencing data (not eligible for the main curation pipeline). 

The visibility of other statuses in the deposition app should not change.

**Comment by ala-ebi** [comment]
if no studies associated with the publication are published, and there are some in Scientific Pilot => publication: OPEN FOR SUBMISSION
behaviour remains the same for the rest.

**Comment by ljwh2** [comment]
Close ticket when I have added some new studies

**Comment by Santhi1901** [comment]
tested with some studies and those PMIDs were findable in the deposition app
