### ISSUE TITLE
download filtered list of studies from curation app

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/goci#394]
This is a feature request for a way to download a list of high level study meta-data from the curation app.

The use case is a curator filtering the studies in the curation system using the functions on the 'curation home' page (https://www.ebi.ac.uk/gwas/curation/studies?page=1), and being able to download (e.g. csv format) all the results returned.  The download should include all the fields visible in the curation home page (e.g. author, title, curator, status, notes etc.) AND GCST (which is not currently visible).

My primary use case is searching the notes (using the 'search notes' search box) for a specific term. I then want to examine the returned studies more closely.

Ideally there would be a download button, similar to the one on the main UI.  But a script-based method would also be workable.

**Comment by sprintell** [comment]
@aoifemcm , can you please test the filter study list export in snoopy, its ready for testing : http://snoopy.ebi.ac.uk:9680/gwas/curation/studies?page=1&notesquery=PGS

**Comment by sprintell** [comment]
@ljwh2 and @aoifemcm , I will also like to know if there will be a use case requiring you to export all the studies i.e without applying any filter, thats going to be a huge list of over 10,000 records, and such large request will take some length of time to deliver, I just pegged the maximum downloadable rows to 1000 rows at the moment. 

You can let me know if there might be need to download all 11,000+ studies, I will open up the limit, but I will need to implement multithreading enhancement on the query to make it faster

**Comment by ljwh2** [comment]
@sprintell I think it is fine to release with 1000 row limit. The functionality works fine for me, @aoifemcm please confirm?
