### ISSUE TITLE
Failed import of Woori Kim, PMID 33106845

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#397]
User was in contact with us firstly due to Globus ID issue and then for help validating sumstats file. 

Import to Curation App failed on 12.04.21. 

Submission does not appear to have gone through metadata validation. 
There is no button to see accession ID. 
https://www.ebi.ac.uk/gwas/deposition/submission/603e752f0164810001f50e64

Submission template:
[https://app.zenhub.com/files/2995118/775e54ba-f191-4fdb-94db-4cd36a18bf5b/download](https://app.zenhub.com/files/2995118/775e54ba-f191-4fdb-94db-4cd36a18bf5b/download)

**Comment by ala-ebi** [comment]
The issue is this submission is being treated (on the curation side) as a sumstats only submission. The reason behind it is that the Publication is in an ELIGIBLE status (OPEN FOR SUBMISSION), when it should be CLOSED.

**Comment by ala-ebi** [comment]
We'll wait and see if the user comes back to us, then we'll act.
