### ISSUE TITLE
The search queries for EFO_0004747 (protein measurement) and "cancer" do not load

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#401]
The search query for EFO_0004747 (protein measurement) does not load, probably due to the big number of data mapped to this term.
From gwas-info from Sofie ten Brink on 15/04/21
https://www.ebi.ac.uk/gwas/efotraits/EFO_0004747

The search query for "cancer" does not load, probably due to the big number of child terms.
From gwas-info from rjanivara3@gatech.edu on 4/05/21

**Comment by ljwh2** [comment]
This likely due to number of child terms, can be rolled in with future work to optimise web page loading

**Comment by jdhayhurst** [comment]
also https://www.ebi.ac.uk/gwas/efotraits/EFO_0005278

**Comment by ljwh2** [comment]
fixed in new UI
