### ISSUE TITLE
Users need access to usage license info

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#406]
Users need access to a list of summary stats indicating which are made available under CC0 license of terms of use. This should be included as an optional column in the summary statistics tables, unchecked by default (same as ftp path in the first table) https://www.ebi.ac.uk/gwas/downloads/summary-statistics

**Comment by sajo-ebi** [comment]
Identified the changes that need to be made but the Dev instance of Solr doesn't have the CC0 field , need to add the same to Dev Solr instance & load data in order to be able to deploy in Dev & test

**Comment by sajo-ebi** [comment]
@ljwh2 the column should be included for both published & unpublished studies summary stats table ?

**Comment by ljwh2** [comment]
yes both @sajo-ebi

**Comment by sajo-ebi** [comment]
@ljwh2 Changes have been deployed in Dev2 Snoopy. Kindly validate the same

**Comment by ljwh2** [comment]
@sajo-ebi Changes look good for far. 

I noticed in the header we have "These data are made available through EMBL-EBI’s standard terms of use". Please could you change this to
"These data are made available either through CC0 [https://creativecommons.org/publicdomain/zero/1.0/], or EMBL-EBI’s standard terms of use [http://www.ebi.ac.uk/about/terms-of-use/], more details can be found here [link to FAQ H7]. For licensing information of individual studies, please reveal "Usage License" column."

If possible, could the text in the table also link to the CC0 page https://creativecommons.org/publicdomain/zero/1.0/ or EBI terms of use http://www.ebi.ac.uk/about/terms-of-use/ as appropriate.

**Comment by sajo-ebi** [comment]
@ljwh2 Can you clarify on the below ? What is the link to FAQ mentioned below , where can I find the exact link?

more details can be found here **[link to FAQ H7]**

**Comment by ljwh2** [comment]
@sajo-ebi yes that's correct

**Comment by sajo-ebi** [comment]
@ljwh2 deployed the changes in snoopy Dev2 , kindly validate & confirm

**Comment by ljwh2** [comment]
@sajo-ebi The text for EBI terms of use could be shortened to "EBI terms of use", otherwise ready to release.

**Comment by sajo-ebi** [comment]
@ljwh2 have shortened the message & deployed.
