### ISSUE TITLE
Changes to documentation ready for next release

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#411]
Added link to the recent webinar on the Related Resources page (in documentation branch): https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/related-resources-content.adoc

Checked changes on snoopy and looks good, link works. Ready for release to production.

Just creating ticket for tracking to make sure this is included at next release.

**Comment by buniello** [comment]
Also updated the Related Resources page with link to latest blog posts and webinars

**Comment by eks-ebi** [comment]
Also updated the Submission page to clarify how to access GCSTs and study-specific sumstats folders on the FTP:
https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/submission-content.adoc

**Comment by eks-ebi** [comment]
Further edits sequencing studies section on Inclusion Criteria page also ready for release:
https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/methods/criteria-content.adoc

**Comment by eks-ebi** [comment]
Also some edits to the FAQ page to clarify sequencing study eligibility:
https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/faq-content.adoc
