### ISSUE TITLE
Curators need to access ancestry information from the curation queue in bulk

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#412]
Occasionally curators need access to sample information for all studies in the curation queue. There is currently a script available to curators for summarising information from the queue, but it does not include sample info - the first script on this page: https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=GOCI&title=GWAS+Curation+Utility+Scripts

The desired output is the same as this script, but with additional columns INITIAL SAMPLE DESCRIPTION and REPLICATION SAMPLE DESCRIPTION

**Comment by jdhayhurst** [comment]
@ljwh2 and @Santhi1901 I've made the changes - if you run the script as the [confluence page](https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=GOCI&title=GWAS+Curation+Utility+Scripts) says - can you let me know if this fulfils your request?

**Comment by Santhi1901** [comment]
@jdhayhurst, @ljwh2 yes it has the required information

**Comment by jdhayhurst** [comment]
Thanks @Santhi1901 - I'lll close this ticket
