### ISSUE TITLE
Dormant submission reverts to "closed" status. Should be "open". 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#415]
Received e-mail notifying submission had been dormant for 30 days and would be removed: 
![Screenshot 2021-05-27 at 11.22.51.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/ab292122-f13e-4ab4-9fab-86c97b456763)

Issue 1: 
The hyperlinks in the email are not accessible off VPN: http://193.62.54.159/gwas/deposition/submission/6063239a37158e000124e0de

Issue 2: 
The submission status should revert to 'Open'. 
![Screenshot 2021-05-27 at 11.27.45.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/74d071b0-4192-4919-8095-ee58e370b682)

Please revert the status of this PMID (33462484) back to 'open for submission'.

**Comment by ala-ebi** [comment]
submission unarchived for now, the rest is TODO

**Comment by ala-ebi** [comment]
dormant SS only submission => publication reverts to 'Open for SS submission'
dormant metadata or metadata + SS submission => publication reverts to 'Open for submission'
no changes for GCP behaviour
