### ISSUE TITLE
Bulk downloading and formatting >200 vcfs from OpenGWAS - prioritised for harmonisation by OTAR 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#418]
The files can be accessed from here: https://gwas.mrcieu.ac.uk/datasets/?gwas_id__icontains=met-d

Bulk download instructions here: https://gwas.mrcieu.ac.uk/about/#bulk-downloads

Upon download, @buniello will proceed with the vcf to tsv processing.

**Comment by buniello** [comment]
Thank you for bulk downloading these vcfs @jdhayhurst. I have converted them all into the EBI-GWAS tsv format.
They are in preanalysis/buniello/metd_formatted - ready for harmonisation and handling to Mohd.
These will not be made available in the GWAS catalog for now - I am in communications with the authors.

**Comment by jdhayhurst** [comment]
queued for harmonisation

**Comment by jdhayhurst** [comment]
completed and sent to otar
