### ISSUE TITLE
Create a blog page on the GWAS Catalog website

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#424]

**Comment by ljwh2** [comment]
The GWAS Catalog needs a blog page to describe upcoming changes such as the background traits annotation. This should allow text and images, and an archive of previous blog posts. It should be linked from the homepage in the "we'd love to hear from you" section at the bottom and from the menu bar at the top.

**Comment by sprintell** [comment]
The blog page is hosted in github here at the moment: 

https://ebispot.github.io/gwas-blog/background-trait-update

Other old blogs have also been archived here: https://ebispot.github.io/gwas-blog

@ala-ebi can help link to it from the homepage as required

Other enhancements will be iteratively added to the blog system in future
