### ISSUE TITLE
All publications without sumstats should have 'open for summary statistics submission' status

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#433]
Currently, submissions created through the Deposition app and then published in the Catalog remain closed for future sumstats submission. 

All publications without sumstats should be 'open for summary statistics submission', regardless of whether a previous submission for metadata-only was made.

**Comment by ala-ebi** [comment]
Should be all _published_ studies' publication should be open for SS right?

**Comment by earlEBI** [comment]
Yes

**Comment by ala-ebi** [comment]
made changes to sync process. it usually ignores UNDER_SUBMISSION publications, I have changed that to only ignore if (UNDER_SUBMISSION AND (HAS_SS OR IS_NOT_PUBLISHED)), that way under submission, published studies that don't have SS can get synced.

**Comment by ala-ebi** [comment]
Requires Review study crashes the import process for SS only submissions cause it doesn't have GCST. Added a condition to ignore studies without GCST on import/sync.

**Comment by ala-ebi** [comment]
import works, few inconsistencies on SS file names reported by Lizzy, will have to confirm with james if moving files to FTP works for dev env.

**Comment by ljwh2** [comment]
@Santhi1901 reported that this is still a problem - publications curated through the submission app are not open for sumstats submisson
