### ISSUE TITLE
Intermediate published/unpublished state for 6 studies in PMID 34006833

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#437]
When I have unpublished/republished 8 entries for PMID 34006833 https://www.ebi.ac.uk/gwas/curation/publication/34006833 (to untick sumstats tick box), 6 of them have entered an intermediate published/unpublished status:
![Screenshot 2021-07-13 at 10.20.40.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/3ff0ccd7-47de-494f-acc6-1cf58ccf9c4d)

https://www.ebi.ac.uk/gwas/curation/studies/80754553/housekeeping

From previous experience, we know that this status stops the entries to be released, and therefore the problem should ideally be fixed before the next data release.

**Comment by ljwh2** [comment]
@sajo-ebi check that this is fixed in DR
