### ISSUE TITLE
Re-harmonising file 24097068-GCST002222-EFO_0004611.f.tsv.gz to replace wrong one of the FTP and in OTAR genetics 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#456]
See user email for details (Zhana Kuncheva):

Dear GWAS Catalog team,

I am contacting you wrt to a dataset for which you have provided both the original summary statistics and the harmonized ones:

http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST002001-GCST003000/GCST002222

In using the harmonized results, we have identified that the harmonized file 24097068-GCST002222-EFO_0004611.h.tsv.gz 
has two identical variant positions with identical alleles and different p-values. (See result below)

hm_variant_id hm_rsid hm_chrom hm_pos hm_other_allele hm_effect_allele hm_beta hm_odds_ratio hm_ci_lower hm_ci_upper hm_effect_allele_frequency hm_code variant_id effect_allele other_allele beta standar
d_error n p_value eaf_ref chromosome base_pair_location ci_upper effect_allele_frequency odds_ratio ci_lower
19_19506847_G_A rs1054308 19 19506847 G A 0.0262 NA NA NA NA 12 rs1054308 t c 0.0262 0.0039 166119.00 3.039e-10 0.6834 19 19506847 NA NA NA NA
19_19506847_G_A rs1054308 19 19506847 G A 0.0229 NA NA NA NA 10 rs1054308 a g 0.0229 0.0115 83055.49 0.07511 0.04222 19 19506847 NA NA NA NA

However, when checking the corresponding rsID in the original file 24097068-GCST002222-EFO_0004611-build37.f.tsv.gz
we note that only one of the p-values has been captured by the rsID

rs1054308 a g 0.0229 0.0115 83055.49 0.07511 0.04222 chr19 19617656 NA NA NA NA

When we compare the result to the https://genetics.opentargets.org/variant/19_19506847_G_A it appears that the variant highlighted in yellow has been properly harmonized.
However, it is unclear where from is the other variant's p-values coming from. This is very alarming as the unhighlighted variant has a significant p-value and has been progressed as a top loci by the colocalisation analysis in open targets genetics. 

Could this be a bigger issue related to the harmonization process? 

--------------

AB comment

It looks to me that the wrong pvalue associated to rs1054308 in the duplication in the harmonised file belongs to rs377481857. 
rs377481857 is, in fact, missing on the harmonised file.

from formatted file: 
rs377481857	t	c	0.0262	0.0039	166119.00	3.039e-10	0.6834	chr19	19617655	NA	NA	NA	NA
rs1054308	a	g	0.0229	0.0115	83055.49	0.07511	0.04222	chr19	19617656	NA	NA	NA	NA

from harmonised file: 
19_19506847_G_A	rs1054308	19	19506847	G	A	0.0262	NA	NA	NA	NA	12	rs1054308	t	c	0.0262	0.0039	166119.00	3.039e-10	0.6834	19	19506847	NA	NA	NA	NA
19_19506847_G_A	rs1054308	19	19506847	G	A	0.0229	NA	NA	NA	NA	10	rs1054308	a	g	0.0229	0.0115	83055.49	0.07511	0.04222	19	19506847	NA	NA	NA	NA

**Comment by jdhayhurst** [comment]
This is the result of the OTAR harmonisation process, which uses the genomic location and alleles to orient the alleles to a reference. In this case there are two variants at that location in the reference:
```
19	19506846	rs377481857	TG	CA	.	.	dbSNP_151;TSA=substitution;E_Freq;E_Hapmap;AA=CG
19	19506847	rs1054308	G	A	.	.	dbSNP_151;TSA=SNV;E_Freq;E_1000G;E_TOPMed;E_gnomAD;MA=A;MAF=0.0684904;MAC=343;AA=G
```
In the sumstats, the alleles for rs377481857 were given as T and C. The harmoniser, looks at the above reference and checks for T and C. It can't find them. However, it also checks for the reverse compliments, A and G. Now it finds them - rs1054308. And so that is the harmonised variant. 

If we reharmonised it would give the same result. I don't know if this is strictly correct or not, but that is what the code does. To me it looks like the alleles for rs377481857 in the sumstats are incorrect, because rs377481857 describes a locus with TG or CA.

**Comment by buniello** [comment]
Thank you for looking into this @jdhayhurst, I will pass your comment to the user.
