### ISSUE TITLE
Adding a "summary statistics" column populated with y/n to the study download

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#457]
Adding a "summary statistics" column populated with y/n  to the "All studies v1.0.2"  download fill will allow curators to track the number of summary statistics added over time (not by publication date) in an efficient and less error-prone way.

At the moment, Annalisa tracks these numbers by comparing the study download (which includes a "date added to Catalog" column) to the summary statistics download with the command line; however, the amount of data we are ingesting at the moment is huge and performing this task is becoming challenging on the local machine.

**Comment by ljwh2** [comment]
A short term solution would be to add an endpoint and access this data via the REST API. Then we can plan to add a column to the download next time when we have a new version with other new columns, likely in the next 6months.

**Comment by jdhayhurst** [comment]
@buniello would it be possible to give me a list of fields that you need?

**Comment by buniello** [comment]
@jdhayhurst I was thinking about adding one column to the Catalog "All studies v1.0.2" download file. 
The header could be "has summary statistics" or just "summary statistics". The field will be populated with "yes" if that particular study/GCST has summary statistics in the Catalog and "no" if it hasn't.

**Comment by jdhayhurst** [comment]
script for merging the sumstats status in with the study download table: documented here https://github.com/EBISPOT/gwas-utils/wiki/Catalog-plots#generate-study-table-with-summary-stats-truefalse-status

**Comment by jdhayhurst** [comment]
when tested it get's to 10 out of 20 REST calls, and then exits quietly.

**Comment by jdhayhurst** [comment]
decreased "size" on the REST call to 10 - it run's to completion but it takes 2.5 hours.
