### ISSUE TITLE
Add new page to GWAS Catalog website displaying a list of valid Countries of Recruitment

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#47]
Background:
Users who are submitting data to the GWAS Catalog are asked to follow the instructions on this page to find out how to correctly fill in the "sample" tab in the sumstats+metadata template: https://www.ebi.ac.uk/gwas/docs/submission-summary-statistics-plus-metadata#samples. Users are currently directed to The United Nations M49 Standard of Geographic Regions for the list of allowed country names that can be entered in the field "Country of recruitment". However the country names in that resource do not exactly match the list of country names that we actually use in the database. Therefore, we need to provide users with our own definitive list of country names. This will help to ensure that users enter valid values in the template (we have had some problems so far with "U.K." vs "UK") and reduce the amount of editing by curators after import.

Tasks:
1. Add a new page to the GWAS Catalog documentation:
* Suggested filename: countries.adoc
* Suggested URL: https://www.ebi.ac.uk/gwas/docs/countries

(The new page does not have to be accessible directly from the GWAS Catalog homepage, so no new icons/buttons need to be created. The page will only be linked to from https://www.ebi.ac.uk/gwas/docs/submission-summary-statistics-plus-metadata.)

2. Provide an up-to-date list of countries of recruitment from the GWAS Catalog database: 
- you could either add the list directly to the new page or send a text file to Elliot to add later, whatever's easier. Don't worry about formatting, I can sort that out.

**Comment by eks-ebi** [comment]
Discussed with Jackie today and this is needed for the updates to the documentation ahead of the unpublished studies work being released. Assigning to Jon for now and adding a priority.

**Comment by jstewart-ebi** [comment]
Deployed at https://www.ebi.ac.uk/gwas/docs/countries
