### ISSUE TITLE
Migrate Deposition Software from Embassy Hosted Kubernetes (EHK) to Production Cluster

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#477]
On 28/09/2021 16:56, David ..
Hi ...,

Jeremy Mason was the technical contact for the tenancy called GWAS. ... We are in the final phase of the Embassy Cloud migration and would need this tenancy to be migrated to the new infrastructure or retired.
Many thanks,
David

---------------------------------------------------------------------

We use as this as sandbox (dev and test) environment for the depositions software.

There are some limitations with this kind of set up, especially since the Embassy Cloud does not have access to internal EBI resources, hence, we can't do full end-to-end test in the dev/test environment.

We have previous plans to migrate everything (deposition dev and test) into the WebProd Cluster so that dev, test, and prod can be in the same environment and we can be sure of full access to internal EBI resources while testing.

Now that the Embassy Cloud will be retired in 4 weeks time, so we have an option of requesting for a brand new tenancy in the new Embassy Cloud infrastructure via RUP and do a new set up for our sandbox environment there, but we won't want to do that.

Moving the resources to the WedProd Cluster will be our preferrred choice and we'll commence this immediately so it can be done before the 4 weeks

**Comment by sajo-ebi** [comment]
Migrated all applications from EHK  Sandbox cluster to HH cluster  -:


[Deposition Backend](http://hh-rke-wp-webadmin-09-worker-2.caas.ebi.ac.uk:30183/gwas/deposition/api/v1/)

[Deposition UI](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31233/gwas/deposition)

[Curation Backend](http://hh-rke-wp-webadmin-09-worker-2.caas.ebi.ac.uk:30895/gwas/depo-curation/api/docs/api-guide.html)

[Ingest Backend](http://hh-rke-wp-webadmin-09-worker-1.caas.ebi.ac.uk:31370/v1/)

[Curation Ui](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:32268/gwas/depo-curation)
