### ISSUE TITLE
EBI cluster migration to codon

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#478]
EBI is migrating to a new cluster called codon. The key difference is that codon is in HL, whereas the existing cluster is in HX. More info on the cluster is here: https://sysinf.ebi.ac.uk/doku.php?id=codon_cluster_good_computing_guide

An inventory has been made for all processes, scripts, tasks, that need to be migrated: https://docs.google.com/document/d/1ocTAhI_CMktjWlCA-Ci_t30CZffUrayVNr9p8ilrl_0/edit?usp=sharing

A preliminary deadline of end of 2021 to complete this task has been given.

**Comment by ljwh2** [comment]
all issues complete or deprioritised
