### ISSUE TITLE
Discrepancy in UI between search and top search, the trait page does not include child traits 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#48]
For cardiovascular disease, with 'child traits' ticked, the number of associations is 331. When unticked and re-ticked, the number is 5027. 

https://www.ebi.ac.uk/gwas/efotraits/EFO_0000319

**Comment by earlEBI** [comment]
From gwas-info - h.ismail@sheffield.ac.uk

**Comment by mcerezof** [comment]
The user detected the discrepancy between the number of associations and studies for Cardiovascular disease in the search and the number of associations and studies when selecting the top search results.
The same is happening for cancer, maybe a problem when the EFO has lots of child traits?

**Comment by ljwh2** [comment]
The same bug was reported by user Thomas Kollmeyer on 10 May for glioma and other traits. Glioma only has 125 associations so this is not limited to large traits.

**Comment by twhetzel** [comment]
I have a fix for this in branch `issGOCI48_trait_page_child_term_loading`.

When we have time to test and make any needed updates we can review.

**Comment by ljwh2** [comment]
@twhetzel let me know when/where this is ready for testing

**Comment by twhetzel** [comment]
@ljwh2 this is deployed to Snoopy 9580 (I've taken over both dev servers to test items for the next release)

**Comment by ljwh2** [comment]
I have tested and all looks good, ready for release. 

I note that loading of large traits is very slow. A fix for this is out of scope for this ticket, but would be good to document if you have any thoughts on how this can be improved in future @twhetzel

**Comment by twhetzel** [comment]
Merged into `dev` to prepare for the release
