### ISSUE TITLE
FTP link in search interface does not work for summary stats that come through deposition

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#49]
An external user submitted summary statistics for the publication Nag A PMID 31960908. The summary statistics were transferred using Globus. I believe they are now stored at this location: gwas_cat/c27cd630-6d6f-468e-9d33-4fc86339c9c1.

The submission has now been imported and the publication has been re-published in the GWAS Catalog. However, on the search interface page for this publication (https://wwwdev.ebi.ac.uk/gwas/publications/31960908), the link to the summary stats on the FTP does not work.

It seems to be attempting to link to a directory using the old sumstats folder naming convention (i.e. ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/NagA_31960908_GCST009885) which does not exist, because the summary stats were introduced through Globus and are now in a folder with a different name.

**Comment by eks-ebi** [comment]
In the long term, the construction of the FTP links will need to be updated to reflect the new folder names for Globus-transferred sumstats, while maintaining access to older sumstats contained in folders with the old naming convention.

In the short term, these summary statistics should made accessible when the data is released. Maybe via a work-around?

**Comment by eks-ebi** [comment]
As a related issue, the SPOT robot email flags NagA_31960908_GCST009885 as a missing folder. However, as the summary stats for this publication are in a folder with a different name (c27cd630-6d6f-468e-9d33-4fc86339c9c1), we don't actually expect there to be a folder called NagA_31960908_GCST009885.

This could be a problem, because the SPOT robot email might quickly fill up with apparently "missing" folders that are actually just under a different name.

**Comment by twhetzel** [comment]
@eks-ebi is this still an issue on the production site?

**Comment by eks-ebi** [comment]
The FTP link now works correctly for the PMID that I gave as an example (31960908). I can't be sure if it works for all new entries. It's possible that this one worked because someone (@jdhayhurst ?) moved or renamed something manually??

**Comment by jdhayhurst** [comment]
I think there are two things going on - 1) I changed the nightly release to check only for folders named with their GCST and 2) the communication between the depo app and curation has some bugs that resulted in files not being released. 
There is a fix ready to release that should solve all future submissions. We are manually fixing those that are already submitted.

**Comment by ljwh2** [comment]
Waiting for all old submissions to go through process

**Comment by buniello** [comment]
Directories from there submissions are still missing from public FTP:
https://www.ebi.ac.uk/gwas/deposition/submission/5ef9f6b7513eba0001e02c7e
https://www.ebi.ac.uk/gwas/deposition/submission/5ee2731d3152df0001d84087
