### ISSUE TITLE
Curators need to be able to unpublish multiple studies in bulk

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#502]
There is a specific list of studies that were received as user submissions, but where there were previously too many studies per publication for a curator to be able to include all of the manually-curated top associations. Therefore these were published in the Catalog without the top associations. _Now_, with the new depo-curation app, we have the features needed to add these associations. Each study needs to be unpublished from the GWAS Catalog to allow re-curation, in order to add the assocs.

The issue is that currently, each study must be unpublished individually, which is not practical for such large numbers of studies. Two possible solutions are to:
1) have a developer manually change the status of just these studies in the database as a one-off operation, or
2) add a new feature to allow curators to unpublish multiple studies in a publication in bulk

Initial tasks:
- investigate which is the most appropriate approach
- estimate the time/effort required

**Comment by eks-ebi** [comment]
@buniello could you please add the list of publications with numbers of studies from yesterday's curation meeting to this ticket, to give Sajo an idea of the scale of the issue?

**Comment by buniello** [comment]
<google-sheets-html-origin><style type="text/css"></style>
@eks-ebi @sajo-ebi list of PMID/studies 
PMID | Author | Number of studies
-- | -- | --
32641083 | Hillary RF | 70 studies
32888493 | Chen MH | 88 entries
32929287 | Orru V | 731 studies
33288918 | Julie D White | 126 studies
33414548 | Lotta LA/Maik Pietzner | 141 studies
33462482 | Rühlemann MC | 430 studies
33623009 | Gaurav Thareja | 45 studies
33821002 | Sahin Naqvi | 285 studies
33875891 | Smith S | 3935 studies
33983923 | Hanne Hoskens | 1048 studies
34594039 | Saori Sakaue | 440 studies

**Comment by sajo-ebi** [comment]
@ljwh2 As a short term workaround we can manually update DB to accelerate the work, for a long term development it looks like 2 sprint work to create a Bulk upload page for Un-publishing studies

**Comment by ljwh2** [comment]
Curation tracker is here: https://docs.google.com/spreadsheets/d/1pLA2uTsO3I_1lgvNMcI1IlEHo8Ms_-QxN-z9RZNMp1g/edit?usp=sharing
6 more to do as of 12/1/22
