### ISSUE TITLE
~17k associations need updating for 1 publication with 440 studies

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#510]
Submission ID 609c44af4e974a0001bec83d
PMID 34594039
GCP000172

This publication was published to the GWAS Catalog with ~17k associations but effect allele information was not included as it was not clear from the publication. 

We have had an email from the user asking for the effect allele to be included and clarifying which to extract. Curators can update the submission template with this information. 

All 440 studies then need unpublishing from the Catalog so the template can be resubmitted through the DepoCuration App, imported and then published again. 

There is currently no mass unpublish button, and there is a known bug for mass publishing 'temporarily unpublished' studies using the Curation App publication page.

**Comment by earlEBI** [comment]
Just for when there is a solution to the bulk unpublishing issue: 
The submission template has now been updated with correct data. Current state: failed sumstats re-validation. 
https://www.ebi.ac.uk/gwas/depo-curation/submissions/609c44af4e974a0001bec83d

**Comment by earlEBI** [comment]
Please unpublish all studies from this publication - related to https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/502 and 510.

**Comment by sajo-ebi** [comment]
@earlEBI have unpublished studies for Pmid 34594039, Kindly confirm

**Comment by earlEBI** [comment]
@sajo-ebi Thanks Sajo. The associations are now updated. 
Please re-publish all studies except for 91777260 which should remain as 'requires review'.

**Comment by sajo-ebi** [comment]
@earlEBI Have published the studies , kindly confirm the same

**Comment by earlEBI** [comment]
@sajo-ebi looks good - thanks!
