### ISSUE TITLE
Update FAQ on CNV studies

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#518]
FAQs currently say that no CNV studies are included in the Catalog and that there is therefore no flag to identify them.

However, we have recently accepted summary statistics submissions for some CNV studies.

FAQs need to be updated to say:
* CNV studies are not generally within the scope of the GWAS Catalog
* In the interests of making summary statistics available, we do accept CNV summary stats submissions and will make sumstats files and basic metadata available for these studies
* But CNV studies will not be curated to include top associations

**Comment by ljwh2** [comment]
Suggest changing the text as follows: 

CNV studies are not currently within the scope of the GWAS Catalog for literature identification and curation of associations. However, we can accept submissions of summary statistics from CNV studies and will make files and metadata available for these studies.

**Comment by ljwh2** [comment]
Noting here that we need to add a column to the studies download indicating CNV y/n. This is currently included in the associations download, but this is no use since no associations will be extracted

**Comment by eks-ebi** [comment]
Changed the text as suggested, and I am creating a new ticket to add a CNV y/n field to the studies download.

**Comment by eks-ebi** [comment]
text edits ok in snoopy, ready for release

**Comment by ljwh2** [comment]
Still not released
