### ISSUE TITLE
Formatting errors in the ancestry v1 download (OTAR user request)

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#520]
A user from Open Targets reported more problems in the formatting of the the ancestry download file:
 
All ancestry data v1.0

message from user pasted below:

"studies: GCST010653 and GCST010729
still have some mis-alignment in the ancestry API file (https://www.ebi.ac.uk/gwas/api/search/downloads/ancestry)
which led to the n_initial to appear as the n_replication"

**Comment by ljwh2** [comment]
@buniello could you please check if this error still exists in the latest DR?

**Comment by buniello** [comment]
I asked Jack from OTAR to double-check for me - he's the one who reported the latest issues

**Comment by buniello** [comment]
The error does not exist in the latest DR
