### ISSUE TITLE
Bulk adding EFO terms to the Curation App database

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#522]
479 EFOs need to be added to the curation database so that I can import a large submission from the deposition app this week. 

[https://app.zenhub.com/files/2995118/916ed4a7-4f43-471b-a3ab-1cabd0524392/download](https://app.zenhub.com/files/2995118/916ed4a7-4f43-471b-a3ab-1cabd0524392/download)

**Comment by ljwh2** [comment]
This is the process that is normally performed on this page https://www.ebi.ac.uk/gwas/curation/efotraits
