### ISSUE TITLE
Bulk upload 'reported trait' function allows case-insensitive duplicates

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#527]
Duplicate traits have been created when attempting to bulk upload reported traits. 
An example of the result, shown in the Curation App reported trait search bar: : 

![Screenshot 2021-11-16 at 15.28.56.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/7425c847-bc5b-4efa-bae3-a3303f95e624)

Duplicate traits (regardless of case) cause import of studies from the Deposition App to fail. Example error: 
** Errors: **
Creating study [GCST90081485] | Unable to create study [RGC_HF__BIN__SV | GCST90081485]: result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements

![Screenshot 2021-11-17 at 09.30.20.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/6c117899-e41a-4dec-b974-821c2c37715a)

**Comment by ljwh2** [comment]
This should be checked in the new depo app features

**Comment by ljwh2** [comment]
@earlEBI has this been handled correctly in the DepoCuration functionality?
