### ISSUE TITLE
Investigate missing FTP files for PMID34616010 

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#528]

**Comment by eks-ebi** [comment]
- Submission is complete in deposition with 3 sumstats files.
- Studies are displayed with FTP links on UI: https://www.ebi.ac.uk/gwas/publications/34616010#study_panel
- FTP links are broken --> 404 errors

**Comment by jdhayhurst** [comment]
resync'd files from depo app. They'll release on the public FTP this evening.
