### ISSUE TITLE
Summary statistics table - rows capped at 10k

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#531]
The 'List of published studies with summary statistics' table on this page https://www.ebi.ac.uk/gwas/downloads/summary-statistics is capped at 10,000 rows, which means newly added studies are not shown, either on the page or in the CSV download. 

Please remove the cap.

**Comment by ljwh2** [comment]
As a quick fix, this can be increased to 50K. In the long term, the page needs refactoring.
