### ISSUE TITLE
Improved efficiency of calls from the curation app to the database for traits

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#533]
The number of EFOs and reported traits in the database are rapidly increasing due to large submissions.  Calls from the curation app to the database for traits are inefficient and result in frequent server time-out errors, hindering use of the app. Curators need this to be improved to improve the usability of the curation app.

**Comment by ljwh2** [comment]
@sprintell we should revisit whether it could be possible to improve in the short term.

**Comment by sprintell** [comment]
There are over 32,000 disease traits in the database and 5193 EFO Traits, this list huge list is been pulled in all the pages. 
The way this is pulled on all the pages is presently been adjusted to leverage on spring inbuilt Ehcache technology, as soon as this is modified to be called in an efficient way, there will be improved performance on all the pages
