### ISSUE TITLE
Originally submitted studies for Backman submission should not be displayed to users

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#535]
Submission ID 615df545921d1b00012f1e6e
List of GCSTs attached

These studies were submitted and then retracted by the user. The files have been made inaccessible to users, but the studies still appear in the search UI (in the sumstats downloads table and indexed in the search, though the landing pages are unavailable, see screenshots)
![Screenshot 2021-11-23 at 16 41 04](https://user-images.githubusercontent.com/30795297/143070520-56622fe1-5fb1-4eea-ae3f-26c6587a8f31.png)

![Screenshot 2021-11-23 at 16 40 54](https://user-images.githubusercontent.com/30795297/143070545-72ea9e97-96d9-45c0-b1db-6c83112e8023.png)
These studies should be made fully inaccessible to users. Ideally we would archive them to preserve the GCSTs, but if that is not possible they should be deleted.
[Backman GCSTs.xlsx](https://github.com/EBISPOT/goci/files/7589822/Backman.GCSTs.xlsx)

**Comment by ljwh2** [comment]
@earlEBI could you please confirm this is the correct list of GCSts for the original submission

**Comment by earlEBI** [comment]
Confirmed. Except, to me, the landing pages *are* visible @ljwh2 ? https://www.ebi.ac.uk/gwas/studies/GCST90045365
![Screenshot 2021-11-23 at 17 15 11](https://user-images.githubusercontent.com/61545198/143072198-b8ee4293-4375-4609-bb4d-5beb925420e4.png)

**Comment by sajo-ebi** [comment]
@earlEBI Have deleted the Unpublished studies from DB as per the excel sheet , they will not see those studies once data is released

**Comment by jdhayhurst** [comment]
All summary stats files for these GCSTs have been removed completely
