### ISSUE TITLE
Author Alexey Shadrin has requested to re-open her submission to make amendments

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#537]
from gwas-info 26/11/21:

Dear Sir/Madam,

we spotted a mistake in recently submitted summary statistics (Submission ID: 61602e54c325ee0001339508, PMID:34560273). Could you please remove the submission then we will upload correct version.

Best,
Alexey Shadrin

**Comment by sajo-ebi** [comment]
@buniello the submission has been reset

**Comment by buniello** [comment]
Thanks @sajo-ebi, I will now close the ticket
