### ISSUE TITLE
Extend submission 618eb7c9911f5a0001f21c0c to prevent deletion for another month

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#539]

**Comment by eks-ebi** [comment]
Submission was created 2021-11-12, so due for deletion after 30 days on 2021-12-12.

The user has had some delays, so requests the submission to be kept open.

Please keep the submission open for another month, until January 2022, to allow the user time to complete the submission.

**Comment by sajo-ebi** [comment]
@eks-ebi Have Updated the submission update date to 12 Dec 2021 which means the user has time till 12th January to work on the submission

**Comment by eks-ebi** [comment]
thanks @sajo-ebi I've just let the user know about the new expiry date
