### ISSUE TITLE
Unpublishing all 45 studies from Thareja PMID 33623009

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#540]
This issue is linked to the parent ticket:

https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/502

Thanks @sajo-ebi!

**Comment by buniello** [comment]
The reason for unpublishing should be 
1 : Temporarily unpublished for editing

**Comment by sajo-ebi** [comment]
@buniello the studies have been updated in DB , Kindly confirm

**Comment by buniello** [comment]
@sajo-ebi yes, I conform they are all unpublished. Thank you!
