### ISSUE TITLE
Investigate missing and/or corrupted harmonised files for PMID 34059833

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#541]
*User request*

PMID 34059833 has 24 studies, all with summary stats: see https://www.ebi.ac.uk/gwas/publications/34059833

Harmonised files are missing for the following studies, for no clear reason:
- GCST90002225
- GCST90002226
- GCST90002227
- GCST90002228
- GCST90002235
- GCST90002241

The harmonised file for GCST90002247 seems to be corrupted as it is only 180 mb (looks like it contains only the headers).

There might be additional issues that the user has not come across.

**Comment by jdhayhurst** [comment]
regarding GCST90002247, it does not meet the validation criteria. It went through the harmonisation pipeline anyway and then all "invalid" lines (e.g. missing p_value) were removed as part of the QC. That is why it's only a header row. Should we remove the harmonised file?
Submitted file:
```
chromosome	base_pair_location	effect_allele	other_allele	log10BF	sample_size	het_p_value
10	100000012	A	G	-0.40838	44043.1	0.3048
10	10000011	A	G	0.10722	5674	1
10	100000122	A	T	-0.33741	60306	0.6666
10	10000018	A	G	-0.5192	194648	0.9796
10	100000259	A	G	-0.27964	9567.03	1
10	100000274	A	G	-0.68338	8333.97	1
10	10000033	A	G	-0.07489	26576	0.8533
10	100000430	T	G	-0.31029	9046.98	1
10	100000439	T	C	-0.67812	9566.99	1
```

**Comment by jdhayhurst** [comment]
same is true for GCST90002235 GCST90002241, in that they do not meet the validation criteria. For GCST90002225, GCST90002226, GCST90002227, GCST90002228 I have queued them up. But there are about 7 thousand in the queue at the moment so it will take some time to reach them

**Comment by eks-ebi** [comment]
ok thanks James - does this mean that we should never have accepted these sumstats?

**Comment by jdhayhurst** [comment]
These would have been waved through the validation as acceptable even though they do not meet the criteria
