### ISSUE TITLE
Investigating missing harmonised files from the FTP- OTAR query

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#544]
Jeremy S. from OTAR wrote:

I noticed that there are a small number of studies that had harmonized sumstats in our previous release (and I have the sumstats for them ingested), but which no longer have harmonized sumstats available. Do you have any idea what could have happened?
Here they are:
GCST90000025
GCST90000026
GCST90000027
 
These also used to have harmonized sumstats, although we didn’t ingest them since we’re still only taking European studies.
GCST90000024
GCST90002235
GCST90002241

For GCST90002235 and GCST90002241 - see this: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/gwas-user-requests/28

**Comment by jdhayhurst** [comment]
resync'd GCST90000025-GCST90000027 back to ftp. Need to resolve general issue to prevent repeat occurrences ([gwas-utils#98](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/gwas-utils/98))
