### ISSUE TITLE
Sumstat validation failed for Submission ID: 5f4e7796fa551c0001c9cec3

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#546]
the sumstat submitted by the user. I updated the template with associations. It is showing the following error:

"Summary_Segment4_US.tsv: Summary statistics file validation failed, please run the validator on your file to see the errors (available here: https://pypi.org/project/ss-validate/)
Summary_Segment39_US.tsv: Summary statistics file validation failed, please run the validator on your file to see the errors (available here: https://pypi.org/project/ss-validate/)"

GCST Ids
GCST90007181-GCST90007306

**Comment by jdhayhurst** [comment]
The depo-curation currently tries to validate the sumstats, but there is a [ticket](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/gwas-curation-service/67) open to prevent it from doing this. We can get them to pass for you if you need?

**Comment by jdhayhurst** [comment]
sumstats validation error:
```
(ERROR): {row: 43108, column: "other_allele"}: "<DEL>" does not match the pattern "^[ACTGNactgn]+$"
```
As requested from @Santhi1901 these should pass. Will bypass the validation.
