### ISSUE TITLE
Reopen PMID 33143745 for full metadata+sumstats submission (without deleting existing curated studies)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#548]
**Background**

We have already manually curation 12 studies for PMID 33143745 - this was done manually in the curation interface, so there are no submissions involved, and they are now in production with curation status=“Publish study”.

The author would now like to submit summary statistics: _not_ for the current 12 studies, but for 20 _additional_ studies belonging to the same publication, which we did not curated.

We would like to keep the existing curated studies (without sumstats) and also allow the user to submit the additional studies (with metadata and sumstats).

**Proposed steps**
1. Delete the current invalid sumstats-only submission
2. Change the status of the publication in deposition to OPEN_FOR_SUBMISSION (so even though there are 12 curated studies already in the production database, the publication will appear in deposition as if no curation has been done)
3. The author makes a new metadata+sumstats submission with a blank submission template and provides metadata and new sumstats for the 20 additional studies
4. We import the new metadata+sumstats submission into the curation interface. Because the existing 12 studies were created in the curation interface and did not come from a submission, we think that they will not be deleted, but will change status to “Requires Review”. We want to keep these studies, so need to make sure they would not be wiped.
5. A curator can check the new imported studies and then make sure all 12 + 20 studies are set to “Publish study” so they should all appear in production.

**Developer tasks requested**
* Steps 1 and 2 above
* Confirm that the existing 12 manually-curated studies will _not_ be deleted if we import a new metadata+sumstats submission (step 4)
* Check if there are any other concerns/consequences of the proposed plan that have been missed

**Comment by eks-ebi** [comment]
This is the current invalid submission: https://www.ebi.ac.uk/gwas/deposition/submission/61ad073606ff200001926304

**Comment by sajo-ebi** [comment]
@Elliot W.r.t Step 4 the studies will be deleted as they have been assigned GCST , As per the logic while designing Depo Curation we had decided to identify the studies as pre Deposition if they are not assigned GCST Ids

**Comment by eks-ebi** [comment]
Ok thanks @sajo-ebi ...
@earlEBI that is a bit of a problem, but hopefully we can get around it. Do you think we can save all the data for the current studies and add them back in as an edit to the submission template later in depo-curation?

**Comment by earlEBI** [comment]
@eks-ebi ok, am happy to do that. I've downloaded the associations currently in the Catalog and also the study info so shouldn't be difficult. Happy for steps 1 and 2 to go ahead from my POV.

**Comment by eks-ebi** [comment]
Nice, thanks @earlEBI! I agree - @sajo-ebi feel free to go ahead with steps 1 and 2 when you're able to

**Comment by sajo-ebi** [comment]
@earlEBI @eks-ebi Only concern will be new GCST Ids will be assigned for the old studies once they are submitted using Deposition App, will that be fine with you ?

**Comment by eks-ebi** [comment]
@sajo-ebi we agree that it should be ok for the old GCSTs to be replaced, as they were not attached to any sumstats and are therefore unlikely to have been used for anything by the author

**Comment by sajo-ebi** [comment]
@earlEBI @eks-ebi the pubmed Id is now open for submission & the invalid submission has been archived

**Comment by eks-ebi** [comment]
brilliant, thanks @sajo-ebi! I've confirmed that it is open in deposition. I'll keep this ticket open to track the curation side of the process @earlEBI

**Comment by eks-ebi** [comment]
@earlEBI Can we close this ticket now? I see that the publication is now OPEN FOR SUBMISSION in deposition. I think we are now waiting for the user to resubmit, right?

**Comment by earlEBI** [comment]
@eks-ebi yes... I thought we'd have to keep resetting to 'open for submission' if there was a syncing issue with curation app... but it does seem to have remained open overnight. So I think this is done for now, yes.
