### ISSUE TITLE
Re-Publishing the 45 entries from Thareja PMID 33623009

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#552]
This ticket is related to the previous task: 
https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/540.

Entries can be all seen here: 
http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/publication/33623009

**Comment by sajo-ebi** [comment]
@buniello Have Published the studies for the Pmid '33623009', kindly confirm if everything looks good

**Comment by buniello** [comment]
Yes, everything looks good. Thanks @sajo-ebi!
