### ISSUE TITLE
Investigating a list of studies that failed harmonisation - from OTAR

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#557]
There are a few studies which seem to have failed harmonization. For example, I can see that the harmonized files have no content. It looks as if the raw (original) files just don’t have the required information, probably.
Is there a way to have these studies either not go through harmonization, or not appear in the harmonized list?
Here are the ones I’m talking about:
 
GCST006079
GCST010116
GCST90011881
GCST90011882
GCST90011883
GCST90000181
 
and 40 studies from publication 34270794 (Watts et al).

I also noticed that in some cases the unharmonized files are uncompressed, i.e. plain .tsv. (Is there a reason they’re sometimes compressed, sometimes not?)

**Comment by jdhayhurst** [comment]
> I also noticed that in some cases the unharmonized files are uncompressed, i.e. plain .tsv. (Is there a reason they’re sometimes compressed, sometimes not?)
There is no requirement currently imposed, so users can and have sent us compressed and uncompressed files.

**Comment by jdhayhurst** [comment]
Everything goes through the harmonisation but we could prevent it from being published if it's empty after QC? In that case, would we simply not publish or would we need to communicate to users why there are no harmonised files?

**Comment by buniello** [comment]
I think I would prevent empty files to be published after QC and perhaps add a reference to this in the readme? 
Tagging @ljwh2 as well for discussion

**Comment by ljwh2** [comment]
Agree, we should not publish the empty files. Communication could go in the main readme for the study or a speaker one in the harmonised folder. Is it easy to automate a readme saying exactly why it could not be harmonised? If not it could just say something like "This study could not be harmonised for technical reasons e.g. unknown genome build or other missing data"

**Comment by jdhayhurst** [comment]
OK I can create a ticket for creating a report. Where should we publish the report? Is it ok if we create a harmonised directory just to store the report?

**Comment by ljwh2** [comment]
I think so - otherwise users will not know where to look for it

**Comment by buniello** [comment]
yes, that sounds like a good plan

**Comment by jdhayhurst** [comment]
ticket raised: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/gwas-sumstats-harmoniser/24
