### ISSUE TITLE
missing sumstats from ftp

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#558]
the following sumstats are missing from the FTP:
GCST009969
GCST90006364
GCST90006365
GCST90006366
GCST90006367
GCST90006368
GCST90006369
GCST90006370
GCST90006371
GCST90006372
GCST90006373
GCST90006374
GCST90006375
GCST90006376
GCST90006377
GCST90006378
GCST90006379
GCST90006380
GCST90006381
GCST90006382
GCST90006383
GCST90006384
GCST90006385
GCST90006386
GCST90006387
GCST90006388
GCST90006389
GCST90006390
GCST90006391
GCST90006392
GCST90006393
GCST90006394
GCST90006395
GCST90006396
GCST90006397
GCST90006398
GCST90006399
GCST90006400
GCST90006401
GCST90006402
GCST90006403
GCST90006404
GCST90006405
GCST90006406
GCST90006407
GCST90006408
GCST90006409
GCST90006410
GCST90006411
GCST90006412
GCST90006413
GCST90006414
GCST90006415
GCST90006416
GCST90006417
GCST90006418
GCST90006419
GCST90006420
GCST90006421
GCST90006422
GCST90006423
GCST90006424
GCST90006425
GCST90006426
GCST90006427
GCST90006428
GCST90006429
GCST90006430
GCST90006431
GCST90006432
GCST90006433
GCST90006434
GCST90006435
GCST90006436
GCST90006437
GCST90006438
GCST90006439
GCST90006440
GCST90006441
GCST90006442
GCST90006443
GCST90006444
GCST90006445
GCST90006446
GCST90006447
GCST90006448
GCST90006449
GCST90006450
GCST90006451
GCST90006452
GCST90006453
GCST90006454
GCST90006455
GCST90006456
GCST90006457
GCST90006458
GCST90006459
GCST90006460
GCST90006461
GCST90006462
GCST90006463
GCST90006464
GCST90006465
GCST90006466
GCST90006467
GCST90006468
GCST90006469
GCST90006470
GCST90006471
GCST90006472
GCST90006473
GCST90006474
GCST90006475
GCST90006476
GCST90006477
GCST90006478
GCST90006479
GCST90006480
GCST90006481
GCST90006482
GCST90006483
GCST90006484
GCST90006485
GCST90006486
GCST90006487
GCST90006488
GCST90006489

**Comment by jdhayhurst** [comment]
GCST90006364-GCST90006489 are duplicated from this https://github.com/EBISPOT/goci/issues/546
do we need these to be published or did something go wrong?
We bypassed the validation on these for goci#546 but then they were assigned new GCSTs - should that have happened? @Santhi1901 do you know about these?

**Comment by jdhayhurst** [comment]
No record of GCST009969 in sumstats service, nor is it on the staging server.

**Comment by sajo-ebi** [comment]
@Santhi1901 have corrected the GCST in Curation app , the GCST for Pmid '**33288918**'  has been changed to the series '**GCST90007181' - 'GCST90007306'**

**Comment by jdhayhurst** [comment]
summary stats are named according to the series 'GCST90007181' - 'GCST90007306'
