### ISSUE TITLE
Studies without sumstats incorrectly marked as with sumstats upon import

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#56]
In “View Submissions”, submissions that do not have summary statistics are being incorrectly labelled as “Metadata Summary Stats and Top Associations”.

Example: Buchwald J 32157176 was submitted by a curator with metadata and top associations but no summary stats (see submission:
https://www.ebi.ac.uk/gwas/deposition/submission/5e846f9e4c489b0001928d5a) but it appears in the View Submissions table as “Metadata Summary Stats and Top Associations”. When the studies were imported, they were therefore incorrectly marked as having summary statistics.

**Comment by eks-ebi** [comment]
Tested in snoopy:9680 - this is now fixed.

**Comment by eks-ebi** [comment]
I've seen this issue come up again for this paper: https://www.ebi.ac.uk/gwas/curation/publication/28322283

It was fixed in the snoopy test, but still seems to be a problem in production.

**Comment by jstewart-ebi** [comment]
I don't think it has been released yet, it will be part of the next build.

**Comment by jstewart-ebi** [comment]
Released.
