### ISSUE TITLE
Investigating beta direction for summary statistics from Teslovich 20686565

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#561]
The Open Targets team has identified a mistake in beta values for sumstats for all studies in this publication: https://www.ebi.ac.uk/gwas/publications/20686565.
I will take a look and flip betas/alleles if needed, so that the files can be re-harmonised with the corrected values.

Original OTAR ticket for reference: https://github.com/opentargets/genetics/issues/525.

**Comment by buniello** [comment]
sumstats downloaded by AB from here http://csg.sph.umich.edu/willer/public/lipids2010/  
on 8/2/19

**Comment by buniello** [comment]
The files have now been re-formatted and alleles swapped (for effect directionality):
formatted_20686565-GCST000755-EFO_0004612-build36.f.tsv
formatted_20686565-GCST000758-EFO_0004530-build36.f.tsv
formatted_20686565-GCST000759-EFO_0004611-build36.f.tsv
formatted_20686565-GCST000760-EFO_0004574-build36.f.tsv

They are in preanalysis/buniello.
@jdhayhurst could you please add to the harmonisation queue when possible?

**Comment by jdhayhurst** [comment]
added to the queue

**Comment by jdhayhurst** [comment]
harmonised files were  released Jan 23rd
