### ISSUE TITLE
Implement process to detect and update obsoleted EFO terms prior to data release

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#564]
EFO sometimes obsoletes terms and replaces them with new ones. When obsolete terms have been used in the GWAS Catalog and not updated, this causes the data release to fail. 

We need a process to to detect and update obsolete terms to be run prior to data release.  

EFO release notes are here:
https://github.com/EBISPOT/efo/blob/master/ExFactor%20Ontology%20release%20notes.txt

See also these tickets:
gwas-utils#15
goci#366 (wider issue of propogating changes in EFO eg term name, definition, to the GWAS catalog, not required now but we should plan for this in the future)

**Comment by ljwh2** [comment]
@ala-ebi is this the same issue that you recently fixed?

**Comment by ala-ebi** [comment]
@ljwh2 No, the one that was recently fixed involves ignoring EFOs that have no parent that is defined within our system when generation the EFO Mappings file

**Comment by ala-ebi** [comment]
1- we will check if other teams have processes in place to detect and update obsolete terms
2- we will check with EFO team if they can provide and standardised format for what has changed
3- we will crawl the .owl file and see if any obsoleted terms (using the 'obsolete' tag) exist in the catalog and replace them with new term

**Comment by ljwh2** [comment]
@ala-ebi it would be useful to include James M in any discussion with the EFO team

**Comment by ljwh2** [comment]
Irene Lopez is the right person for Open Targets

**Comment by ala-ebi** [comment]
use mongo DB instead
send emails to curators as well

**Comment by sprintell** [comment]
waiting for automated deployment @ala-ebi
