### ISSUE TITLE
Update sync for https://www.ebi.ac.uk/gwas/deposition/submission/61dc499181051b0001edae77

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#566]
Changes to the metadata in the prefilled template were required before the author could submit summary statistics for this study.

The sample description has been updated in the curation interface for two studies:
- GCST005362 (http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/studies/27279568/sampledescription)
- GCST012597 (http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/studies/93944681/sampledescription)

However this has not been synced to the deposition interface, so when the author created a new submission today, the pre-filled template still displays the old sample descriptions. (https://www.ebi.ac.uk/gwas/deposition/submission/61dc499181051b0001edae77)

**Comment by sajo-ebi** [comment]
@eks-ebi Have updated the details for GCST from backend in Depo App. But the user will have to create a new sumstats only submission for the PubmedId . Have opened the Pmid for submission , kindly request the user to create a new submission for the Pmid to generate new pre-filled template with updated details

**Comment by eks-ebi** [comment]
The sync was successfully updated and the new data has been submitted. The sumstats files are now available on the ftp.
