### ISSUE TITLE
Background EFOs on import are not auto-applied to associations

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#567]
Example submission: https://www.ebi.ac.uk/gwas/deposition/submission/61dc5b7681051b0001edaef3 , PMID 34680357.

On import, main EFO and background EFO are correctly applied at study level:
http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/publication/34680357

but background EFO is not applied at association level. 

Please fix for this study and for all imports going forward.

**Comment by earlEBI** [comment]
I will fix this publication (3468035) manually. 

The import issue still needs to be fixed going forward.

**Comment by ala-ebi** [comment]
testing was held due to changes I made to Sajo's changes while he was away, will merge to dev and flag Lizzy
