### ISSUE TITLE
PMID 34757267 needs resetting to allow re-import

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#572]
I curated this paper in the deposition app with 1 study, imported and published. 

I then realised I needed to edit and add another study. 

I unpublished, edited in the depocuration app and tried to reimport but the status in 'view submissions' is 'Review' with the import button greyed out. 

I deleted the originally imported study from the Curation App in case that might fix things, resubmitted in the depocuration app but the status is still 'Review' and the import button still disabled. 
http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/submissions/61dc2d4481051b0001edadad?

Please could someone look at how I can reset and import this submission again?

**Comment by ljwh2** [comment]
@earlEBI  please confirm whether this is outstanding

**Comment by earlEBI** [comment]
I think there may still be an issue.

The paper is now published in the Catalog: https://www.ebi.ac.uk/gwas/publications/34757267
but there are no published studies in the Curation app. 
I tried to resubmit during the depocuration app but the metadata validation wheel appears to be stuck spinning. 

In the Deposition app, the status has been reset to 'open for submission', so maybe I should just start a fresh submission...

**Comment by earlEBI** [comment]
I just created a new submission and it looks okay so far. Will update if all goes okay publishing.

**Comment by earlEBI** [comment]
appears ok.
