### ISSUE TITLE
Bulk trait upload fails without giving sufficient error report

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#573]
I tried to upload the following file of 718 traits. 

[https://app.zenhub.com/files/2995118/7f58b7e7-7a5d-4576-8697-7bf3f0f1fbd9/download](https://app.zenhub.com/files/2995118/7f58b7e7-7a5d-4576-8697-7bf3f0f1fbd9/download)

When I test with this page https://wwwdev.ebi.ac.uk/gwas/depo-curation/reported-traits I get an error: 

![Screenshot 2022-01-14 at 14.57.17.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/36462c50-6dd6-49e4-808a-c7c6105921c0)

But this does not explain at what point the error occurred. 
There may be an issue with the special characters such as underscores? 

Some of the traits have been created because they are there when I search for them in the dev environment.

**Comment by ljwh2** [comment]
is this issue still outstanding @earlEBI ?

**Comment by earlEBI** [comment]
@ljwh2 yes.
