### ISSUE TITLE
Re-opening the submission GCP000274 for the suer Cathy Philippe 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#574]
The user Cathy Philippe has uploaded the wrong files for her submission GCP000274, and also filled the submission form incorrectly.

https://www.ebi.ac.uk/gwas/deposition/submission/61d7068b06ff200001948d1d

@sajo-ebi could you please re-open this submission for her?

**Comment by sajo-ebi** [comment]
@buniello have reopened the submission

**Comment by buniello** [comment]
thank you @sajo-ebi

**Comment by ljwh2** [comment]
@buniello can this ticket be closed?
