### ISSUE TITLE
GWAS Search always returns "clinical treatment" 

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#576]
In the GWAS search UI, whatever you search for, it always returns the "clinical treatment" trait in addition.
e.g. https://www.ebi.ac.uk/gwas/search?query=anything

**Comment by jdhayhurst** [comment]
It doesn't seem to be an issue with solr slim: http://ves-hx-7f.ebi.ac.uk:8983/solr/gwas_slim/select?q=anything returns nothing.

**Comment by sprintell** [comment]
@ljwh2 said: I don’t think we need to work on this urgently in this sprint, it’s been like that for a while. Next sprint is ok

**Comment by ala-ebi** [comment]
ui is issuing t[his request](http://ves-pg-7e.ebi.ac.uk:8983/solr/gwas_slim/select?wt=json&facet=true&facet.field=resourcename&rows=1000&start=0&defType=dismax&qf=title%5E2.0+synonyms%5E20.0+parent%5E2.0+text%5E1.0&q=text%3A%22anything%22+OR+title%3A%22anything%22+OR+synonyms%3A%22anything%22) when a search is done
the dismax flag seems to affect the search result adding 'clinical treatment' to it
a possible solution is to use edismax instead, which is being used for auto suggest already
