### ISSUE TITLE
Investigating the mapping pipeline for SNPxSNP interactions 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#577]
The user Seth Crosby reported a consistent behavior in our mapping pipeline for SNPxSNP interactions.
It looks like the mapping pipeline skips the first SNP, so that majority of mappins look like this:

**no mapped gene x gene(s)***

Below mappings shared by the user: 

No mapped genes x No mapped genes
PSORS1C1 x No mapped genes
RPL3P2 - WASF5P x MICA - LINC01149
No mapped genes x LINC02571
LINC02571 x HLA-S - MICA
HCG27 - HLA-C x LINC02571
No mapped genes x HCG27 - HLA-C
No mapped genes x PSORS1C1
No mapped genes x LINC02571 - HLA-B
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x No mapped genes
RNU6-283P - FGFR3P1 x MICA - LINC01149
PSORS1C1 x CCHCR1
No mapped genes x CCHCR1
No mapped genes x HCG27 - HLA-C
HCG27 - HLA-C x RNU6-283P - FGFR3P1
No mapped genes x C6orf15 - PSORS1C1
No mapped genes x HLA-B - DHFRP2
HCG27 - HLA-C x MICB - PPIAP9
RNU6-283P - FGFR3P1 x MICA - LINC01149
No mapped genes x No mapped genes
No mapped genes x LINC02571 - HLA-B
HCG27 - HLA-C x RNU6-283P - FGFR3P1
No mapped genes x No mapped genes
No mapped genes x RPL3P2 - WASF5P
No mapped genes x HCG27 - HLA-C
No mapped genes x PSORS1C1
No mapped genes x LINC02571
No mapped genes x HLA-C - USP8P1
HCG27 - HLA-C x LINC01149
No mapped genes x RPL3P2 - WASF5P
No mapped genes x WASF5P - LINC02571
RNU6-283P - FGFR3P1 x NOTCH4 - TSBP1-AS1
No mapped genes x LINC02571
No mapped genes x No mapped genes
No mapped genes x No mapped genes
No mapped genes x No mapped genes
No mapped genes x LINC02571
No mapped genes x LINC02571
HCG27 - HLA-C x No mapped genes
LINC02571 x HLA-S - MICA
TCF19 x HCG27 - HLA-C
No mapped genes x LINC02571 - HLA-B
No mapped genes x LINC02571
No mapped genes x LINC01149
No mapped genes x No mapped genes
LINC02571 - HLA-B x MICA - LINC01149
C6orf15 - PSORS1C1 x HCG27 - HLA-C
No mapped genes x DHFRP2 - RNU6-283P
CCHCR1 x C2
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x FGFR3P1
No mapped genes x No mapped genes
HCG27 - HLA-C x PSORS1C1, PSORS1C2
No mapped genes x No mapped genes
No mapped genes x HCG27 - HLA-C
No mapped genes x HCG27 - HLA-C
LINC02571 x MICB
No mapped genes x No mapped genes
No mapped genes x No mapped genes
HCG27 - HLA-C x No mapped genes
HCG27 - HLA-C x LINC02571
HCG27 - HLA-C x HLA-C - USP8P1
HCG27 - HLA-C x No mapped genes
HCG27 - HLA-C x LINC02571
HCG27 - HLA-C x HLA-C - USP8P1
PSORS1C1, PSORS1C2 x No mapped genes
PSORS1C1, PSORS1C2 x HLA-C - USP8P1
PSORS1C1, PSORS1C2 x LINC02571
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x USP8P1
No mapped genes x LINC02571
No mapped genes x LINC02571 - HLA-B
No mapped genes x USP8P1
No mapped genes x LINC02571
No mapped genes x LINC02571 - HLA-B
No mapped genes x No mapped genes
No mapped genes x RNF5
No mapped genes x PSORS1C1, PSORS1C2
No mapped genes x No mapped genes
No mapped genes x No mapped genes
No mapped genes x No mapped genes
LINC02571 x MICB
No mapped genes x HLA-C - USP8P1
No mapped genes x LINC02571
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
LINC02571 x HLA-S - MICA
LINC02571 x MICA - LINC01149
LINC02571 x No mapped genes
USP8P1 x HLA-S - MICA
USP8P1 x MICA - LINC01149
USP8P1 x No mapped genes
CCHCR1 x RNU6-283P - FGFR3P1
CCHCR1 x RNU6-283P - FGFR3P1
HCG27 - HLA-C x MICA
No mapped genes x HLA-C - USP8P1
No mapped genes x LINC02571
No mapped genes x HCG27 - HLA-C
No mapped genes x LINC02571
RNU6-283P - FGFR3P1 x PPIAP9 - RPL15P4
HCG22 x HCG27 - HLA-C
No mapped genes x HCG27 - HLA-C
No mapped genes x RPL3P2 - WASF5P
No mapped genes x PPIAP9 - RPL15P4
HLA-S - MICA x LINC02571 - HLA-B
LINC02571 - HLA-B x MICA - LINC01149
LINC02571 - HLA-B x No mapped genes
No mapped genes x MICB
HCG27 - HLA-C x LINC02571
No mapped genes x MICB-DT
No mapped genes x HCP5
No mapped genes x MICB-DT
No mapped genes x TSPAN9
No mapped genes x MICB-DT
No mapped genes x No mapped genes
No mapped genes x LINC01747 - KRT18P3
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x No mapped genes
No mapped genes x LINC02571
No mapped genes x USP8P1
No mapped genes x C2
No mapped genes x LINC02571 - HLA-B
No mapped genes x No mapped genes
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1
No mapped genes x RNU6-283P - FGFR3P1

**Comment by ljwh2** [comment]
Now fixed for majority of SNPs, awaiting further input from Ensembl for remainder. Closing since this is covered by goci#831 and goci#1157
