### ISSUE TITLE
Bulk unpublish to add associations - PMID 32929287

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#579]
Please unpublish all studies for PMID '32929287'    

I will then add associations through depocuration app and ask to republish.

**Comment by sajo-ebi** [comment]
@earlEBI have unpublished the studies kindly confirm

**Comment by sajo-ebi** [comment]
@earlEBI the studies have been published

**Comment by earlEBI** [comment]
@sajo-ebi great thanks!
