### ISSUE TITLE
Validation for submission 61f142fc7058c20001333554 still running

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#586]
The meta data for the submission has been validating for more than 2.5 hours. The submission has only 1 study, no associations and no sumstat data.

https://www.ebi.ac.uk/gwas/deposition/submission/61f142fc7058c20001333554

**Comment by ljwh2** [comment]
please look at this when you have time @jdhayhurst

**Comment by ljwh2** [comment]
Is this issue still outstanding @Santhi1901 ?

**Comment by Santhi1901** [comment]
@ljwh2 It got solved, Thanks
