### ISSUE TITLE
User request - title change for GCP000265

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#587]
A user has requested an edit to the title of their submission GCP000265
'61be1f35911f5a0001553d66'

Please change the title to: 
'Characterising metabolomic signatures of lipid-modifying therapies through drug target Mendelian randomization'

**Comment by sajo-ebi** [comment]
@earlEBI Updated the title for body of work

**Comment by earlEBI** [comment]
@sajo-ebi great, thank you!
