### ISSUE TITLE
Import button in curation interface remains active after being clicked

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#59]
After clicking the “Import” button, it remains active. It should be disabled once the data is imported, to prevent multiple import actions for the same submission.

For investigation: if the button _does_ remain active, what happens if it is clicked a second time? Is the import action repeated? How does this affect the imported data/studies?

**Comment by jstewart-ebi** [comment]
Disabled import button for successful import.

**Comment by eks-ebi** [comment]
Annalisa mentioned that this had become an issue again for a submission she was dealing with.

@buniello Could you please confirm and add any relevant details here?

**Comment by buniello** [comment]
The import button was not disabled after the successful import of the Ellinghaus submission (pre-published submission): https://www.ebi.ac.uk/gwas/deposition/submission/5ee1056f2c250200010558e5.
In fact, the button is still active now, even though the submitted and curated data have been made available to users in the Catalog.

**Comment by twhetzel** [comment]
I think part of the issue for the Import button still being active for the Ellinghaus submission may be related to the issue that the original placeholder study (requires review status) was curated vs. the intended imported study.

**Comment by buniello** [comment]
Same issue with "import "button for these two pre-published submissions:
https://www.ebi.ac.uk/gwas/deposition/submission/5ede2b89d1d92a0001920cf9
https://www.ebi.ac.uk/gwas/deposition/submission/5ee00d1ed1d92a000192189e

**Comment by buniello** [comment]
also tagging @tudorgroza and @ljwh2 to my latest comment
