### ISSUE TITLE
Delete submission GCP000288

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#590]
User created two identical submissions. 
One is now valid: '61f1f38b7058c20001333a77'

The invalid one should be deleted to avoid later confusion when linking PMID: '61f33f542101880001fb71d7'.

**Comment by ljwh2** [comment]
@earlEBI please confirm whether this is still required

**Comment by earlEBI** [comment]
Doesn't seem to be, no. I'll close the issue.
