### ISSUE TITLE
Re-opening a submission for Arwa 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#591]
Arwa had a problem with importing this submission - perhaps related to the submission app problems from last week https://www.ebi.ac.uk/gwas/deposition/submission/61f417323893270001d3376d.

She now needs to edit this submission, could you please re-open it @sajo-ebi?

**Comment by sajo-ebi** [comment]
@buniello the submission has been reset

**Comment by buniello** [comment]
thank you @sajo-ebi
