### ISSUE TITLE
Harmonization file missing

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#594]
A user has reported about missing harmonization file in gwas-info dated 01-02-2022

http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90079001-GCST90080000/GCST90079535/

**Comment by jdhayhurst** [comment]
file has been queued for harmonisation. Please be aware there are thousands in the queue and limited resources allocated to process these so it may take some time for these to come through

**Comment by jdhayhurst** [comment]
file was released 13th Feb
