### ISSUE TITLE
Import button is broken for completed submissions

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#595]
Two submissions have been completed in deposition, and are available to view in the curation app, but the button to *import* them is unavailable. It seems like they may be stuck in an incorrect status that prevents them from being "ready to import".

Both are republished submissions from external submitters, including sumstats and metadata:

https://www.ebi.ac.uk/gwas/curation/submissions/61a8f605911f5a00015488ab
https://www.ebi.ac.uk/gwas/curation/submissions/617978a63d37930001a57fd8

**Comment by eks-ebi** [comment]
@earlEBI I think this is fixed now, after rerunning the deposition sync

**Comment by earlEBI** [comment]
@eks-ebi  great, thank you
