### ISSUE TITLE
Truncated harmonised file on FTP

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#596]
Truncation found for 2 harmonised file:
ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST009001-GCST010000/GCST009982/harmonised/31969693-GCST009983-EFO_0003761.h.tsv.gz
ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90000001-GCST90001000/GCST90000291/harmonised/32814899-GCST90000291-EFO_0008205.h.tsv.gz

GCST009983 has only variants from chr 1-11 and GCST90000291 chr 1-19.
Unharmonised version of both these studies contains all chromosome.
Reported by user in gwas-info dated 02-02-2022

**Comment by jdhayhurst** [comment]
The harmonised files for GCST009983 and GCST90000291 were indeed truncated partway through a line, so it looks as though there was some corruption. I've removed the affected files from the FTP and have queued the files for harmonisation again.

**Comment by jdhayhurst** [comment]
GCST009983 is complete. Waiting on GCST90000291
