### ISSUE TITLE
Replacing a corrupted file with new one on public FTP - user request 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#598]
The user Alexander Guojonsson has identified a problem with one of his submitted files and has uploaded a replacement file onto our private FTP. This now needs to be moved onto the public FTP.

private FTP Directory: Guðjónsson_GCST90088598 
file hecksum: 1ade54716c1968f0983abac00a88dc01
public FTP directory: GCST90088001-GCST90089000/GCST90088598/

**Comment by ljwh2** [comment]
closing due to duplicate ticket gwas-user-requests#48
