### ISSUE TITLE
GWAS Zooma data loaded on test

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#601]
Hi there Yomi, Laura & Elliot,

Recall that we wanted to replace Zooma reading the GWAS database directly with a file upload. The file upload is now available on Zooma test: http://snarf.ebi.ac.uk:8580/spot/zooma/. Note that you will have to be on the VPN to access Zooma test.

 Changes we needed to make to the file to get it to upload were

 (1) Add a header: STUDY    BIOENTITY    PROPERTY_TYPE PROPERTY_VALUE    SEMANTIC_TAG

 (2) File needs to be in TSV format rather than CSV format. This ensures that commas in text will not be seen as a delimiter.

 Suggested next steps:

 (1) GWAS to provide TSV file with header as describe above.

 (2) GWAS to provide a permanent file location from where Zooma can download this file. This could be from example ftp://ftp.ebi.ac.uk/pub/databases/... or say Github. The main point is that it should be a permanent location from which we can fetch the latest GWAS data.

 (3) Once we have (1) and (2) we will again test on Zooma test.

 (4) When (3) is successful we will update Zooma prod accordingly.

 If you have any questions, please let me know.

 Keep well,

**Comment by sprintell** [comment]
Sample output TSV File here: https://docs.google.com/spreadsheets/d/1AzwwTvTylRRgyyimSI0RLSA9NnfOT3LM3OSbwpnX-fs/edit#gid=1537702113

**Comment by ljwh2** [comment]
Needs documentation @sprintell
