### ISSUE TITLE
Adding EFO in bulk to curation app

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#607]
I have added the required EFO and the respective link in the spreadsheet

https://docs.google.com/spreadsheets/d/1drot5vkiXYYfT_uk48Aec6WMB5YVqeGTVitEoMY05-8/edit#gid=0

**Comment by ljwh2** [comment]
@Santhi1901 what's the deadline for this please?

**Comment by Santhi1901** [comment]
atleast 2 days before next data release

**Comment by Santhi1901** [comment]
@ljwh2 it is still not added in the curation app

**Comment by ljwh2** [comment]
EFO release is now out including fix for the duplicate URIs so you should be able to add these now @ala-ebi @Santhi1901 
Note EFO have some problems with the update to the OLS website (working on a fix) but should be available in the API
