### ISSUE TITLE
Check that updates to PMID 33040646 have been synced to deposition

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#614]
I added 11 studies (--> new total of 12 studies) to this publication in the curation interface.

Could you please check that the new studies have been synced to the deposition interface? All 12 studies should appear in the pre-filled template that will be generated when the author creates a sumstats-only submission.

**Comment by sajo-ebi** [comment]
HI @eks-ebi I can see 12 studies in the Deposition Side , so for a fresh sumstats submission the user should get all those in prefilled template

**Comment by eks-ebi** [comment]
Great thanks @sajo-ebi !
