### ISSUE TITLE
Email to submitter after successful submission is missing text that was previously there

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#624]
The email that is sent to submitters after a successful submission appears to be missing some text that was previously added to explain the post-submission data release process.

Here is an example of the full text of the email as it should be, and as it was previously implemented (see old ticket: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/321). The section that is now missing is in _italics_.

> Dear ____,
> 
> The summary statistics for 19169253 - Deletion of the late cornified envelope LCE3B and LCE3C genes as a susceptibility factor for psoriasis. by de Cid R et al., were successfully validated and submitted to the GWAS Catalog.
> 
> Following submission the accession ID(s) for your submission will be available to download by pressing on the 'Download Study Accessions' button on the studies page.
> 
> _For more information about how and when your data will become publicly accessible, please see our documentation pages: https://www.ebi.ac.uk/gwas/docs/submission#link-15_
> 
> Thanks for sharing your data with us.
> 
> Best wishes,
> GWAS Catalog team

Here is a recent example of the email with the last paragraph missing:

> Dear Elliot Sollis,
> 
> The summary statistics for 34424336 - Different Pigmentation Risk Loci for High-Risk Monosomy 3 and Low-Risk Disomy 3 Uveal Melanomas. by Mobuchon L et al., were successfully validated and submitted to the GWAS Catalog.
> 
> Following submission the accession ID(s) for your submission will be available to download by pressing on the 'Download Study Accessions' button on the studies page.
> 
> Thanks for sharing your data with us.
> 
> Best wishes,
> GWAS Catalog team

**Comment by sajo-ebi** [comment]
Code changes have been deployed in Prod
