### ISSUE TITLE
Editing a submission in depo-curation should not trigger resending validation emails to the original submitter

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#627]
When a curator edits a submission in depo-curation, the original submitter of the submission (in deposition) should not receive a new email about the (successful or unsuccessful) validation of their submission.

**Comment by sajo-ebi** [comment]
Started Working on this ticket , have identified the section where the email was sent , it was for metadata only submission

**Comment by sajo-ebi** [comment]
Deployed the fix in Prod
