### ISSUE TITLE
Bulk unpublish studies - Backman PMID 34662886

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#629]
Please unpublish all studies so I can add associations.

**Comment by ljwh2** [comment]
@earlEBI  what is the deadline for this please

**Comment by earlEBI** [comment]
@ljwh2 I need this to be done in time to resubmit, deal with any issues (create tickets to push through sumstats etc) and republish before an intervening data release. 
So, if the next data release is due to start on the 28th, I would need this done today. Otherwise, it should be done ASAP after the next data release goes through.

**Comment by ljwh2** [comment]
@sajo-ebi just a reminder to do this asap please

**Comment by sajo-ebi** [comment]
@earlEBI the pubmedId has been unpublished , kindly confirm

**Comment by earlEBI** [comment]
Thanks Sajo, please can you change status of all 7,972 studies to 'publish study' before the data release?

**Comment by earlEBI** [comment]
@sajo-ebi confirmed, thanks
