### ISSUE TITLE
Add link from submission summary page to a view of the imported studies

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#63]
After importing a submission from the submission summary page, curators should be able link directly to a view of the imported studies and begin editing them.

Link either to Curation Home, filtered by the PMID of the imported submission, or to the publication-centric view for that PMID. This decision (which location to link to) should wait until more curators have started using the new submission/import process and we can collect more information about the preferred workflow.

**Comment by jstewart-ebi** [comment]
Added link to Publication page from View Submission.
