### ISSUE TITLE
Change FTP sync behaviour wrt to unpublishing

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#632]
When a curator set IS_PUBLISHED to FALSE, the ftp sync revokes public permissions on the FTP. This is no longer the desired behaviour. Instead, point to the "permanently unpublished from catalog" field as mentioned in the comment here:https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/gwas-user-requests/51

**Comment by jdhayhurst** [comment]
@sprintell please could you expose the "Permanently unpublished from Catalog" field with the curation API (https://www.ebi.ac.uk/gwas/curation/api/v1/public/studies) so that the sync script can access this value. I don't know how this value is mapped in the DB.

**Comment by eks-ebi** [comment]
Here is the "Permanently unpublished from Catalog" status in the status field, e.g. on the Curation homepage in the list of filters:
![Screenshot 2022-03-09 at 11.28.03.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/e57e4e1b-19e6-48eb-851a-f9792df050b7)

There are also 2 studies in the Catalog that currently have this status:
study ID: `10065894` and `6425`

**Comment by jdhayhurst** [comment]
@sprintell how much work do you think it is to implement in the curation API?

**Comment by jdhayhurst** [comment]
Removed the "IS_PUBLISHED" status from the logic

**Comment by ljwh2** [comment]
Ok to release. Create new ticket for downstream work.
