### ISSUE TITLE
Bug in construction of sample description for replication samples after import

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#64]
This bug concerns studies imported into the curation interface from deposition.

For replication samples only, when the Number of cases and Number of controls are not given, they are being incorrectly imported as 0 in the curation interface - and therefore the free-text replication description incorrectly reads “0 cases, 0 controls” (Example: Chibnik LB 28322283). Instead these fields should be blank.

**Comment by eks-ebi** [comment]
Tested in snoopy:9680.

The original issue is now fixed: the free-text replication description is now constructed using the correct numbers.

But there are two other minor issues related to the replication sample that are still incorrect:
1. In the structured sample table (bottom of screen), the Number of Cases and Number of Controls still appear as "0". No value was entered in the spreadsheet for these fields, so they should appear blank in the curation interface, rather than 0. It is incorrect to say that there are 0 cases and 0 controls for this study, instead they should be undefined.
2. The replication sample has "NR" as the Ancestry Category: in this case, the free-text Replication Sample Description (top of screen) should appear as "369 individuals" not "369 ancestry individuals".

![Chibnik_screenshot](https://user-images.githubusercontent.com/42406380/81300753-fb4b3100-906f-11ea-83bd-7052ef7207ed.png)

**Comment by eks-ebi** [comment]
Let me know if you prefer me to make new GitHub issues for these two follow-up comments.

**Comment by tudorgroza** [comment]
@eks-ebi - I'm working on this ticket. Do you have by any chance the template / spreadsheet you've used for testing? Thank you.

**Comment by eks-ebi** [comment]
@tudorgroza Just emailed you the template for this example.

**Comment by tudorgroza** [comment]
Thank you @eks-ebi . Are you certain that the bug is still there? The current code seems to fix it ...

**Comment by eks-ebi** [comment]
Bug 1 appears to be fixed now. The case and control spaces in the curation app are correctly left blank when these were not specified in the the submitted template:

See test submission here:
> http://193.62.54.159/gwas/deposition/submission/5f101b033b86f300014d7379
And the review page here:
> http://snoopy.ebi.ac.uk:9680/gwas/curation/submissions/5f101b033b86f300014d7379
And the sample page showing the imported sample numbers here:
> http://snoopy.ebi.ac.uk:9680/gwas/curation/studies/61989519/sampledescription

Bug 2 is improved, but the "Replication Sample Description" field still not exactly what we would expect. It says "900 NR individuals", but ideally, when the ancestry = NR, it should be omitted, i.e.
> 900 individuals

![Screenshot 2020-07-16 at 10.39.34.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/b08168ef-3172-4e8e-a860-92a389eb7aec)

**Comment by tudorgroza** [comment]
@eks-ebi - thank you. I'll fix that.

**Comment by twhetzel** [comment]
@eks-ebi can you also email me the template?

**Comment by twhetzel** [comment]
@eks-ebi this is available for testing on Snoopy 9680

**Comment by eks-ebi** [comment]
@twhetzel I emailed you the original template - but the links in my comment above are for the latest test.

**Comment by eks-ebi** [comment]
Tested again 2020-07-20 with new submission:

> http://193.62.54.159/gwas/deposition/submission/5f156a8f3b86f30001dbe74a

Reviewed in curation interface here (all looks OK):

> http://snoopy.ebi.ac.uk:9680/gwas/curation/submissions/5f156a8f3b86f30001dbe74a?

And after import:

> http://snoopy.ebi.ac.uk:9680/gwas/curation/studies/61989695/sampledescription

The sample information is all correctly filled in and the sample description reconstituted as expected
![Screenshot 2020-07-20 at 11 02 29](https://user-images.githubusercontent.com/42406380/87925721-98671480-ca78-11ea-8c7c-868e2ed9f290.png)

**Comment by eks-ebi** [comment]
Closed by mistake (wrong process), so now reopening - over to @twhetzel now...
