### ISSUE TITLE
Deleting a duplicate "importable" submission entry for Guðjónsson PMID 35078996 - submission ID 6198ce0f81051b000178cee4

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#640]
There is a duplicated "importable" submission entry for Guðjónsson PMID 35078996 in the curation app (first in list here http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/submissions). Probably due to a duplicated sync process for this submission?

In practice, the all studies from the Guðjónsson paper have already been imported and successfully published in the Catalog: 

http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/publication/35078996
https://www.ebi.ac.uk/gwas/publications/35078996

Therefore this duplicated entry should be deleted to avoid downstream problems if someone clicks import by mistake.

**Comment by ljwh2** [comment]
Noting this could be causing issues in the data table displayed on the search UI - studies from this publication appear with no author or title

**Comment by buniello** [comment]
Another duplicate  importable submission entry appeared in the curation app for guindo-martinez PMID 33893285:
http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/submissions.
This has to be deleted as well as it may create problems downstream.

**Comment by sajo-ebi** [comment]
@buniello can you confirm the submisisonId to be deleted for pmid '33893285 ' is '6185126281051b00017070d1'

**Comment by buniello** [comment]
yes, thanks @sajo-ebi!

**Comment by ljwh2** [comment]
@sajo-ebi @buniello can you confirm that the duplicate submission from Gudjonnson originally mentioned in the ticket was deleted please, and when? That publication is still appearing with errors in the search UI, but maybe we need to wait for the next DR for it to clear.

**Comment by buniello** [comment]
yes, it's not here anymore: http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/submissions @ljwh2

**Comment by sajo-ebi** [comment]
@ljwh2 for Search UI to be updated  we need for DR to finish

**Comment by buniello** [comment]
@sajo-ebi @buniello the current pre-published sumstats download still has the "NA" entries for Guodjonsson

**Comment by sprintell** [comment]
Waitin for the next data release

**Comment by buniello** [comment]
@ljwh2just a reminder that this should be checked after next DR

**Comment by ljwh2** [comment]
Prepublished table still contains NA entries for this publication after the DR. Closing this ticket and opening a new one to focus on that issue.

**Comment by ljwh2** [comment]
Adding a comment that the submission for Gudjonsson (GCP000257) seems to have been deleted entirely from the database. It is not accessible in depocuration for editing. This means curators cannot update the traits.
