### ISSUE TITLE
data_snapshot-GOCI-2181.py needs to be put under version control and migrated to codon

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#643]
See https://docs.google.com/document/d/1w1AZl0rZtYMhvf2pqc3LVeeYfCYrJxj2gmEFcqKhwUg/edit# for more details. This script runs weekly, but is not under version control. We should add it to the gwas-utils repo and set up a the crontab on codon to schedule it.

**Comment by jdhayhurst** [comment]
Strong dependency on database and secrets stored on filesystem. 
- Refactoring and placing in gwas-utils

**Comment by jdhayhurst** [comment]
It does work but in a fundamentally unportable way, in that it appends to a file that lives on the filesystem. Will migrate that file for now, but this could be rewritten in future so that it can be run from anywhere (ideally using the curation API)

**Comment by jdhayhurst** [comment]
Cron setup on for spotbot on codon - confirm working at next scheduled execution

**Comment by jdhayhurst** [comment]
@earlEBI Please could you let me know if this is working correctly - the next run will be on Sunday. I have deactivated the current (old) implementation and activated the new one.

**Comment by earlEBI** [comment]
@jdhayhurst yes, I received both data release and curation snapshot emails on Sunday as usual, thank you
