### ISSUE TITLE
Bulk unpublish Naqvi PMID 33821002 to add associations

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#650]
Please unpublish all studies for PMID 33821002 so I can add associations and republish. 

This needs to be done before Wednesday 23rd March to allow time to republish before next data release.

**Comment by sajo-ebi** [comment]
@earlEBI the studies have been unpublished, kindly confirm

**Comment by earlEBI** [comment]
@sajo-ebi Thanks Sajo. Please could you republish all studies except '80465123' before the next DR? thank you

**Comment by sajo-ebi** [comment]
Hi @earlEBI Studies have been published , kindly verify for '80465123' whether it is not published

**Comment by earlEBI** [comment]
@sajo-ebi perfect, thank you!
