### ISSUE TITLE
Set up self managed gitlab runner

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#651]
As developers, we need a self hosted runner on the new gwas-gromit VM in Harlow to support GitLab jobs. 

The present shared runner used by the GWAS project CI/CD has been problematic and has gone from bad to worse in the past weeks, now almost impossibile to use. The web prod has responded that the shared runners should not be relied on for production.

**Useful info from previous conversation with IMPC Project team:**
There are different types of runners that can be set up, the IMPC project has used a docker runner, but that may not be the best option if working with docker-compose. There are also some caching issues to consider. Any machine you put together will need some kind of task to do some house keeping as otherwise the disk can fill up very quickly. Also worhty of note is that if DinD is used at all there will be need to make the runner a privileged user which is definitely a security risk.

[Confluence Guide on Installation:](https://www.ebi.ac.uk/seqdb/confluence/display/SPOT/Gitlab+-+Creating+Runners+on+an+external+VM )

**Comment by jdhayhurst** [comment]
TODO:
- figure out and document how the gitlab logs work
- determine whether the resources can support another runner or whether we should provision another VM

**Comment by jdhayhurst** [comment]
- allocated more free space to the /var dir
- increased the concurrency to 4
