### ISSUE TITLE
Investigating integration of Exome sequencing summary statistics from Astra Zeneca, linked to Wang Q. PMID 34375979 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#654]
Both Open Targets and the SAB have prioritised the integration of exome sequencing results from AstraZeneca: https://azphewas.com/.
While we are waiting for the AZ team to prepare their data for submission to the Catalog, we have also obtained the summary statistics from the Open Targets team. @ljwh2 would like to explore the option to wrangle and submit the data internally to save time.
The AZ team have shared links to four folders with us, which I have downloaded onto my home directory in the codon cluster:
![Screenshot 2022-03-22 at 16.31.49.png]
(https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/d531c183-780c-4807-9c1c-8627ebc89fc6)

[buniello@codon-login-04 ~]$ ls -la
total 660
drwx--x--x    4 buniello ensembl   4096 Mar 22 16:04 .
drwxr-xr-x 2864 root     root    225280 Mar 21 15:14 ..
-rw-rw-r--    1 buniello spot     94532 Mar 22 16:02 azphewas-com-450k-exwas-binary.csv.bz2
-rw-rw-r--    1 buniello spot     94700 Mar 22 16:02 azphewas-com-450k-exwas-quantitative.csv.bz2
-rw-rw-r--    1 buniello spot     95898 Mar 22 16:04 azphewas-com-450k-phewas-binary.csv.bz2
-rw-rw-r--    1 buniello spot     94494 Mar 22 16:04 azphewas-com-450k-phewas-quantitative.csv.bz2

I am not, however, able to open the folders and investigate what's inside. @jdhayhurst could you please investigate that and provide an opinion on how much work it would require to format the data in house?

**Comment by ljwh2** [comment]
Closing this for now as AZ seem fully engaged to format and submit themselves
