### ISSUE TITLE
Beta not imported into curation interface from deposition

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#66]
Beta was entered in the submission template but was not imported into the curation interface - Example Buchwald J 32157176.

**Comment by eks-ebi** [comment]
Tested in snoopy:9680 - Buchwald J 32157176 and Kristjansson RP 26838040.

The main bug is now resolved - "Beta" is now imported correctly for these publications.

But there is a related issue - "Beta unit" is not being imported for these studies.

**Comment by jstewart-ebi** [comment]
Fixed import of beta unit.
