### ISSUE TITLE
Richardson - Blocker to DR - cannot publish 18 studies which have 'no mapping assigned' 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#665]
All but 18 studies are now in publish state from PMID '35213538'. 
These 18 studies have some approved associations, but some remain unapproved with the following error:
'Cannot approve all associations as no Mapping assigned'

![Screenshot 2022-03-29 at 09.00.57.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/c88e6afe-f492-4a11-a4a7-b23419a532fc)

List of affected studies: 

[https://app.zenhub.com/files/2995118/d9c31a90-5690-4bb0-9266-57679b8985ee/download](https://app.zenhub.com/files/2995118/d9c31a90-5690-4bb0-9266-57679b8985ee/download)

**Comment by ljwh2** [comment]
Is this reolved?

**Comment by earlEBI** [comment]
@ljwh2 yes
