### ISSUE TITLE
Investigating file formats for Yueji

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#666]
I am working with the studies of publication 29346644, and there are four studies (GCST005359, GCST005360, GCST005358, and GCST009144). I found study GCST005359 and GCST005360 are also on your Study Status Tracker list without any reason they cannot be harmonised. However, I found the data is strange in the following ways (example of GCST005359):
There are two files for this study: YanQ_29346644_allele_freq.txt.gz (allele file) and YanQ_29346644_GAprogression_wo_base_severity.txt.gz (data file).
1. MAF in data file is different from AF in the allele file.
 e.g. MAF of rs8138437 is 0.159528, while it is 0.165713708195516 in the AF column of the allele file
2. A same rsid have different positions in the file:
e.g. for rs113940759 non-duplicate records, two records for the position 22:42247503  and two for 22:42247507 (which rsid rs113940759 in hg37 is 42247508 )
3. The same position has different data in the file:
example: for rs113940759 22:42247503 position, it also has two records without any distinction reason
I found one multiple records site in chr22 and I am not sure how many similar sites appeared in other chromosomes.
Could I ask your suggestions on the following things?
1. which allele frequency should be believed
2. how should I deal with multiple records for a same rsid.

**Comment by ljwh2** [comment]
Now resolved by input from user, please confirm @buniello ?

**Comment by buniello** [comment]
Yes, that is now resolved and I will close this ticket.
