### ISSUE TITLE
Display the current EFO release in the Search UI

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#669]
A user has requested to be able to see the EFO release/version that is in use for the current GWAS Catalog release.

This could be added to the end of this list of information in the Search UI results page:

![Screenshot 2022-03-30 at 13.43.19.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/090677b7-d29d-4835-926d-cbcf735e6040)

**Comment by eks-ebi** [comment]
EFO releases and their dates can be looked up at https://github.com/EBISPOT/efo/releases

**Comment by ala-ebi** [comment]
confirmed after release, can be closed
