### ISSUE TITLE
Update how background EFO traits are assigned in Depo-curation to match how main EFO traits are assigned

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#670]

**Comment by eks-ebi** [comment]
If possible, I think it would be most efficient if main and background EFO traits can be assigned to studies using the **same** operation, e.g. using two different columns in the same .tsv bulk-assigning template.

**Comment by ala-ebi** [comment]
@eks-ebi I have a few questions: 
1. Does this mean we should add another Background EFO trait column to the *Study | EFO | Reported trait* template?
2. Should the behaviour be the same as the STUDY-EFO assignment? Meaning the existing value will be overwritten by the new one (including an empty value).
3. Should we accept multiple background EFOs (pipe separated)?

**Comment by eks-ebi** [comment]
@ala great questions!

1. Yes, I would add an extra _Background EFO_ column to the template
2. The behaviour should be the same: any existing value will be overwritten by the new one (including an empty value) - this will be especially important for background traits, as we often need to revise how we represent them and that might include removing the background trait entirely
3. Yes, we should accept multiple background EFOs (pipe separated)

**Comment by eks-ebi** [comment]
Oops!

**Comment by ala-ebi** [comment]
depocuration deployed, need to implement import

**Comment by ala-ebi** [comment]
done.
Things to test: 
1. assigning Background traits using the UI option in study details side drawer
2. assign Background traits using the Study/Trait mapping template
3. importing in one of the above scenarios, or combine both (assign with file then add more with UI)

**Comment by eks-ebi** [comment]
sorry for delay @ala-ebi. These are now tested in wwwdev:

1. assigning Background traits using the UI option works perfectly for both single and multiple EFO terms - DONE
2. assigning Background traits using the template also works - DONE
3. a possible issue with the import - I used the template to add background EFO terms to just 5 studies (study tag 253-257) in this submission (https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/62cf174ffd97600001ce3f8f) and also made a manual UI edit to add an additional background EFO for one of those studies (257). I left the remaining studies unedited (i.e. no background EFOs). When I look at the import preview for this submission (http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/submissions/62cf174ffd97600001ce3f8f?), the same single background EFO looks like it will be imported for every study in the submission, including the studies where no background EFO was added, as well as the study (257) where I added an extra EFO using the UI.

**Comment by eks-ebi** [comment]
the error above was only seen in the import preview - after actually clicking 'import', the expected data was imported into the curation interface

**Comment by sprintell** [comment]
@eks-ebi could youn please confirm this is ok, and should be be deployed

**Comment by eks-ebi** [comment]
Yes, this is ok and can be deployed
