### ISSUE TITLE
Submission ID link in prod version of Depo-Curation still links to wwwdev

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#671]
In the production version of Depo-Curation, at the top of each submission page (e.g. https://www.ebi.ac.uk/gwas/depo-curation/submissions/6241c47e78a7f500019c78f0) there is a link attached to the submission ID in the breadcrumbs that links to the Deposition interface.

Currently, this is still pointing to e.g. https://wwwdev.ebi.ac.uk/gwas/deposition/submission/6241c47e78a7f500019c78f0
whereas it should point to the production version of Deposition.

**Comment by sprintell** [comment]
@ala-ebi will push this to production and @eks-ebi  will test
