### ISSUE TITLE
Updated documentation / FAQ page. 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#672]
Made an edit to documentation here: https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/faq-content.adoc

For release.

**Comment by sprintell** [comment]
Pls confirm here http://snoopy.ebi.ac.uk:9580/gwas

**Comment by earlEBI** [comment]
I will confirm as soon as I see the snoopy link is working again.

**Comment by earlEBI** [comment]
@sprintell Confirmed looks good on Snoopy, thanks
