### ISSUE TITLE
Reopening submission https://www.ebi.ac.uk/gwas/deposition/submission/622a122378a7f500016a5342

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#675]
Hi @sajo-ebi could you please reopen/reset submission https://www.ebi.ac.uk/gwas/deposition/submission/622a122378a7f500016a5342 so that i can also add sumstats files IDs? 
I will submit both metadata and summary statistics

This is quite urgent as i am going on leave from Thursday - thank you!

**Comment by sajo-ebi** [comment]
@buniello submission has been reset, kindly confirm

**Comment by buniello** [comment]
yes, it looks good, thanks @sajo-ebi
