### ISSUE TITLE
Add reciprocal links for genes in IMPC and GWAS Catalog

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#677]
Request from Helen:

>I need to promote the visibility of the IMPC data and I'd like to link from the genes page to IMPC where we have data.
>Could you let me know what format do you need these in and when could these links be implemented by?

This needs:

1. Initial investigation of data format in IMPC
2. Specifications on what we need from them to link to IMPC
3. Discussion with IMPC devs on what format they need data from us.

**Comment by ljwh2** [comment]
Note, this is high priority from Helen

**Comment by ljwh2** [comment]
More notes are here: https://docs.google.com/document/d/1Yvui2q7CDx0X8PHg3TWm_6nGf28laFSeooukGBr9gLE/edit?usp=sharing Robert confirmed the mouse to human gene mapping data is now available in the API

**Comment by ljwh2** [comment]
User story: 
As a user of the GWAS catalog, when I search for a gene, I want to be able to access data for the mouse ortholog (equivalent gene) in IMPC. I want to access this via the most up to date mapping from IMPC, so this should be updated every time the GWAS Catalog releases data. The mapping is available via IMPC’s API. 
The button should appear on the GWAS Catalog gene page (which is based on HGNC gene names) and link to the relevant page in IMPC, based on the MGI identifier retrieved from the API, e.g.
https://www.ebi.ac.uk/gwas/genes/ADAMTS1
Links to 
https://www.mousephenotype.org/data/genes/MGI:109249
The button should appear in the info box with text “Mouse ortholog in IMPC” (see screen shot). 

In cases where the GWAS gene does not have an ortholog in IMPC, I do not want to see a button, as there is nothing to link to in IMPC. In cases where the mouse genes have a valid ortholog but no phenotyping data, I do want to see the button and link to the relevant page in IMPC, e.g. https://www.mousephenotype.org/data/genes/MGI:2152878

**Comment by ljwh2** [comment]
We will need to get guidance on  how to retrieve the mapping from the IMPC API from Robert rwilson@ebi.ac.uk

**Comment by sajo-ebi** [comment]
UI changes have been deployed in Dev environment @ljwh2 you can test the functionality in Dev1 [Gwas SNoopy](http://gwas-snoopy.ebi.ac.uk:9780)

**Comment by ljwh2** [comment]
Tested for genes with homologs, without homologs and with no phenotyping, all looks good. We need to add some documentation (FAQ) I will work on this asap

**Comment by ljwh2** [comment]
@sajo-ebi just asking here for the record - you said we would take an offline dump of IMPC data to avoid calling API each time. What is the plan for updating this please?

**Comment by sajo-ebi** [comment]
@ljwh2 there is a scheduler which runs each day in morning which will refresh the Impc data , in addition have also created an API which can be called to do an on demand Data refresh.

**Comment by jdhayhurst** [comment]
updated FAQ on documentation branch: https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/faq-content.adoc#23-how-can-i-find-the-mouse-orthologs-in-impc-for-the-genes-in-the-gwas-catalog

**Comment by ljwh2** [comment]
Looks good thanks @jdhayhurst
