### ISSUE TITLE
Change "Readme file" column header in submission template

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#68]
Change "Readme file" column header in submission template from "Readme file" to "Readme text"

Change documentation (submission instructions) to reflect this change

**Comment by twhetzel** [comment]
@jdhayhurst was this update released?

**Comment by jdhayhurst** [comment]
done

**Comment by Santhi1901** [comment]
@jdhayhurst  checked and it is working column header says Readme text
