### ISSUE TITLE
Enable assigning EFOs to studies one-by-one

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#682]
Currently, reported traits can be assigned to studies either through bulk template upload, or individually in the user interface. However, EFOs can only be assigned through the bulk template upload.

Curators should also be able to assign EFOs to individual studies in the UI, as for reported traits. The field in the UI where EFOs would be added is already there, but not yet functional.

**Comment by eks-ebi** [comment]
I am able to add individual EFOs to the right field in the side panel, e.g. https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/61e9424581051b000160458e

![Screenshot 2022-06-23 at 11.04.32.png]
(https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/baf7446a-055d-43ff-809d-fede97c4b3b0)

However, the new EFOs do not appear in the study table after I save them, so I don't know if they've really been saved or not:

![Screenshot 2022-06-23 at 11.05.47.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/8981b348-21f2-447d-b88e-de898e89f366)

**Comment by eks-ebi** [comment]
Also, sometimes a study already has an EFO, which is displayed in the study tab table, e.g. https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/61dc6fa081051b0001edaf70

![Screenshot 2022-06-23 at 11.18.52.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/d19ff677-33d3-4faf-99c0-cecf31c57fd0)

But when I click on the study, that EFO is not displayed in the field for individually adding new EFOs:

![Screenshot 2022-06-23 at 11.19.58.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/385c6df7-d446-4802-af2c-615aa9c33e5d)

It seems like these two UI features are not being updated from the same source

**Comment by ljwh2** [comment]
@eks-ebi to confirm

**Comment by eks-ebi** [comment]
tested and working ok
