### ISSUE TITLE
Reported trait similarity analysis in depo-curation gives 'an unexpected error occurred'

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#684]
When uploading a set of reported traits for similarity analysis, the depo-curation page consistently fails and returns 'an unexpected error occurred'.

Example templates attached:

**Comment by eks-ebi** [comment]
Here is one (very large) example of a template that failed analysis:

[https://app.zenhub.com/files/2995118/1d47e786-3e9d-4bbc-84a5-d9e7202ce7fb/download](https://app.zenhub.com/files/2995118/1d47e786-3e9d-4bbc-84a5-d9e7202ce7fb/download)

(note: it was uploaded to depo-curation as a .tsv but that can't be attached in Zenhub, so I just changed it to .txt to upload it here)

**Comment by eks-ebi** [comment]
@earlEBI please add any other relevant details or examples

**Comment by earlEBI** [comment]
[Mbatch_similarity.txt](https://github.com/EBISPOT/goci/files/8440988/Mbatch_similarity.txt)

Another example of a list of traits I tried to analysed but only got a vague error message returned.

**Comment by ljwh2** [comment]
@eks-ebi @earlEBI Just to clarify, is this a problem with all uploads to the similarity analysis or only these specific examples? In Elliot's example I can see some of the traits have inverted commas, does it work if you remove them?

**Comment by earlEBI** [comment]
All uploads. Just tried it again with a .txt and .csv file with only a few traits and got the same vague unexpected error:
[similarity test.csv](https://github.com/EBISPOT/goci/files/8519986/similarity.test.csv)
<img width="733" alt="Screenshot 2022-04-20 at 10 02 29" src="https://user-images.githubusercontent.com/61545198/164192299-5c0e65b9-0697-4d1d-9471-26fa6fbcdb51.png">

<img width="1208" alt="Screenshot 2022-04-20 at 10 01 25" src="https://user-images.githubusercontent.com/61545198/164192128-91fc8c7d-f309-4c9a-bc1d-68fb2999b113.png">

**Comment by ljwh2** [comment]
@earlEBI @eks-ebi has this been fixed by the login timeout issue?

**Comment by earlEBI** [comment]
I just tried a small file and it did work although it took about a minute for 5 traits. Not sure if the threshold is maybe set too low.

**Comment by ljwh2** [comment]
@earlEBI Could you please create a new ticket for that? I will close this one
