### ISSUE TITLE
Re-publishing Suhre PMID:28240269

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#687]
Re-publishing 1124 studies for https://www.ebi.ac.uk/gwas/curation/publication/28240269 before the next data release

**Comment by sajo-ebi** [comment]
@Santhi1901 The studies have been published for '28240269' . Kindly  verify & confirm.

**Comment by ljwh2** [comment]
@Santhi1901  please confirm this ticket can be closed now?

**Comment by Santhi1901** [comment]
This can be closed.
