### ISSUE TITLE
Assigning EFOs to studies should accept multiple EFOs per line 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#693]
Curators need to be able to assign multiple EFO terms to the same study. This is currently possible by creating 2 rows for the same GCST as shown below.

[Screenshot 2022-04-19 at 17.38.39.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/655da223-d794-46ae-b015-d8ab6d589611)

Curators would find it easier to use a template that permits the upload of multiple EFO traits on one line, separated by a pipe, instead of creating additional rows or uploading the template multiple times.

![Screenshot 2022-04-19 at 17.38.12.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/3d93cee1-a1ef-495e-baaf-06318b487748)!

**Comment by ljwh2** [comment]
@eks-ebi tagging for reference

**Comment by eks-ebi** [comment]
Tested: successfully assigned multiple EFO terms per line to studies: https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/61aa850c81051b0001ebf7aa

Assigning file example:
![image.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/017b32b3-929b-45b5-bd4e-32bd8bc1f343)

Successful report:
![image.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/c8755a4e-d1c1-49f8-9c77-15813129fe60)

The only problem is that the study tab table is not updated, so I cannot see evidence in the UI that the added data has been saved. See [#goci713](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/713)
