### ISSUE TITLE
Depocuration App Study tab headers

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#695]
Suggest showing the following submission template columns on the Study tab:

Accession
Study Tag
Genotyping Technology
Array Manufacturer
Array Information
Imputation
Variant Count
Statistical Model
Study Description
Reported trait
Mapped trait [as EFO]
Mapped background trait [as Background EFO]
Summary statistics file
Cohort(s)

Even more headers are currently shown on the Curation App import[ page](http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/submissions/61cc1bf481051b0001ed18db?) which I don't think looks too crowded, especially if we can scroll across the same:

![Screenshot 2022-04-20 at 09.41.16.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/fde8a668-9721-434b-87bd-6e6631d6ccab)

**Comment by eks-ebi** [comment]
This hasn't been completed exactly according to spec above. See: https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/62b42888b18fd300019835ee

To meet the spec, Variant Count should be move down, after Imputation. Everything else is in the right place.

Accession
Study Tag
_(Variant Count)_
Genotyping Technology
Array Manufacturer
Array Information
Imputation
**<-Variant Count**
Statistical Model
Study Description
Reported trait
Mapped trait [as EFO]
Mapped background trait [as Background EFO]
Summary statistics file
Cohort(s)

**Comment by ljwh2** [comment]
@ala-ebi to make final change

**Comment by ala-ebi** [comment]
done
