### ISSUE TITLE
migrate deposition sync to harlow

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#697]
- Deposition sync is currently triggered from Bamboo to run on garfield: http://gromit:10001/browse/GWAS-DS
- change to trigger from codon crontab and run on gwas-garfield

**Comment by jdhayhurst** [comment]
- setup temp solution to trigger from codon-cron and run from garfield. Will need updating to run from gwas-garfield but the software are not there yet

**Comment by sprintell** [comment]
we need to remove from cron tab and add spring scheduler so it can run off anywhere by itself

**Comment by ljwh2** [comment]
@sajo-ebi please create development ticket for this and close this one

**Comment by sajo-ebi** [comment]
@ljwh2  goci#761 created as development story
