### ISSUE TITLE
Make submitter email available to curators

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#70]
Curators need access to submitter email so they can send email to submitter when goes live.

Add submitter name, email address and date submitted to curation interface - to study details page under the publication details.

Add submitter name and email address to email report of summary statistics made available in a release.

**Comment by JalMacArthur** [comment]
@twhetzel Please add this info on study details page under corresponding author info, rather than publication info as previously stated. Please see attached image to illustrate.

[https://app.zenhub.com/files/2995118/d816fe1d-fa69-41f1-b8d3-cce39429ba09/download](https://app.zenhub.com/files/2995118/d816fe1d-fa69-41f1-b8d3-cce39429ba09/download)

**Comment by twhetzel** [comment]
@JalMacArthur we'll need to make some backend changes to have name, email, date submitted available on the study details page. Can you confirm that the study details page is the ideal place to get this information vs. say a new page in the Curation app with a searchable table like that used in the Search UI?

**Comment by twhetzel** [comment]
Tudor decided to take this ticket

**Comment by twhetzel** [comment]
Ready for QA on Snoopy 9680

UAT
- login to Curation app
- go to Home page and view a study page for a publication without a submission
--> Submitter name and email will show as N/A

Also review the study details page for submissions that have been Imported and those that have not been imported and are either valid or invalid. These can be found from the "View submissions" page.

**Comment by earlEBI** [comment]
Tested non-submission study, non-imported submission study, and an imported submission study. All correct.

**Comment by eks-ebi** [comment]
Tested by @earlEBI  and @eks-ebi , 2020-07-30. All looks good!
