### ISSUE TITLE
Bulk unpublish studies for PMID 35213538

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#706]
Please unpublish all studies for PMID 35213538 so I can update EFO and republish before the next DR

**Comment by sajo-ebi** [comment]
@earlEBI the Pmid has been unpublished , kindly confirm

**Comment by earlEBI** [comment]
@sajo-ebi thank you! please republish all studies from this pmid except for '95284419' which should remain 'requires review', before the next DR.

**Comment by earlEBI** [comment]
done, thank you
