### ISSUE TITLE
Bulk unpublish 141 entries from Lotta PMID 33414548 to add associations

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#709]
I need to add associations to an old big submission - Lotta et al 33414548.
List of GSTSs are here: http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/publication/33414548

**Comment by sajo-ebi** [comment]
Unpublished , @buniello please confirm

**Comment by buniello** [comment]
Hi @sajo-ebi @ljwh2 - I have re-uploaded the submission form with the associations for Lotta et al and as a consequence, all the GCSTs have changed. They are not the ones originally published in the Catalog with the Lotta sumstats: https://www.ebi.ac.uk/gwas/publications/33414548

We cannot re-publish these studies with different GCSTs as they were originally linked to the author submission of summary statistics and original GCSTs are also reported in the paper. It is not normal behaviour for the system to create new GCST upon re-curation/Level 2 curation.

**Comment by buniello** [comment]
We decided to publish all the Lotta studies again from curation app (GCSTs are still correct in curation app) and look at this GCSTs overwrite issue after DR has started.
