### ISSUE TITLE
Presentation of error report produced on assigned traits to studies needs improvement 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#710]
When assigning traits to studies, after uploading the template curators want to be presented with a message informing them whether the upload was successful for all studies or not. If unsuccessful for any study, the message should state the upload had errors and prompt the curator to review the report.

**Comment by ljwh2** [comment]
@eks-ebi please confirm

**Comment by eks-ebi** [comment]
Tested today, and I would say this is done. When I upload the file, I get the message "Trait file was uploaded successfully."

If all traits have been assigned successfully, I get no message, but can now download the report if I want. I think this is sufficient to know that the trait assigning has worked for all studies.
When one or more traits failed to be assigned, I get this error message: "Report may contain errors, please download and have a look." I think this is very clear.

**Comment by eks-ebi** [comment]
@ljwh2 If you're happy with that, then I think this ticket can be closed.

**Comment by ljwh2** [comment]
No error was displayed for Backman trait assignment that caused duplicates (no traits were assigned). Need to handle these unexpected situations if traits are not successfully added.

**Comment by ljwh2** [comment]
The specific issue with Backman does not need an error message . Unexpected technical errors should produce an error something like "An unexpected error occurred, please contact the dev team"
