### ISSUE TITLE
EFO and reported trait should be assigned to studies in a single action

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#713]
When assigning trait to studies, curators need to be able to assign both EFOs and reported traits in the same template, in order to maximise efficiency. The process should allow assignment of either EFOs, or reported traits, or both.

**Comment by eks-ebi** [comment]
see also, comment in https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/670

**Comment by eks-ebi** [comment]
Tested for this submission: https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/602402ea0164810001f6720e

Template works well for efficient upload of Reported Trait and EFO Trait in a single action.

One issue: after uploading the template, the Reported Trait is displayed in the study tab table - this provides good feedback to the user that the uploaded data has been successfully assigned and saved. However, the EFO does not appear in the table.

![Screenshot 2022-06-23 at 11.29.25.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/ccc1791c-60a3-480c-be62-9b04bc163998)
