### ISSUE TITLE
Investigating change of GCSTs after re-curation for Lotta et al - PMID 33414548 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#714]
After re-curation (adding associations) for Lotta PMID 33414548, submission ID 5f840f4702f2a50001f1b51b, 
the GCSTs have changed.

Studies from Lotta are all already published in the Catalog with sumstats - therefore GCSTs should be kept. 
https://www.ebi.ac.uk/gwas/publications/33414548

Moreover, this is not a new submission but re-curation of an author submission - so GCSTs should not change as per pipeline design.

This ticket is linked to another ticket: 
https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/709.

**Comment by sajo-ebi** [comment]
@buniello the GCST have been updated for the submission [5f840f4702f2a50001f1b51b](https://www.ebi.ac.uk/gwas/deposition/submission/5f840f4702f2a50001f1b51b), kindly validate

**Comment by buniello** [comment]
Thank you @sajo-ebi - all looks good!

**Comment by buniello** [comment]
@sajo-ebi I have checked the GCSTs and their links with study tags do not match with the ones already published in Lotta: https://www.ebi.ac.uk/gwas/publications/33414548.
I have shared a file with all the specific matches with you on slack, so that you can check all links.

**Comment by ljwh2** [comment]
@buniello please confirm if this can be closed?

**Comment by sprintell** [comment]
@eks-ebi  please help check this. Thanks

**Comment by eks-ebi** [comment]
@sprintell Annalisa's last comment seems to be saying that the GCSTs now in the GWAS Catalog **do not** match the GCSTs that the author has cited in their paper. However, I have checked it and the GCST range that we are currently using  **does** seem to match what the author has cited.

In the paper, they say:

> All genome-wide summary statistics... were further uploaded to the GWAS catalog (https://www.ebi.ac.uk/gwas/, accession numbers GCST90010722–GCST90010862).

This is the same range of GCSTs listed in the study table here: https://www.ebi.ac.uk/gwas/publications/33414548

The only possibility I can see is that the range is correct, but that the studies are out of order (i.e. matched to different studies than they were originally). However, I can't find anywhere in the paper where the author lists specific correspondences of studies/traits to GCSTs. So it doesn't seem to be an issue. Unless I'm missing something.

**Comment by sajo-ebi** [comment]
[https://app.zenhub.com/files/2995118/f7e1bb83-e8f4-48ee-a6ed-90aeda977725/download](https://app.zenhub.com/files/2995118/f7e1bb83-e8f4-48ee-a6ed-90aeda977725/download) @eks-ebi this is the file shared by Annalisa

**Comment by eks-ebi** [comment]
Thanks @sajo-ebi... I don't quite understand how to read this file, since there are no headers. But it looks like the same set of GCSTs have been assigned to the studies in two different orders at different times. What I don't know is whether that affects the summary statistics files. i.e. are the sumstats files still matched to the correct study tags, but with the GCSTs reordered? Or could the sumstats files have been assigned to the wrong study tags?

**Comment by eks-ebi** [comment]
Checked GCSTs, study tags, traits and sumstats file names in Search UI and Curation interface, and all seem to be correctly assigned in both places. Agreed to close ticket.
