### ISSUE TITLE
Fix Obsolete Traits in Curation DB

### ISSUE THREAD

**Issue by sajo-ebi** [EBISPOT/goci#720]
These are the new Traits mappings for the obsolete traits provided by Zoe, which needs to changed in Curation DB

http://www.orpha.net/ORDO/Orphanet_2573 -> MONDO_0016820
http://www.orpha.net/ORDO/Orphanet_1253 -> MONDO_0007198
http://www.orpha.net/ORDO/Orphanet_130 -> MONDO_0015263
http://www.orpha.net/ORDO/Orphanet_101997 -> MONDO_0003778
http://www.orpha.net/ORDO/Orphanet_98896 -> MONDO_0010679
http://www.orpha.net/ORDO/Orphanet_98724 -> MONDO_0020292
http://www.orpha.net/ORDO/Orphanet_85443 -> MONDO_0019438
http://www.orpha.net/ORDO/Orphanet_3437 -> MONDO_0018092
http://www.orpha.net/ORDO/Orphanet_182098 -> MONDO_0015926
http://www.orpha.net/ORDO/Orphanet_53351 -> MONDO_0010747
http://www.orpha.net/ORDO/Orphanet_355 -> MONDO_0018150
http://www.orpha.net/ORDO/Orphanet_388 -> MONDO_0018309
http://www.orpha.net/ORDO/Orphanet_399 -> MONDO_0007739
http://www.orpha.net/ORDO/Orphanet_440 -> EFO_0004209

http://purl.obolibrary.org/obo/MONDO_0044965 -> HP:0011458

**Comment by sajo-ebi** [comment]
@ljwh2 the above EFO traits are not present in DB , need the curators to add them using new Depo Curation feature so that we can map the new traits

**Comment by earlEBI** [comment]
@sajo-ebi I have added all the MONDO terms. The EFO and HP term already existed. 

Are you able to delete the orphanet terms from the db when you are done remapping or should I?

**Comment by sajo-ebi** [comment]
@earlEBI I will have yo unlink all studies & associations then only we can delete the orphaned traits , i will do that from backend
