### ISSUE TITLE
Replacing a sumstats file on the public FTP and pushing the file through harmonisation pipeline.

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#722]
The user Holger Hummerich contacted us to update his summary statistics file on the public FTP in this folder: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90001001-GCST90002000/GCST90001389/.

The new file is currently on our private FTP in a folder named "JonesE_GCST90001389" (gwas_cat/SummaryStatsUploads/JonesE_GCST90001389) and needs to be moved to http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90001001-GCST90002000/GCST90001389/. 

Moreover, the file needs to be pushed through harmonisation - as this is a manual file replacement and the file will not enter the automatic harmonisation pipeline (triggered by submission app).

I am not familiar enough with CODON to perform the above file move from private to public FTP.

**Comment by ljwh2** [comment]
The priority is moving the file to the public ftp, harmonisation can wait for Jame if necessary

**Comment by buniello** [comment]
thanks yomi - we should remember that for a period of time we will host raw and harmonised files not matching 100% (the harmonised file is from previous version of sumstats)

**Comment by sprintell** [comment]
@jdhayhurst  Please finish up by adding to harmonisation pipeline

**Comment by jdhayhurst** [comment]
removed existing harmonised data and queued up the new data for harmonising
