### ISSUE TITLE
Create GitHub repo to contain documentation on new Sumstats standard

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#723]
This will contain the content of the paper and some example files. We will open this for public comment for a fixed time period. In future we will update with latest versions.

**Comment by sprintell** [comment]
The Documentation Github Repository has been created: 

https://github.com/EBISPOT/gwas-summary-statistics-standard

**Comment by jdhayhurst** [comment]
created the content and committed to a "draft" branch

**Comment by jdhayhurst** [comment]
TODO: create github pages

**Comment by jdhayhurst** [comment]
page created: https://ebispot.github.io/gwas-summary-statistics-standard/
links should work/content should update when push the draft branch to master
