### ISSUE TITLE
Open PMID 35074870 for submission of additional sumstats files

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#724]
The PMID is 35074870 and the original submission was for Metadata and Sumstats. The author originally submitted 3 studies but only provided sumstats for 1/3. They have now provided sumstats files for the remaining 2 studies, and I (@eks-ebi) have them on my computer ready to upload.

Original submission page is: https://www.ebi.ac.uk/gwas/deposition/submission/61d8b18a06ff20000194a0c0

The publication should be reopened for submission (in principle, we only need to do a sumstats-only submission as the metadata is already in the Catalog). Please coordinate with me so that I can add the files before the deposition sync resets.

**Comment by sajo-ebi** [comment]
@eks-ebi None of the studies have been added for pre-filled template ,this is normally done using Depo Sync but even for the existing single study , we need to manually add entries for all 3 studies in pre-filled template

**Comment by sprintell** [comment]
@sajo-ebi will finish this up

**Comment by eks-ebi** [comment]
@sajo-ebi Can you please create a prefilled template for me containing information about all 3 studies, as discussed? The information you will need is in the Catalog here: https://www.ebi.ac.uk/gwas/publications/35074870

**Comment by sajo-ebi** [comment]
@eks-ebi the entries have been added for the pre-filled template for be populated for sumstats submission, kindly create a fresh sumstats submission

**Comment by eks-ebi** [comment]
new files now available on ftp
