### ISSUE TITLE
Submission to be forced through validation

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#725]
Submission GCP000324 from user Tomas Fitzgerald needs forcing through validation: https://www.ebi.ac.uk/gwas/deposition/submission/625fbac60b24d90001d13a21

James left instructions on how to do this (issue 2 on this page: https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=GOCI&title=Sumstats+common+issues%2C+FAQ+and+troubleshooting+advice)

**Comment by jdhayhurst** [comment]
passed validation for submission, callback id: `h2DDmaG8`
will release manually, need to bypass harmonisation

**Comment by jdhayhurst** [comment]
added files to FTP staging server, but not the harmonisation pipeline

**Comment by ljwh2** [comment]
When will the data be released to production @jdhayhurst?

**Comment by jdhayhurst** [comment]
The summary stats files are there e.g. http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90103001-GCST90104000/GCST90103375
