### ISSUE TITLE
Bulk unpublish PMID 33875891 - to be republished before the next DR

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#728]
Please unpublish all studies for PMID 33875891 from the Catalog. 

I will then add associations and ask for it to be republished before the next DR

**Comment by sajo-ebi** [comment]
@earlEBI done , kindly confirm.

**Comment by earlEBI** [comment]
@sajo-ebi Thanks Sajo, done. could you please change all except study id '80521241' back to 
Curator status: 'publish study' 
and 
Curator: 'GWAS Catalog' ?

**Comment by sajo-ebi** [comment]
@earlEBI done , please validate

**Comment by earlEBI** [comment]
@sajo-ebi sorry, study '80521241' has been published but needs to stay 'requires review' and 'unassigned'. I don't seem to have the option to unpublish - could you?

**Comment by sajo-ebi** [comment]
@earlEBI Unpublished the study , Kindly validate.

**Comment by earlEBI** [comment]
@sajo-ebi great thanks!

**Comment by earlEBI** [comment]
@ljwh2 can be closed, thanks
