### ISSUE TITLE
Change text for trait fields in curation interface

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#73]
Text and order of trait fields in the "Study details" tab of the curation interface needs changing for clarity. 

1. "Disease trait" should read "Reported trait"
2. "EFO trait" should read "Main EFO trait"
3. "Background Trait" should read "Background trait (author submitted)"
4. "Mapped Background Trait" should read "Background EFO Trait"

The order of the fields should be as follows:
1.
2.
4. 
"Apply EFO trait(s) to all SNPs" button
3.

**Comment by jstewart-ebi** [comment]
Released.
