### ISSUE TITLE
LD plot not loading

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#730]
The LD plot on the variant page (e.g. https://www.ebi.ac.uk/gwas/variants/rs2249296) is not loading. Unclear whether this is associated with the last data release.

![Screenshot 2022-05-24 at 08.54.14.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/d4e3edbe-58f0-4a0b-9439-8cca1edd513d)

**Comment by ala-ebi** [comment]
LD plot not loading cause EBI proxy times out the request after some time. the request takes too long to finish cause it makes calls to OLS which is currently unusually slow
