### ISSUE TITLE
Erroneous rows in prepublished sumstats table in search UI

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#731]
In the prepublished sumstats table (on this page: https://www.ebi.ac.uk/gwas/downloads/summary-statistics) there are many rows that appear with NA in first author and title. Looks like these studies are all associated with the same submission which is now published with PMID 35078996 and so should not appear in the pre-published table anymore. The same studies also appear correctly in the UI as published studies, e.g. https://www.ebi.ac.uk/gwas/search?query=GCST90086971

Note there was an issue with the import of this submission, described in this ticket: https://github.com/EBISPOT/goci/issues/640

**Comment by sajo-ebi** [comment]
Hi @ljwh2 we have to manually delete the entries from Unpublished studies from Curation DB & then Data Release needs to be done . Kindly confirm if we can delete all entries from unpulished studies which share the GCST with PMID '35078996'.

**Comment by ljwh2** [comment]
@sajo-ebi to check if there is a submission for this PMID. Confirm after DR.

**Comment by sajo-ebi** [comment]
@ljwh2 unfortunately there appears to be no submission attached to the PMID '35078996', we will have to submit a fresh submission via Deposition including the existing studies , this will change the GCST but we can update it from backend before importing the submission

**Comment by ljwh2** [comment]
OK thanks for the note and we will deal with this if the publication needs editing in the future.

**Comment by ljwh2** [comment]
Confirm after DR 29/6/22

**Comment by sajo-ebi** [comment]
Have Deleted the Unpuplished studies for '35078996'   from Curation DB , will wait for Depo Sync to run if that is causing these studies to be reinserted

**Comment by ljwh2** [comment]
Confirming that all studies from the originally reported PMID 35078996 have now been deleted in production
