### ISSUE TITLE
Change GCST for user submission Jami PMID 35378236 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#736]
This submission 'https://www.ebi.ac.uk/gwas/deposition/submission/616d86e9921d1b0001ed6591' was originally assigned GCST90054778 but after editing in the depocuration app was assigned GCST90102284 so sumstats are no longer connected in Catalog UI. 

Please change GCST back to GCST90054778 with sumstats published and then do a data release.

**Comment by sajo-ebi** [comment]
Updated in Curation DB , need to wait for DR to reflect

**Comment by sajo-ebi** [comment]
@earlEBI  can you confirm if it worked after  DR

**Comment by sajo-ebi** [comment]
@earlEBI the issue is that the GCST is existing both as published as well as unpublished study, let me know if you want to delete the unpublished study entry before DR, it should resolve the issue

**Comment by sajo-ebi** [comment]
@earlEBI yes I will delete it from backend

**Comment by sajo-ebi** [comment]
@earlEBI done , need to confirm after DR

**Comment by sajo-ebi** [comment]
@earlEBI please confirm if this is resolved after DR
