### ISSUE TITLE
update prepublication submission information - user request

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#739]
Following an email via gwas-subs, please update the following information for the user, for submission id '610e3efad0e96f0001dfb411':

"
The title and abstract have changed slightly during review. Lastly, I just noticed that one of the corresponding author's name is incorrect - it should be Eric Moses, not Eric Eric.

Please see the updated details below.

Title: Comprehensive genetic analysis of the human lipidome identifies loci associated with lipid homeostasis with links to coronary artery disease

Abstract: We integrated lipidomics and genomics to unravel the genetic architecture of lipid metabolism and identify genetic variants associated with lipid species putatively in the mechanistic pathway for coronary artery disease (CAD). We quantified 596 lipid species in serum from 4,492 individuals from the Busselton Health Study. The discovery GWAS identified 3,361 independent lipid-loci associations, involving 667 genomic regions (479 previously unreported), with validation in two independent cohorts. A meta-analysis revealed an additional 70 independent genomic regions associated with lipid species. We identified 134 lipid endophenotypes for CAD associated with 186 genomic loci. Associations between independent lipid-loci with coronary atherosclerosis were assessed in ~456,000 individuals from the UK Biobank. Of the 53 lipid-loci that showed evidence of association (P<1x10-3), 43 loci were associated with at least one lipid endophenotype. These findings illustrate the value of integrative biology to investigate the aetiology of atherosclerosis and CAD, with implications for other complex diseases.

Corresponding Author(s):
Eric Moses eric.moses@utas.edu.au
Peter Meikle Peter.Meikle@baker.edu.au
"

**Comment by sajo-ebi** [comment]
@earlEBI data has been updated , kindly confirm

**Comment by earlEBI** [comment]
Now published. Looks fine.
