### ISSUE TITLE
Submission template validator should validate that study tags provided by submitter are unique within the submission

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#74]
Submission template validator should validate that study tags provided by submitter are unique within the submission. As study tags are used to identify the study they must be unique within a particular submission.

**Comment by tudorgroza** [comment]
@JalMacArthur - Implemented and deployed in sandbox. Please give it a try with a couple of examples that should fail.

**Comment by tudorgroza** [comment]
@eks-ebi - this is the ticket. Thank you.

**Comment by ljwh2** [comment]
@eks-ebi please confirm this works

**Comment by eks-ebi** [comment]
@tudorgroza @ljwh2 Tested 2020-07-16 confirmed that this works.

Uploaded a template with same study tag used for two different studies and got this error:

> Studies: Study tags should be unique. Found duplicated study tags: 'study_double_use'

See test submission here: http://193.62.54.159/gwas/deposition/submission/5f1010253b86f300014c50c8

**Comment by tudorgroza** [comment]
Thank you. Please close the ticket.
