### ISSUE TITLE
Update prepublication submission - link to medRxiv paper

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#740]
Following an email on gwas-subs, please add the link to the prepub paper (https://www.medrxiv.org/content/10.1101/2022.05.27.22275343v1) to the submission '628d25f48b8c550001f59a1c'.

**Comment by ljwh2** [comment]
User followed up 25 July

**Comment by sajo-ebi** [comment]
@earlEBI the PrePub link has been updated , kindly confirm

**Comment by sprintell** [comment]
@sajo-ebi  will update the daatbase and @earlEBI will confirm

**Comment by ljwh2** [comment]
@earlEBI please confirm if this is resolved

**Comment by earlEBI** [comment]
@ljwh2  can confirm
