### ISSUE TITLE
Change the study tag in sample sheet  (Submission id: 5f58f4d2fa551c0001ca61dc)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#744]
Need to change the study tag in the sample sheet from **Type 2 diabetes** to **type 2 diabetes** to match the study sheet.

**Comment by ljwh2** [comment]
Note, this is causing study to appear with no ancestry. Reported in Daniel's list gwas-info 27 May

**Comment by sajo-ebi** [comment]
@Santhi1901 please confirm is it good to close

**Comment by Santhi1901** [comment]
@sajo-ebi yes it is resolved.
