### ISSUE TITLE
Improve documentation for SNP context / most severe consequence

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#745]
*This is a documentation task for curators to complete*

Add explanation of the CONTEXT column in the download and the Most Severe Consequence field in the search UI (variant page) in tooltip and/or on documentation pages.

This information comes from Ensembl and is explained in detail on their website: https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html#consequences

**Comment by ljwh2** [comment]
@Santhi1901  will do this, please can you show her how to edit the documentation pages when ready @eks-ebi

**Comment by eks-ebi** [comment]
Thanks @Santhi1901 - this is the folder on GitHub that contains the text that is displayed on the website: https://github.com/EBISPOT/gwas-ui/tree/documentation/goci-interfaces/goci-ui/src/main/docs.

I think the places to edit would be:
* file-downloads-content.adoc for the download column header
* faq-content.adoc for a Q&A about the Most Severe Consequence field on the variant page (maybe under section **E. Genomic mappings**?)

If you start writing some text, I can help you get it onto the page when you're ready.

We might also want to add a tooltip to the UI, which will need help from developers to add.

**Comment by ljwh2** [comment]
@Santhi1901 have the edits been made in the documentation branch yet?

**Comment by Santhi1901** [comment]
I will make the changes today

**Comment by Santhi1901** [comment]
The edit is completed
