### ISSUE TITLE
Let submitters know where to find their accession IDs

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#75]
Add info to submission email to let users know where to find their accession IDs.

******************
Dear Jackie MacArthur,

The summary statistics for Jackie's_test_GWAS by uk.ac.ebi.spot.gwas.deposition.domain.Author@e6bc64ac et al., ID GCP000037 were successfully validated.

Please review the submission report to confirm the submission details. To finalise the submission process, click "Submit".

Following submission the accession ID(s) for your submission will be available to download from the [submission report]link.

Thanks for sharing your data with us.

Best wishes,
GWAS Catalog team

**Comment by tudorgroza** [comment]
Done.
