### ISSUE TITLE
Mystery GCST

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#751]
GCST90017149 is **not** indexed in the search UI and not in the studies download and yet it **is** listed in the unpublished sumstats table in the UI and in the unpublished ancestries download (downloaded 7th June 2022), and sumstats are available http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90017001-GCST90018000/GCST90017149/

The GCST can be found in submission 603383bdb13a9000016f0712[https://www.ebi.ac.uk/gwas/deposition/submission/603383bdb13a9000016f0712] with GCP000131 

I found a gwas-subs email thread with author Daniel Crouch from 30 March 2021 that quotes a different accession, GCST90013791 for GCP000131. This one **is** indexed in the UI: https://www.ebi.ac.uk/gwas/studies/GCST90013791
and also has sumstats and is listed correctly in the UI sumstats table and download files. But it doesn't appear in submission GCP000131.

I can't make any sense of this. I haven't checked if the sumstats are identical for both GCSTs.

**Comment by ljwh2** [comment]
@jdhayhurst both these GCSTs GCST90017149 and GCST90013791 have sumstats, could you please check if they are identical before we delete GCST90017149?

**Comment by jdhayhurst** [comment]
Can confirm that these are identical

**Comment by ljwh2** [comment]
@sajo-ebi I noticed the meta-data is different for these two studies, and now I can see the author had requested to re-open the submission to change the metadata. I think this is where the additional GCST came from. Please confirm you haven't already deleted GCST90017149? I would like to go back to the author on this.

**Comment by sajo-ebi** [comment]
@ljwh2 I haven't deleted any GCST

**Comment by ljwh2** [comment]
Contacted user Daniel Crouch on 4/7/22

**Comment by ljwh2** [comment]
I have now discussed with the user, it's bit more complicated than we thought. 
He made an original submission with GCST90013791 which has sample metadata 7977 European
This metadata is incorrect so he asked to reopen the submission and made a new one, which is  GCST90017149 with 181214 European

He would like to keep GCST90013791, since he has quoted that in a manuscript. That's good because it is the one that appears correctly in the UI:  https://www.ebi.ac.uk/gwas/studies/GCST90013791
But he still needs to change the sample metadata to 181214 European.
Can we make this change on the back end, and delete GCST90017149? Or what is the best solution?

**Comment by sajo-ebi** [comment]
@ljwh2 we can update the Sample description free text from backend , & then we can delete the study from DB, kindly confirm if you want us to go ahead , changes will reflect in the next DR

**Comment by sajo-ebi** [comment]
@ljwh2 Sample Description updated for 'GCST90013791' &  'GCST90017149' has been deleted

**Comment by ljwh2** [comment]
GCST90017149 still appearing in unpublished download table 24/8/22, with NA in First Author

**Comment by sajo-ebi** [comment]
@ljwh2 as per my investigation the submission associated with 'GCST90017149' is being picked up by Depo Sync & this study get reinserted , I can delete this submission from DB , kindly confirm if you are good with that

**Comment by ljwh2** [comment]
Confirmed

**Comment by sajo-ebi** [comment]
The Unpublished studies have been deleted from DB & the submission has been deleted from Mongo DB

**Comment by sprintell** [comment]
waiting for DR

**Comment by ljwh2** [comment]
GCST90017149 Not visible in DR 14/9/22
