### ISSUE TITLE
Reported trait similarity analysis tool - too slow / unexpected error output

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#752]
I am still getting 'An unexpected error' returned when I upload a file to the Depocuration app similarity analysis tool. 

Here is the tsv file I am trying to upload, uploaded here as a .txt file as zenhub allows:

[https://app.zenhub.com/files/2995118/93f72f48-81a5-4227-a1cd-564c8a6ec91f/download](https://app.zenhub.com/files/2995118/93f72f48-81a5-4227-a1cd-564c8a6ec91f/download)

If the issue is timing out, could I suggest raising the match threshold to 0.8 
and also only returning the top 2 or 3 results per input term.

**Comment by ljwh2** [comment]
@sajo-ebi please provide details to Lizzy for testing

**Comment by ljwh2** [comment]
Create new ticket to run offline
