### ISSUE TITLE
Change the study tag in sample sheet for submission 61afeffe911f5a000154cb74 (PMID:35637384)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#753]
the study tag in the sample sheet needs to be changed from 'GWAS among Black' to 'GWAS among black' to match the study sheet. After importing to curation app, the sample description appears blank for this study. https://www.ebi.ac.uk/gwas/curation/studies/97362591/sampledescription

**Comment by sajo-ebi** [comment]
@Santhi1901 please confirm if this has been resolved

**Comment by Santhi1901** [comment]
@sajo-ebi this issue is resolved
