### ISSUE TITLE
user request - reset sumstats-only submission

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#755]
A user submitted sumstats post-publication here (sumstats-only submission): https://www.ebi.ac.uk/gwas/deposition/submission/62942239164a74000167b4de

They then requested for these to be held back from release, so I unchecked the 'full p-value set' box in the Curation App. So these sumstats have never been released. 

The user has now requested to replace the submitted sumstats file with a new version. 

Could:
1. the current sumstats file be deleted?
2. And the PMID be reset / reopened for sumstats-only?

**Comment by sajo-ebi** [comment]
@earlEBI Have opened the Pmid for sumstats only submission , kindly confirm

**Comment by earlEBI** [comment]
Thanks Sajo, I've let the user know. Will update if any problems.
