### ISSUE TITLE
Replace the sumstat for GCP000043 (PMID: 33204752)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#757]
The user has requested to replace the sumstat for submission id: 5f529a8ef10d27000109a3bc.

The updated file is placed in https://www.dropbox.com/home/Butler-Laporte%20G_%20GCP000043

The submission has HLA allele in the rsid column and it needs to be manually pushed through

**Comment by Santhi1901** [comment]
these are the list of GCST ids:

GCST90006884
GCST90006885
GCST90006886
GCST90006887
GCST90006888
GCST90006889
GCST90006890
GCST90006891
GCST90006892
GCST90006893
GCST90006894
GCST90006895
GCST90006896
GCST90006897
GCST90006898
GCST90006899
GCST90006900
GCST90006901
GCST90006902
GCST90006903
GCST90006904
GCST90006905
GCST90006906
GCST90006907
GCST90006908
GCST90006909
GCST90006910
GCST90006911
GCST90006912
GCST90006913
GCST90006914
GCST90006915
GCST90006916
GCST90006917
GCST90006918
GCST90006919
GCST90006920
GCST90006921
GCST90006922
GCST90006923
GCST90006924
GCST90006925
GCST90006926
GCST90006927
GCST90006928
GCST90006929

**Comment by Santhi1901** [comment]
[GCST ids.xlsx](https://github.com/EBISPOT/goci/files/9190996/GCST.ids.xlsx)

The spreadsheet has the list of new sumstats file names from the dropbox folder and the corresponding GCST ids

**Comment by jdhayhurst** [comment]
ok so these need to be released but not added to the harmonisation pipeline?

**Comment by jdhayhurst** [comment]
This is done. There were harmonised files for all the studies so I removed them from the FTP. I have queued these new files up for harmonisation - I don't think hla alleles will be harmonised, but the rest of the file should.
