### ISSUE TITLE
Display of Terms/Licence on GCST pages for PMID 30510241

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#763]
On the request of a user, please remove the link to the general terms of use which would usually be displayed here:

![Screenshot 2022-06-27 at 10.38.06.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/f4f86257-7b9f-44c2-a935-b36ab552e0a1
)

Instead, show 'Please refer to readme file' for all 5 studies with sumstats. 

(note: the relevant studies have only recently been published and so are not currently visible in the UI.)

**Comment by sprintell** [comment]
@ljwh2 pls check this here: http://gwas-snoopy.ebi.ac.uk:9780/gwas/studies/GCST007856

**Comment by ljwh2** [comment]
This is fine.
