### ISSUE TITLE
Blog post for new standard format

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#765]
Text for the blog post is here: https://docs.google.com/document/d/1kEBzqmzNXYa_zuFOafmkZmrWsddJR7brgaDI_X98FEY/edit?usp=sharing

The paper is now live so this needs to be posted asap, thanks

**Comment by sprintell** [comment]
@ljwh2  you can please check it here https://ebispot.github.io/gwas-blog , its online now
