### ISSUE TITLE
New feature for SNP validation

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#768]
User story: As a curator, when I upload associations in the Deposition or DepoCuration apps, I want SNP IDs to be validated against Ensembl (i.e. present or absent in Ensembl) and to see the outcome of SNP validation. This should serve as a “sanity check” to ensure there are no errors in SNP data entry (i.e. incorrect/truncated rsIDs, special characters etc). 
I want the process to check variant IDs against Ensembl and return a warning stating “Warning: X out of Y SNPs were invalid” where X is the number of invalid SNPs and Y is total number of SNPs uploaded, or a success message if all SNPs are valid. If there are invalid SNPs, I want to be able to download a report detailing which SNPs are invalid. 
Invalid SNPs should produce a warning only not a blocker, I want to be able to proceed with curation and publishing regardless of invalid SNPs.

**Comment by ljwh2** [comment]
@eks-ebi Please advise where we want to display the outcome and create some mockups. Also could be useful to check what the current process in the curation app is and whether it still works.

**Comment by eks-ebi** [comment]
Mockups here: https://docs.google.com/presentation/d/1EqT7KFAcrf_MG31ngTYlivuPXM2XJ_980_nf6UsEn7M/edit#slide=id.p

**Comment by ljwh2** [comment]
@eks-ebi do we really want to load all the SNPs on the page? I was thinking of a message of success or failure, and if invalid SNPs were present you could download a report (similar to the trait functionality).

**Comment by eks-ebi** [comment]
Current validation messages in the old curation interface, e.g. http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/studies/97056169/associations/getUploadResults

**Comment by eks-ebi** [comment]
![Screenshot 2022-06-29 at 10.00.05.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/76f85d8f-ff5e-4841-89e6-808568895a76)

**Comment by eks-ebi** [comment]
@ljwh2 good point, happy to change it

**Comment by ljwh2** [comment]
Sajo suggested this should run in background on upload in deposition, but only visible to curations in deposition.

**Comment by ljwh2** [comment]
Yomi thinks the old curation all calls the variant endpoint in Ensembl

**Comment by ljwh2** [comment]
@sprintell to review technical side and assign to a developer

**Comment by ala-ebi** [comment]
show error if ensembl db is down

**Comment by ala-ebi** [comment]
show if snps were invalid but were approved

**Comment by ala-ebi** [comment]
possible better change green text to "All SNPs were approved"
and warning to: "Some approved SNPs may have had errors"

**Comment by eks-ebi** [comment]
@eks-ebi test, including with large number of associations

**Comment by ala-ebi** [comment]
add "enabled" property in application.properties to enable/disable the app.

**Comment by earlEBI** [comment]
Note: cannot yet test using a new submission due to other dev work going on. 

Testing using existing submissions in depocuration app, uploading new templates: 
Works well. Tested up to 20k SNPs - chr:bp / gene name / exmID / psy_ prefix etc. 

Also tested to see if duplicate SNPs for the same study would be picked up and they are! although they also appear in the report as 'Not found in Ensembl', at least this might draw attention to them [if a 'duplicate SNP' message can't appear instead]: 

<img width="766" alt="Screenshot 2022-10-13 at 11 37 43" src="https://user-images.githubusercontent.com/61545198/195575305-91f27235-fc81-4451-b7b4-35b51faa6b34.png">

**Comment by earlEBI** [comment]
Latest download report looks good.
