### ISSUE TITLE
Republish 430 studies for Ruhlemann PMID 33462482

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#770]

**Comment by sajo-ebi** [comment]
@eks-ebi Done , please confirm

**Comment by eks-ebi** [comment]
Hi @sajo-ebi I'm sorry, I forgot that I had to assign the reported trait and EFO to these studies again after editing the template, so this information was wiped after import. Could you please unpublish them again so I can redo that?

**Comment by sajo-ebi** [comment]
@eks-ebi Done, please confirm

**Comment by eks-ebi** [comment]
confirmed, all studies are unpublished. I will now re-assign the traits

**Comment by eks-ebi** [comment]
@sajo-ebi re-import is complete and I've approved all associations. Can you please re-publish these studies?

**Comment by sajo-ebi** [comment]
@eks-ebi done , please confirm

**Comment by eks-ebi** [comment]
@sajo-ebi confirmed, all studies are published
