### ISSUE TITLE
assigning trait and EFO in bulk - unexpected error - Backman - 7972 studies

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#771]
I am trying to assign traits and EFO for backman - 7972 studies but keep getting 'an uexpected error occurred'. 
'https://www.ebi.ac.uk/gwas/depo-curation/submissions/615df545921d1b00012f1e6e'
These are the files I'm trying to upload: 

traits: [https://app.zenhub.com/files/2995118/2be67e34-058e-4198-92d2-d3072a1867a5/download](https://app.zenhub.com/files/2995118/2be67e34-058e-4198-92d2-d3072a1867a5/download)

EFO: [https://app.zenhub.com/files/2995118/c5db6184-cbc9-4881-9e54-6d24c811c191/download](https://app.zenhub.com/files/2995118/c5db6184-cbc9-4881-9e54-6d24c811c191/download)

**Comment by earlEBI** [comment]
Tried to test uploading the same 7972 traits / EFO to test submission 'https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/62becbb2b18fd30001b73302' using this template:

[Uploading... Backman study-multi-trait-bulk-upload - test.tsv]

The 'upload' button greyed out for about 30 seconds as expected but then turned blue again. Nothing else happened. Traits / EFO have not been assigned.

**Comment by earlEBI** [comment]
@sajo-ebi Thanks for bulk unpublishing. I have re-uploaded the submission template and EFO/trait template successfully. Import also successful. Approved associations. 
Please now change the status for all studies (with PMID 34662886) to:
curator: GWAS Catalog
curation status: publish study

**Comment by sajo-ebi** [comment]
@earlEBI the studies has been published , kindly confirm

**Comment by earlEBI** [comment]
@sajo-ebi confirmed
