### ISSUE TITLE
Edit EFO traits for 'age of onset' studies in bulk

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#774]
A number of new EFO terms have been created to better represent studies on the age of onset of a disease. These terms take the form:
* age of onset of [disease X]

They will replace previous annotations where two separate terms were used:
* age at onset | [disease X]

As multiple studies need to be reannotated, and many were created before the new deposition software, these edits will need to be performed manually, in bulk. The attached spreadsheet contains the PMID and STUDY ACCESSION for each affected study, and the current MAPPED_TRAIT and MAPPED_TRAIT_URI. These should be replaced with the new terms under NEW_MAPPED_TRAIT and NEW_MAPPED_TRAIT_URI.

Note that a handful of studies also contain a third EFO term that is not affected by these merges, and therefore should not be removed or changed. For those examples, the additional term is included in both the MAPPED_TRAIT and NEW_MAPPED_TRAIT columns.

**Comment by eks-ebi** [comment]
[https://app.zenhub.com/files/2995118/e1dbe68b-05c7-4bfe-855e-7b3f35cd85f1/download](https://app.zenhub.com/files/2995118/e1dbe68b-05c7-4bfe-855e-7b3f35cd85f1/download)

**Comment by sajo-ebi** [comment]
@Elliot the file is in funny format unable to format in excel with delimiters , can you share over email or slack the file

**Comment by sajo-ebi** [comment]
@Elliot the file is in funny format unable to format in excel with delimiters , can you share over email or slack the file

**Comment by eks-ebi** [comment]
@sajo-ebi just sent an updated copy of the file to your email

**Comment by sajo-ebi** [comment]
Hi @eks-ebi , for GCST90027235 in the Mapped Trait is 'migraine without aura, susceptibility to, 4' , there is no EFO Trait  like this in DB , but I can find two entries for 'migraine without aura' in DB , can you confirm what is the exact EFO, also we might have to delete the duplicate EFO from DB for 'migraine without aura'

**Comment by eks-ebi** [comment]
ah ok, I see - the two entries for 'migraine without aura' in the database are http://purl.obolibrary.org/obo/MONDO_0100431 (which has the correct name) and http://purl.obolibrary.org/obo/MONDO_0011847 (which is officially called 'migraine without aura, susceptibility to, 4' in EFO). It might be that the commas caused some problems when this was added to the database.

For the study in my spreadsheet (GCST90027235), I believe it was originally annotated with http://purl.obolibrary.org/obo/MONDO_0011847, which is why I used that term. However, I actually made a mistake with the name of the "age of onset" term that should replace it. The replacement term name should be just "**age of onset of migraine without aura**" - the EFO URI is correct though (http://purl.obolibrary.org/obo/OBA_2001028).

**Comment by sajo-ebi** [comment]
@eks-ebi the studies have been updated in Curation DB kindly validate

**Comment by eks-ebi** [comment]
Confirmed! I checked about half of the studies and those all looked good

**Comment by ljwh2** [comment]
@eks-ebi to confirm after DR

**Comment by ljwh2** [comment]
@eks-ebi please close the ticket if you are happy

**Comment by eks-ebi** [comment]
all look good in production, can close ticket
