### ISSUE TITLE
Submission to be pushed through validation (PMID: 34375979)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#775]
Submission for PMID: 34375979 from user Fengyuan Hu needs to be manually pushed through validation

https://www.ebi.ac.uk/gwas/deposition/submission/62c592398a6cfa0001651079

**Comment by jdhayhurst** [comment]
staged for release

**Comment by jdhayhurst** [comment]
Not yet released on FTP because the studies are not in the curation db
