### ISSUE TITLE
Investigating best process to curate studies not present in deposition DB

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#779]
Some studies are present in the curation db and have been curated in the old curation app, but not published yet. These do not have any submission associated with them. They fall into two categories:

Some have already had reported traits and/or EFOs assigned to them (under the old system), examples are:
Study IDs: 92919997, 93023048, 91754937, 91754978 [a]
Some have not yet had reported traits or EFOs assigned to them, some examples are:
Study IDs: 96123382, 91777240, 91777344 [b]

We need to verify how we can 
1. Publish studies that have traits already assigned to them such as [a]
2. Add rep traits or EFOs that already exist in the curation db to studies such as [b]
3. Create new rep traits or EFOs and add them to studies such as [b]

Note for information, in the future, Yomi plans to migrate all old studies into the deposition database.

**Comment by sajo-ebi** [comment]
@ljwh2 Based on my investigation only we can edit these is open the Pmid in Deposition app & create a submission template for existing studies & then remap existing traits using Depo curation . We will to have  retain GCST for the existing studies before the importing the new submission
