### ISSUE TITLE
3 studies appear incorrectly in prepublished download table. 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#780]
There are some studies that appear in the prepublished sumstats table with NA in metadata:

GCST90032652
GCST90032653
have NA in First Author, Title, Ancestry and No of individuals

These have no study page in the UI, and do not appear in the data downloads, I can't find out anything else about them. 

GCST90006559
This appears with NA in first author and title. The reported trait is Type 2 diabetes and I suspect it might have something to do with this issue: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/744 but I can't verify that

These need cleaning up

**Comment by Santhi1901** [comment]
GCSTs mentioned in the paper match with the published GCST in the Catalog. For PMID: 34873335 GCST90027163,GCST90027164, and for PMID: 33188205 GCST90006934

**Comment by ljwh2** [comment]
Since the authors have used the published GCSTs, we can delete the unpublished studies.

**Comment by sajo-ebi** [comment]
@ljwh2 the unpublished studies have been deleted & will reflect after DR
