### ISSUE TITLE
Fix issues for production Search UI

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/goci#781]
there are two issues we often see in the search UI: 
1. After doing a software release on Bamboo, the deployment process hangs on the Tomcat App Reload, further investigation showed that the VMs are consuming about 98% of the available memory, half of that being Tomcat.
2. https://www.ebi.ac.uk/gwas/downloads/summary-statistics on Chrome sometimes shoes an 'Aw, Snap' Error ![image.png](https://images.zenhubusercontent.com/60190c8d2d567e0492e6fdd9/4cb207b0-0def-42e1-9abf-f4026974d22a)

**Comment by ljwh2** [comment]
See also goci#828

**Comment by ala-ebi** [comment]
We increased the memory for the production VMs and I havent encountered any issues since, can be closed.
