### ISSUE TITLE
Edit trait details for prepub submission

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#783]
From a user request:

I just noticed, the reported trait for files of large artery stroke and small vessel stroke was interchanged in attached excel sheet.
Notably "Large artery stroke" should be the reported trait for Study accessions: GCST90104542, GCST90104547, GCST90104552, GCST90104557, GCST90104562, instead of "Small vessel stroke".

Similarly, "Small vessel stroke" should be the reported trait for Study accessions: GCST90104543, GCST90104548, GCST90104553, GCST90104558, GCST90104563 instead of "Large artery stroke".

Please edit before the next DR.

**Comment by ljwh2** [comment]
This might be do-able in depocuration, could you please try?

**Comment by ljwh2** [comment]
tagging @sajo-ebi for Lizzy's question above

**Comment by sajo-ebi** [comment]
Hi @earlEBI please refer to the attached screenshot , you can use the attached screen to edit Reported Traits for the individual GCST
<img width="890" alt="image" src="https://user-images.githubusercontent.com/77010716/178959119-e2d3f15e-7043-4329-ae82-e402dd4c7b64.png">

**Comment by earlEBI** [comment]
@sajo-ebi Currently there are no reported traits / EFOs assigned to any of the studies, because it is a prepublished submission. Do I need to add reported traits to all studies? In order to change the traits on these prepublication pages? https://www.ebi.ac.uk/gwas/studies/GCST90104563

**Comment by sajo-ebi** [comment]
@earlEBI, we can add traits in Depocuration,  the details will be reflecting in Curation App when the Pmid is attached to the submission & the submission is imported

**Comment by earlEBI** [comment]
@sajo-ebi We need the changes to be reflected in the Catalog before we import and publish through the Curation App.

**Comment by sajo-ebi** [comment]
sorry @earlEBI it may be updated by Depo Sync we can try, not sure  about behaviour of Unpublished studies

**Comment by earlEBI** [comment]
@sajo-ebi Do you still think I need to use the trait edit page you screenshotted? Or because the information was originally pulled from the template (as is always the case for prepublished submissions), updating the template may be enough? Is there any way to test it or will we only know when DR is in staging?

**Comment by sajo-ebi** [comment]
Hi @earlEBI as per my investigation Depo Sync updates only newly created body of work , for existing  body of works there is no sync , hence the update in template didn't reflect . I was confused with the published study where behaviour is different . In this case I have manually updated the Reported Trait in Curation DB , the data will be updated after DR

**Comment by earlEBI** [comment]
@sajo-ebi great, thank you!
