### ISSUE TITLE
Display of Terms/Licence on GCST page for GCST90129505

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#790]
Similar ticket to https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/763

On the request of a user, please remove the link to the general terms of use which would usually be displayed on their GCST page. 
Instead, show 'Please refer to readme file'.

This is currently a prepublished GCST under embargo until date of publication, but the text should appear once released.

**Comment by ljwh2** [comment]
Needs to be done before next DR starts

**Comment by earlEBI** [comment]
@sprintell This study has now been published to Catalog and so the above text needs adding to the UI page before the next DR, ty.

**Comment by sprintell** [comment]
![Screenshot 2023-01-16 at 21.29.01.png](https://images.zenhubusercontent.com/5f0f4126d974dfe9149c1910/73127a8f-c95f-45e0-b478-bac7e16b4fba)

**Comment by ljwh2** [comment]
screen shot looks good, this can be deployed
