### ISSUE TITLE
Splitting sumstats for Shin 24816252

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#798]
Related to https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/496

I will submit 533 studies - 486 metabolites with sumstats and the rest ratio traits without sumstats. 

Currently there are 453 sumstats files attached to GCST002443

There are another 33 relevant files here: https://metabolomics.helmholtz-muenchen.de/gwas/index.php?task=download under shin_et_al.xeno.metal.out.tar.gz

Do you need me to do anything to get these extra files @jdhayhurst ?

The submission template is here:

[https://app.zenhub.com/files/2995118/bf501ad4-21a8-4190-bc44-eda6157dc779/download](https://app.zenhub.com/files/2995118/bf501ad4-21a8-4190-bc44-eda6157dc779/download)

**Comment by ljwh2** [comment]
@earlEBI @jdhayhurst Can I just clarify what this ticket is waiting for? Are the split sumstats available yet? Are we still waiting for EFOs?

**Comment by earlEBI** [comment]
@ljwh2 not waiting for EFO

**Comment by earlEBI** [comment]
@sajo-ebi Hi Sajo please could you change the following GCSTs:

From GCST90243402 to GCST002443
From GCST90243934 to GCST002442

**Comment by earlEBI** [comment]
GCSTs changed as above and publication imported to Catalog.

**Comment by earlEBI** [comment]
For the record, because only some of the sumstats files had already been harmonised (by request), I formatted all the raw files (486) and submitted for validation along with the raw untouched files. 
All files will be [re-]harmonised through the automatic pipeline.

**Comment by earlEBI** [comment]
Need to move sumstats manually:
From GCST90243402 to GCST002443
From GCST90243934 to GCST002442

**Comment by earlEBI** [comment]
Currently a problem with permissions so folders have not been created. Studies should be released in next DR but links may be broken.
