### ISSUE TITLE
OTAR prioritised splitting of old GWAS/QTL studies to match summary statistics design - KETTUNEN

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#800]
related to https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/496

I have created the submission form here: 

[https://app.zenhub.com/files/2995118/4328bfe0-5bac-4fe7-999a-de2a8ac29241/download](https://app.zenhub.com/files/2995118/4328bfe0-5bac-4fe7-999a-de2a8ac29241/download)

Is there anything else you need @jdhayhurst before I unpublish the original and create a submission?

**Comment by jdhayhurst** [comment]
@earlEBI perfect - thanks, that's going to work. Please go ahead and create the submission when ready. It will fail, just let me know.

**Comment by earlEBI** [comment]
hi @sajo-ebi this publication is currently in the Catalog with the following GCSTs:
GCST003664
GCST003665
GCST003666

Summary statistics for 123 traits are currently under GCST003664
Therefore the status of the submission in the Submission App is 'closed'. 

Please change the status for this publication (PMID 27005778) to 'open for submission' so I can make a fresh submission with sumstats for 123 studies. 

Before importing to the Curation App, I will ask you to keep the original GCSTs within the new ones. 

This needs to be done well before the next data release is started to allow for the full process to be complete.

**Comment by sajo-ebi** [comment]
@earlEBI the Pmid has been opened for submission, please let me know once you have uploaded the template , I will update the GCST from backend

**Comment by earlEBI** [comment]
I will upload the template once I know the data release has gone through, so that I can unpublish the paper and the next steps can be done without rushing.

**Comment by earlEBI** [comment]
Hi @sajo-ebi, the stasus of PMID 27005778 in the submission app is closed again. 
Please can you set it to 'open for submission' again, as soon as possible?

**Comment by sajo-ebi** [comment]
@earlEBI done

**Comment by jdhayhurst** [comment]
Plan:

1. get gcsts - check the first one
2. create dirs
3. cp the harmonised data somewhere safe
4. copy raw files
5. move dirs to bins on staging
6. run sumstats sync
7. sync harmonised data to ftp
8. md5sums for harmonised

One file had not been harmonised (XXL.VLDL.TG) - harmonising this one and then will proceed with plan

**Comment by earlEBI** [comment]
Imported 123 studies to Curation App and published to Catalog.

**Comment by jdhayhurst** [comment]
The sync will run over night. Once released, I'll release the harmonised data

**Comment by jdhayhurst** [comment]
sync'd harmonised files

**Comment by ljwh2** [comment]
@earlEBI is this now resolved?

**Comment by earlEBI** [comment]
@ljwh2 yes.
