### ISSUE TITLE
Sync Traits Issue - Fix the EFO Traits Delete issue

### ISSUE THREAD

**Issue by sajo-ebi** [EBISPOT/goci#803]
It has been observed that during sync Traits delete operation the mapping for All Efos are getting removed, this is not expected & only the EFO being deleted should be unlinked

**Comment by sajo-ebi** [comment]
Code changes completed , waiting for code review

**Comment by sprintell** [comment]
@sprintell to review solution

**Comment by sajo-ebi** [comment]
@earlEBI this is deployed in [Dev1](http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/), kindly validate

**Comment by sajo-ebi** [comment]
@earlEBI this is to test when Traits are deleted in Depo CUration , the studies that are mapped with the deleted traits are unmapped not the other EFO traits mapped to the same study, the issue which you found in Production

**Comment by earlEBI** [comment]
@sajo-ebi it shouldn't allow deletion of _any_ EFO if they're already connected to a study, right?

**Comment by earlEBI** [comment]
I am receiving an error which doesn't allow to delete EFO traits when they are already attached to a study, as expected.

**Comment by sajo-ebi** [comment]
@earlEBI yes you will first unlink the EFO which is to be deleted in Depo CUration then delete the EFO Trait ,this is more testing on the CUration side whether the changes are replicated correctly on the Curation App, we can talk over Zoom tomorrow if it not clear

**Comment by earlEBI** [comment]
tested by doing the following:
1. Added EFO http://www.ebi.ac.uk/efo/EFO_0001739 as 'test trait - investigator' to depocuration app test environment https://wwwdev.ebi.ac.uk/gwas/depo-curation/efo-traits
2. Assigned reported trait and multiple EFO to this submission https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/62cf1a31fd97600001ce8be4
3. Waited for trait sync to run between the Curation and Depocuration Apps. 
4. Imported submission 
5. Reuploaded submission template in depocuration https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/62cf1a31fd97600001ce8be4
6. Reassigned EFOs, not including 'test trait - investigator'
7. Deleted 'test trait - investigator' EFO on this page https://wwwdev.ebi.ac.uk/gwas/depo-curation/efo-traits
8. Re-imported to Curation App. 
Result: as expected http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/publication/18313986 

@sajo-ebi Let me know if this does not cover the testing required.

**Comment by sajo-ebi** [comment]
Thanks @earlEBI , this looks good
