### ISSUE TITLE
submission import ui displaying the wrong (the text) value for background traits 

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/goci#804]
![Screenshot 2022-07-27 at 14.33.38.png](https://images.zenhubusercontent.com/60190c8d2d567e0492e6fdd9/83c268cf-df3b-49f2-88a9-1dc6627f6b11)

**Comment by ala-ebi** [comment]
fixed, need to deploy ingest + depocuration + goci for this

**Comment by ala-ebi** [comment]
@eks-ebi could you please confirm the import submission UI now displays correct values

**Comment by eks-ebi** [comment]
Confirmed, import submission UI now displays correct values!
