### ISSUE TITLE
Cole - submission status is 'closed'.  PMID '32193382'

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#806]
I am trying to submit metadata and summary statistics for PMID '32193382' but the status in submission app is closed. 

Could you tell me if this is because an external user is submitting? Or because it's an old publication that needs resetting to allow submission?

**Comment by earlEBI** [comment]
Curation status in Curation App was 'outstanding query'. I've changed to 'awaiting curation' and will see if the submission status is changed after sync.

**Comment by earlEBI** [comment]
Still was showing as closed. 
Full p-value set was also ticked in curation app. unticking and seeing if *that* fixes it.

**Comment by earlEBI** [comment]
The status in the submission app is still 'closed'. Please could someone investigate?

**Comment by sajo-ebi** [comment]
@earlEBI opened the Pmid , there was submission which was created which has been archived , hence Pmid was not open for submission
