### ISSUE TITLE
GWAS Catalog API display errors

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#811]
Please investigate the following gwas-info: 

Over the past week or so I’ve been trying to access the GWAS Catalog API however have been experiencing various errors, for example the following call doesn’t return the entire JSON (gets truncated, showing the last few lines):
 
https://www.ebi.ac.uk/gwas/rest/api/efoTraits/EFO_0003095/studies
 
![image.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/7bd8c7b8-e510-48fd-8e1c-606b1d420ac7)
I’ve tried this on several different networks to confirm it wasn’t a local issue.
 
Another call to https://www.ebi.ac.uk/gwas/rest/api/efoTraits/EFO_0003914/studies, returns an error
 
![image.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/7aabd3e3-6c4c-4a6c-b952-51d87a623f17)
 
Any advice on what’s the cause for this?

**Comment by ala-ebi** [comment]
2 errors seen in logs, from HATEOAS/SpringDataRest
1st error is complaining about the variable "Pooled" giving NPE, due to it being a non boxed, primitive boolean instead of Boolean in some places in Study model.
2nd error is "Id must be assignable to Serializable!: null"
**note to self:**
```
3330,2181,2313,2313,2313,3327,193,3305,3151,47453841,61959544,47453841,62250452,62250440,56243973,56243973,56243973,91699453,93453699,94048084,94048084,93997943,93997943,92919920,92919920,94848214,92919920,92919920
FOR EVERY STUDY WITH THIS EFO EFO_0003095 TRY SETTING THE PUBLICATION ID TO ONE OF THE PUBLICATIONS ABOVE, RETRY UNTIL YOU FIND THE BAD PUBLICATION
COMPARE WITH THIS EFO'S PUBLICATION CAUSE IT WORKS EFO_0600008

```

**Comment by ljwh2** [comment]
@sprintell can we update the user on this issue at all? Our last communication to them was that we would look into it.
