### ISSUE TITLE
GWAS to EFO mappings file on our File Downloads page is incomplete

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#813]
A user alerted us to this issue via gwas-info:

"On the downloads page, there is GWAS to EFO mappings section which reads  "A file showing all GWAS Catalog reported trait to EFO mappings, including the parent category each trait is mapped to on the diagram can be found here and on our FTP server." However, it only has data for two traits (cervical cancer, clubfoot) and not all traits. "

The file is on this page: https://www.ebi.ac.uk/gwas/docs/file-downloads

Please investigate

**Comment by earlEBI** [comment]
We've had another email about this from the GWAS Diversity Monitor who also use this data, so it might be good if this could be prioritised as much as possible. Please let me know when I can update the users.

**Comment by ala-ebi** [comment]
problem was that some terms were obsolete (Orphanet) and replaced by MONDO terms, they also had their parent terms edited, causing problems in pour system, as the parents do not exist in the software.

currently it stop as soon as it finds a term with an unrecognised parent, the implement fix will still display these rows but with NR in the parent columns, it will also send a report to gwas-curator containing the number of unmapped terms.

We will need to edit the terms in our DB. For that we need a list of obsoleted Orphanet terms, and their MONDO counterparts from the EFO team

**Comment by ala-ebi** [comment]
deployed to prod

**Comment by ala-ebi** [comment]
[julyorphanet.xlsx](https://github.com/EBISPOT/goci/files/9358070/julyorphanet.xlsx)
