### ISSUE TITLE
Curation App post-Oracle migration - loading issues and error log

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#825]
16.08.22
Several issues including:
- Unable to login 
            - intermittent throughout morning
- Pages never loading, only buffering - no specific page. All pages.
           -  eg. 11am. filtering by 'awaiting curation' and 'level 1 curator' on this page: http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies?page=1&status=21&curator=42
- Error pages on notes tab and when filtering by author on the main page:
            - eg. 11am. http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies?page=1&pubmed=34534736
![Screenshot 2022-08-16 at 11.06.59.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/927deca3-bd74-4b1a-a98f-f74531f3fca7)

**Comment by Santhi1901** [comment]
![Screenshot 2022-08-16 at 11.12.32 am.png](https://images.zenhubusercontent.com/60658482a4f4a6458dcdf52b/e5dfb158-7f67-4a3b-9881-e41c9b9f7eca)

Error is shown while trying to login to the curation tool

**Comment by earlEBI** [comment]
Curation App has been restarted but problems persist. 
Eg. ~12.30pm, this page not loading when I clicked to duplicate notes to all studies: http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies/97056071/notes

**Comment by earlEBI** [comment]
Notes tab eventually (after about half an hour) returned this page: 

![Screenshot 2022-08-16 at 13.03.47.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/28d4dbf3-02bd-4bda-bac0-49526ff1ec7d)

**Comment by Santhi1901** [comment]
![Screenshot 2022-08-16 at 1.32.27 pm.png](https://images.zenhubusercontent.com/60658482a4f4a6458dcdf52b/0df67bb6-ddf2-416e-b641-0b022ee1c3d7)
Got this error while trying to log in to the curation app around 1.30 pm

**Comment by Santhi1901** [comment]
![Screenshot 2022-08-16 at 1.32.27 pm.png](https://images.zenhubusercontent.com/60658482a4f4a6458dcdf52b/0df67bb6-ddf2-416e-b641-0b022ee1c3d7)
Got this error while trying to log in to the curation app around 1.30 pm

**Comment by earlEBI** [comment]
6pm: error loading study page https://www.ebi.ac.uk/gwas/curation/studies/98547545
![Screenshot 2022-08-16 at 17.58.13.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/4ad8fcee-583a-4e74-9bd7-ad73d7024652)

**Comment by earlEBI** [comment]
7.15pm: again trying to duplicate notes to all studies, the page only spins, never finishes loading. Tried refreshing but notes have not been duplicated. Tried again, still loading. http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies/97005673/notes

**Comment by earlEBI** [comment]
8.30am - Curation App pages are only spinning, never loading. eg. 
http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies/99877989/associations
http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/
![Screenshot 2022-08-17 at 08.34.42.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/b9b4364b-185a-4205-96d7-9966fcb87bac)

**Comment by earlEBI** [comment]
Notes tab: After clicking the 'duplicate to all studies' button next to a note, and after the eternal buffering, and the restarting of Curation App, the note has been copied thousands of times within the same study: http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies/99811541/notes

**Comment by earlEBI** [comment]
11.50am: Curation App was briefly working after restart but now no pages are loading again, eg: http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies/99811521/housekeeping

**Comment by earlEBI** [comment]
Curation App has been restarted again. 
12.42: Error loading this page http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies?page=1&author=Care%20AG
![Screenshot 2022-08-17 at 12.41.59.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/ee1fd51c-0230-45d2-96f1-194d206ccd6e)

**Comment by earlEBI** [comment]
18.08.22:
Curation App working a lot better but for this study, when I changed status to publish study on the curator information tab of this study http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies/99877989 I received this error:
 ![Screenshot 2022-08-18 at 10.06.02.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/2337a930-a5a1-4672-bdd2-4b823d871214)
But status does seem to have changed successfully. 
Also can't load the notes page for the same study http://ves-ebi-e4-x.ebi.ac.uk:8080/gwas/curation/studies/99877989/notes

**Comment by earlEBI** [comment]
10.10am:
Receiving this error page when trying to open this study page: https://www.ebi.ac.uk/gwas/curation/studies/98547545
![Screenshot 2022-08-18 at 10.11.23.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/03d2eeac-efb8-4c30-9a8b-64e9ab416b48)
