### ISSUE TITLE
Publication stuck in 'import in progress' status - PMID 34282934

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#826]
I tried to import this publication last week - I think Friday 12th August - and it is still showing as 'import in progress'. 

Please reset the status so I can try again / allow other publications to be imported. 

submission id '612734b609113d0001bb5b35'

**Comment by ljwh2** [comment]
Is this issue still current @earlEBI ?

**Comment by earlEBI** [comment]
@ljwh2 yes, still needs resetting, please

**Comment by sajo-ebi** [comment]
@earlEBI the submission is available to be imported, kindly confirm if this needs to go before DR?

**Comment by earlEBI** [comment]
@sajo-ebi Thanks. No, doesn't need to go before DR.

**Comment by ljwh2** [comment]
@earlEBI Is this resolved now?

**Comment by earlEBI** [comment]
@ljwh2 resolved now, thanks
