### ISSUE TITLE
Update sumstats file for GCST010144

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#829]
User contacted us to update the summary statistics file they had submitted in 2020, which contained 0 p-values. 

I don't have permissions on the folder in staging to replace it myself. 

I have put the file and md5sum in the following directory: /nfs/production/parkinso/spot/gwas/curators/GCST010144

Please replace the sumstats file and md5sum on FTP. 

Please also remove the harmonised file currently on FTP and re-add to harmonisation pipeline.

**Comment by jdhayhurst** [comment]
replaced on staging. It should automatically be released and picked up by the harmonisation queue

**Comment by sprintell** [comment]
wait for Data release before closing

**Comment by ljwh2** [comment]
@earlEBI can this be closed?

**Comment by earlEBI** [comment]
@jdhayhurst yes
