### ISSUE TITLE
Script to output doi for pre-published submission

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#842]
Need doi for pre-published submission if submitted by the user to check if the submission has been linked to a pmid using the Article Status Monitor of European PMC.

**Comment by ljwh2** [comment]
@ljwh2 expand details

**Comment by ljwh2** [comment]
@sajo-ebi  this requires a script that curators can run periodically to generate a list of GCPs for all prepublication submissions (including embargoed submissions) and preprint DOI.  See screenshots for where DOI is displayed in the UIs![Screenshot 2022-09-21 at 11.17.41.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/8ed90d51-84e3-42d4-9de4-9e76ab2eb54a)

**Comment by ljwh2** [comment]
@Santhi1901 is there any other information that would be useful to include in the output, like author, title etc?

**Comment by Santhi1901** [comment]
Yes it will be good if the title, as well as authors name can be included

**Comment by ljwh2** [comment]
@sajo-ebi columns in output should be GCP, first author, title, preprint DOI, embargo y/n

Not that note all submissions will have DOI, please list all submissions whether or not they have DOI, DOI can be blank or NA for those submissions.

**Comment by ljwh2** [comment]
Closing since we found a workaround in old curation app - search for wildcard in "Add Study" page gives all submissions including DOI
