### ISSUE TITLE
Landing page errors for GCP000366

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#845]
We’ve had an email from this [user](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=592837) (submission https://www.ebi.ac.uk/gwas/deposition/submission/62a87ed1bc08100001ccd5e0) who noticed their GCSTs appear in the Catalog but once you click on them, all that appears is this message: 
‘The study accession GCST90104542 cannot be found in the GWAS Catalog database’. eg. https://www.ebi.ac.uk/gwas/studies/GCST90104542

The sumstats are available on the FTP fine: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90104001-GCST90105000/

This is a ticket that was open for this submission to edit the reported traits https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/783

I think there’s been a data release since the edit was made. Not sure if the trait edit is the cause of the issue. Please investigate.

**Comment by sprintell** [comment]
@earlEBI  could you please confirm this has been fixed ? Thanks

**Comment by earlEBI** [comment]
@sprintell Seems fine now, yes.

**Comment by earlEBI** [comment]
The user has contacted us again because the message is appearing for all studies again. 
I added PMID last week and published. The GCSTs look good on dev, but not in prod: https://www.ebi.ac.uk/gwas/studies/GCST90104542
![Screenshot 2022-10-10 at 08.06.31.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/52543ecd-eb2f-4142-ae44-9451419bcbbe)

Is the issue caused by every data release?

**Comment by ljwh2** [comment]
@earlEBI this seems to be ok currently, please confirm after next DR that it is still visible

**Comment by ljwh2** [comment]
@earlEBI could you please confirm this for the current DR in staging?

**Comment by earlEBI** [comment]
@ljwh2 looks fine
