### ISSUE TITLE
Create a new page in the documentation to highlight training

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#848]

**Comment by ljwh2** [comment]
Online training resources are currently listed under "Related Resources". Helen and EBI training team would like these to be highlighted better. I suggest we have a separate page for training (could be merged with FAQs as a general help page?)

**Comment by earlEBI** [comment]
Updated the 'Related resources' header to 'Training Resources' (on UI page https://www.ebi.ac.uk/gwas/docs)
Edited the Documentation branch here: 
https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/resources/templates/docs.html

Moving to 'done'. 

Please push this change so I can test how it looks in Dev environment.

**Comment by ljwh2** [comment]
@earlEBI did you manage to check this in Snoopy?

**Comment by earlEBI** [comment]
@ljwh2 no, I think something needs to be pushed before it's visible there.

**Comment by ljwh2** [comment]
@ala-ebi please can you help Lizzy to test and release this
