### ISSUE TITLE
Edit typo in trait for prepub submission - GCP000430

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#850]
Similar to this ticket here: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/783

As per user request, please update reported trait for GCST90137412 from Sqaumous cell carcinoma' to Squamous cell carcinoma'

**Comment by sajo-ebi** [comment]
Data updated in Curation DB will reflect after DR in Catalog

**Comment by earlEBI** [comment]
@ljwh2 confirmed
