### ISSUE TITLE
Special characters in associations 

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#853]
There are some special characters present in the SNPS column and STRONGEST SNP-RISK ALLELE columns which needs to be removed 

![image.png](https://images.zenhubusercontent.com/60658482a4f4a6458dcdf52b/cac92c7e-e536-4a30-aa4e-b1c2ec53a305)

**Comment by ljwh2** [comment]
In some cases this prevents display of the variant in the UI e.g. https://www.ebi.ac.uk/gwas/publications/31251335
In others it looks normal in the UI but can be seen in the associations download e.g. https://www.ebi.ac.uk/gwas/publications/34011927

**Comment by ljwh2** [comment]
Fixed in db, @Santhi1901 to check after DR

**Comment by Santhi1901** [comment]
only the special characters in the 'SNPs' column are fixed; there are still special characters in the 'STRONGEST SNP-RISK ALLELE' column in the association download file. Have added some more to the list which has special characters in the 'STRONGEST SNP-RISK ALLELE' column

**Comment by ala-ebi** [comment]
@Santhi1901 fixed for the risk allele, should be there next DR

**Comment by ljwh2** [comment]
@Santhi1901 please confirm if this can be closed

**Comment by Santhi1901** [comment]
everything looks ok except GCST011536, In UI it is showing [undefined](https://www.ebi.ac.uk/gwas/variants/rs1784128%C2%A0-A%C2%A0)

**Comment by ljwh2** [comment]
@Santhi1901 please confirm this can be closed?

**Comment by Santhi1901** [comment]
this can be closed
