### ISSUE TITLE
Search UI page loading issues - detail pages

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#859]
Detail pages in the UI have problems loading (especially in Chrome) due to data volume. This due to inefficient pagination. 

An acceptable solution for the details pages would be to identify a cutoff that can be loaded successfully. Beyond this, the table would appear with a message something like "Warning: only the first 2000 rows could be displayed" and an option to download the data in a text file.  

This would enable us to keep all the search/sort features of the tables. 

ideally the association data should be loaded **pre-sorted by p value**, with the most significant association first, as this probably the most common use cases for the search/sort features. Users can then access the most significant associations even if the data is capped.

**Comment by ljwh2** [comment]
Here is an example of a page that does not load: https://www.ebi.ac.uk/gwas/publications/32888494

Note there may be a separate issue for loading trait pages, associated with the number of child terms, e.g. https://www.ebi.ac.uk/gwas/efotraits/EFO_0000311. This may be out of scope to fix for now.

**Comment by sprintell** [comment]
@ljwh2  it seems these are solved now with the immediate solution proposed, someone can help confirm in snoopy 

http://gwas-snoopy.ebi.ac.uk:9780/gwas/publications/32888494
http://gwas-snoopy.ebi.ac.uk:9780/gwas/publications/30595370
http://gwas-snoopy.ebi.ac.uk:9780/gwas/publications/30595370

http://gwas-snoopy.ebi.ac.uk:9780/gwas/publications/33462484

**Comment by ljwh2** [comment]
These are not loading for me after 5 mins

**Comment by ljwh2** [comment]
This looks good to me now, one small thing the text should read "download catalog **data** button"

**Comment by ljwh2** [comment]
This works for associations but I tested for a publication with >5K **studies**, only 5K rows are displayed but no message is shown: 
http://gwas-snoopy.ebi.ac.uk:9780/gwas/publications/34662886

**Comment by ljwh2** [comment]
@sprintell I think this can be closed but I would first like to confirm whether the association data is pre-sorted by p value

**Comment by sprintell** [comment]
Association data should be loaded pre-sorted by p value,

**Comment by ljwh2** [comment]
not complete but will be fixed in new UI framework
