### ISSUE TITLE
Incorrect headers gwas-catalog-v1.0.3-ancestries-r2020-06-13

### ISSUE THREAD

**Issue by mcerezof** [EBISPOT/goci#86]
The tsv file you can download from UI for gwas-catalog-v1.0.3-ancestries-r2020-06-13 has incorrect headers. 
The added headers in comparison with gwas-catalog-v1.0-ancestries should go at the end and not in the middle?

**Comment by ljwh2** [comment]
I checked this and can't replicate the problem

**Comment by ljwh2** [comment]
The column headers are in the correct order but incorrect data is being pulled into some of the columns e.g.INITIAL SAMPLE DESCRIPTION contains journal name info

**Comment by ljwh2** [comment]
Also in the studies download gwas-catalog-v1.0.3-unpublished-studies-r2020-06-13.tsv the submission date field is not populated

**Comment by jstewart-ebi** [comment]
Ancestry download files are generated incorrectly. The logic to determine which type of download to create was wrong. Created pull request to merge into gwas-ui. https://github.com/EBISPOT/gwas-ui/pull/167
Fixed unpublished studies submission date in gwas-utils and updated on ebi-cli, should be corrected with the next data release.

**Comment by twhetzel** [comment]
Merged feature branch into `dev` and deploy for testing, neither of the new downloads (study or ancestry) work now. Need to investigate how this was designed to work and what needs to be updated.

**Comment by twhetzel** [comment]
The updated download files were not in place for the `dev` testing server. Created these files by making a call to the appropriate endpoint as found in the Data Release Bamboo plan stage to create these files and saved to `dev` directory. Now the endpoint to download the files both successfully finds the download file and current data release stats file and returns the download file. Also, updated the `application.properties` file on the DEV2 server for `download.new_format.studies` and `download.new_format.ancestries`.

Ready for QA

**Comment by ljwh2** [comment]
gwas-catalog-v1.0.3-ancestries-r2020-07-06.tsv is now correct, but unpublished-studies and unpublished-ancestries have the wrong headers - could this have been an old version that got merged in?  unpublished-studies and unpublished-ancestries should have the exact same headers as v1.0.3-studies and v1.0.3-ancestries

**Comment by twhetzel** [comment]
@ljwh2 I gather these are the file names:
```
gwas-catalog-v1.0.3-unpublished-studies-r2020-06-30.tsv
gwas-catalog-v1.0.3-unpublished-ancestries-r2020-06-30.tsv
```
What was wrong with the headers?

**Comment by ljwh2** [comment]
for unpublished-studies, the headers in the file gwas-catalog-v1.0.3-unpublished-studies-r2020-06-30.tsv mentioned above are:
STUDY ACCESSION
FIRST AUTHOR
STAGE
NUMBER OF INDIVDUALS
BROAD ANCESTRAL CATEGORY
COUNTRY OF RECRUITMENT
ADDITONAL ANCESTRY DESCRIPTION
Founder/Genetically isolated population
Number of cases
Number of controls
Sample description
DOI
DATE ADDED TO CATALOG
JOURNAL
STUDY
DISEASE/TRAIT
PLATFORM [SNPS PASSING QC]
GENOTYPING TECHNOLOGY
Statistical model

but they should be: 
DATE ADDED TO CATALOG
PUBMED ID
FIRST AUTHOR
DATE
JOURNAL
LINK
STUDY
DISEASE/TRAIT
INITIAL SAMPLE SIZE
REPLICATION SAMPLE SIZE
PLATFORM [SNPS PASSING QC]
ASSOCIATION COUNT
MAPPED_TRAIT
MAPPED_TRAIT_URI
STUDY ACCESSION
GENOTYPING TECHNOLOGY
SUMMARY STATS LOCATION
SUBMISSION DATE
STATISTICAL MODEL
BACKGROUND TRAIT
MAPPED BACKGROUND TRAIT
MAPPED BACKGROUND TRAIT URI

for unpublished-ancestries, the headers in the file mentioned above gwas-catalog-v1.0.3-unpublished-ancestries-r2020-06-30.tsv are:
STUDY ACCESSION
FIRST AUTHOR
STAGE
NUMBER OF INDIVDUALS
BROAD ANCESTRAL CATEGORY
COUNTRY OF RECRUITMENT
ADDITONAL ANCESTRY DESCRIPTION
Founder/Genetically isolated population
Number of cases
Number of controls
Sample description
DOI

but they should be:
STUDY ACCESSION
PUBMED ID
FIRST AUTHOR
DATE
INITIAL SAMPLE DESCRIPTION
REPLICATION SAMPLE DESCRIPTION
STAGE
NUMBER OF INDIVIDUALS
BROAD ANCESTRAL CATEGORY
COUNTRY OF ORIGIN
COUNTRY OF RECRUITMENT
ADDITIONAL ANCESTRY DESCRIPTION
ANCESTRY DESCRIPTOR
FOUNDER/GENETICALLY ISOLATED POPULATION
NUMBER OF CASES
NUMBER OF CONTROLS
SAMPLE DESCRIPTION
COHORT(S)
COHORT-SPECIFIC REFERENCE

In the current version in production, the column headers are correct. 

Of notes, the actual data in the files mentioned above is dummy data added by Jon, not sure if that is what you were expecting.

**Comment by ljwh2** [comment]
discussed with @twhetzel, now ready for release
