### ISSUE TITLE
Improve Catalog UI search box functionality

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#863]
User request via gwas-info to improve findability of papers via the search box. Part of the e-mail pasted below: 

"For example, sometimes I know that a study has sumstats, and I know the author and title… but searching on e.g. “authorname titleword” fails to find anything.
 ...
Example – I want to find GCST90027158, from the paper by Bellenguez et al. 2022, “New insights into the genetic etiology of Alzheimer's disease and related dementias”.
If I search on Bellenguez, then I get dozens of studies, and the recent one is far down the list.
If I search on Bellenguez Alzheimer, it finds nothing.
If I search just on a portion of the title, e.g. “genetic etiology of Alzheimer”, it finds nothing."

**Comment by ljwh2** [comment]
This will be complicated to do, bearing in mind the need to primarily search for traits. A quick fix would be improve the example queries to direct the user to search by PMID. Now incorporated into roadmap.
