### ISSUE TITLE
Search results summary numbers do not match the results returned

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#864]
When searching in the Search UI, the returned results for each category (Trait, Publication, Gene etc.) are summarised in the filtering buttons on the left of the screen. The numbers displayed here do not match the actual numbers of returned results.

For example, searching for "coronary artery disease": https://www.ebi.ac.uk/gwas/search?query=coronary%20artery%20disease
* actual search results: 2 publications, 2 traits and 0 genes
* summary: 69 publications, 304 traits and 1 gene

One of these is wrong. I suspect that actual search results are correct and the numbers in the summary are wrong.

![Screenshot 2022-10-10 at 15.07.01.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/02f58267-650f-41d6-963f-eeeea40c09c2)

**Comment by ljwh2** [comment]
As a first step, we need to understand where the numbers in the summary are coming from. The actual numbers here are not particularly useful to users (more like an indication that there are results for that data type) and could be misleading even if correct. For example, a user may do a quick search for a trait and conclude that there are a certain number of publications in the catalog with that trait, but this is not true.
