### ISSUE TITLE
Update reported trait for PMID with two submission IDs - PMID 35007327

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#865]
Paper was first curated by a curator through depocuration app (submission id '626ab5660b24d90001d1d7e0') and published in Curation App. 

External user then submitted sumstats through submission app (submission id '634018fb15ccca0001f49c50'). 

By user request, I need to add a new reported trait and attach it to the study. 

Which submission should I edit to do this?

**Comment by ljwh2** [comment]
Sajo thinks it should be ok to edit the metadata submission, before the sumstats-only submission is imported. Please let the devs know if you encounter any issues.

**Comment by earlEBI** [comment]
@ljwh2 The sumstats-only submission was already imported, so that the sumstats could be released.

**Comment by ljwh2** [comment]
@sajo-ebi what do you think? Should Lizzy carry on and edit the metadata submission and keep us updated on what happens?

**Comment by sajo-ebi** [comment]
@ljwh2 if sumstats submission has already been imported , I think we will have to add sumstats data again when we edit the submission in Depo Curation , since data will be overwritten when metadata only submission is imported with Sumstats data as NR

**Comment by earlEBI** [comment]
@sajo-ebi Is it worth me trying to edit the metadata-only submission and importing? could possibly reset sumstats-only submission and re-import afterwards? 
Or... would it just be easier for a developer to update the reported trait for the existing study via the backend? I've just added the new reported trait in the depocuration app ('Peripheral blood CD34+ cell levels') so it will be synced after 15:05-ish. I think the only reason I can't update it in the Curation App is because it won't appear in the reported trait dropdrown menus.

**Comment by earlEBI** [comment]
@sajo-ebi would you be able to update the reported trait for GCST90102460 to 'Peripheral blood CD34+ cell levels' before the next data release, Sajo? or should I try the import? thank you

**Comment by earlEBI** [comment]
looks good, thanks, done.
