### ISSUE TITLE
632c967737db2600018dd446 stuck in Validation

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#867]
Submission id: 632c967737db2600018dd446
GCP Id: GCP000432
PMID: 35870639

It is showing validating since 29th Sep 2022.

**Comment by ljwh2** [comment]
@Santhi1901 please confirm if this ticket can be closed?

**Comment by Santhi1901** [comment]
The submission is still showing Validating template. Had contacted the author to correct the md5sum of one of the files. gwas-subs #620925

**Comment by ljwh2** [comment]
@jdhayhurst to check if there is an issue

**Comment by ljwh2** [comment]
Can this be closed now @santhi1901?

**Comment by Santhi1901** [comment]
yes, it can be closed
