### ISSUE TITLE
Can't add EFO traits to depocuration if the text is already contained in another term

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#868]
Attempted to add the following EFO on depocuration EFO trait page:
URI: http://purl.obolibrary.org/obo/MONDO_0019956
name: encephalitis

Receive the following error: 

![Screenshot 2022-10-14 at 14.25.23.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/98f0b89e-9e48-4add-9615-0fb190abe41a)

Also tried via bulk upload EFO feature, received the following download report: 
![Screenshot 2022-10-14 at 14.28.08.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/e25d7b1c-ceab-4939-ab1e-42700def5851)

Tried adding as 'encephallitis' (with two Ls and it allowed me, so I think it won't let you add a trait label that is contained in other trait names? (eg. 'viral encephalitis' exists. 

The rules of adding EFOs should allow trait labels that are contained within already existing trait labels.

**Comment by earlEBI** [comment]
I've deleted the EFO trait for now and will wait to re-add when I can spell it properly.

**Comment by earlEBI** [comment]
I don't need this EFO anymore because I've requested a new specific one, but may be needed in future

**Comment by ljwh2** [comment]
@earlEBI could you verify this in sandbox with a few other examples?

**Comment by Santhi1901** [comment]
[EFO_new.xlsx](https://github.com/EBISPOT/goci/files/9851651/EFO_new.xlsx)
Not able to add these terms as the error says term already exist. Most of these terms exist within already existing trait names

**Comment by earlEBI** [comment]
Fixed by Sajo, thank you.
