### ISSUE TITLE
Submission not able to import:633c04e4c6aae200010a2ccf (PMID 36150907)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#871]
This is a published submission, unpublished to add extra studies as requested by the user. But I am not able to import it.  A user has already opened the submission for sumstats (submission id:6349908437db260001901267), not sure if it is because of that.  PMID:36150907

**Comment by ljwh2** [comment]
@sajo-ebi A user created a new (sumstats-only?) submission for this PMID, but Santhi needed to edit the PMID to add some additional studies first. Now she is unable to import the edited submission. We think the solution might be to delete the users submission. Could you please confirm so we can follow up with the user?

**Comment by sajo-ebi** [comment]
@ljwh2 @Santhi1901 the submission status has been updated from backend it should be ready to import state now, for sumstats submission by user '6349908437db260001901267' since it is only in "STARTED"  stage , i think user can proceed once the submission has been imported

**Comment by Santhi1901** [comment]
@sajo-ebi The additional studies are now added and published, but the https://www.ebi.ac.uk/gwas/deposition/submission/6349908437db260001901267 for sumstat submission is missing the download submission button

**Comment by sajo-ebi** [comment]
@Santhi1901 the download button is visible now not sure Depo Sync updates the status if tomorrow again the button is not visible let me know I will change status from backend

**Comment by Santhi1901** [comment]
@sajo-ebi 
For this, initially, there were only 3 studies published. After a request from the author, I added 7 more studies and published them. But when I downloaded the submission, only the initial 3 studies were available.

**Comment by ljwh2** [comment]
@sajo-ebi to look w/c 3rd Jan 2023

**Comment by ljwh2** [comment]
Noting that Elliot is now working on this submissions

**Comment by eks-ebi** [comment]
The original submission has now been deleted. @ala-ebi loaded in the new studies, so I have now been able to create a new submission with the correct studies. I will handle the submission from here. There is just one issue with a possible duplicate sumstats file, which I have contacted the author about.
