### ISSUE TITLE
Error downloading template for submission 6352aee215ccca0001f5f44f

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#873]
This publication (36066633) was manually reopened for a sumstats-only submission. Now when I try to download the submission template, I get an error:
`There is a fault on our end. Please contact gwas-subs@ebi.ac.uk for help.`

Submission page: https://www.ebi.ac.uk/gwas/deposition/submission/6352aee215ccca0001f5f44f

**Comment by sajo-ebi** [comment]
Hi @Elliot for the submission the sumstats related data was not populated for the Pmid '36066633' in Deposition DB , this usually happens by Depo Sync process , not sure why it was not triggered for this Pmid , Have manually added the details from Backend . You will need to create a fresh sumstats only submission which will create the prefilled template for sumstats

**Comment by eks-ebi** [comment]
@sajo-ebi thanks for doing that, but the publication is currently closed (because it already has some sumstats) - can you please reopen it again, so I can try a new submission?

**Comment by sajo-ebi** [comment]
@eks-ebi the publication is open for sumstats submission now, as discussed the Depo Sync resets it every night when it runs so we need to create the submission today only
