### ISSUE TITLE
bulk unpublish all studies for PMID 35264221

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#876]
This publication requires unpublishing from the Catalog in order to update some EFOs to newly requested terms. 

Please unpublish all studies well before a data release so that I can edit through Depocuration App and re-import.

**Comment by ljwh2** [comment]
@sajo-ebi just a reminder to do this asap so Lizzy can complete the work before the next DR. I have created goci#898 for training curators to do this themselves, but this one needs doing sooner.

**Comment by sajo-ebi** [comment]
@ljwh2 Done , apologies lost track of this ticket

**Comment by earlEBI** [comment]
Thanks. Have republished myself, seems okay. Ticket can be closed.
