### ISSUE TITLE
Change GCST for a study

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#878]
Would it be possible to change 'GCST90188384' to 'GCT90002413'? 

GCT90002413 exists and is referenced in the user's paper, but I had to resubmit all their sumstats in a new submission: '635a4733c6aae2000190d5a5'. 

The original submission '5f4513ae2d70930001d640f5' could be deleted, if necessary.

**Comment by earlEBI** [comment]
The user has confirmed all 16 files should be made available. Similar to ticket #886, I suggest:
1. Delete submission '5f4513ae2d70930001d640f5' and 'GCT90002413' (including sumstats folder on FTP). 
2. Change GCST90188384 to GCT90002413

**Comment by earlEBI** [comment]
@sajo-ebi okay, I think that's because the template is invalid 'https://www.ebi.ac.uk/gwas/deposition/submission/5f4513ae2d70930001d640f5'. Please could you change 'GCST90188384' to 'GCT90002413' anyway?

**Comment by sajo-ebi** [comment]
@earlEBI done

**Comment by earlEBI** [comment]
@sajo-ebi brill, thank you.

**Comment by earlEBI** [comment]
ticket can be closed.
