### ISSUE TITLE
Delete and replace GCST - PMID 35995766

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#886]
The user has created 2 submissions for this paper: 
1. GCP000365, 1 study: GCST90104476 (given in manuscript). This file is top hits only for all ~3000 traits together.
The author was contacted to resubmit separate files. They submitted again through a body of work: 
2. GCP000329 - 3,085 studies.
I have added PMID to this GCP and have started curating at Level 2. 

To maintain the GCST given in the paper, I propose:
a. Delete GCP000365 and GCST90104476 completely.
b. Replace any of the 3,085 GCSTs for GCP000329 with the original GCST (GCST90104476). 

Q1: Will the sumstats folder for the GCST you replace have to be renamed also? 
Q2: I may need to update EFOs at a later date. Will the GCST revert at that point?

**Comment by earlEBI** [comment]
(I've not yet uploaded the final curated submission template.)

**Comment by ljwh2** [comment]
@earlEBI please let @sajo-ebi know when this is ready for him

**Comment by earlEBI** [comment]
@sajo-ebi Hi Sajo, I've now finished curation of this publication. Please let me know when I can import.

**Comment by earlEBI** [comment]
@sajo-ebi thank you. will import now.
