### ISSUE TITLE
Change GCSTs for resubmitted sumstats - Lee CJ, PMID 36329257

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#889]
User submitted sumstats under 2 separate GCPs and received 3 GCSTs: GCST90161239, GCST90161237, GCST90161236

User re-submitted under the PMID and received 3 new GCSTs. Please change the new GCSTs to the original GCSTs as follows:

GCST90239601 (T2D) to GCST90161239
GCST90239602 (FG) to GCST90161236
GCST90239603 (HbA1c) to GCST90161237

**Comment by sajo-ebi** [comment]
@earlEBI GCST has been updated from Backend , please validate

**Comment by earlEBI** [comment]
@sajo-ebi looks good, thank you
