### ISSUE TITLE
Replace obsolete EFO IDs with new MONDO equivalents

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#893]
A user has pointed out some EFO terms are showing the prefix "obsolete" in the Search UI. This is because they have been made obsolete in EFO in favour of equivalent terms from MONDO (see EFO ticket https://github.com/EBISPOT/efo/issues/1750).

**Task:**

Replace the following EFO IDs with their MONDO equivalents. The trait name can remain unchanged.

cancer:
http://www.ebi.ac.uk/efo/EFO_0000311 --> http://purl.obolibrary.org/obo/MONDO_0004992

coronary stenosis:
http://www.ebi.ac.uk/efo/EFO_1000882 --> http://purl.obolibrary.org/obo/MONDO_0006715,

glaucoma:
http://www.ebi.ac.uk/efo/EFO_0000516 --> http://purl.obolibrary.org/obo/MONDO_0005041

bipolar disorder:
http://www.ebi.ac.uk/efo/EFO_0000289 --> http://purl.obolibrary.org/obo/MONDO_0004985

systemic lupus erythematosus:
http://www.ebi.ac.uk/efo/EFO_0002690 --> http://purl.obolibrary.org/obo/MONDO_0007915

cognitive disorder:
http://www.ebi.ac.uk/efo/EFO_1001457 --> http://purl.obolibrary.org/obo/MONDO_0002039

**Comment by ljwh2** [comment]
mentioned in [this ticket](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/564)

**Comment by ljwh2** [comment]
To work on w/c 3rd Jan

**Comment by ljwh2** [comment]
Close after DR
