### ISSUE TITLE
Solution for curators to bulk unpublish 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#898]
User story: As a curator I need to be able to bulk unpublish all studies of a publication without needing developer input. This is not possible using the curation app. 

Suggestion from meeting 18/4/23 - create python wrapper for SQL query, added to an existing repo (gwas-utils) . OR Native SQL in Hibernate, interface via Postman.  It was decided not to add a button to the curation app to avoid working on sunsetted SW. Create command line option for now, in the longer term, publishing actions will be moved to depo-curation and this feature can be retired. 

In some cases, not all studies need publishing/unpublishing. This less common scenario can be left for developers to do in the first instance, possible future enhancement.

**Comment by sajo-ebi** [comment]
Have deployed the script in Prod , Below mentioned is the wiki page containing the steps

[https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Curators+daily+task+utility+scripts](https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Curators+daily+task+utility+scripts)
