### ISSUE TITLE
Remove existing data for PMID 33437986 to allow import

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#900]
I need to remove any studies currently existing for PMID 33437986 (I think I have already done this, but the PMID still exists in the database). I then need to import a new submission for that PMID. The Import button in the Curation app is currently orange and not active.

Depo-curation page: https://www.ebi.ac.uk/gwas/depo-curation/submissions/610591c047082800019acb21
Submission import preview: https://www.ebi.ac.uk/gwas/curation/submissions/610591c047082800019acb21?

**Comment by eks-ebi** [comment]
Closed because an alternative solution was found.

**Comment by sajo-ebi** [comment]
@eks-ebi the submission should be importable now

**Comment by eks-ebi** [comment]
Resolved
