### ISSUE TITLE
Revise email content to cater for the new successful validation workflow

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/goci#91]
Part of: https://github.com/EBISPOT/goci/issues/90

**Comment by eks-ebi** [comment]
Original email text:

`                        <p>Dear <span th:text="${USER_NAME}"></span>,</p>

                        <p>The summary statistics for <span th:text="${PMID}"></span> - <i><span th:text="${PUBLICATION_TITLE}"></span></i>
                        by <span th:text="${FIRST_AUTHOR}"></span> et al., were successfully validated.</p>

                        <p>Please review the <a th:href="${SUBMISSION_ID}">submission report</a> to confirm the submission details. To finalise the submission process, click "Submit".</p>

                        <p>Following submission the accession ID(s) for your submission will be available to download by pressing on the 'Download Study Accessions' button on the <a th:href="${SUBMISSION_STUDIES}">studies</a> page.</p>

                        <p>Thanks for sharing your data with us.</p>

                        <p>Best wishes,<br/>
                        GWAS Catalog team</p>
`

**Comment by eks-ebi** [comment]
Proposed new text:
`
                        <p>Dear <span th:text="${USER_NAME}"></span>,</p>

                        <p>The summary statistics for <span th:text="${PMID}"></span> - <i><span th:text="${PUBLICATION_TITLE}"></span></i>
                        by <span th:text="${FIRST_AUTHOR}"></span> et al., were successfully validated and submitted to the GWAS Catalog.</p>

                        <p>Following submission the accession ID(s) for your submission will be available to download by pressing on the 'Download Study Accessions' button on the <a th:href="${SUBMISSION_STUDIES}">studies</a> page.</p>

                        <p>Thanks for sharing your data with us.</p>

                        <p>Best wishes,<br/>
                        GWAS Catalog team</p>
`

**Comment by eks-ebi** [comment]
Note: the above text addresses most of the following point in the UAT:
5. **If the validation is successful, the submission is automatically SUBMITTED and the submitter receives an email confirming submission** and containing the accession IDs.

Do we need to also add the accession IDs themselves to the email? Or am I misinterpreting the requirement?

**Comment by eks-ebi** [comment]
I haven't written any new text for the failed validation scenario, i.e. for points:
6. If the validation fails, the submitter receives an email outlining the reasons for failure.
7. Upon returning to the platform, the submitter is presented with the option to delete the invalid file and re-upload.

I'm guessing the failed validation email doesn't need any changes??

**Comment by tudorgroza** [comment]
@eks-ebi - thank you.
No need to address the failure branch - it's dealt with in a different place.
W.r.t. the accession IDs - no - they're there, just in the ugly part of my template.

**Comment by eks-ebi** [comment]
Great, thanks for clearing that up, Tudor.

@ljwh2 did you still want to add something about the release schedule to this email?

**Comment by ljwh2** [comment]
@eks-ebi If this email is the same for prepublished and published, then I don't think we can, let's leave it for now.
