### ISSUE TITLE
Mass gwas-curator emails causing problems for EBI listserver

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#911]
Mass gwas-curator emails generated by the curation app upon status change are causing issues for systems. This needs addressing to generate only a single email when the publication page is used to perform mass action on all studies of a publication.  This is high priority requested by TSC.

Note, Sunny advised "mailman list is not designed for these types of automated email", we should look for an alternative solution.

**Comment by ljwh2** [comment]
@sajo-ebi as discussed, please stop the emails being sent as a short term solution

**Comment by sajo-ebi** [comment]
@ljwh2 the curation app has been deployed in Prod with Email sending for status change code block commented

**Comment by ljwh2** [comment]
Thanks Sajo! Keeping ticket open for longer term solution.
