### ISSUE TITLE
Open PMIDs for metadata and sumstats submission

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#913]

**Comment by earlEBI** [comment]
The following three PMIDs have been curated in curation app and so are "closed" for submission in submission app. 

After the next DR has started, I will unpublish all three from the Catalog and then the high priority action needed is: 
Set all three PMIDs to 'open for submission':

1. Draisma - PMID 26068415
2. Sun - PMID 29875488
3. Shin - PMID 24816252

**Comment by earlEBI** [comment]
All three how have now been unpublished, ready for next step.

**Comment by sajo-ebi** [comment]
@earlEBI Done , the Depo sync will again changes the status , we need to create submission today itself
