### ISSUE TITLE
Splitting sumstats for Draisma 26068415

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#915]

**Comment by earlEBI** [comment]
Need to keep GCST002961

**Comment by earlEBI** [comment]
@jdhayhurst Hi James, I've created a submission '6391fa7a4e749e00010afd76'. Could you please push it through validation? 
note: It's only listed 2 errors. Assuming that's expected. There should be 129 studies.

**Comment by earlEBI** [comment]
@sajo-ebi Hi Sajo, please can you change the following GCSTs:
**from                          to**
GCST90239994	GCST002961
GCST90240011	GCST002959
GCST90240014	GCST002965
GCST90240099	GCST002966
GCST90240100	GCST002964

**Comment by earlEBI** [comment]
@sajo-ebi Hi Sajo, please can you change the following GCSTs:
**from                          to**
GCST90239994	GCST002961
GCST90240011	GCST002959
GCST90240014	GCST002965
GCST90240099	GCST002966
GCST90240100	GCST002964

**Comment by sajo-ebi** [comment]
@Lizzy done please confirm

**Comment by earlEBI** [comment]
Sumstats validation pushed through, GCSTs changed, created folders on staging and moved raw files across.

**Comment by earlEBI** [comment]
Published. Waited overnight for sync. Moved harmonised files across. Gave list of GCSTs to James to be removed from harmonisation queue. Done.
