### ISSUE TITLE
Add GCBR logo to GWAS Catalog homepage

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#919]
Now we have been endorsed as a Global Core Biodata Resource, we need to add the logo to our homepage. The logos can be found here: https://drive.google.com/drive/folders/1qyiHHzf-hSHDJi-a3jc68arFA1F9yger?usp=share_link
(access needs to be requested from GCBR)

**Comment by ljwh2** [comment]
![GCBR.jpg](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/a1a3b7d7-1b1e-4bfb-a1dc-0e727e15e39f)

**Comment by ljwh2** [comment]
If complicated to do in current version, this could be rolled in with the new changes

**Comment by ljwh2** [comment]
Open to other suggestions as to where to position logo

**Comment by ljwh2** [comment]
Additional info from Matthew Thakur (email fwd from Helen 24 Jan):

Dear GBC resources,

Just checking back in on this thread from late last year - I note that many of you have already updated your resource websites with GCBR badges.

I was thinking about how to make sure we have a bit of consistency in formatting for resources with more than one badge (CoreTrust Seal, GCBR and ELIXIR). After checking in with Geetika and Niki in the web team about this - when they next update the visual fraemwork, they may tweak some of the existing functionality to reflect the proliferation of badges beyond the ELIXIR CDR it was originally designed for. But in the meantime (and as many resources aren't using visual framework modules anyway) - to make sure resources are displaying badges consistently and avoiding any design and accessibility no-no's, please follow Niki's advice below:

1. Simplest option is to use existing space in the footer - following the example of UniProt. Make sure that the badge is sized large enough to make out the text

2. We advise against customising and duplicating the Elixir banner (sorry ENA!) as this introduces contrast errors between the text and its background. 

To show the badge alongside hypelinked text it's better to use vf-summary--has-image: https://stable.visual-framework.dev/components/vf-summary/#vf-summary--has-image

3. I'm sure you've all noted this particular string attached, but if your resource is a member of a wider consortium that was granted GCBR status, you may only use the GCBR logo and description in association with the wider consortium.

4. Accessability - to make sure the badges are legible to users of your pages using screen readers - provide the title of the destination page the badge links to as alt text (i.e. GLOBAL CORE BIODATA RESOURCES instead of "GCBR logo")

Please consider the above in how your resource displays the badges - we can share this guidance with the next round of GCBRs too in about a year's time!

Thanks,

Matt

**Comment by ala-ebi** [comment]
added to labs
