### ISSUE TITLE
Bulk unpublish PMID:36442731

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#921]
The studies need to be unpublished for updating the EFOs.
44 studies with status: published, and one study (study id:101930096) with requires review status

**Comment by sajo-ebi** [comment]
@Santhi1901 done, please review

**Comment by Santhi1901** [comment]
Thanks it is unpublished

**Comment by Santhi1901** [comment]
@sajo-ebi Could you please re-publish the studies in this pmid **except study ID:101930096**

**Comment by sajo-ebi** [comment]
@Santhi1901 done , please verify the study which shouldn't be published

**Comment by Santhi1901** [comment]
yes the required studies are published
