### ISSUE TITLE
Update documentation for new harmonisation pipeline

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#932]
Sumstats methods page needs updating for new standard and harmonisation pipeline https://www.ebi.ac.uk/gwas/docs/methods/summary-statistics
Overview of all documentation changes is here: 
https://docs.google.com/document/d/18JSvWW9Fvlajxg0tR8O58e_UtwHF_1oWCIVBJT3kNg8/edit?usp=sharing

**Comment by ljwh2** [comment]
@eks-ebi to update in repo

**Comment by eks-ebi** [comment]
have now updated the three main submission instruction pages with the new instructions: [submission-summary-statistics-content.adoc](https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/submission-summary-statistics-content.adoc)
[submission-summary-statistics-plus-metadata-content.adoc](https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/submission-summary-statistics-plus-metadata-content.adoc)
[summary-statistics-format-content.adoc](https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/summary-statistics-format-content.adoc)
