### ISSUE TITLE
Allow import of edited submission

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#934]
Submission has been edited in depo-curation to change EFO terms. I have approved the SNPs, which I thought would make the submission available for import, but the Import button is orange and Submission type is UNKNOWN: https://www.ebi.ac.uk/gwas/curation/submissions/613261186d0dd70001ad971f

This update is required to make sure an example is available in the GWAS Catalog that will be used in an upcoming paper from the ontology team. We need this to go out in this data release.

**Comment by sajo-ebi** [comment]
The Publication '34376796' status changed to Under_Submission & the Submission status changed to 'Submitted' , @eks-ebi please try to import now

**Comment by eks-ebi** [comment]
Thanks @sajo-ebi, submission has been successfully imported. I'll now have to wait for the associations to map, and then republish the studies.
