### ISSUE TITLE
API for retrieving metadata on prepubs by GCST 

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#935]
For the sumstats standard, which requires a metadata file to be written for each sumstast dataset, we need a way to access the prepub metadata.
Prepub metadata is submitted by external users via the submission app. They use the spreadsheet template to upload their metadata. This is may change, which is why I suggest returning all of the fields from the template, but the minimal set would be (as they appear in the template column headers) the following from the 'study' and 'sample' sheets:

'Genotyping technology'
'Number of individuals'
'Ancestry category'
'Reported trait'
'EAF lower limit'
'Ancestry method'
'Case control study'
'Number of cases'
'Number of controls'
'Summary statistics assembly'
'Neg Log10 p-values'
'Analysis Software'
'Imputation panel'
'Imputation software'
'Adjusted covariates'
'Mapped trait'
'Readme text'

API endpoint:
e.g. /prepubs/studies/<GCST> 

Returns:
all of the submitted study metadata (or the above fields at a minimum) for the GCST requested

**Comment by sprintell** [comment]
Hi @jdhayhurst 

You can acess the api from here: https://wwwdev.ebi.ac.uk/gwas/ingest/api/v2/studies/<accession-id>

e.g https://wwwdev.ebi.ac.uk/gwas/ingest/api/v2/studies/GCST90267169

**Comment by sprintell** [comment]
@jdhayhurst 

When  its deployed, it can be retrieved from here: .../v2/studies/<studyAccessionId>/samples

**Comment by sprintell** [comment]
@sajo-ebi needs to update camelCase snakeCase for consistency

**Comment by sprintell** [comment]
@sajo-ebi needs to update camelCase snakeCase for consistency
