### ISSUE TITLE
Delete GCP000513 and its submission 63d13b577325c200011f80bf

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#938]
The user had some issues with this GCP/submission, so abandoned them and created a new one. They were able to finalise submission on the other GCP, so this one can be deleted.

**Comment by ala-ebi** [comment]
Done, just for info, there are APIs to delete both submission and BoW, info below

HTTP DELETE 
url: 'https://www.ebi.ac.uk/gwas/deposition/api/v1/submissions/${submissionId}'
headers: 'authorisation: bearer ${token}'

HTTP DELETE
url: 'https://www.ebi.ac.uk/gwas/deposition/api/v1/bodyofwork/${GCP}'
headers: 'authorisation: bearer ${token}'

**Comment by eks-ebi** [comment]
thanks @ala-ebi - good to know for next time!
