### ISSUE TITLE
Update sample size for a user submission 63da9a737325c200011ff20f (GCP000522)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#942]
The user has requested to update the sample information submitted for their pre-published submission. The following are the updates which are needed:

Number of individuals: 11209
Number of cases: 1917
Number of controls: 9292

gwas-subs #640543

**Comment by ala-ebi** [comment]
@ljwh2 @Santhi1901 
I did this on the database, but changes wont be reflected in the submitted file.
I'd like to ask if this ticket can be done using depo-curation instead?

**Comment by Santhi1901** [comment]
@ala-ebi, @ljwh2  It worked.
