### ISSUE TITLE
Update prepublication submission details - GCP000415

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#943]
As per user request, please add DOI to submission iD '63d123357325c200011f7fbd'. 
DOI: https://doi.org/10.1101/2022.10.05.22279072

And update abstract to: 
Atopic dermatitis (AD) is a common inflammatory skin condition and prior genome-wide association studies have identified 71 associated loci. In the current study we conducted the largest AD GWAS to date (discovery N=1,086,394, replication N=3,604,027), combining previously reported cohorts with additional available data. We identified 81 loci (29 novel) in the European-only analysis and 15 additional loci in the multi-ancestry analysis (6 novel). All 81 variants replicated in a separate European analysis. Eleven variants from the multi-ancestry analysis replicated in at least one of the populations tested (European, Latino or African). While four variants appeared to be specific to individuals of Japanese ancestry. AD loci showed enrichment for DNAse I hypersensitivity and eQTL signals in blood. At each locus we prioritised candidate genes by integrating multi-omic data. The implicated genes are predominantly in immune pathways of relevance to atopic inflammation and some offer drug repurposing opportunities.

**Comment by ljwh2** [comment]
Is this required before data release @earlEBI ?

**Comment by earlEBI** [comment]
@ljwh2 Not really. It's more to make sure we notice when it receives a PMID.

**Comment by sajo-ebi** [comment]
@eks-ebi done , as Lizzy is out of office tagging you to validate

**Comment by ljwh2** [comment]
@earlEBI please confirm if this is done

**Comment by earlEBI** [comment]
I can't see that the DOI has been added, either on the submission page: https://www.ebi.ac.uk/gwas/deposition/submission/63d123357325c200011f7fbd 
or in the curation app add PMID page: 
http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/studies/new

**Comment by ljwh2** [comment]
@sajo-ebi please verify the DOI is added?

**Comment by sajo-ebi** [comment]
@earlEBI the doi is updated now & visible on both the pages , please verify

**Comment by earlEBI** [comment]
Thanks. Verified.

**Comment by earlEBI** [comment]
The user has got back in touch - see gwas subs and Slack.
The DOI is not showing on their landing pages - GCST90244787 and GCST90244788
Please rectify as requested.

**Comment by ljwh2** [comment]
@earlEBI is this still an issue?

**Comment by earlEBI** [comment]
@ljwh2 No, this seems fine now
