### ISSUE TITLE
API EFO term endpoint - empty responses

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#945]
User-reported issue: 

EFO searches in the form https://www.ebi.ac.uk/gwas/rest/api/associations/search/findByEfoTrait?efoTrait=MONDO_0005147 return empty JSON. 

Please investigate.

**Comment by sprintell** [comment]
Hi @earlEBI ,

The endpoint you are visiting does not take the EFO Trait Id as request parameter. It is expected to be given the trait name itself which for this instance is **type 1 diabetes mellitus**

Hence, the API request is expected to be formualted as: https://www.ebi.ac.uk/gwas/rest/api/associations/search/findByEfoTrait?efoTrait=type 1 diabetes mellitus

if you want to retrieve associations using the EFO Trait Id you cna use the endpoint below:

https://www.ebi.ac.uk/gwas/rest/api/efoTraits/MONDO_0005147/associations

👍

**Comment by ljwh2** [comment]
Responded to user
