### ISSUE TITLE
Submission stuck in import 63eb6008ff81b7000156caa6 PMID:36515925

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#948]
Submission is stuck in import from yesterday. Please reset it for importing.

http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/submissions/63eb6008ff81b7000156caa6

**Comment by earlEBI** [comment]
Mine is also stuck in import - '6153061809113d00018b107a', PMID '34215507'. Not sure if related. Please reset for importing.

**Comment by Santhi1901** [comment]
I've another submission 63c805d37325c200011f3570 (PMID:36320039) also stuck in submission

**Comment by earlEBI** [comment]
Also this one 62de55b9c6aae20001d385d5
