### ISSUE TITLE
'Whole genome sequencing' genotyping technology is not imported from the deposition app template

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#95]
On importing PMID 32499645 to the curation interface, the 'genotyping technology' field on the 'study details' tab was left blank, although the template field has been correctly filled out with 'Whole genome sequencing'. 

'Genome-wide sequencing' is the corresponding option in the curation interface.

Import page with template info:
https://www.ebi.ac.uk/gwas/curation/submissions/5eedde3b2c2502000105c8cf

**Comment by twhetzel** [comment]
This is available for testing on Snoopy 9680. 
- Go to Sandbox Deposition app
- Login
- Select a publication that is Open for Submission
- Create a submission using a template with a few studies to test various combinations of Genotyping technology entries per study:
Whole genome sequencing
Exome genotyping array
Whole genome sequencing | Targeted genotyping array
- Submit the template
- Go to Snoopy 9680 Curation app
- Click View submsisions and then Review your submission
- Click Import
- Verify on the Study details page for each study has the correct genotyping technology value

**Comment by earlEBI** [comment]
Tested all four genotyping tech options and all imported successfully.
