### ISSUE TITLE
Change the GCST for submission 63f8add57325c20001210db7 (PMID-36635386)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#952]
The GCSTs need to be changed to the original ones mentioned in the published article. I've attached the list of study tags and GCST. Column C has the correct list of GCST.

The user submitted 2 different submissions for the same PMID. I combined those 2 submissions and submitted it under the PMID. The submission was manually pushed through validation. Now the GCSTs need to be changed to the ones submitted by the user.
[https://app.zenhub.com/files/2995118/3a37c878-9cc5-4a3f-8c76-1c7fb7a12768/download](https://app.zenhub.com/files/2995118/3a37c878-9cc5-4a3f-8c76-1c7fb7a12768/download)

**Comment by sajo-ebi** [comment]
@Santhi1901 Updated the GCST in Deposition side , couldn't find the GCST in Curation App so assuming the submission has not been imported, Kindly confirm if the data looks good

**Comment by Santhi1901** [comment]
@sajo-ebi it looks good, thanks

**Comment by ljwh2** [comment]
The GCSTs from this publication appear in both unpublished and published sumstats tables, e.g. GCST90203512. There are 4443 studies affected. This needs fixing in production before the ESHG conference June 10th.

**Comment by sajo-ebi** [comment]
@sajo-ebi please do before DR

**Comment by sajo-ebi** [comment]
deleted unpublished studies which have been duplicated from Curation DB, need to wait for DR to reflect in Catalog

**Comment by ljwh2** [comment]
@ljwh2 confirm and close ticket

**Comment by ljwh2** [comment]
confirmed
