### ISSUE TITLE
Unpublish studies for PMID: 33441150 (submission id:5fb7b9121b0c9c0001719502)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#953]
The studies in this PMID need to be unpublished to update EFOs. 

173 studies with curation status Publish study (GCST90012603-GCST90012782) need to be unpublished.

This has to be re-published before the next DR.

**Comment by sajo-ebi** [comment]
HAve Unpublished all studies for the Pmid there were 183 studies in total, kindly confirm

**Comment by Santhi1901** [comment]
@sajo-ebi could you please republish the studies? I have now updated the EFOs. In this paper, some of the studies need not be published. I have attached the list of studies which need to be published.[https://app.zenhub.com/files/2995118/7536a728-81d5-46c6-b7e3-21eabc4f55a4/download](https://app.zenhub.com/files/2995118/7536a728-81d5-46c6-b7e3-21eabc4f55a4/download)

**Comment by Santhi1901** [comment]
yes this is completed
