### ISSUE TITLE
Check on licensing details

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#954]
Request from Helen, due end March. 

Individual Resource pages - make sure resources you manage have licensing details displayed prominently, are unambiguous (eg don't refer to EBI general terms of use in one place and cc0 in another) and are up to date. https://www.ebi.ac.uk/licencing has some boilerplate text on licensing to reuse if required - by end of March.

In the first instance, please review and check where any changes are needed @eks-ebi

**Comment by eks-ebi** [comment]
Changed to:
> Summary statistics are available under CC0 terms unless otherwise indicated - see below for more details. Other GWAS Catalog data can be used under the standard Terms of Use for EBI services which can be found at http://www.ebi.ac.uk/about/terms-of-use. Our code is available under the Apache version 2.0 license

(note: "below" links to the other FAQ answer explaining the sumstats licence terms)
