### ISSUE TITLE
Sumstats table download file - no FTP paths

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#957]
User reported issue: unable to find FTP paths to studies of interest. 
https://www.ebi.ac.uk/gwas/downloads/summary-statistics

The table is capped at 5,000 rows. 
The old download button (top right of table - csv option, with FTP paths) is also capped at 5,000 rows. 
The new link to download all sumstats files (see screenshot) does not contain FTP paths.  Should contain FTP paths.

![Screenshot 2023-03-03 at 17.15.30.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/f4d6ef75-230b-48f1-9172-14a406627c2e)

**Comment by ljwh2** [comment]
@ala-ebi to confirm this is included in the new version
