### ISSUE TITLE
Update documentation to reflect new submission workflow

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#96]
Under the new submission workflow, submissions will automatically be submitted if they pass validation - so users will not need to manually click "Submit". Documentation pages on the website should be updated to reflect this (once the new functionality is ready):
1. Update submission instructions with new workflow
2. Replace obsolete screenshots with new ones
3. Review other documentation pages for any statements that clash with the new workflow

**Comment by eks-ebi** [comment]
@ljwh2 If you have text prepared about the data release, could you please add it here as a comment? Then I can incorporate it into the docs when I edit them.

**Comment by ljwh2** [comment]
Once the submission has successfully validated, click "Submit" to complete the submission.

You will be taken to the My Submissions page, where you can see your latest submission at the top, with the status SUBMITTED.
For submission associated with a published manuscript, a curator will then review your submission and make the summary statistics available to the public as soon as possible through the GWAS Catalog website. We will let you know when these are available.
For unpublished data submissions, or those associated with a preprint, each summary statistics file will be made available via direct link on our ftp server within 48 hours. The direct links take the format ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCSTXXXXXXXX
Following our biweekly data release, the studies will also be listed in the summary statistics download area https://www.ebi.ac.uk/gwas/downloads/summary-statistics and associated metadata will be available to download via https://www.ebi.ac.uk/gwas/docs/file-downloads

**Comment by eks-ebi** [comment]
This page now updated in GitHub, with new text and screenshots:
https://github.com/EBISPOT/gwas-ui/blob/documentation/goci-interfaces/goci-ui/src/main/docs/submission-content.adoc

Ready for review

**Comment by eks-ebi** [comment]
I haven't found any other parts of the documentation that no longer make sense with the new workflow.

**Comment by ljwh2** [comment]
Please amend end of step 1 as follows:
Large files may take some time to transfer, but you do not need to wait until this is finished  - the transfer will continue in the background while you proceed with the next step. You do however need to wait for confirmation of file transfer before clicking "Submit submission form" (step 3).

**Comment by eks-ebi** [comment]
Added now

**Comment by ljwh2** [comment]
checked and all good to go now, thanks
