### ISSUE TITLE
Delete duplicate submissions

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#960]
Please delete the following submissions:

'64089805d51a04000156c1e2'
'640895c782c559000138277d'

**Comment by sajo-ebi** [comment]
Bothe the submissions have archived , do we need to delete them ?

**Comment by sajo-ebi** [comment]
@earlEBI Both the submissions have archived , do we need to delete them ?

**Comment by earlEBI** [comment]
I guess not. The problem was there was more than one submission associated with the PMID so we were worried it would break when importing. But if they've been automatically deleted, I will try to import the remaining submission.

**Comment by earlEBI** [comment]
It's not possible to import the submission as the import button is yellow 'review'. 
![Screenshot 2023-04-20 at 11 11 56](https://user-images.githubusercontent.com/61545198/233335839-fc0d8ee4-ee1f-4f48-b2af-a4c39a4009bb.png)

**Comment by sajo-ebi** [comment]
@earlEBI The submission should be enabled , kindly confirm after import , I can start the DR

**Comment by earlEBI** [comment]
@sajo-ebi Great thanks. DR doesn't need to wait for this paper.
