### ISSUE TITLE
Reopen publication 36539618 for sumstats only submission

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#961]
I have added new studies to this publication, and have received the additional sumstats files from the author that need to be added.

I would like to reopen it for sumstats-only submission in deposition app, so I can add the additional sumstats.

If details need to be manually entered into deposition, I have attached them as a spreadsheet. Let me know if anything is missing.

**Comment by eks-ebi** [comment]
[https://app.zenhub.com/files/2995118/6f858afe-35f3-4329-83b7-78dc3c62a5d4/download](https://app.zenhub.com/files/2995118/6f858afe-35f3-4329-83b7-78dc3c62a5d4/download)

**Comment by sajo-ebi** [comment]
@eks-ebi , you need to create a new sumstats only submisssion for the Pmid, the prefilled template should have the required entries

**Comment by eks-ebi** [comment]
Hi @sajo-ebi , thanks but it still shows as CLOSED for me.
<img width="1319" alt="Screenshot 2023-03-13 at 17 06 35" src="https://user-images.githubusercontent.com/42406380/224774274-da83914a-8ade-4b26-b19a-f0f7c68f28da.png">

**Comment by sajo-ebi** [comment]
@eks-ebi Pmid opened , you will have to create the submission today or else it will be closed again by Depo-Sync process

**Comment by eks-ebi** [comment]
@sajo-ebi thanks! I've created the submission now and all metadata is correct. I'll close this ticket now
