### ISSUE TITLE
remove harmonised files with no data

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#964]
there are many reasons why such files could be empty. OTAR sent us alist that we should remove:

+--------+---------+-----------+

|    pmid|emptyFrac|study_count|

+--------+---------+-----------+

~~|29899525|      0.2|          5| <- one of the 5 studies are empty.~~

~~|32915782|      1.0|          1|~~

~~|33414548|   0.0426|        141| <- 6 studies are empty~~

~|33983923|      1.0|       1021| <- all studies are empty!~

~|34270794|      1.0|         41|~

~|34662886|      0.5|       7972|~ (I didn't create a ticket for this. I think I did it separately. Can't find a sign of the harmonised directories now.)

~|34782693|      1.0|          6|~

+--------+---------+-----------+

**Comment by ljwh2** [comment]
Lizzy to do this

**Comment by earlEBI** [comment]
I will create a ticket for each PMID: 

1. https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1089

**Comment by ljwh2** [comment]
I think this ticket can be closed, any objections @earlEBI ?

**Comment by earlEBI** [comment]
@ljwh2 I'm still working my way through, was just doing one a week. I think just 2 small ones to go.

**Comment by earlEBI** [comment]
This is now completed and can be closed.
