### ISSUE TITLE
New data fields imported into curation app 'study details' page disappear after editing the page

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#97]
After first importing a submission, the lower half of the study details page might look like this:
![Screenshot 2020-06-25 at 14.27.46.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/28b1c939-039d-477e-a2a5-af57d8e090f8)

But after editing the page - eg. adding a reported trait and EFO - it looks like this:

![Screenshot 2020-06-25 at 14.28.30.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/fd3b3042-08c2-4a5f-82dc-664a16419aa3)

The same applies to the study tag at the top of the page:
![Screenshot 2020-06-25 at 14.28.17.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/80661cc1-8956-4c98-a72b-50a622cebf9b)
becomes:
![Screenshot 2020-06-25 at 14.28.24.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/6347c19a-8958-45d8-afc8-7aaf95343c46)

**Comment by twhetzel** [comment]
Change to test requested in [PR](https://github.com/EBISPOT/goci/pull/115)

**Comment by twhetzel** [comment]
Saving the form content results in an error. See PR for more details

**Comment by twhetzel** [comment]
Ready for Curator QA

**Comment by earlEBI** [comment]
Tested and appears fixed!

**Comment by twhetzel** [comment]
While study information is retained, it was later mentioned that on Import sample and SNP information is not imported. Need to check if that is due to this update.
