### ISSUE TITLE
Identify sumstats that have not been harmonised and harmonise them

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#975]
- [x] Identify unharmonised GWAS (sub harmonised from all)
- [x] if has metadata and GWAS-SSF -> harmonised with v1.1.0)
- [x] else create metadata file (pre-GWAS-SSF) -> filter where headers -> harmonise with v1.0.1 
- [ ] create metadata files for already harmonised sumstats (both raw and harmonised)

**Comment by ljwh2** [comment]
Will not be completed before James leaves.Should not need manual intervention once automated by gwas-utils#151. Will email gwas-dev-logs with success/fail. Failures will not hold up other files.

**Comment by ljwh2** [comment]
@jiyue1214 I think this ticket can be closed now, would you agree?
