### ISSUE TITLE
Change homepage banner content

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#979]
NEWS!! GWAS Catalog submission requirements are changing from 12th April 2023! Read all about it in our blog post https://ebispot.github.io/gwas-blog/gwas-ssf-release/

**Comment by ljwh2** [comment]
If possible this text should also appear on the deposition app homepage https://www.ebi.ac.uk/gwas/deposition

**Comment by ljwh2** [comment]
The text there could read:
NEWS!! GWAS Catalog submission requirements are changing from 12th April 2023! Please read this article before starting a new submission  https://ebispot.github.io/gwas-blog/gwas-ssf-release/

**Comment by eks-ebi** [comment]
Once the new sumstats standard has been released, banner text can be replace with: 

> NEWS!!
> GWAS Catalog submission requirements have changed.
> Read all about it in our blog post.

**Comment by ala-ebi** [comment]
added banner in deposition app that will go in 3 months for new ssf (until 12 jul)
