### ISSUE TITLE
SPOT robot email lists folders as missing from the staging area if they are not labelled in the old format.

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#98]
ThaventhiranJED_32499645_GCST90000530 is listed as missing from the staging area in the SPOT robot email:

![Screenshot 2020-06-25 at 16.45.11.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/25dd6488-e25a-491b-a243-1722cff271c2)

But the folder should not exist with this name, because the sumstats were submitted via Globus.

**Comment by ljwh2** [comment]
@earlEBI @jdhayhurst is this issue still relevant now we are adding sumstats through the deposition app?

**Comment by jdhayhurst** [comment]
When we release gwas-utils#20 (the ftp new structure and sync) this will be irrelevant

**Comment by ljwh2** [comment]
closing ticket since gwas-utils#20 is soon to be released
