### ISSUE TITLE
Manually replace summary statistics file for GCST90093377

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#980]
The author has identified an error in the summary statistics for this study, and has sent us a corrected file via FTP. The new file is valid (according to old sumstats standard), and I have confirmed with the author that the genome assembly (GRCh38) is the same, only changes are some amended pvalues, and some rows have been removed.

New file (on private FTP): `/SummaryStatsUploads/Kaivola_35381062/Kaivola_35381062.tsv.gz`

Old file to be replaced (public FTP): `/summary_statistics/GCST90093001-GCST90094000/GCST90093377/GCST90093377_buildGRCh38.tsv`

**Comment by earlEBI** [comment]
@eks-ebi I've replaced the file on staging so it should sync overnight. Is that okay? or if it's urgent I can replace on public too...

**Comment by eks-ebi** [comment]
Overnight is okay, thanks @earlEBI !

**Comment by earlEBI** [comment]
@jdhayhurst Not sure if you talked about this in the iteration meeting but the original file has already been harmonised. Will this automatically go back in the queue? Does it need to?

**Comment by eks-ebi** [comment]
@jdhayhurst could you please follow up on this when you get back? Looking at the file creation dates, I think the harmonised file is still the one created from the old submitted file, so the harmonisation does need to be done again
