### ISSUE TITLE
Completely retract BoW GCP000470 and all associated studies + sumstats

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#981]
User has requested to retract Body of Work GCP000470, as well as the associated pre-publication sumstats+metadata submission `637d0d71ff81b70001d07974`, as there are errors in the sumstats files. The sumstats files should also be removed from the public FTP and staging: GCST90239784, GCST90239785 and GCST90239786

The author will create a new submission after reanalysing the data, so all existing data should be completely removed.

(I previously tried to retract the sumstats by manually deleting them from the public FTP, but they just got automatically replaced from staging.)

**Comment by ljwh2** [comment]
This needs doing before DR @ala-ebi

**Comment by ala-ebi** [comment]
removed BoW and studies from Oracle
removed BoW, submisison, studies, file uploads and all associated entries from Mongo
@jdhayhurst please remove the sumstats from FTP

**Comment by eks-ebi** [comment]
confirmed:BoW is no longer visible in

**Comment by eks-ebi** [comment]
@eks-ebi Check after data release to make sure landing pages are no longer there
