### ISSUE TITLE
Bug downloading full list of studies with sumstats

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#983]
A user has reported a bug downloading the full list of published studies with sumstats from this link: https://www.ebi.ac.uk/gwas/api/search/summaryStatistics/download)

Apache Tomcat/8.0.33 - Error report (ebi.ac.uk)
 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template "Your search could not be performed - we encountered a problem.  Weve been notified and will attempt to rectify the problem as soon as possible.  If problems persist, please email gwas-info@ebi.ac.uk", template might not exist or might not be accessible by any of the configured Template Resolvers
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by ljwh2** [comment]
Just a reminder about this one @ala-ebi, when you have time

**Comment by ljwh2** [comment]
If it's possible to generate an offline version of this table to send to users, that would be helpful in the immediate term.

**Comment by sajo-ebi** [comment]
@eks-ebi have fixed the issue in Snoopy http://gwas-snoopy.ebi.ac.uk:9780/gwas/downloads/summary-statistics, please validate then I can deploy the fix in Prod

**Comment by eks-ebi** [comment]
@sajo-ebi thanks - I can confirm, this is fixed in Snoopy

**Comment by eks-ebi** [comment]
@sajo-ebi I can confirm that the link is now working. However, the file is not quite as expected. It has exactly 50,000 rows of data, whereas the banner suggests there should be more:

**Comment by ljwh2** [comment]
@ala-ebi to update number of rows in download
