### ISSUE TITLE
Change statuses of submission to allow import

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#989]
I want to import this submission: https://www.ebi.ac.uk/gwas/curation/submissions/6284ef37a2d24400017d7c4c (PMID: 35120996). I can't do this at the moment because the Import button is disabled.

There are existing studies for this PMID in the curation app. I want to overwrite those old studies and replace them with the new studies from depocuration:
https://www.ebi.ac.uk/gwas/depo-curation/submissions/6284ef37a2d24400017d7c4c. The GCSTs in the new submission are the ones I want to keep.

I believe this requires the statuses to be change:
* Submission status to be changed from CURATION COMPLETE to READY TO IMPORT
* PMID status to be changed from CLOSED to UNDER SUBMISSION

**Comment by eks-ebi** [comment]
So far, I have not unpublished the old studies in the curation interface, but let me know if this is needed

**Comment by ljwh2** [comment]
Still not fixed @eks-ebi to provide details

**Comment by sajo-ebi** [comment]
@eks-ebi the submission is enabled now , can you import today as it might get disabled after Depo Sync runs

**Comment by eks-ebi** [comment]
confirmed! It works and I have imported the submission, so will now close this ticket.
