### ISSUE TITLE
Uploading very large unpublished sumstats dataset

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#99]
Helen had contact with authors of an unpublished dataset and we had offered to upload it for them when the submission interface was ready. There are over 3000 files, I think around 1.5TB of data. Curators are not able to handle this volume of data, so we need another solution. 

Data is here: https://open.win.ox.ac.uk/ukbiobank/big40/

**Comment by ljwh2** [comment]
This info from the website

3,935 files, one file per trait, containing: chr rsid pos a1 a2 beta se pval(-log10). The beta coefficient is in the direction of a2.
The download for trait 1 is:    release2/stats/0001.txt.gz

@

**Comment by jdhayhurst** [comment]
It looks like the files need to be formatted en masse, which is something that I can do/advise how to do with the new formatter. pvalues will need to be converted from -log - I will need to add an option to the formatter to enable this. Genome assembly appears to be GRCh37, but please confirm. 


```
chr rsid pos a1 a2 beta se pval(-log10)
01 rs367896724 10177 A AC -0.001157 0.014236 0.029085
01 rs201106462 10352 T TA -0.0020071 0.014645 0.050126
01 rs534229142 10511 G A -0.08748 0.19528 0.18431
01 1:10616_CCGCCGTTGCAAAGGCGCGCCG_C 10616 CCGCCGTTGCAAAGGCGCGCCG C 0.073579 0.091994 0.37282
01 rs575272151 11008 C G -0.033773 0.024695 0.76589
01 rs544419019 11012 C G -0.033773 0.024695 0.76589
01 rs540538026 13110 G A 0.058805 0.033066 1.1229
01 rs62635286 13116 T G 0.014839 0.019169 0.35765
01 rs62028691 13118 A G 0.014839 0.019169 0.35765
```

**Comment by ljwh2** [comment]
Yes, GRCh37/hg19, and A2 effect allele

**Comment by ljwh2** [comment]
Completed submission template is here: GWASCatalog_template-BIG40.xlsx

**Comment by jdhayhurst** [comment]
After formatting the above looks like this:
```
chromosome	variant_id	base_pair_location	other_allele	effect_allele	beta	standard_error	neg_log10_p_value	odds_ratio	ci_lower	ci_upper	effect_allele_frequency	p_value
1	rs367896724	10177	A	AC	-0.001157	0.014236	0.029085	NA	NA	NA	NA	0.9352226147136065
1	rs201106462	10352	T	TA	-0.0020071	0.014645	0.050126	NA	NA	NA	NA	0.8909924008180644
1	rs534229142	10511	G	A	-0.08748	0.19528	0.18431	NA	NA	NA	NA	0.654169060596548
1	NA	10616	CCGCCGTTGCAAAGGCGCGCCG	C	0.073579	0.091994	0.37282	NA	NA	NA	NA	0.4238185877576885
1	rs575272151	11008	C	G	-0.033773	0.024695	0.76589	NA	NA	NA	NA	0.17143914810708835
1	rs544419019	11012	C	G	-0.033773	0.024695	0.76589	NA	NA	NA	NA	0.17143914810708835
1	rs540538026	13110	G	A	0.058805	0.033066	1.1229	NA	NA	NA	NA	0.07535290502354003
1	rs62635286	13116	T	G	0.014839	0.019169	0.35765	NA	NA	NA	NA	0.4388842542088914
1	rs62028691	13118	A	G	0.014839	0.019169	0.35765	NA	NA	NA	NA	0.4388842542088914
```
Please can you confirm this is correct and I will apply to all

**Comment by ljwh2** [comment]
@jdhayhurst formatting looks good to me

**Comment by jdhayhurst** [comment]
formatted, submitted and released on FTP
