### ISSUE TITLE
Allow import of studies without unpublishing first

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#996]
Allow import of studies without unpublishing first, after editing EFOs. In theory this is possible, but “Allow import” button is only activated if a curator has edited the template (not only EFOs).

**Comment by sajo-ebi** [comment]
@ala-ebi this requires some some UI changes . The details are 

- [ ] Allow Import to be enabled for submission status 'CURATION_COMPLETE'.
- [ ] A dialog box should appear if submission status is 'CURATION_COMPLETE' with following message 'Please ensure you have unpublished studies before updating traits for published studies'

**Comment by sajo-ebi** [comment]
@Santhi1901 @Lizzy the changes are deployed in Sandbox [https://wwwdev.ebi.ac.uk/gwas/depo-curation](https://wwwdev.ebi.ac.uk/gwas/depo-curation), kindly validate & confirm

**Comment by sajo-ebi** [comment]
@Santhi1901 @earlEBI please confirm if the prompt message is fine 'Please ensure you have unpublished any published studies before updating them'.

**Comment by earlEBI** [comment]
@sajo-ebi What is the curation app site we should test importing to? the 'view submissions' page of http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/studies?page=1 shows an error.

**Comment by sajo-ebi** [comment]
@earlEBI the page is working for me , what is the error you are getting?

**Comment by sajo-ebi** [comment]
@earlEBI please ignore just saw the view submission note

**Comment by sajo-ebi** [comment]
@earlEBI the view submission page is working now in snoopy

**Comment by sajo-ebi** [comment]
@Santhi1901 did you click on Allow Import Button before importing?

**Comment by Santhi1901** [comment]
I am not able on click on allow import button in depo-curation; it is disabled.

**Comment by sajo-ebi** [comment]
@Santhis can you try now , it is showing as enabled?

**Comment by earlEBI** [comment]
I think it's difficult to test because all the publications I've found in dev depocuration don't match up with what's in snoopy curation app. Eg. 
https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/6385e4e697cac50001ed3fcd
and 
http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/publication/34910505

So changing the GCST / study tag on import might be breaking things. 

(I've tried with PMID [34210852](http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/studies?page=1&pubmed=34210852) which I think may be stuck in import... or just taking a long time.)

I would try with an entirely new submission but there don't appear to be any open. Do you have any PMIDs that are open for submission @sajo-ebi ? Or any that match between depocuration and curation?

**Comment by sajo-ebi** [comment]
@earlEBI the following Pmids are open for submission 32341337, 32378051,32372017,32370229,32391884,32424261,32493226

let me know if you need more examples

**Comment by earlEBI** [comment]
@sajo-ebi Seems to be working well as far as I can see, but I can't test from the point of publishing and unpublishing because my SNPs won't map. Is the mapping pipeline not running in Snoopy?

**Comment by ljwh2** [comment]
@earlEBI @sajo-ebi if SNP mapping is a blocker, could delete the SNPs to test the publish action?

**Comment by earlEBI** [comment]
Ok sure, I'll try again without SNPs.

**Comment by Santhi1901** [comment]
It worked for me for one paper; for the another paper, I was not able to import to snoopy as the import button was disabled.

**Comment by earlEBI** [comment]
My test submission worked as expected.

**Comment by sajo-ebi** [comment]
@Santhi1901 can you give the submission which did have import enabled, Also did you try Allow Import before trying to import the submission?

**Comment by Santhi1901** [comment]
This is one that has import disabled:
http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/submissions/61976e5a06ff20000191a051
I have clicked allowed import in the depo-curation app, but the import button is not enabled in snoopy. 

This submission worked fine: http://gwas-snoopy.ebi.ac.uk:9780/gwas/curation/submissions/61e988b206ff20000162133e

**Comment by sajo-ebi** [comment]
@Santhi1901 The submission '61976e5a06ff20000191a051' is a very old one & has never been curated so it is not in proper state in Dev DB , Also the Depo sync doesn't run in Dev environment so the Publication is not in proper state in Deposition DB , can you try to create a fresh submission & test as the old data in Dev DB is not reliable & we will not face similar issue with Prod as Depo sync always runs & data is syncs between Depo & curation side

**Comment by earlEBI** [comment]
The confirmation to unpublish published studies message looks okay to me.

**Comment by ljwh2** [comment]
Reopening to account for prepublished studies submissions

**Comment by ljwh2** [comment]
Unclear what the issue with prepublished submissions is. Reopen ticket if scenario arises again and properly investigate.
