### ISSUE TITLE
Feature for curators to allow submissions to bypass sumstats validation

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#998]
This is usually needed for external users who wish to submit sumstats that don’t meet our validation criteria, eg. gene-based, CNV. 
The metadata template should pass validation. It’s only the format of the sumstats file itself which fails validation after template upload, and needs to manually be made to pass.  

Notes from discussion: The process already exists but needs UI feature in deposition only accessible to curators - this should be doable via role management using JWT. Needs different flag from the one used in depocuration to prevent revalidation. In this case we want the processing to proceed, just skip validation first.

**Comment by sajo-ebi** [comment]
@jdhayhurst can you provide the API details for SS

**Comment by sajo-ebi** [comment]
@ljwh2 the automated script has been deployed in Sandbox , Curators can validate the same . The instructionscan be found in the below link

[https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Curators+daily+task+utility+scripts](https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Curators+daily+task+utility+scripts)

**Comment by ljwh2** [comment]
@earlEBI @Santhi1901 please test in sandbox, thanks

**Comment by Santhi1901** [comment]
![Uploading Screenshot 2023-05-18 at 2.44.02 pm.png…]()
I am getting an error in globus while trying to upload sumstats
"Remote Endpoint Failure: Command Failed: Error (connect) Endpoint: GWAS Curation upload (a496988c-7e44-11ea-97a5-0e56c063f437) Server: hx-gridftp-2.ebi.ac.uk:2811 Message: Could not connect to server --- Details: globus_xio: Unable to connect to hx-gridftp-2.ebi.ac.uk:2811\nglobus_xio: System error in connect: Connection refused\nglobus_xio: A system call failed: Connection refused\n "

**Comment by earlEBI** [comment]
My test worked as far as I can see (submission 64665276909aed0001e40901). 

note: I did have some invisible formatting issues when copying the example. Had to use my saved 'remove embargo' text and edit that to fit.

**Comment by sprintell** [comment]
@sajo-ebi and @jdhayhurst  pls deploy in prod
